"""Marking tolerance data: what else counts as the same point.

Two tables, both matched against the words that actually appear in a question
and its marking points, so they only ever add guidance that is relevant:

* ``EQUIV``          - a term used in the mark scheme and the everyday wordings
                       that earn the same mark.  Students lose marks by writing
                       the right idea in the wrong words, so every scheme on the
                       site lists the wordings an examiner would also accept.
* ``MISCONCEPTIONS`` - the answer that looks right, is commonly written, and
                       earns nothing.  Shown as "Do not credit".

Each entry is ``(trigger words, text)``.  A trigger matches on whole words,
case-insensitively, anywhere in the question text or the marking points.
"""

# ---------------------------------------------------------------- equivalents
EQUIV = [
    # --- atmosphere, climate -------------------------------------------------
    (("albedo",), "reflectivity / the proportion of solar radiation reflected / how much sunlight is bounced back"),
    (("insolation",), "incoming solar radiation / energy arriving from the Sun"),
    (("anthropogenic",), "human-caused / caused by human activity"),
    (("enhanced greenhouse effect",), "extra warming caused by added greenhouse gases"),
    (("infrared", "long-wave"), "heat radiation / long-wave radiation re-emitted by the Earth"),
    (("global warming potential", "gwp"), "warming effect compared with the same mass of carbon dioxide"),
    (("residence time",), "the time a molecule stays in the atmosphere / atmospheric lifetime"),
    (("temperature inversion",), "a layer of warm air above cooler air that traps pollutants"),
    (("photochemical smog",), "ground-level ozone and PANs formed by sunlight acting on oxides of nitrogen and VOCs"),
    (("stratospheric ozone", "ozone layer"), "the ozone in the stratosphere that absorbs UV"),
    (("cfcs", "chlorofluorocarbons"), "CFCs / halogenated organic compounds releasing chlorine"),
    (("positive feedback",), "a change that makes itself larger / a self-reinforcing cycle"),
    (("negative feedback",), "a change that cancels itself out / a self-correcting cycle"),
    (("thermohaline",), "the ocean conveyor driven by temperature and salinity"),
    (("latent heat",), "the energy absorbed or released when water changes state"),

    # --- hydrosphere, soils --------------------------------------------------
    (("infiltration",), "water soaking into the soil surface"),
    (("percolation",), "water moving downwards through soil or rock"),
    (("transpiration",), "water lost as vapour from the leaves"),
    (("evapotranspiration",), "evaporation plus transpiration"),
    (("aquifer",), "a permeable rock that stores groundwater / underground water store"),
    (("permeability", "permeable"), "how easily water passes through / lets water through"),
    (("impermeable",), "does not let water through"),
    (("leaching", "leached"), "nutrients or ions washed down out of the soil / washed away by water"),
    (("interstitial",), "pore spaces / air spaces between the particles"),
    (("peds", "ped"), "soil crumbs / aggregates of soil particles"),
    (("loam",), "a balanced mixture of sand, silt and clay"),
    (("field capacity",), "the water a soil holds after free drainage"),
    (("cation exchange", "adsorb", "adsorption"), "nutrient ions sticking to the surfaces of clay and humus"),
    (("humus",), "dark, decomposed organic matter in soil"),
    (("salinisation",), "salt building up in the soil / soil becoming salty"),
    (("waterlogging", "waterlogged"), "soil pores filled with water so there is no air"),
    (("abstraction",), "water taken out of a river, lake or aquifer"),

    # --- pollution -----------------------------------------------------------
    (("bioaccumulation",), "a pollutant building up inside one organism over time"),
    (("biomagnification",), "concentration rising at each step along a food chain"),
    (("persistent", "persistence"), "does not break down / stays in the environment for a long time"),
    (("synergism", "synergistic"), "two pollutants together doing more damage than the sum of each alone"),
    (("ld50",), "the dose that kills half of a test population"),
    (("threshold level", "threshold"), "the concentration below which no harm is detected"),
    (("critical group",), "the people most at risk / most heavily exposed"),
    (("indicator species",), "a species whose presence or absence shows the conditions present"),
    (("biochemical oxygen demand", "bod"), "the oxygen used by aerobic decomposers in a water sample"),
    (("eutrophication",), "nutrient enrichment of water leading to algal growth"),
    (("deoxygenation",), "loss of dissolved oxygen from the water"),
    (("point source",), "pollution from one identifiable outlet"),
    (("diffuse", "non-point"), "pollution from a wide area with no single outlet"),
    (("half-life",), "the time for the activity, or the amount, to fall by half"),
    (("ionising radiation",), "radiation with enough energy to remove electrons and form ions"),
    (("becquerel",), "one radioactive decay per second"),
    (("sievert",), "the unit of radiation dose received"),
    (("electrostatic precipitator", "precipitator"), "charged plates that attract and collect particulates"),
    (("flue gas desulfurisation", "desulfurisation", "fgd"), "removing sulfur dioxide from flue gases with lime or limestone"),
    (("catalytic converter",), "a catalyst that converts NOx, CO and unburnt hydrocarbons to nitrogen, carbon dioxide and water"),
    (("particulates", "pm10", "pm2.5"), "fine solid particles / smoke and dust"),
    (("leachate",), "polluted liquid draining out of waste"),
    (("vitrification",), "sealing waste into glass"),
    (("biodegradable",), "broken down by decomposers"),

    # --- living environment --------------------------------------------------
    (("biodiversity",), "the variety of life: habitat, species and genetic diversity"),
    (("species richness",), "the number of different species present"),
    (("simpson", "simpson's index"), "a diversity index that uses both the number of species and their abundance"),
    (("genetic diversity", "gene pool"), "the range of alleles / genes present in a population"),
    (("keystone species",), "a species whose loss changes the whole community"),
    (("endemic",), "found naturally only in that one place"),
    (("carrying capacity",), "the largest population the area can support"),
    (("niche",), "the role a species plays and the conditions it needs"),
    (("abiotic",), "non-living / physical factors"),
    (("biotic",), "living factors / effects of other organisms"),
    (("limiting factor",), "the factor in shortest supply that holds the rate or population back"),
    (("range of tolerance", "tolerance"), "the range of conditions in which a species can survive"),
    (("succession",), "the gradual change in the community over time"),
    (("pioneer species",), "the first species to colonise bare ground"),
    (("climax community",), "the stable final community"),
    (("plagioclimax", "deflected succession"), "a community held back from its climax by human activity"),
    (("trophic level",), "the feeding level in a food chain"),
    (("primary productivity", "npp", "gpp"), "the rate at which producers make biomass"),
    (("detritivore",), "an animal that feeds on dead organic matter and breaks it up"),
    (("decomposer", "saprotroph"), "bacteria and fungi that break down dead organic matter"),
    (("mutualism", "symbiosis", "symbiotic"), "a close relationship in which both species benefit"),
    (("mycorrhiza", "mycorrhizal"), "a fungus living with plant roots that improves nutrient uptake"),
    (("nitrogen fixation", "nitrogen-fixing"), "nitrogen gas converted into ammonium or other nitrogen compounds"),
    (("nitrification", "nitrifying"), "ammonium oxidised to nitrite and then nitrate"),
    (("denitrification", "denitrifying"), "nitrate converted back to nitrogen gas"),
    (("ammonification",), "ammonium released from dead organic matter and protein"),
    (("ex situ",), "away from the natural habitat, eg a zoo, botanic garden or seed bank"),
    (("in situ",), "in the species' own natural habitat"),
    (("captive breeding",), "breeding in captivity to increase numbers for release"),
    (("studbook",), "a record of relatedness used to avoid inbreeding"),
    (("cites",), "the treaty that controls international trade in endangered species"),
    (("maximum sustainable yield", "msy"), "the largest catch that can be taken without reducing the stock"),
    (("bycatch",), "non-target species caught by accident"),
    (("quota",), "a legal limit on the mass or number that may be caught"),
    (("mesh size",), "net hole size, set so that young fish escape"),
    (("aquaculture",), "fish or shellfish farming"),

    # --- agriculture, forestry, resources -----------------------------------
    (("monoculture",), "one crop grown over a large area"),
    (("agroforestry",), "growing trees and crops together on the same land"),
    (("shelter belt", "windbreak"), "a line of trees or hedge that slows the wind"),
    (("contour ploughing",), "ploughing along the slope rather than up and down it"),
    (("terracing",), "cutting the slope into level steps"),
    (("integrated pest management", "ipm"), "combining several control methods to keep pests below the damage threshold"),
    (("biological control",), "using a natural predator, parasite or pathogen of the pest"),
    (("selective pesticide",), "a pesticide that kills the pest but not other species"),
    (("broad-spectrum",), "kills a wide range of species, including harmless ones"),
    (("food conversion ratio", "conversion efficiency"), "the feed needed per unit of food produced"),
    (("hydroponics",), "growing plants in nutrient solution without soil"),
    (("embodied energy",), "all the energy used to make and transport a product"),
    (("sustainable", "sustainability"), "meeting present needs without stopping future generations meeting theirs"),
    (("environmental impact assessment", "eia"), "a study of the likely environmental effects before a development is approved"),
    (("recycling",), "reprocessing a material to make something new"),
    (("reuse",), "using the item again as it is"),
    (("landfill gas",), "the methane and carbon dioxide produced by anaerobic decomposition of waste"),
    (("incineration",), "burning waste, usually with energy recovery"),

    # --- energy --------------------------------------------------------------
    (("base load",), "the steady minimum demand that must always be met"),
    (("peak load", "peak demand"), "the short periods of highest demand"),
    (("intermittent", "intermittency"), "only generates when the wind blows or the Sun shines / supply is not continuous"),
    (("pumped storage",), "water pumped uphill when demand is low and released to generate at peak"),
    (("combined heat and power", "chp"), "using the waste heat from generation for heating"),
    (("hep", "hydroelectric"), "electricity generated from falling water"),
    (("energy conservation",), "using less energy, eg by insulation or behaviour change"),
    (("energy efficiency",), "getting more useful output from the same energy input"),
    (("u-value",), "a measure of how fast heat passes through a material - a lower value insulates better"),
    (("fuel cell",), "a cell that produces electricity from hydrogen and oxygen"),
    (("fracking", "hydraulic fracturing"), "pumping fluid into rock at high pressure to release gas or oil"),
    (("enriched uranium", "uranium enrichment"), "raising the proportion of uranium-235 in the fuel"),
    (("moderator",), "slows the neutrons so that fission continues"),
    (("control rods",), "absorb neutrons to control the rate of fission"),
    (("decommissioning",), "safely dismantling a power station at the end of its life"),
    (("carbon capture", "ccs"), "capturing carbon dioxide from flue gases and storing it underground"),
    (("eroei", "energy return"), "the energy released compared with the energy used to get it"),

    # --- research methods ----------------------------------------------------
    (("quadrat",), "a square frame of known area used to sample a fixed area"),
    (("transect",), "a line along which samples are taken to show change with distance"),
    (("pitfall trap",), "a sunken container that catches ground invertebrates"),
    (("longworth",), "a live mammal trap"),
    (("tullgren",), "a funnel that drives soil invertebrates down into a collecting jar"),
    (("kick sampling",), "disturbing the stream bed and catching the organisms carried downstream"),
    (("random", "randomised"), "positions chosen using random numbers so the choice is not biased"),
    (("systematic sampling",), "sampling at regular intervals"),
    (("stratified",), "sampling each area or group in proportion to its size"),
    (("reliability", "reliable"), "repeatable / gives consistent results when repeated"),
    (("validity", "valid"), "actually measures what it is meant to measure"),
    (("accuracy", "accurate"), "close to the true value"),
    (("precision", "precise"), "readings close together / fine resolution"),
    (("anomalous", "anomaly"), "an outlier / a result that does not fit the pattern"),
    (("control variable",), "a variable kept the same so it cannot affect the result"),
    (("standard deviation",), "a measure of the spread of the data about the mean"),
    (("spearman",), "a test for correlation between two sets of ranked data"),
    (("chi-squared", "chi squared"), "a test comparing observed frequencies with expected frequencies"),
    (("mann-whitney",), "a test for a difference between two sets of unpaired, non-normal data"),
    (("student's t", "t-test"), "a test for a difference between the means of two normally distributed sets"),
    (("null hypothesis",), "a statement that there is no significant difference or correlation"),
    (("significance level", "statistically significant", "p = 0.05"), "a probability of 0.05, ie a 1 in 20 chance that the result happened by chance"),
    (("critical value",), "the table value the calculated statistic must reach to be significant"),
    (("correlation",), "a relationship in which the two variables change together"),
    (("causation", "causal"), "one variable actually causing the change in the other"),
    (("gis",), "a geographical information system - mapped layers of data"),
    (("remote sensing",), "collecting data from aircraft or satellites"),
    (("mark-release-recapture", "lincoln index"), "estimating population size from the proportion of marked animals recaptured"),
]

# -------------------------------------------------------------- misconceptions
MISCONCEPTIONS = [
    (("ozone layer", "ozone depletion", "cfcs"),
     "answers that make ozone depletion a cause of global warming, or that describe CFCs as physically blowing a hole - chlorine atoms catalyse the breakdown of ozone and are regenerated"),
    (("greenhouse effect",),
     "'the greenhouse effect is bad for the planet' - the natural greenhouse effect keeps the Earth habitable; it is the enhanced effect that causes the problem"),
    (("acid rain", "acidification"),
     "carbon dioxide as the main cause of acid rain - the gases responsible are sulfur dioxide and oxides of nitrogen"),
    (("eutrophication", "algal"),
     "'the algae use up all the oxygen' on its own - the oxygen is used by aerobic decomposers breaking down the dead algae"),
    (("bod", "biochemical oxygen demand"),
     "'a high BOD means the water contains a lot of oxygen' - a high BOD means a lot of oxygen will be removed"),
    (("biomagnification", "bioaccumulation"),
     "answers that swap the two terms - bioaccumulation is the build-up inside one organism, biomagnification is the rise along a food chain"),
    (("nuclear",),
     "'nuclear power releases no carbon dioxide' - mining, fuel processing, construction and decommissioning all do"),
    (("renewable", "renewables"),
     "'renewables cause no pollution at all' - manufacture, construction and the land they occupy all have impacts"),
    (("half-life",),
     "'after two half-lives nothing is left' - each half-life halves what remains, so some activity always continues"),
    (("pesticide", "pesticides", "pesticide resistance"),
     "pests 'getting used to' a pesticide - the few naturally resistant individuals survive and pass the trait on"),
    (("simpson", "diversity index"),
     "'more species always means a higher index' - the evenness of the abundances matters as well"),
    (("soil erosion",),
     "'the soil loses its nutrients' as a description of erosion - erosion is the physical loss of the soil itself"),
    (("carbon cycle",),
     "'plants breathe in carbon dioxide and breathe out oxygen' - name photosynthesis and respiration"),
    (("sustainable", "sustainability"),
     "'sustainable means it lasts a long time' - it means use that can continue without reducing what is available in future"),
    (("recycling",),
     "'recycling uses no energy' - collection, sorting and reprocessing all use energy, usually less than making the material from new"),
    (("energy loss", "low-grade heat", "wasted energy"),
     "'the energy is used up' - energy is converted, with the losses ending up as low-grade heat"),
    (("correlation",),
     "a correlation presented as proof of cause - say that it suggests a link that further work would have to test"),
    (("reliability", "reliable", "repeatability"),
     "'repeat the readings to make them more accurate' - repeats improve reliability; accuracy depends on the method and the instrument"),
    (("random sampling", "randomly", "at random", "random numbers"),
     "'pick places at random by eye' - positions have to be generated with random numbers to remove bias"),
    (("null hypothesis",),
     "'the hypothesis was proved' - a statistical test either rejects the null hypothesis or fails to reject it"),
    (("critical value", "chi-squared", "spearman", "mann-whitney", "t-test"),
     "'the result was significant' without comparing the calculated value with the critical value at p = 0.05"),
    (("anomalous", "anomaly"),
     "discarding a result only because it does not fit the expected pattern, with no reason to think it is faulty"),
    (("trophic", "food chain", "energy transfer"),
     "'energy is lost between trophic levels' on its own - say how it is lost: respiration, excretion, egestion and uneaten parts"),
    (("captive breeding", "zoo"),
     "captive breeding alone as conservation - credit needs reintroduction, habitat protection or genetic management as well"),
    (("cites",),
     "'CITES bans all trade in wildlife' - it controls and licenses trade, with different rules for each appendix"),
    (("deforestation",),
     "'trees give us the oxygen we breathe' as the main impact - credit carbon storage, soil protection, the water cycle and habitat loss"),
    (("solar panel", "solar panels", "solar cells", "photovoltaic"),
     "'solar panels do not work in cold countries' - output depends on insolation, and cells are slightly more efficient when cool"),
    (("wind turbine", "wind turbines", "wind farm", "wind power"),
     "'wind turbines can generate all the time' - output depends on wind speed, and they shut down in very high winds"),
    (("dam", "hep", "reservoir"),
     "a dam described as having no environmental impacts - flooded land, blocked fish migration, trapped sediment and methane from drowned vegetation"),
    (("gm", "genetically modified"),
     "'GM crops are unnatural' as an environmental impact - credit gene flow, resistance, effects on non-target species or reduced pesticide use"),
    (("organic farming", "organic produce", "organically"),
     "'organic farming uses no pesticides' - a restricted list of pesticides is permitted"),
    (("heavy metal", "heavy metals", "mercury", "cadmium", "lead compounds"),
     "'the body breaks the metal down' - metals are elements, cannot be broken down, and are stored in tissue"),
    (("ground-level ozone", "photochemical smog", "peroxyacyl"),
     "ground-level ozone described as protecting us from UV - that is stratospheric ozone; at ground level it is a pollutant"),
    (("landfill",),
     "'landfill gas is just carbon dioxide' - it is roughly half methane, a far stronger greenhouse gas"),
    (("lichen", "indicator species"),
     "'lichens die where the air is polluted' without naming the pollutant - it is their sensitivity to sulfur dioxide that is used"),
    (("quota", "fishing"),
     "quotas described as solving overfishing on their own - undersized fish are still caught and discarded"),
    (("albedo",),
     "'ice reflects the heat back' - albedo is the reflection of incoming short-wave solar radiation, before it is absorbed"),
    (("carrying capacity",),
     "'the population cannot grow any more' as a definition - numbers fluctuate around the carrying capacity"),
    (("succession", "climax"),
     "'the climax community never changes' - it is stable only while the conditions stay the same"),
    (("precautionary",),
     "the precautionary principle described as banning anything new - it shifts the burden of proof onto showing that harm is unlikely"),
]
