"""Index of the questions in the real AQA 7447 past papers, by topic.

Each entry: (file, question number, PDF page the question starts on, marks, subtopic slug, short title).
Question 11 (the essay choice) is listed with the subtopic of each essay title.
Pages are the page index inside the PDF (1 = cover), used for  file.pdf#page=N  links.
"""

OFFICIAL_INDEX = {
    # ---------------- Paper 1 ----------------
    "AQA-74471-QP-JUN22.PDF": [
        (1, 3, 5, "pollution-control", "Pollution control technologies (complete the table)"),
        (2, 4, 10, "fossil-nuclear", "Plutonium and thorium reactors; radioactive isotopes and half-lives"),
        (3, 8, 10, "biogeochem", "Carbon reservoirs; atmospheric CO2 calculation in standard form"),
        (4, 10, 10, "renewables", "Energy density of biofuels; elephant grass"),
        (5, 12, 10, "energy-conservation", "Loft insulation U-values"),
        (6, 16, 5, "renewables", "Wave energy devices (multiple choice)"),
        (7, 19, 10, "air-pollution", "PM10 gravimetric particle analyser"),
        (8, 22, 10, "climate-change", "El Nino, Pacific winds and ocean currents"),
        (9, 26, 10, "soils", "Soil water and organic matter content investigation"),
        (10, 28, 15, "nutrient-pollution", "Sewage treatment stages"),
        (11, 31, 25, "hydro-management", "Essay: managing water resources to meet demand while minimising impacts"),
        (11, 31, 25, "minerals", "Essay: managing mineral resources to meet demand while minimising impacts"),
    ],
    "AQA-74471-QP-JUN23.PDF": [
        (1, 2, 5, "biogeochem", "Phosphorus cycle"),
        (2, 4, 10, "minerals", "Mineral exploration techniques"),
        (3, 6, 10, "soils", "Soil texture triangle"),
        (4, 10, 10, "soils", "Soil erosion, slope gradient and land use (southern China)"),
        (5, 12, 15, "energy-features", "Pakistan's electricity generation mix"),
        (6, 17, 5, "energy-storage", "UK 24-hour electricity demand and supply mix"),
        (7, 18, 5, "hydro-cycle", "Hydrological cycle transfers and residence time"),
        (8, 21, 10, "noise", "Noise level and maximum exposure time"),
        (9, 24, 10, "water-pollution", "MV Wakashio oil spill, Mauritius"),
        (10, 26, 15, "climate-change", "El Nino events and the Peruvian anchovy catch"),
        (11, 29, 25, "pollutant-properties", "Essay: how knowledge of the properties of pollutants reduces their impacts"),
        (11, 29, 25, "energy-features", "Essay: how knowledge of the properties of energy resources reduces their impacts"),
    ],
    "AQA-74471-QP-JUN24-CR.PDF": [
        (1, 2, 5, "pollution-control", "Atmospheric pollution control technologies (complete the table)"),
        (2, 3, 10, "renewables", "UK electricity generation 1990-2020; vertical-axis wind turbines; storage"),
        (3, 6, 10, "soils", "Soil erosion and land use in the Sap drainage basin; USLE"),
        (4, 10, 10, "noise", "HS2 railway noise with distance"),
        (5, 14, 10, "biogeochem", "Human impacts on the nitrogen cycle; measuring nitrate"),
        (6, 17, 10, "climate-change", "Proxy and observed global temperature data"),
        (7, 19, 5, "sampling", "Tullgren funnel and soil organisms"),
        (8, 20, 10, "minerals", "Geological cross-section and extraction sites (multiple choice)"),
        (9, 22, 10, "radiation", "Fukushima: caesium-134 and caesium-137"),
        (10, 25, 15, "ozone", "Ozone concentration and ozone-depleting substance emissions"),
        (11, 28, 25, "pollutant-properties", "Essay: anthropogenic and environmental factors affecting the dispersal and severity of pollution"),
        (11, 28, 25, "energy-features", "Essay: anthropogenic and environmental factors affecting the choice and use of energy resources"),
    ],
    "AQA-74471-QP-NOV20-CR.PDF": [
        (1, 2, 5, "climate-change", "Greenhouse gases: residence time and global warming potential"),
        (2, 4, 5, "climate-change", "Land ice volume and sea-level rise"),
        (3, 6, 15, "fossil-nuclear", "Uranium ore grade, extraction energy and emissions"),
        (4, 10, 10, "noise", "Aircraft noise contours around an airport"),
        (5, 14, 10, "renewables", "Wind lens turbine vs conventional HAWT"),
        (6, 19, 10, "energy-storage", "Hydrogen as a secondary fuel; fuel cells"),
        (7, 23, 5, "methodology", "Representative soil sampling for a farmer"),
        (8, 24, 10, "biogeochem", "Pine plantation biomass and carbon storage"),
        (9, 28, 15, "pesticides", "Pesticide residues in food (MRL)"),
        (10, 32, 10, "hydro-cycle", "Dead Sea water budget"),
        (11, 35, 25, "air-pollution", "Essay: technology and atmospheric pollution at local, regional and global scales"),
        (11, 35, 25, "soils", "Essay: soil management and environmental damage at local, regional and global scales"),
    ],
    "AQA-74471-QP-NOV21-CR.PDF": [
        (1, 2, 5, "hydro-management", "Water treatment processes (complete the table)"),
        (2, 3, 10, "ozone", "Rowland-Molina hypothesis and CFCs"),
        (3, 6, 10, "air-pollution", "Acid rain and seed germination investigation"),
        (4, 10, 10, "minerals", "Copper ore grade and exploitable reserves"),
        (5, 12, 5, "atm-energy", "Structure of the atmosphere; temperature with altitude"),
        (6, 14, 10, "hydro-management", "Water resources and demand in India"),
        (7, 16, 10, "soils", "Agricultural practices and soil erosion; stone walls"),
        (8, 18, 10, "renewables", "UK solar PV capacity"),
        (9, 21, 10, "nutrient-pollution", "Nitrogen deposition and the harebell"),
        (10, 24, 15, "climate-change", "Bering Sea warming and species replacement"),
        (11, 28, 25, "pollution-control", "Essay: extent to which control methods reduce the impacts of pollutants"),
        (11, 28, 25, "energy-conservation", "Essay: extent to which energy conservation reduces environmental impacts"),
    ],
    "AQA-74471-SQP-CR.PDF": [
        (1, 2, 5, "energy-features", "Features of energy resources (complete the table)"),
        (2, 3, 10, "noise", "Motorway noise and road materials"),
        (3, 6, 10, "minerals", "Granite batholith and hydrothermal ore deposits"),
        (4, 10, 10, "renewables", "Wind turbine power output and blade diameter"),
        (5, 15, 5, "ozone", "CFCs and stratospheric ozone depletion"),
        (6, 16, 10, "hydro-management", "Treating borehole water for a brewery"),
        (7, 18, 5, "heavy-metals", "Minamata Bay mercury"),
        (8, 20, 10, "air-pollution", "Smoke levels: particle analyser and sampling variability"),
        (9, 22, 15, "soils", "Universal Soil Loss Equation"),
        (10, 27, 15, "climate-change", "Arctic sea ice and monitoring technologies"),
        (11, 29, 25, "energy-features", "Essay: new technologies and the impacts of energy resources"),
        (11, 29, 25, "pollution-control", "Essay: new technologies and the impacts of pollutants"),
    ],
    # ---------------- Paper 2 ----------------
    "AQA-74472-QP-JUN22-CR.PDF": [
        (1, 2, 5, "cbr-habitat", "Habitat conservation terms: rewilding, gene pool, niche, plagioclimax"),
        (2, 3, 5, "natural-systems", "Low energy-density natural processes"),
        (3, 4, 10, "human-impacts", "Culling of red foxes in France"),
        (4, 6, 10, "fishing", "Reducing by-catch: net design investigation"),
        (5, 8, 10, "sampling", "Adelie penguin colony population estimate"),
        (6, 10, 10, "food-species", "Micropropagation"),
        (7, 13, 5, "human-impacts", "Acid mine drainage, river pH and wildlife"),
        (8, 14, 15, "habitats", "Temperate broadleaf forest; canopy cover and temperature"),
        (9, 18, 15, "life-conditions", "Magnetosphere and axial tilt"),
        (10, 21, 10, "circular-economy", "Biocapacity vs global ecological footprint"),
        (11, 24, 25, "life-processes", "Essay: ecological processes and effective conservation"),
        (11, 24, 25, "dynamic-equilibria", "Essay: dynamic equilibria and sustainable human activities"),
    ],
    "AQA-74472-QP-JUN23-CR.PDF": [
        (1, 3, 5, "life-processes", "Ecological terms and definitions"),
        (2, 4, 10, "life-conditions", "How early life changed environmental conditions"),
        (3, 6, 10, "eco-monitoring", "Bat detectors and species richness"),
        (4, 10, 10, "life-processes", "Succession after glacier retreat"),
        (5, 14, 15, "habitats", "Threats to tropical vs deep-water coral reefs"),
        (6, 18, 5, "food-species", "Energy ratios of livestock systems"),
        (7, 20, 15, "food-species", "Bt corn (GM) and pollen drift investigation"),
        (8, 25, 5, "agri-impacts", "Farm income and government subsidies"),
        (9, 26, 10, "aquaculture", "Shrimp farming in India"),
        (10, 28, 10, "forests", "Causes and rates of deforestation by region"),
        (11, 31, 25, "agri-impacts", "Essay: methods to reduce the impacts of crop production"),
        (11, 31, 25, "fishing", "Essay: methods to reduce the impacts of fishing"),
    ],
    "AQA-74472-QP-JUN24.PDF": [
        (1, 2, 5, "conservation-priorities", "EDGE species (evolutionarily distinct, globally endangered)"),
        (2, 4, 10, "cbr-habitat", "Sumatran rhinoceros captive breeding"),
        (3, 6, 10, "habitats", "Antarctica: global temperature regulation and tourism"),
        (4, 8, 10, "cbr-habitat", "Nature reserve design: pond area : perimeter ratio"),
        (5, 11, 10, "agroecosystems", "Worldwide pesticide use in agriculture"),
        (6, 14, 5, "agri-impacts", "Ethical, quota and political influences on agriculture"),
        (7, 16, 10, "fishing", "Wild Atlantic salmon: sustainable exploitation grades"),
        (8, 20, 15, "aquaculture", "Disease control and intensive aquaculture"),
        (9, 23, 10, "forests", "Eucalyptus plantations and carbon sequestration"),
        (10, 28, 10, "circular-economy", "Circular economy and recycling"),
        (11, 30, 25, "conservation-priorities", "Essay: legislation, protocols and agreements to slow biodiversity decline"),
        (11, 30, 25, "agri-impacts", "Essay: agriculture adapting to and reducing climate change"),
    ],
    "AQA-74472-QP-NOV20.PDF": [
        (1, 2, 5, "sampling", "Ecological sampling activities and equipment"),
        (2, 4, 10, "human-impacts", "Rat eradication and tree abundance on a Pacific island"),
        (3, 6, 15, "cbr-habitat", "Northern pool frog reintroduction; carrying capacity"),
        (4, 10, 10, "eco-monitoring", "Living Planet Index; electronic monitoring technology"),
        (5, 13, 5, "life-conditions", "Features of Earth that make it suitable for life"),
        (6, 14, 10, "food-species", "Intensive agriculture energy inputs; orange production"),
        (7, 16, 10, "agroecosystems", "Oil palm and other oil-seed crops"),
        (8, 20, 10, "fishing", "Ocean primary productivity: upwelling, shelf and open ocean"),
        (9, 24, 10, "forests", "Woodland cover in England since 1100"),
        (10, 26, 10, "dynamic-equilibria", "Climate feedback mechanisms"),
        (11, 28, 25, "aquaculture", "Essay: reducing the environmental impacts of aquaculture"),
        (11, 28, 25, "agri-impacts", "Essay: reducing the environmental impacts of livestock production"),
    ],
    "AQA-74472-QP-NOV21.PDF": [
        (1, 3, 5, "conservation-priorities", "IUCN criteria for prioritising conservation"),
        (2, 4, 10, "human-impacts", "Owston's civet: direct exploitation"),
        (3, 6, 10, "conservation-priorities", "Monkey puzzle tree and CITES"),
        (4, 8, 10, "habitats", "Mangroves: adaptations and links to coral reefs"),
        (5, 12, 10, "agroecosystems", "Sterile insect technique (medfly)"),
        (6, 14, 5, "agroecosystems", "Systemic pesticides and soil nutrients"),
        (7, 15, 10, "fishing", "American lobster population monitoring"),
        (8, 18, 10, "aquaculture", "Water temperature and yellowtail kingfish growth"),
        (9, 22, 15, "forests", "UK forest loss and CO2"),
        (10, 28, 10, "food-species", "Embodied energy losses in the food supply chain"),
        (11, 32, 25, "cbr-habitat", "Essay: managing captive breeding and release programmes"),
        (11, 32, 25, "food-species", "Essay: genetic manipulation of food species - advantages and problems"),
    ],
    "AQA-74472-SQP-CR.PDF": [
        (1, 2, 5, "agroecosystems", "Commercial strawberry agriculture terms"),
        (2, 3, 5, "methodology", "Runoff and algal growth investigation: standardising variables"),
        (3, 5, 10, "forests", "Deforestation and insect biodiversity in fragments"),
        (4, 7, 10, "hydro-cycle", "Water table in a coastal aquifer"),
        (5, 11, 10, "eco-monitoring", "Satellite surveys of Adelie penguin colonies"),
        (6, 14, 10, "aquaculture", "Polyculture lakes in Malaysia"),
        (7, 18, 10, "agroecosystems", "Soil pH and crop yield"),
        (8, 23, 5, "conservation-priorities", "African forest elephants and the IUCN Red List"),
        (9, 24, 15, "fishing", "Atlantic mackerel vs orange roughy: overexploitation"),
        (10, 28, 15, "agroecosystems", "Neonicotinoid insecticides"),
        (11, 31, 25, "agri-impacts", "Essay: changes in food production systems and sustainability"),
        (11, 31, 25, "circular-economy", "Essay: the circular economy and sustainable lifestyles"),
    ],
}
