"""Pollution: atmospheric pollution - smoke/PM10, acid rain, NOx, hydrocarbons, CO, smogs, tropospheric ozone
(spec 3.4.3.2.1-3.4.3.2.5).  Genn pp. 245-254."""
from gen.model import Q, P, Table, Chart, Essay

T = "air-pollution"

QUESTIONS = [
    Q("AIR-01", T, "3.4.3.2.1", "245-247",
      intro="Figure 1 shows the daily deaths in London and the mean concentration of smoke in the air during the smog of December 1952.",
      figures=[Chart("line", "Date (December 1952)", "Deaths per day",
                     {"Deaths per day": [(1, 250), (2, 260), (3, 270), (4, 300), (5, 420), (6, 620), (7, 880), (8, 930), (9, 820), (10, 600), (11, 480), (12, 400), (13, 360), (14, 330)]}, y_min=0),
               Table(["Date", "3 Dec", "5 Dec", "7 Dec", "8 Dec", "10 Dec", "12 Dec"], [["Smoke / mg m^-3", "0.4", "1.5", "4.4", "4.5", "1.2", "0.5"]], caption="Table 1")],
      parts=[
          P("Describe the relationship between smoke concentration and daily deaths shown in Figure 1 and Table 1.", 2,
            ms=["Deaths rise as smoke concentration rises, peaking at about 930 per day on 8 Dec when smoke was highest (4.5 mg m^-3)",
                "Deaths fall as smoke falls but remain above the starting level for several days (time lag / delayed effect)"]),
          P("Calculate the percentage increase in daily deaths between 1 December and 8 December.", 2, calc=True, unit="%",
            ms=["(930 - 250) / 250 x 100", "= 272%"]),
          P("Explain how the weather conditions in December 1952 caused the smog to form.", 3,
            ms=["Anticyclonic conditions: clear skies allowed rapid radiation of heat from the ground at night so the ground and air near it cooled",
                "Low wind velocity so air layers did not mix; London lies in a valley / basin where cold dense air collected: a temperature inversion formed",
                "Smoke from coal fires was trapped below the inversion; moist air cooled to its dew point forming fog; smoke + fog = smog; the smog's high albedo prolonged the inversion"]),
          P("Explain why most of the deaths were among the elderly, the very young and people with existing respiratory disease.", 2,
            ms=["Smoke particles (PM10) are inhaled deeply and irritate the lungs / kill cilia so particles and bacteria are not cleared, causing bronchitis / infections",
                "These groups have weaker lungs / immune systems / less reserve so the extra stress (with sulfur dioxide acting synergistically) was fatal"]),
          P("State the legislation introduced in the UK in response to this smog.", 1, ms=["Clean Air Act (1956)"]),
      ]),

    Q("AIR-02", T, "3.4.3.2.1", "245-247",
      parts=[
          P("Describe how an <b>electrostatic precipitator</b> removes smoke particles from the effluent gases of a coal-fired power station.", 3,
            ms=["Effluent gases pass through a chamber containing electrically charged wires / plates",
                "Smoke particles become (negatively) charged and are attracted to the oppositely charged plates where they collect / stick",
                "Plates are shaken and the particles fall as fly ash which is collected (and may be used, eg in building materials)"]),
          P("Explain how a <b>cyclone separator</b> works.", 2,
            ms=["Effluent gases are forced to rotate / spin in a cylindrical chamber",
                "The (denser) particles are thrown outwards to the chamber walls where they fall and collect; cleaned gases leave through a central pipe"]),
          P("Explain why heating coal to remove tar reduces smoke emissions.", 1,
            ms=["The tar / volatile organic compounds that produce smoke on incomplete combustion are driven off, producing smokeless coal / coke"]),
          P("Explain why turbochargers reduce the smoke produced by diesel engines.", 2,
            ms=["Turbochargers deliver more air / oxygen to the combustion chamber", "So combustion is more complete and fewer unburnt carbon particles / soot are produced (especially during acceleration)"]),
          P("Explain why smaller smoke particles (PM1) are a greater health risk than larger ones.", 2,
            ms=["Smaller particles remain suspended in the atmosphere for longer so they are more likely to be inhaled", "They penetrate deeper into the lungs / alveoli and are not cleared; may carry toxic / carcinogenic chemicals"]),
      ]),

    Q("AIR-03", T, "3.4.3.2.2", "250-252",
      intro="Table 1 shows the pH of rainwater and the number of fish species in lakes in four areas of Scandinavia with different bedrock geology.",
      figures=[Table(["Lake area", "Bedrock", "Mean rainfall pH", "Mean lake pH", "Number of fish species", "Dissolved aluminium / mg dm^-3"],
                     [["A", "Granite", "4.3", "4.6", "0", "0.42"], ["B", "Granite", "4.8", "5.1", "3", "0.20"], ["C", "Limestone", "4.3", "7.2", "8", "0.01"], ["D", "Limestone", "5.5", "7.6", "9", "0.01"]])],
      parts=[
          P("State the pH below which rain is described as acid rain and explain why unpolluted rain is already slightly acidic.", 2,
            ms=["pH 5.6", "Atmospheric carbon dioxide dissolves in rainwater to form (weak) carbonic acid"]),
          P("Use Table 1 to explain why lakes in area C contain many more fish species than lakes in area A, even though the rainfall has the same pH.", 4,
            ms=["Limestone bedrock (calcium carbonate) is alkaline / basic and neutralises the acids as water percolates through it, so the lake pH stays high (7.2)",
                "Granite does not neutralise acids so lake water in A is acidic (4.6)",
                "Low pH mobilises / dissolves aluminium ions from the soil and rock (0.42 mg dm^-3 in A) which are toxic to fish (damage gills)",
                "Acids also damage fish eggs / gills (exposed living cells) and dissolve the exoskeletons of invertebrate food; lichens and other food organisms lost"]),
          P("Describe <b>two</b> effects of acid rain on non-living objects.", 2, items=2,
            ms=["Corrodes metals: railway lines, railings, pipes, pylons, overhead power lines", "Dissolves / weakens limestone and marble buildings and statues (eg York Minster)"]),
          P("Explain how sulfur dioxide released from a power station is converted to sulfuric acid in the atmosphere.", 2,
            ms=["Sulfur dioxide is oxidised (by ozone / other oxidants) to sulfur trioxide", "Sulfur trioxide dissolves in water droplets to form sulfuric acid (SO2 alone gives the weaker sulfurous acid)"]),
      ]),

    Q("AIR-04", T, "3.4.3.2.2-3.4.3.2.3", "252-253",
      parts=[
          P("Describe how sulfur can be removed from coal <b>before</b> combustion.", 2,
            ms=["Most sulfur in coal is present as (solid) iron pyrites (FeS2)", "Coal is crushed and put in a stream of flowing water: the coal is carried away while the denser pyrites are left behind (washing / streaming)"]),
          P("Describe the process of dry flue gas desulfurisation and explain how the product can be used.", 3,
            ms=["Flue gases are passed through a bed of crushed calcium carbonate (limestone)",
                "Sulfur dioxide reacts (with oxygen and calcium carbonate) to form solid calcium sulfate (and carbon dioxide)",
                "If the gases have already been cleaned of smoke, the calcium sulfate is pure enough to be sold as gypsum for building plaster"]),
          P("In wet flue gas desulfurisation the flue gases are bubbled through sodium sulfite solution. Explain <b>one</b> advantage of this method over dry FGD.", 2,
            ms=["The sodium hydrogen sulfite formed can be heated to regenerate sodium sulfite (re-used) and release concentrated sulfur dioxide",
                "The pure sulfur dioxide is a valuable raw material for making sulfur / sulfuric acid, so a waste becomes a resource"]),
          P("Explain how each of the following reduces NOx emissions.", 3, labels=["Fluidised bed combustion", "Catalytic converters", "Urea sprays"],
            ms=["Fluidised bed: increased surface area allows rapid combustion at lower temperatures so less nitrogen and oxygen react to form NOx (production prevented)",
                "Catalytic converter: platinum / palladium catalyst chemically reduces NOx back to nitrogen and oxygen gases in the exhaust",
                "Urea sprayed into the hot flue / exhaust gases reacts with NOx, converting it to nitrogen, carbon dioxide and water"]),
      ]),

    Q("AIR-05", T, "3.4.3.2.3-3.4.3.2.4", "248-249, 253-254",
      intro="Figure 1 shows the concentrations of three pollutants in the air of a large city in a valley during one sunny day.",
      figures=[Chart("line", "Time of day / hours", "Concentration / arbitrary units",
                     {"NO": [(4, 5), (6, 20), (8, 60), (10, 35), (12, 15), (14, 8), (16, 12), (18, 25), (20, 15)],
                      "NO_2": [(4, 5), (6, 10), (8, 35), (10, 55), (12, 40), (14, 25), (16, 20), (18, 30), (20, 20)],
                      "Ozone": [(4, 2), (6, 2), (8, 5), (10, 25), (12, 60), (14, 80), (16, 70), (18, 40), (20, 15)]}, y_min=0)],
      parts=[
          P("Use Figure 1 to describe how the ozone concentration changes during the day and explain the pattern.", 4,
            ms=["Ozone is very low overnight / early morning, rises from about 08:00, peaks at about 80 units at 14:00 and falls in the evening",
                "Ozone is a secondary pollutant formed by photochemical reactions requiring sunlight (UV), so it peaks in the afternoon after several hours of sunlight",
                "NO2 (from morning traffic) is broken down by UV to NO and monatomic oxygen; monatomic oxygen reacts with O2 to form ozone",
                "Ozone lags behind the NO / NO2 peaks (which are produced by the morning rush-hour traffic) because the reactions take time; falls at night when there is no sunlight"]),
          P("Explain why the early-morning peak in NO is followed by a peak in NO<sub>2</sub>.", 2,
            ms=["NO is the primary pollutant produced in engines when nitrogen and oxygen react at high temperature / pressure",
                "NO is oxidised in the atmosphere (by oxygen / ozone) to NO2, a secondary pollutant"]),
          P("Name <b>one</b> other toxic secondary pollutant produced in photochemical smogs and give one of its effects on humans.", 2,
            ms=["PANs (peroxyacetyl nitrates)", "Eye irritation / breathing difficulty / asthma / emphysema / increased risk of heart attacks (toxic at much lower concentrations than NOx)"]),
          P("Explain why cities such as Los Angeles and Mexico City are particularly prone to photochemical smogs.", 2,
            ms=["Heavy vehicle use giving high NOx and hydrocarbon emissions", "Sunny climate providing the UV for photochemical reactions", "Valley / basin topography and frequent temperature inversions trapping pollutants"]),
      ]),

    Q("AIR-06", T, "3.4.3.2.4-3.4.3.2.5", "249, 254",
      parts=[
          P("Give <b>three</b> sources of unburnt hydrocarbons in urban air.", 3, items=3,
            ms=["Unburnt fuel in vehicle exhaust gases", "Evaporation from fuel tanks / spillage at filling stations", "Solvents (paints, cleaning products)", "Aerosol propellants", "Gas leaks / fossil fuel exploitation (methane)"]),
          P("Describe <b>two</b> methods used to control hydrocarbon emissions at petrol filling stations.", 2, items=2,
            ms=["Vapours displaced from the vehicle tank are collected, condensed and returned to the main storage tank", "Vapours are passed through an activated carbon filter where the hydrocarbons adsorb onto the carbon"]),
          P("Explain how a catalytic converter controls the emissions of carbon monoxide, hydrocarbons and NOx.", 3,
            ms=["A platinum / palladium catalyst on a high surface-area honeycomb in the exhaust pipe",
                "Carbon monoxide and hydrocarbons are oxidised to carbon dioxide (and water)",
                "NOx are chemically reduced to nitrogen and oxygen"]),
          P("Explain why carbon monoxide is toxic to humans.", 2,
            ms=["Binds to haemoglobin (more strongly than oxygen) so haemoglobin cannot carry oxygen from the lungs to tissues", "Brain damage / death if enough haemoglobin is inactivated; low doses worsen chronic heart disease"]),
      ]),

    Q("AIR-07", T, "3.4.3.2.1-3.4.3.2.5", "245-254",
      parts=[
          P("Explain how the properties of smoke and of the gases involved in acid rain lead to their environmental effects, and evaluate the effectiveness of the methods used to control them.", 9, level=True,
            ms=["Smoke: solid particulates (PM10, PM5, PM1) from incomplete combustion; small particles stay suspended, penetrate lungs; toxic chemicals (acids, phenols, metals) carried on particles; high albedo cools climate; blocks light reducing photosynthesis; damages buildings",
                "Smoke smogs form under temperature inversions in valleys (London 1952, 12 000 deaths); synergism with SO2",
                "Controls: Clean Air Act 1956 (smokeless zones), smokeless fuels / gas / electricity, coal treatment, electrostatic precipitators, cyclones, bag filters, scrubbers, DPFs, better combustion; smoke smogs have largely been eliminated in UK cities",
                "Acid rain gases: SO2 (coal combustion, smelting sulfide ores) oxidised by ozone to SO3 - sulfuric acid; NOx (high temperature combustion) - nitric acid; HCl from PVC incineration; reactive gases travel long distances (transboundary pollution)",
                "Effects: pH denatures proteins / enzymes in exposed cells (gills, eggs, root hairs, stomata); dissolves exoskeletons; leaches Ca and Mg then mobilises toxic Al and Pb; corrodes metals, dissolves limestone; severity depends on bedrock (limestone neutralises)",
                "Controls: fuel desulfurisation (coal washing, hydrodesulfurisation, low-sulfur ship fuels), dry and wet FGD, fluidised bed combustion, catalytic converters, urea sprays; switching from coal to gas / renewables",
                "Evaluation: SO2 emissions in Europe have fallen dramatically and lake pH is recovering; NOx harder to control because of growing vehicle numbers; catalytic converters need lead-free fuel and warm engines; FGD is costly and produces wastes / gypsum; controlling primary pollutants also prevents secondary pollutants (ozone, PANs)",
                "Judgement on relative success of controls for particulates vs SO2 vs NOx"]),
          P("State <b>one</b> effect of tropospheric ozone on plants.", 1, ms=["Reduces growth rates of trees / crops", "Damages leaf cuticles (allowing SO2 to cause more damage)"]),
      ]),

    Q("AIR-08", T, "3.4.3.2.1-3.4.3.2.3", "245-253",
      intro="Table 1 shows the annual emissions of two pollutants in the UK in 1970 and 2015.",
      figures=[Table(["Pollutant", "Emissions in 1970 / thousand tonnes", "Emissions in 2015 / thousand tonnes", "Main source in 2015"],
                     [["Sulfur dioxide", "6 400", "220", "Energy industries"], ["Nitrogen oxides", "2 700", "930", "Road transport"]])],
      parts=[
          P("Calculate the percentage reduction in sulfur dioxide emissions between 1970 and 2015.", 2, calc=True, unit="%",
            ms=["(6400 - 220) / 6400 x 100", "= 96.6% (accept 97%)"]),
          P("Suggest <b>three</b> reasons why sulfur dioxide emissions fell by a much larger percentage than nitrogen oxide emissions.", 3, items=3,
            ms=["Switch from coal to natural gas (which is desulfurised) / closure of coal-fired power stations removed the main SO2 source",
                "Flue gas desulfurisation fitted to remaining coal plants; coal / oil desulfurisation",
                "NOx comes mainly from road transport and vehicle numbers / distance travelled increased greatly",
                "NOx is produced from air (nitrogen + oxygen) in any high-temperature combustion, so cannot be removed from the fuel like sulfur",
                "Catalytic converters only work when warm / diesel engines produce more NOx / older vehicles remained in use"]),
          P("Explain why a reduction in NOx emissions would also reduce concentrations of tropospheric ozone and PANs.", 2,
            ms=["Ozone and PANs are secondary pollutants formed by photochemical reactions involving NO2 (broken down by UV to monatomic oxygen which forms ozone)",
                "If the primary pollutant is reduced the reactants are not present so the secondary pollutants cannot form"]),
          P("Explain why lichens are used to monitor sulfur dioxide pollution.", 3,
            ms=["Lichens are very sensitive to acidic conditions / SO2 and different species have different tolerances",
                "The species present, their abundance, size / health can be used as a biotic index of the pollution level",
                "They give a long-term integrated measure of pollution rather than a single instantaneous reading; cheap, no equipment needed"]),
      ]),
]

ESSAYS = []
