"""Physical environment: the atmosphere - energy processes (spec 3.2.1.1) and ozone depletion (3.2.1.3).
Genn pp. 86-89, 108-113."""
from gen.model import Q, P, Table, Chart, Essay

QUESTIONS = [
    # ---------------- 3.2.1.1 energy processes ----------------
    Q("ATM-01", "atm-energy", "3.2.1.1", "86-89",
      intro="Table 1 shows the composition of the dry atmosphere. Figure 1 shows the changes in carbon dioxide concentration measured at a site in the northern hemisphere over one year.",
      figures=[Table(["Gas", "Percentage by volume / %"], [["Nitrogen", "78"], ["Oxygen", "21"], ["Argon and other rare gases", "0.9"], ["Carbon dioxide", "0.04"], ["Ozone", "0.000007"]]),
               Chart("line", "Month", "CO_2 concentration / ppm", {"CO_2": [(1, 412), (2, 413), (3, 414), (4, 415), (5, 416), (6, 414), (7, 411), (8, 408), (9, 407), (10, 408), (11, 410), (12, 412)]}, y_min=400, y_max=420)],
      parts=[
          P("Describe and explain the pattern shown in Figure 1.", 4,
            ms=["CO2 rises from about 412 ppm in January to a peak of 416 ppm in May, falls to a minimum of 407 ppm in September, then rises again",
                "During spring / summer, photosynthesis by plants (growing season) removes CO2 faster than respiration releases it, so the concentration falls",
                "In autumn / winter photosynthesis is reduced (leaf fall) but respiration and decomposition continue, so CO2 rises",
                "The atmosphere is in dynamic equilibrium: the concentration fluctuates around a mean; more land / vegetation in the northern hemisphere makes the cycle large"]),
          P("Explain why the atmosphere is described as being in a state of <b>dynamic equilibrium</b>.", 2,
            ms=["Natural processes that add gases (respiration, combustion, volcanoes, denitrification) are balanced by processes that remove them (photosynthesis, dissolving, nitrogen fixation)",
                "So the average composition stays the same over long timescales although the rates vary and concentrations fluctuate around a mean"]),
          P("Give <b>two</b> ways in which the atmosphere supports life other than by providing gases for biological molecules.", 2, items=2,
            ms=["Absorbs harmful UV / solar wind radiation in the stratosphere (ozone layer)", "Greenhouse gases delay the escape of infrared, keeping the surface warm (33 &deg;C warmer than without)",
                "Atmospheric pressure allows liquid water to exist", "Distributes heat from the tropics to higher latitudes by winds", "Transports water vapour to areas that would otherwise be dry"]),
          P("Name the two layers of the atmosphere most affected by human activities.", 2, items=2, ms=["Troposphere", "Stratosphere"]),
      ]),

    Q("ATM-02", "atm-energy", "3.2.1.1", "87-89",
      intro="Figure 1 shows a simplified energy budget for the Earth and its atmosphere. Values are percentages of incoming solar radiation.",
      figures=[Table(["Energy flow", "Percentage of incoming solar radiation / %"],
                     [["Reflected by clouds, dust and atmosphere", "25"], ["Reflected by the Earth's surface", "5"], ["Absorbed by the atmosphere", "20"], ["Absorbed by the Earth's surface", "50"],
                      ["Infrared emitted by the surface and absorbed by greenhouse gases", "95"], ["Infrared re-emitted by the atmosphere back to the surface", "85"], ["Infrared emitted to space", "70"]], caption="Figure 1")],
      parts=[
          P("Use Figure 1 to calculate the planetary albedo of the Earth.", 1, calc=True, unit="%", ms=["25 + 5 = 30%"]),
          P("Describe how each of the following wavelengths of electromagnetic radiation behaves in the atmosphere.", 6,
            labels=["Ultraviolet (UV)", "Visible light", "Infrared (IR)"],
            ms=["UV: short wavelength; mostly absorbed in the stratosphere by monatomic, diatomic and triatomic oxygen (ozone layer) which are formed and destroyed in a dynamic equilibrium; converted to chemical energy in these reactions; little reaches the surface",
                "Visible light: transmitted through the atmosphere easily (some reflected by clouds / dust); absorbed by the Earth's surface and converted to heat; some absorbed by chlorophyll and converted to chemical energy in photosynthesis",
                "IR: emitted by the warm surface (long-wave); absorbed by greenhouse gases (CO2, water vapour, methane) and converted to heat; the warm atmosphere re-emits IR to the surface and reduces conduction losses; some escapes to space"]),
          P("Explain why the amount of infrared re-emitted to the surface (85%) is larger than the amount emitted to space (70%).", 2,
            ms=["Greenhouse gases absorb most of the IR emitted by the surface and re-radiate it in all directions, including back down",
                "The surface is repeatedly warmed and re-emits, so the total IR exchanged between surface and atmosphere exceeds the incoming solar energy; only the net loss (70%) balances the absorbed solar energy at equilibrium"]),
          P("Explain the term <b>thermal stratification</b> of the atmosphere.", 1,
            ms=["The atmosphere forms layers (troposphere, stratosphere, mesosphere) with different temperature gradients because energy is absorbed at different altitudes (eg UV heating the stratosphere, surface heating the troposphere)"]),
      ]),

    Q("ATM-03", "atm-energy", "3.2.1.1, 3.2.2.3", "87, 96-97",
      parts=[
          P("Explain how energy absorbed in tropical regions is distributed to higher latitudes such as the UK.", 4,
            ms=["Most solar energy is absorbed at the surface in the tropics where insolation is most intense / the Sun is overhead",
                "The warm surface heats the air above; warm winds (eg south-westerlies) carry heat energy to higher latitudes",
                "Winds blowing over the oceans create currents (North Atlantic Conveyor / Gulf Stream) carrying warm water from the tropics to NW Europe",
                "Evaporation in the tropics stores latent heat in water vapour which is released when it condenses at higher latitudes; also transports water to areas that would be dry"]),
          P("Explain why the UK has milder winters than Moscow or Churchill, Canada, which are at similar latitudes.", 2,
            ms=["The North Atlantic Conveyor brings warm water from the tropics to the coast of NW Europe", "Prevailing south-westerly winds blowing over the warm sea carry the heat onto the land"]),
          P("Explain why the atmosphere would not retain liquid water if atmospheric pressure were much lower.", 2,
            ms=["Atmospheric pressure controls how easily water molecules evaporate / escape from the surface", "At low pressure water would boil / evaporate at low temperatures so all surface water would become vapour"]),
          P("Give <b>two</b> industrially important gases extracted from the atmosphere.", 2, items=2, ms=["Nitrogen", "Oxygen", "Carbon dioxide", "Argon / neon / krypton / xenon"]),
      ]),

    # ---------------- 3.2.1.3 ozone depletion ----------------
    Q("OZ-01", "ozone", "3.2.1.3", "108-109",
      parts=[
          P("Describe how ozone is formed and destroyed naturally in the stratosphere.", 3,
            ms=["UV light splits diatomic oxygen (O2) into two monatomic oxygen atoms (O)", "Monatomic oxygen reacts with diatomic oxygen to form ozone (O3)",
                "UV light also splits ozone into O2 and O; the reactions form a dynamic equilibrium which absorbs UV (converting it to chemical energy / heat)"]),
          P("Explain the properties of CFCs that made them useful, and the properties that cause ozone depletion (the Rowland-Molina hypothesis).", 6,
            labels=["Useful properties", "Properties causing ozone depletion"],
            ms=["Useful: boiling points near ambient temperature so easily liquefied under low pressure (aerosol propellants, fridge / air-conditioning coolants); dissolve grease but do not damage electrical components (solvents); non-flammable; non-toxic",
                "Persistence: chemically stable / unreactive in the troposphere so they remain long enough to be carried up to the stratosphere",
                "Dissociation by UV: in the stratosphere higher UV levels break the carbon-chlorine bonds releasing chlorine free radicals",
                "Chlorine reacts with monatomic oxygen (and ozone), preventing ozone formation; chlorine is regenerated so one atom destroys many ozone molecules; bromine / iodine act similarly"]),
          P("Explain why increased UVB reaching the Earth's surface is harmful to living organisms. Give <b>three</b> effects.", 3, items=3,
            ms=["UVB energy is absorbed by cells and breaks up biological molecules / DNA causing mutations, skin cancer, cataracts, sunburn (human health)",
                "Damage to leaf tissue and reduced photosynthesis / crop yields (plants)", "Damage to marine algae, phytoplankton, corals and planktonic larvae (marine organisms), reducing productivity and food webs"]),
          P("State what is meant by an <b>ozone hole</b>.", 1, ms=["An area where the total ozone column falls below 220 Dobson Units (normal is about 300 DU) - a level never recorded before CFC pollution"]),
          P("Give <b>one</b> reason why concentration in ppm is not used to measure ozone depletion.", 1, ms=["Concentration varies with altitude and the stratosphere is not normally sampled; Dobson Units measure the total column thickness instead"]),
          P("Give <b>one</b> reason why the first evidence for ozone depletion came from ground-based measurements.", 1, ms=["The British Antarctic Survey at Halley detected higher UV at ground level, showing ozone above had decreased (satellites above the stratosphere cannot measure downward UV directly)"]),
      ]),

    Q("OZ-02", "ozone", "3.2.1.3", "110-111",
      intro="Figure 1 shows the minimum ozone concentration recorded over Antarctica each spring between 1979 and 2015.",
      figures=[Chart("line", "Year", "Minimum ozone / Dobson Units", {"Minimum ozone": [(1979, 225), (1983, 195), (1987, 125), (1991, 110), (1995, 95), (1999, 100), (2003, 105), (2007, 110), (2011, 100), (2015, 115)]}, y_min=0, y_max=300)],
      parts=[
          P("Describe the trend shown in Figure 1.", 2,
            ms=["Minimum ozone fell steeply from about 225 DU in 1979 to about 95 DU in the mid 1990s", "Since then it has fluctuated around 100-115 DU with a slight recovery / no further decline"]),
          P("Calculate the percentage decrease in minimum ozone between 1979 and 1995.", 2, calc=True, unit="%", ms=["(225 - 95) / 225 x 100", "= 57.8% (accept 58%)"]),
          P("Explain why ozone depletion is most severe over Antarctica in spring.", 4,
            ms=["Stratospheric temperatures over Antarctica are the lowest on Earth so stratospheric clouds / ice crystals form",
                "Ice crystal surfaces allow reactions that convert the chlorine released from CFCs into chlorine molecules (Cl2) during the dark winter",
                "The polar vortex (rotating winds) prevents mixing with the rest of the atmosphere, keeping temperatures low and chlorine concentrated",
                "When sunlight returns in spring (September) it splits the chlorine molecules into free radicals that destroy ozone; levels recover by December as the vortex breaks down"]),
          P("Explain why the data in Figure 1 alone could not confirm that CFCs were the cause of the depletion, and describe how the cause was confirmed.", 2,
            ms=["Ground and satellite UV / ozone measurements show depletion but not the chemistry / correlation is not causation",
                "Air samples collected from the stratosphere by helium balloons and high-flying research aircraft detected chlorine and chlorine monoxide, confirming the Rowland-Molina hypothesis"]),
      ]),

    Q("OZ-03", "ozone", "3.2.1.3", "112-113",
      parts=[
          P("Describe the main features of the Montreal Protocol (1987).", 3,
            ms=["Manufacture and use of CFCs and other ozone-depleting substances (ODSs) phased out then banned", "HCFCs to be phased out (by 2030); some essential uses (eg halon fire extinguishers in aircraft) still permitted",
                "A fund to help (developing) countries implement the Protocol; legally binding targets (unlike the 1985 Vienna Convention)"]),
          P("For each of the following CFC uses, give the alternative process or material now used and one disadvantage of the alternative.", 4,
            labels=["Aerosol propellant", "Refrigerant"],
            ms=["Aerosols: pump-action sprays / roll-on deodorants (alternative process), or hydrocarbon propellants (propane, butane) - flammable / fire risk",
                "Refrigerants: HCFCs (less stable so break down in the troposphere, but still some ozone depletion) then HFCs (no chlorine) - more expensive, less effective, powerful greenhouse gases"]),
          P("Describe how waste CFCs from old refrigerators are disposed of safely.", 2,
            ms=["CFCs are drained from the appliance and incinerated / broken down at high temperature", "Products are CO2 and acidic gases (HCl, HF) which are neutralised with crushed lime"]),
          P("State <b>one</b> reason why the ozone layer is not expected to recover fully for many decades.", 1,
            ms=["CFCs are persistent, so those already released continue to reach the stratosphere and destroy ozone for many years; some ODSs (eg dichloromethane) are not banned"]),
      ]),

    Q("OZ-04", "ozone", "3.2.1.3, 3.2.1.2", "108-113, 105-106",
      parts=[
          P("Ozone depletion is often described as an environmental problem that has been tackled successfully. Compare the effectiveness of the methods used to restore the ozone layer with the effectiveness of attempts to tackle global climate change, and explain the reasons for the difference.", 9, level=True,
            ms=["Stages of scientific method illustrated by ozone: identification (Antarctic UV data), hypothesis (Rowland-Molina 1974), data collection / analysis (Dobson units, satellites, balloons confirming ClO), proposed solutions, enactment (Vienna 1985, Montreal 1987)",
                "Evidence of success: ozone hole area and depth stabilised and beginning to shrink; CFC concentrations in the atmosphere falling; UV levels not rising further; global ozone loss limited to about 4%",
                "Reasons for success: international recognition of serious consequences (skin cancer); agreement of nearly every country; legally binding targets with a fund for developing countries; relatively few producers / products; alternatives (HCFCs, HFCs, pump sprays, hydrocarbons) already available and cheap; no lifestyle change needed",
                "Limits: persistence of CFCs means recovery takes decades; some ODSs still used; HFC replacements are greenhouse gases",
                "Climate change contrast: greenhouse gases come from almost every human activity (energy, transport, agriculture, industry) in every country; fossil fuels underpin economies so control requires major lifestyle and economic change",
                "Agreements (Kyoto, Paris) have weaker / non-binding targets, disputes between developed and developing nations; emissions still rising; natural fluctuations, time delays and tipping points make cause-effect less clear to the public",
                "Judgement: ozone control was a technical substitution problem; climate change is a systemic one, so the ozone success is only partly transferable"]),
          P("Name the international agreement of 1985 that preceded the Montreal Protocol and state its main weakness.", 1,
            ms=["Vienna Convention for the Protection of the Ozone Layer - no legally binding goals"]),
      ]),

    Q("OZ-05", "ozone", "3.2.1.3", "108-112",
      parts=[
          P("Which of the following statements about stratospheric ozone is correct? Tick one box.", 1,
            mcq=["Ozone is destroyed only by CFCs", "Ozone absorbs mainly infrared radiation", "Ozone is formed when monatomic oxygen reacts with diatomic oxygen", "Ozone concentrations are highest at ground level"],
            ms=["C"]),
          P("Explain the difference between the roles of ozone in the stratosphere and in the troposphere.", 2,
            ms=["Stratospheric ozone is natural and beneficial: absorbs UV, protecting living organisms", "Tropospheric ozone is a secondary pollutant (from NOx photochemistry) that is toxic to plants and humans and is a greenhouse gas"]),
          P("Explain why HCFCs cause less ozone depletion than CFCs.", 2,
            ms=["HCFCs are less chemically stable / contain hydrogen so they are broken down in the troposphere", "So most do not persist long enough to reach the stratosphere where UV would release their chlorine"]),
      ]),
]

ESSAYS = [
    Essay("ESS-P1-OZONE", 1,
          "Discuss the extent to which the study of ozone depletion illustrates how scientific investigation can lead to the successful solution of an environmental problem.",
          "3.2.1.3", "108-113",
          ["Stages of investigation: identifying the issue (Halley Station UV data, Dobson unit measurements), hypothesis formation (Rowland-Molina 1974: persistence, UV dissociation, chlorine reactions), data collection (ground, satellite, balloon and aircraft air sampling detecting ClO), analysis of spatial, temporal and altitude variability, proposal of solutions, enactment",
           "Why Antarctica: low stratospheric temperatures, ice crystals, stratospheric clouds, polar vortex, spring sunlight",
           "Effects of UVB: skin cancer, cataracts, DNA damage, plant and marine damage - motivating action",
           "Solutions: Vienna Convention, Montreal Protocol - phase-out and bans, alternative processes (pump sprays), alternative materials (HCFCs, HFCs, hydrocarbons, HFAs), collection and incineration of CFCs, fund for developing countries",
           "Evaluation of success: ozone hole area / depth stabilising, CFC levels falling; limitations - persistence, remaining ODSs, HFCs as greenhouse gases, decades to full recovery",
           "Comparison with other atmospheric problems (climate change, acid rain) - why ozone was easier; role of peer review, international cooperation, availability of substitutes",
           "Conclusion on the extent to which it is a model for other issues"]),
]
