"""Physical environment: global climate change (spec 3.2.1.2).  Genn pp. 89-107 (also 370-372 sustainability, 148-152 carbon cycle)."""
from gen.model import Q, P, Table, Chart, Essay

T = "climate-change"

QUESTIONS = [
    Q("CC-01", T, "3.2.1.2", "89-90",
      intro="Table 1 shows information about some greenhouse gases.",
      figures=[Table(["Gas", "Main anthropogenic sources", "Approximate residence time", "Global warming potential (per molecule, relative to CO_2 over 100 years)"],
                     [["Carbon dioxide", "Fossil fuel combustion, deforestation, cement", "100+ years (variable)", "1"], ["Methane", "Rice paddies, cattle, landfill, gas leaks, coal mines", "About 12 years", "28"],
                      ["Nitrous oxide (NOx)", "Fertilisers, combustion", "About 120 years", "265"], ["CFCs", "Refrigerants, aerosols (now banned)", "50-100+ years", "5 000-10 000"], ["Tropospheric ozone", "Secondary pollutant from NOx and hydrocarbons", "Days-weeks", "-"]])],
      parts=[
          P("Explain the natural greenhouse effect.", 3,
            ms=["Visible light passes through the atmosphere easily and is absorbed by the Earth's surface, which warms and emits infrared",
                "Greenhouse gases (naturally water vapour and CO2) absorb infrared better than the average for the atmosphere, converting it to heat and re-emitting some back to the surface",
                "This keeps the surface about 33 &deg;C warmer than it would otherwise be"]),
          P("Use Table 1 to explain why carbon dioxide is considered the most important anthropogenic greenhouse gas even though methane and CFCs absorb far more infrared per molecule.", 3,
            ms=["CO2 is emitted in far larger quantities (every combustion process, deforestation) so its total effect is greatest",
                "CO2 has a long residence time so it accumulates; methane has a short residence time (12 years) so it is removed faster",
                "CFC emissions are now very small following the Montreal Protocol"]),
          P("Explain why reducing methane emissions would produce a faster reduction in warming than reducing CO<sub>2</sub> emissions by the same mass.", 2,
            ms=["Methane has a much higher global warming potential (28x) so each tonne removed has a bigger effect", "Its short residence time (about 12 years) means atmospheric concentrations fall quickly once emissions are cut"]),
          P("Give <b>two</b> methods of reducing methane emissions from agriculture or waste.", 2, items=2,
            ms=["Collect landfill / anaerobic digester gas and use as fuel", "Changes in cattle diet / fewer cattle / less meat consumption", "Draining rice paddies periodically", "Anaerobic digestion of manure with gas capture"]),
      ]),

    Q("CC-02", T, "3.2.1.2", "94-96",
      intro="Table 1 shows the area of Arctic sea ice in September (the annual minimum) in selected years. Figure 1 shows the mean thickness of Arctic sea ice in the same years.",
      figures=[Table(["Year", "1980", "1990", "2000", "2010", "2020"], [["September sea ice area / million km^2", "7.7", "6.2", "6.3", "4.9", "3.9"]]),
               Chart("bar", "Year", "Mean ice thickness / m", {"Thickness": [("1980", 3.6), ("1990", 3.1), ("2000", 2.6), ("2010", 2.0), ("2020", 1.6)]}, y_min=0)],
      parts=[
          P("Calculate the percentage decrease in September sea ice area between 1980 and 2020.", 2, calc=True, unit="%", ms=["(7.7 - 3.9) / 7.7 x 100", "= 49.4% (accept 49%)"]),
          P("Explain why the loss of sea ice does <b>not</b> directly raise sea level, but the loss of land ice does.", 2,
            ms=["Floating sea ice has already displaced its own mass of water; when it melts it contracts and occupies the same volume as the ice below the water line",
                "Melting land ice (glaciers, ice sheets) adds new water to the sea, increasing its volume"]),
          P("Explain how the changes shown in Table 1 and Figure 1 could lead to further warming.", 3,
            ms=["Ice and snow have a high albedo and reflect most sunlight; open sea water has a low albedo",
                "As ice area shrinks more sunlight is absorbed by the sea and converted to heat, raising temperatures", "This melts more ice: a positive feedback mechanism; thinner ice melts more easily each summer"]),
          P("Explain <b>two</b> ways in which rising temperatures cause sea level to rise.", 2,
            ms=["Thermal expansion: warmer sea water expands (slow because of the huge volume and high heat capacity; only surface water warms directly)", "Melting of land ice (glaciers, Greenland and Antarctic ice sheets) adds water to the oceans"]),
          P("Explain why the break-up of an ice shelf can increase the rate at which land ice flows into the sea.", 1,
            ms=["Ice shelves grounded on the seabed hold back / block the forward movement of the glaciers or ice sheet behind them; once removed the land ice flows faster (eg West Antarctica)"]),
      ]),

    Q("CC-03", T, "3.2.1.2, 3.2.2.3", "96-99",
      intro="Figure 1 shows the sea surface temperature anomaly in the eastern Pacific off Peru and the annual Peruvian anchovy catch for a series of years including a strong El Ni&ntilde;o event in 1997-98.",
      figures=[Chart("line", "Year", "Anchovy catch / million tonnes", {"Catch": [(1994, 11.9), (1995, 8.6), (1996, 8.9), (1997, 7.7), (1998, 1.7), (1999, 8.7), (2000, 11.3), (2001, 7.2)]}, y_min=0)],
      parts=[
          P("Describe the normal (non-El Ni&ntilde;o) pattern of winds and ocean currents in the tropical Pacific and explain why the Peruvian coast supports a rich fishery.", 4,
            ms=["Trade winds blow westwards across the Pacific near the equator, driving a surface current in the same direction",
                "Surface water moving away from South America is replaced by deep, cold water drawn upwards (upwelling) near the coast",
                "The upwelling water is rich in nutrients (nitrates, phosphates) so large algal / phytoplankton blooms occur",
                "These support a rich food web including the anchovy fishery; the water warms as it travels west"]),
          P("Explain how an El Ni&ntilde;o event caused the collapse of the anchovy catch in 1998 shown in Figure 1.", 3,
            ms=["The trade winds weaken or reverse so the surface current slows / reverses and warm water spreads east",
                "Upwelling of nutrient-rich cold water off South America stops", "Phytoplankton productivity collapses so the food web / anchovy population collapses; catch fell from about 7.7 to 1.7 million tonnes"]),
          P("Describe <b>two</b> other effects of El Ni&ntilde;o events.", 2, items=2,
            ms=["Heavy rain and floods in the normally dry coastal deserts of Peru / South America", "Drought and reduced rainfall in eastern Australia / Indonesia",
                "Droughts in NE Africa, southern Africa, China", "Fewer hurricanes in the North Atlantic / fewer cyclones in Japan"]),
          P("Suggest why some scientists link global climate change to changes in the frequency of El Ni&ntilde;o events, and why this link is uncertain.", 1,
            ms=["Events appear to be occurring more frequently and are driven by wind patterns that warming may alter, but the causes of ENSO are not fully understood and natural fluctuations make trends hard to separate"]),
      ]),

    Q("CC-04", T, "3.2.1.2, 3.2.2.3", "96-97",
      parts=[
          P("Describe the two processes that drive the North Atlantic Conveyor.", 2,
            ms=["Friction with the prevailing south-westerly winds drags surface water north-eastwards from the tropical Atlantic",
                "Water in the NE Atlantic cools, becomes denser (and more saline as ice forms) and sinks, drawing warm surface water in to replace it; the cold water returns southwards at depth (thermohaline circulation)"]),
          P("Explain how global climate change could weaken the North Atlantic Conveyor and describe the possible consequence for the climate of the UK.", 4,
            ms=["Higher temperatures melt land ice on Greenland which flows into the North Atlantic", "The fresh water dilutes the seawater, reducing its salinity and density",
                "Less dense water sinks less easily so the flow rate of the current is reduced",
                "Less heat is transported to NW Europe so the UK could become colder (like Moscow / Churchill at the same latitude) even while global temperatures rise"]),
          P("Explain why the effects of climate change on UK temperatures are difficult to predict.", 3,
            ms=["Several interconnected systems act at once over different timescales: jet stream changes may raise temperatures, a slowing Conveyor may lower them, greenhouse gases raise them",
                "Natural fluctuations (solar output, orbit) can hide or exaggerate anthropogenic change; individual events do not show trends",
                "Time delays between cause and effect (oceans take a long time to warm because of volume and heat capacity); incomplete understanding of the processes"]),
          P("Describe how deep ocean currents are monitored.", 1,
            ms=["Argo floats sink to a set depth for about 10 days, then surface and transmit temperature, salinity and position data; the sequence of positions shows current direction and speed (surface currents also by satellites and buoys)"]),
      ]),

    Q("CC-05", T, "3.2.1.2", "100-102",
      parts=[
          P("Explain why it is difficult to be certain that a particular flood or heatwave is caused by anthropogenic climate change.", 3,
            ms=["The climate naturally fluctuates (solar output, Earth's orbit) so extreme events can occur without human influence",
                "An individual event, or even several, does not show a trend; the change may be in the frequency of events which can only be assessed years later",
                "Changes occur at different time and spatial scales (local storm vs global trend); interconnected systems make attribution complex"]),
          P("Explain why historic temperature records collected in towns may overestimate global warming.", 2,
            ms=["Towns have a heat-island effect (heat emissions, dark surfaces absorbing light)", "As the town grows around the weather station the warming recorded is partly local, not global; older equipment / sparse global coverage also reduce reliability"]),
          P("Describe how each of the following sources of proxy data is used to estimate past climates and give one limitation.", 5,
            labels=["Tree rings (dendrochronology)", "Ice cores"],
            ms=["Tree rings: width of each annual ring shows the growth rate, indicating temperature / rainfall in that year; rings easily dated by counting; limitation: growth also affected by other factors (water, pests, shading), only covers the life of the tree / limited regions",
                "Ice cores: annual snow layers compact into ice; air bubbles trapped in the ice give the CO2 (and methane) concentration when trapped; oxygen isotope ratios indicate temperature; up to 800 000 years (Dome C); limitation: deep layers compressed / less distinct, dating needs radio-isotope analysis and volcanic ash layers; only polar regions",
                "Others accepted: coral growth rings; pollen in lake sediments dated by radiocarbon"]),
      ]),

    Q("CC-06", T, "3.2.1.2", "102",
      intro="Table 1 compares two types of satellite used to monitor the Earth.",
      figures=[Table(["Feature", "Low Earth Orbit (polar) satellite", "Geostationary satellite"], [["Altitude", "About 800 km", "36 000 km above the equator"], ["Orbit period", "About 1.5 hours", "24 hours (fixed position)"], ["Coverage", "Whole Earth surveyed in about 15 days", "Same third of the Earth continuously"], ["Detail", "High resolution", "Lower resolution"]])],
      parts=[
          P("Use Table 1 to explain why LEO satellites are used to monitor changes in ice cover and vegetation, whereas geostationary satellites are used to monitor weather.", 3,
            ms=["LEO: high resolution and coverage of the whole Earth (including the poles) allows detailed mapping of ice area / thickness and forest cover",
                "But each area is only revisited every 15 days so they cannot follow rapidly changing weather", "Geostationary: constant view of the same region allows continuous monitoring of cloud / storm movements, though the poles are not visible and detail is lower"]),
          P("Give <b>three</b> climate-related factors, other than ice cover, that are measured by satellite sensors.", 3, items=3,
            ms=["Wind velocity", "Ocean currents / sea surface temperature", "Wave height", "Ice thickness", "Vegetation cover", "Sea level", "Atmospheric temperature / composition"]),
          P("Explain how a computer climate model can be tested for reliability before its predictions are used.", 2,
            ms=["Data for a past year (eg 1900) are fed in and the model's prediction for a later year (eg 2000) is compared with the real outcome",
                "If the prediction matches, the model can be trusted (with caution); it is continually modified as more data are collected and differences analysed"]),
          P("Explain why representative data are essential for climate modelling.", 2,
            ms=["Models need data from all regions / oceans / altitudes; gaps (eg oceans, polar regions, past periods) introduce uncertainty into predictions",
                "Unrepresentative data (eg urban heat islands, short time series) would bias the model; remote sensing helps fill gaps"]),
      ]),

    Q("CC-07", T, "3.2.1.2, 3.6.1", "103-104, 371-372",
      parts=[
          P("Explain the difference between a negative and a positive feedback mechanism.", 2,
            ms=["Negative feedback: a change causes other changes that reduce the rate or size of the original change, re-establishing equilibrium",
                "Positive feedback: a change causes other changes that increase the original change"]),
          P("Describe <b>two</b> negative feedback mechanisms that may reduce global warming.", 4,
            ms=["Increased low-level cloud: higher temperatures increase evaporation and condensation, producing more cloud; clouds have a high albedo so more sunlight is reflected and warming is reduced",
                "Increased photosynthesis: higher temperatures and CO2 increase photosynthesis, removing CO2; if stored in woody tissue atmospheric CO2 rises less"]),
          P("Explain how melting permafrost and melting methane hydrate act as positive feedback mechanisms.", 4,
            ms=["Permafrost: frozen waterlogged Arctic soils contain dead organic matter that decomposed anaerobically producing methane trapped in the frozen ground",
                "Warming thaws the permafrost, releasing methane (a powerful greenhouse gas) and allowing further decomposition, causing more warming",
                "Methane hydrate: methane from decomposed organic matter in deep sea sediments is held as a solid under high pressure and low temperature",
                "If deep water warms the hydrate melts, releasing methane into the atmosphere and causing further warming"]),
          P("Give <b>three</b> other positive feedback mechanisms.", 3, items=3,
            ms=["Reduced albedo as snow / ice melts", "Ocean acidification reducing coral survival and carbon sequestration", "Increased forest and peat fires releasing CO2",
                "Faster decomposition of soil organic matter releasing CO2", "Increased water vapour (a greenhouse gas) in warmer air", "Increased cirrus (high) cloud which traps infrared"]),
          P("Explain what is meant by a climate <b>tipping point</b>.", 2,
            ms=["A point at which natural processes triggered by human-caused warming become self-sustaining / unstoppable",
                "So that stopping the original human activity would no longer stop climate change (eg runaway permafrost melt, methane hydrate release, forest fires)"]),
      ]),

    Q("CC-08", T, "3.2.1.2", "90-92",
      parts=[
          P("Explain how climate change may affect the survival of species. Use named examples.", 6,
            ms=["Direct effect of abiotic change: species near the edge of their range of tolerance (temperature, water) may die out locally, eg sundews if marshes dry, frogs if climate drier; beech (shallow roots) suffers in drought more than oak",
                "Changes in timing: earlier flowering / emergence may separate flowers from pollinators; plant toxins building up earlier may kill caterpillars; warmer winters disturb dormouse hibernation so they use fat reserves and starve",
                "Biotic changes: food supply, predators, disease vectors (mosquitoes / malaria spreading), pollinators and seed dispersers may change",
                "Distribution changes: species may colonise newly suitable areas (triton molluscs around the UK) but slow-growing species (trees) may disappear from old ranges faster than they colonise; suitable areas or biological corridors may not exist; human land use blocks movement",
                "Population fragmentation: rising seas or upward retreat to mountains isolate populations; divided gene pools increase inbreeding; small populations may not be viable; no repopulation from elsewhere",
                "Some species benefit (bats: warmer winters, more insects) but wetter stormier weather reduces feeding time"]),
          P("Explain why a species living in an interdependent community may be unable to move to a new area even if suitable conditions exist there.", 2,
            ms=["All the species it depends on (food plants, pollinators, prey, mycorrhizae) will not move at the same speed", "Less mobile species (plants, non-flying animals) cannot cross unsuitable areas without a biological corridor"]),
          P("Explain why polar regions warming faster than the equator affects the weather in the UK.", 2,
            ms=["The temperature difference between mid-latitude and polar air drives the jet streams; a smaller difference makes the jet stream slower and more meandering (Rossby waves)",
                "Weather systems stall over an area, giving prolonged drought or rainfall / floods; unusually cold or warm air carried north or south"]),
      ]),

    Q("CC-09", T, "3.2.1.2", "99-100, 105-108",
      intro="A low-lying coastal town in eastern England is at risk of flooding from rising sea level and more intense rainfall.",
      parts=[
          P("Describe <b>three</b> ways the town could adapt to the increased flood risk.", 3, items=3,
            ms=["Raise river banks / build sea walls, flood barriers or wave screens", "Permeable urban surfaces (gravel, soil) instead of concrete / tarmac to slow runoff",
                "River flow management: upstream dams / low soil dams / afforestation / maintained flood plains to delay runoff", "Raised buildings on stilts or floating houses", "Pumping rainwater from land below river level", "Managed retreat - abandoning land where protection costs exceed value (eg Happisburgh)"]),
          P("Explain the circumstances in which managed retreat may be chosen instead of coastal defences.", 2,
            ms=["Where the cost of flood prevention is greater than the value of what is protected, or defences would be ineffective", "Land is abandoned as water levels rise / coast erodes; defences used only where land is very important"]),
          P("Describe <b>two</b> impacts of higher temperatures on transport infrastructure.", 2, items=2,
            ms=["Road surfaces deform as tar melts - need tarmac with a higher melting point", "Rail track expands and buckles above the temperature it was pre-stretched for (27 &deg;C in UK) - relay with higher pre-stress", "Bridge damage from high river flows / debris; landslides on deforested slopes"]),
          P("Explain how carbon capture and storage (CCS) could reduce CO<sub>2</sub> emissions from a fossil fuel power station, and give <b>one</b> limitation.", 3,
            ms=["CO2 is captured from the flue gases (or carbon removed from the fuel before combustion)", "Transported by pipeline / ship / tanker and stored in depleted oil or gas fields, aquifers, or used for secondary oil recovery",
                "Limitation: developmental / expensive, uses energy (reducing efficiency), risk of leakage, limited storage sites"]),
      ]),

    Q("CC-10", T, "3.2.1.2", "89-107",
      parts=[
          P("Evaluate the success of the methods and strategies used to reduce global climate change.", 9, level=True,
            ms=["Control of greenhouse gases: energy conservation (transport, buildings, industry), renewable and nuclear energy replacing fossil fuels, CCS, reduced deforestation and afforestation (carbon sequestration), methane capture from landfill / digesters, HFC controls, changes in agriculture",
                "Geoengineering: white roofs, ocean fertilisation, solar shades - largely untried, possible unpredictable consequences",
                "International agreements: Kyoto Protocol, Paris Agreement - targets, but non-binding / uneven participation; carbon trading and taxes; comparison of per capita carbon footprints between countries",
                "Evidence of limited success: global CO2 concentrations still rising (about 280 ppm pre-industrial to over 410 ppm); temperatures up about 1 &deg;C; emissions in some developed countries falling but rising in developing economies",
                "Reasons for difficulty: fossil fuels underpin economies, need for major lifestyle change, cost, time delays and natural fluctuations masking effects, political disagreement, developing countries' right to develop",
                "Adaptation strategies (flood defences, drainage, managed retreat, infrastructure changes) reduce impacts but do not address the cause",
                "Comparison with the Montreal Protocol's success for ozone",
                "Judgement: partial success - technology exists and some regional reductions achieved, but global strategies have not yet stopped the rise; tipping points make urgency greater"]),
          P("State what is meant by a <b>carbon footprint</b>.", 1, ms=["The total greenhouse gas / CO2 emissions caused by an individual, organisation, product or country (often expressed per capita per year)"]),
      ]),

    Q("CC-11", T, "3.2.1.2", "94-96",
      intro="Figure 1 shows the monthly flow of a river in South America that is fed partly by glacier meltwater, in 1990 and 2020. The glacier feeding the river shrank considerably between the two dates.",
      figures=[Chart("line", "Month", "Mean river flow / m^3 s^-1",
                     {"1990": [(1, 18), (2, 20), (3, 22), (4, 16), (5, 12), (6, 10), (7, 9), (8, 9), (9, 10), (10, 12), (11, 14), (12, 16)],
                      "2020": [(1, 26), (2, 30), (3, 32), (4, 14), (5, 6), (6, 3), (7, 2), (8, 2), (9, 3), (10, 6), (11, 12), (12, 20)]}, y_min=0)],
      parts=[
          P("Compare the river flow in 1990 and 2020.", 3,
            ms=["2020 has higher peak flow in the wet season (32 vs 22 m^3 s^-1 in March)", "2020 has much lower dry-season flow (2 vs 9 m^3 s^-1 in July / August)",
                "Flow is much more variable / seasonal in 2020; the river almost dries up"]),
          P("Explain how the shrinking of the glacier explains the differences.", 3,
            ms=["In 1990 snow / ice stored wet-season precipitation and released it gradually as meltwater during the dry season, evening out the flow",
                "With less ice, precipitation now falls as rain / melts immediately and runs off quickly, increasing wet-season flow and flood risk", "Little stored ice remains to melt in the dry season so flow falls very low"]),
          P("Suggest <b>two</b> problems the change in flow causes for people living downstream.", 2, items=2,
            ms=["Water shortages for irrigation / drinking / HEP in the dry season", "Flooding in the wet season", "Sudden floods from ice-lake outbursts (glacial lake outburst floods)"]),
          P("Explain why a glacier can be extending down its valley yet still be losing ice volume.", 2,
            ms=["Surface meltwater flows down cracks to the base, lubricating the ice so it slides faster; if this exceeds the faster melting at the front, the front advances",
                "But if snowfall at the source has not increased, total volume falls; both retreating and extending glaciers can indicate warming"]),
      ]),
]

ESSAYS = [
    Essay("ESS-P1-CLIMATE", 1,
          "Discuss the difficulties in monitoring and predicting global climate change and evaluate the methods used to overcome them.",
          "3.2.1.2, 3.1.1.3", "89-90, 100-104, 10",
          ["Nature of the problem: interconnected atmosphere-hydrosphere-biosphere systems; changes over different time and spatial scales; natural fluctuations (solar output, orbit) masking or exaggerating anthropogenic change; time delay between cause and effect (ocean heat capacity)",
           "Limitations of historic data: sparse global coverage, unsophisticated equipment, heat island bias, no atmospheric composition records",
           "Proxy data and their reliability: dendrochronology, coral growth rings, pollen in dated sediments, ice cores (gas bubbles, isotope ratios, volcanic ash layers, compaction problems)",
           "Modern monitoring: long-term data sets (Mauna Loa), electronic equipment, satellites (LEO vs geostationary), Argo floats, remote sensing of ice thickness / area / sea level",
           "Feedback mechanisms and tipping points adding uncertainty; ecological uncertainty (species survival, distribution, fragmentation)",
           "Computer models: how they are tested and refined; importance of accurate representative data; scenario-based predictions and ranges",
           "Uncertainty over ENSO / Conveyor / jet stream responses",
           "Evaluation and conclusion: confidence in the overall trend and human cause despite detailed uncertainty; role of peer review and international bodies (IPCC)"]),
    Essay("ESS-P1-FEEDBACK", 1,
          "Explain how feedback mechanisms and tipping points influence the rate of global climate change and discuss the implications for the strategies needed to control it.",
          "3.2.1.2, 3.6.1", "103-107, 371-372",
          ["Negative feedback: increased low-level cloud (albedo), increased photosynthesis and sequestration; hydrological cycle evaporation-precipitation",
           "Positive feedback: melting permafrost (methane), reduced albedo of snow / ice / sea ice, methane hydrate release, ocean acidification and coral loss, forest and peat fires, soil decomposition, water vapour, cirrus clouds",
           "Tipping points: self-sustaining processes; why control must precede them; examples",
           "Implications: urgency and precautionary principle; need for deep cuts in greenhouse gases (energy, transport, buildings, agriculture, forestry, CCS) rather than only adaptation; geoengineering risks",
           "Difficulty of prediction because feedbacks interact at different scales; models; international agreements and per capita footprints",
           "Judgement on whether current strategies are adequate"]),
]
