"""Paper 1 additions (second batch): atmosphere energy processes, water supply and treatment,
pollution-control principles, solar power, heavy metals and solid wastes.  Mostly 5- and
15-mark questions so mock papers can use the real AQA (2 x 15, 5 x 10, 3 x 5) pattern.
Genn pp. 86-89, 122-127, 199-203, 243-245, 275-285, 303-304."""
from gen.model import Q, P, Table, Chart, Essay

QUESTIONS = [
    # ---------------- 3.2.1.1 atmosphere: energy processes ----------------
    Q("ATM-04", "atm-energy", "3.2.1.1", "86-88",
      parts=[
          P("Which gas makes up about 21% of the dry atmosphere by volume? Tick <b>one</b> box.", 1,
            mcq=["Nitrogen", "Oxygen", "Argon", "Carbon dioxide"], ms=["Oxygen"]),
          P("Explain why it is difficult to predict the effect of a human activity on atmospheric processes.", 2,
            ms=["A change to one process causes other processes to alter as a direct result (chains of linked processes / feedback)",
                "There is still a lot that is not understood about how atmospheric processes work"]),
          P("Explain how winds transport both energy and water to areas such as the UK.", 2,
            ms=["The surface warmed in the tropics heats the air above; warm winds (south-westerlies from the Caribbean) carry heat energy to higher latitudes",
                "Winds carry water vapour (evaporated from warm oceans) to areas that would otherwise receive little precipitation"]),
      ]),

    Q("ATM-05", "atm-energy", "3.2.1.1", "87-89",
      intro="Table 1 shows the mean surface temperature of the Earth with and without an atmosphere containing greenhouse gases.",
      figures=[Table(["Condition", "Mean surface temperature / &deg;C"], [["No greenhouse effect", "-18"], ["Natural greenhouse effect", "15"]])],
      parts=[
          P("Use Table 1 to calculate the warming produced by the natural greenhouse effect.", 1, calc=True, unit="&deg;C", ms=["15 - (-18) = 33 &deg;C"]),
          P("Explain how the natural greenhouse effect warms the Earth's surface.", 4,
            ms=["Visible light passes easily through the atmosphere and is absorbed by the surface, which warms",
                "The warm surface emits (long-wave / far) infrared radiation", "Greenhouse gases (water vapour, CO<sub>2</sub>, methane) absorb infrared better than the average for the atmosphere and convert it to heat",
                "The warm atmosphere emits infrared which is absorbed by the surface, and it reduces heat loss from land and oceans by conduction"]),
          P("Explain what is meant by a <b>greenhouse gas</b>.", 1, ms=["Any gas that is better at absorbing infrared radiation than the average for the atmosphere"]),
          P("The wavelengths of radiation arriving at the Earth are different from those leaving. Describe this difference and explain why it matters to the energy budget.", 2,
            ms=["Arriving: mainly ultraviolet, visible light and near infrared (short wavelength); leaving: mainly long-wavelength (far) infrared",
                "Gases that are transparent to the incoming short wavelengths can absorb the outgoing long wavelengths, so changing their concentration changes how much energy is retained"]),
          P("Explain why a change in the movement of energy through the atmosphere could affect the distribution of species.", 2,
            ms=["The energy and the processes it drives control climate, ocean currents and the hydrological cycle",
                "These determine the abiotic conditions (temperature, rainfall) that each species is adapted to, so a change alters where species can survive"]),
      ]),

    Q("ATM-06", "atm-energy", "3.2.1.1, 3.2.1.3", "86-89, 108-113",
      intro="Table 1 shows the three forms of oxygen found in the stratosphere.",
      figures=[Table(["Form of oxygen", "Number of atoms per molecule"], [["Monatomic oxygen (O)", "1"], ["Diatomic oxygen (O<sub>2</sub>)", "2"], ["Triatomic oxygen / ozone (O<sub>3</sub>)", "3"]])],
      parts=[
          P("Explain how the three forms of oxygen protect life at the surface from ultraviolet radiation.", 3,
            ms=["Together they form a dispersed layer in the stratosphere (the ozone layer / ozonosphere)",
                "They absorb ultraviolet light, which drives a dynamic equilibrium of reactions that form and destroy ozone",
                "The UV energy is converted to chemical / heat energy so most UV that passed the upper atmosphere never reaches the surface"]),
          P("Give <b>two</b> other ways in which the atmosphere supports life.", 2, items=2,
            ms=["Provides carbon, oxygen, hydrogen and nitrogen (as N<sub>2</sub>, O<sub>2</sub>, CO<sub>2</sub>, H<sub>2</sub>O) for biological molecules", "Delays the escape of infrared energy, keeping the surface warm",
                "Distributes heat and water vapour by winds / ocean currents", "Provides atmospheric pressure so liquid water can exist", "Deflects damaging radiation of the solar wind in the upper atmosphere"]),
          P("Explain why the atmosphere is thermally stratified into layers.", 1,
            ms=["Energy is absorbed at different altitudes (eg UV absorbed in the stratosphere, surface heating warms the troposphere) so temperature gradients change with altitude, producing layers"]),
          P("The troposphere and stratosphere are the layers most affected by human activities. Discuss how human activities alter the energy processes in these two layers and evaluate the difficulties of predicting the consequences.", 9, level=True,
            ms=["Troposphere: enhanced greenhouse effect - anthropogenic CO<sub>2</sub> (fossil fuels, deforestation), methane (rice, livestock, landfill), N<sub>2</sub>O, CFCs, tropospheric ozone; more infrared absorbed and re-emitted; aerosols and smoke increase albedo / scatter light; land-use change alters surface albedo and evapotranspiration",
                "Stratosphere: CFCs / halons / HCFCs release chlorine and bromine which catalyse ozone destruction, shifting the O / O<sub>2</sub> / O<sub>3</sub> equilibrium; less UV absorbed in the stratosphere, more reaches the surface; stratospheric cooling",
                "Consequences: changes to climate, ocean currents (thermohaline), hydrological cycle, sea level, species distributions; increased UV damage to organisms",
                "Difficulties of prediction: linked processes where one change alters others; feedback (positive and negative) and tipping points; time lags (ocean heat capacity, long residence times of CFCs and CO<sub>2</sub>); natural variability (solar output, volcanoes, Milankovitch cycles); incomplete understanding of atmospheric processes; limited historical data so proxies needed; models with different assumptions",
                "Evaluation: some effects well understood (greenhouse physics, ozone chemistry proven, Montreal Protocol success) but scale and timing of regional impacts uncertain; precautionary principle",
                "Justified conclusion"]),
      ]),

    # ---------------- 3.2.2.4-3.2.2.5 water supply, treatment & conservation ----------------
    Q("HYD-11", "hydro-management", "3.2.2.5", "122-123",
      parts=[
          P("Which of the following is a feature of a river that affects its usefulness as a water source? Tick <b>one</b> box.", 1,
            mcq=["Its total annual discharge", "The albedo of its surface", "Its salinity", "The age of its bedrock"], ms=["Its total annual discharge"]),
          P("Explain why rainwater collection is increasingly important in cities such as those in India.", 2,
            ms=["Public supplies cannot match consumer demand / the water is often cleaner than rivers", "It also reduces urban flooding after heavy rain; surplus can be used for aquifer recharge"]),
          P("Explain why an estuary barrage has fewer land-use conflicts than a reservoir on land but still causes environmental problems.", 2,
            ms=["The reservoir is created in the estuary so no farmland / settlements need to be flooded",
                "But it changes important inter-tidal habitats, obstructs shipping and can be polluted by activities anywhere in the river's catchment"]),
      ]),

    Q("HYD-12", "hydro-management", "3.2.2.4", "126-127",
      intro="Table 1 shows the water quality required for four different uses.",
      parts=[
          P("Complete Table 1 by giving the quality requirement for each water use and the reason for it.", 4,
            table=Table(["Water use", "Quality requirement", "Reason"],
                        [["Potable (public) supply", "", ""], ["Spray irrigation", "", ""], ["Power station condenser cooling", "", ""], ["Industrial boiler water", "", ""]], blank=True, col_widths=[4.5, 5.5, 5]),
            ms=["Potable: no pathogens, toxins at acceptable levels, looks / smells / tastes good - public health, consumer complaints",
                "Spray irrigation: low turbidity, low toxins such as heavy metals - blockage of pipes, contamination of food",
                "Condenser cooling: no gross solids - pipe blockage", "Boiler water: no dissolved minerals / soft water - mineral deposits reduce heat exchange and block pipes"]),
          P("Explain why aeration is used in the treatment of water from anaerobic sources.", 2,
            ms=["Raises dissolved oxygen and removes hydrogen sulfide (bad-egg smell) from decay of organic matter",
                "Some dissolved toxic / bad-tasting metals become insoluble when oxidised and can be removed"]),
          P("Explain how flocculation removes clay particles that sedimentation cannot.", 2,
            ms=["Clay particles carry electrostatic charges that make them repel each other so they stay suspended",
                "Flocculants such as aluminium sulfate (alum) or polyelectrolytes neutralise the charges so the particles clump and settle in the clarifier"]),
          P("Give <b>two</b> methods used to sterilise treated water.", 2, items=2, ms=["Chlorine", "Ozone", "Ultraviolet light"]),
      ]),

    Q("HYD-13", "hydro-management", "3.2.2.4-3.2.2.5", "122-127",
      intro="Figure 1 shows the river level below a reservoir site during one year, before and after a river-regulation reservoir was built.",
      figures=[Chart("line", "Month", "River level / m", {"No reservoir": [(1, 3.6), (2, 3.9), (3, 3.2), (4, 2.4), (5, 1.6), (6, 1.0), (7, 0.7), (8, 0.8), (9, 1.4), (10, 2.6), (11, 3.5), (12, 3.8)],
                                                          "With reservoir": [(1, 2.6), (2, 2.7), (3, 2.5), (4, 2.3), (5, 2.0), (6, 1.8), (7, 1.7), (8, 1.7), (9, 1.9), (10, 2.2), (11, 2.5), (12, 2.6)]}, y_min=0, y_max=4.5)],
      parts=[
          P("Use Figure 1 to calculate the reduction in the annual range of river level produced by the reservoir.", 2, calc=True, unit="m",
            ms=["No reservoir range = 3.9 - 0.7 = 3.2 m; with reservoir = 2.7 - 1.7 = 1.0 m", "Reduction = 2.2 m"]),
          P("Explain how the reservoir produces the changes shown in Figure 1.", 2,
            ms=["After heavy rainfall surplus water is stored, reducing peak flows / flooding downstream",
                "During dry periods the dam is opened to release water and maintain river levels"]),
          P("Explain why human activities in the catchment may have increased the extremes in river flow before the reservoir was built.", 2,
            ms=["Deforestation / urbanisation reduce infiltration and interception", "So runoff reaches the river faster after rain and less water is stored to maintain flow in dry periods"]),
          P("Discuss the factors that should be considered when selecting a site for a new reservoir, and evaluate the alternative strategies for increasing the sustainability of water supplies.", 9, level=True,
            ms=["Site factors: topography - narrow exit from a large deep basin so a small dam holds a large volume; impermeable, strong bedrock without faults or seismic activity; large catchment with regular high rainfall and low evaporation; catchment land use with low pollution risk (pesticides, industry) and low soil erosion to avoid sedimentation; forest / vegetation in the flooded area decaying anaerobically releasing methane; access for workers and materials and distance to demand; value of the land lost (urban, conservation, agricultural) - loss-benefit analysis differs between countries",
                "Alternatives for supply: rainwater collection, rivers, estuary barrages, desalination (energy-intensive so only where freshwater is inadequate), unexploited aquifers (N Africa, Kenya), inter-basin transfers (China, Australia, Wales-England), artificial aquifer recharge using surplus wet-season water, river-regulation reservoirs, afforestation to even out flow",
                "Conservation strategies: low-water appliances, dual-flush toilets, xeriscaping, drip irrigation, grey-water re-use, leak repair (about 20% lost in the UK), metering",
                "Treatment / pollution control allowing re-use of contaminated sources: sewage treatment, buffer strips, mine drainage control",
                "Evaluation: reservoirs give large reliable supplies and flood control but flood land, cause habitat loss and methane; conservation is cheap and quick but limited by behaviour; transfers create conflicts between regions; desalination has high energy / carbon cost; combination needed as demand grows",
                "Justified conclusion"]),
      ]),

    # ---------------- 3.4.3.1 / 3.4.3.3 principles of pollution control ----------------
    Q("PCON-06", "pollution-control", "3.4.3.1", "243-244",
      parts=[
          P("Which of the following best describes the <b>precautionary principle</b>? Tick <b>one</b> box.", 1,
            mcq=["A waste is assumed to cause pollution until research shows it is unlikely to do so", "The polluter must pay for any damage caused", "Emissions should be as low as reasonably achievable",
                 "Only pollutants known to be toxic need to be controlled"], ms=["A waste is assumed to cause pollution until research shows it is unlikely to do so"]),
          P("Explain why the polluter pays principle works best when penalties are high and enforcement is reliable.", 2,
            ms=["If the cost of preventing damage is less than the (penalty for) damage there is a financial incentive to prevent pollution",
                "If polluters can escape their responsibilities / penalties are low, there is little incentive to comply"]),
          P("Give <b>two</b> choices about emission location that reduce the severity of pollution.", 2, items=2,
            ms=["Marine discharges where currents dilute and disperse emissions", "Emissions downwind of urban areas", "Not discharging waste onto permeable rock above an aquifer"]),
      ]),

    Q("PCON-07", "pollution-control", "3.4.3.1, 3.4.3.3", "243-245, 303-304",
      intro="A nuclear fuel reprocessing plant discharges small amounts of radioactive material in liquid effluent to a coastal sea.",
      parts=[
          P("Explain why it cannot be assumed that the discharge will be diluted to insignificant levels.", 2,
            ms=["Natural processes may concentrate the material (eg adsorption onto sediments, bioaccumulation and food-chain concentration)",
                "It may be carried to locations where it is hazardous, such as fishing grounds or beaches used by people"]),
          P("Give <b>four</b> factors that would be included in a Critical Pathway Analysis of this discharge.", 4, items=4,
            ms=["Physical state of the effluent (solution / solid)", "Ocean currents / river flow", "Effect of pH and oxygen on solubility", "Bioaccumulation and food-chain concentration",
                "Food sources and consumption by local people (eg shellfish, seaweed)", "Half-lives of the isotopes", "Meteorological conditions for any gaseous release", "Nature of the environment - geology, vegetation"]),
          P("Explain how the results of the analysis reduce the cost of environmental monitoring.", 2,
            ms=["Monitoring focuses on the sites most at risk of contamination", "No need to sample sites that were never likely to be polluted; sampling checks the accuracy of the predictions"]),
          P("Explain why Critical Group Monitoring measures exposure rather than damage to health.", 2,
            ms=["It assesses the risk to the people most exposed because of their lifestyle before any health effects occur",
                "If their risk is acceptably low everyone else has a lower risk; if unacceptable, emissions are reduced to prevent future exposure"]),
      ]),

    # ---------------- 3.3.4.1 solar power (15 marks) ----------------
    Q("REN-09", "renewables", "3.3.4.1", "199-203",
      intro="Table 1 shows the mean daily solar energy received on a horizontal surface at three locations.",
      figures=[Table(["Location", "Latitude", "Mean solar energy in June / kWh m^-2 day^-1", "Mean solar energy in December / kWh m^-2 day^-1"],
                     [["Sahara desert", "25&deg;N", "7.8", "4.2"], ["Southern England", "51&deg;N", "5.0", "0.7"], ["Northern Norway", "69&deg;N", "4.6", "0.0"]])],
      parts=[
          P("Use Table 1 to calculate how many times more solar energy is received in December in the Sahara than in southern England.", 1, calc=True, unit="times", ms=["4.2 / 0.7 = 6"]),
          P("Explain why northern Norway receives more solar energy in June than in December.", 2,
            ms=["Long summer days (almost 24 hours of daylight) so the total energy received is high, even though the Sun is low",
                "In winter days are very short / the Sun does not rise, so light levels are extremely low"]),
          P("Explain why concentrating solar power systems using parabolic reflectors only work where there is no cloud.", 2,
            ms=["Reflectors can only focus parallel rays of direct sunlight onto the absorber", "Clouds, smoke and dust scatter the light so it cannot be focused and intensified"]),
          P("Explain why the low energy density of solar power is a problem for large-scale generation.", 1,
            ms=["Very large areas of collectors are needed to harness significant amounts of energy (and the changing angle of incidence reduces it further)"]),
          P("Evaluate the extent to which new technologies could overcome the problems of using solar power as a large-scale energy resource.", 9, level=True,
            ms=["Problems: intermittency (daily and seasonal cycles), unpredictable cloud cover, low energy density, changing angle of incidence, land requirements, water for cleaning in deserts, toxic wastes in manufacture (silicon tetrachloride, cadmium), efficiency loss at high temperature",
                "Photothermal: evacuated tubes reduce conduction / convection losses; thermal stores (water, sand, concrete, molten salt) allow later use; passive solar architecture, brise soleil, light tubes; heat pumps deliver up to four times the energy used",
                "Photovoltaic developments: multijunction cells absorbing more wavelengths, anti-reflective / moth-eye textured surfaces (smooth cells reflect 30%), PV-thermal hybrids cooling the cell, transparent PV in windows, heliostats keeping the optimum angle, self-cleaning nanohydrophobic surfaces",
                "Concentrating solar power with molten-salt storage to 550 &deg;C so steam turbines run when needed - overcomes intermittency",
                "Integration: grid-connected solar farms, rooftop space avoiding land conflicts, batteries, pumped storage, links to energy storage and demand management",
                "Evaluation: strong in sunny deserts / low latitudes, weaker in high latitudes in winter; cost falling; manufacturing impacts; no single technology solves all problems; justified conclusion"]),
      ]),

    # ---------------- 3.4.3.2.11 heavy metals (5) ----------------
    Q("HM-06", "heavy-metals", "3.4.3.2.11", "275-279",
      parts=[
          P("Which chemical form of mercury is most easily absorbed and biomagnified in food chains? Tick <b>one</b> box.", 1,
            mcq=["Elemental (liquid) mercury", "Inorganic mercury compounds", "Organic (methyl) mercury", "Mercury vapour"], ms=["Organic (methyl) mercury"]),
          P("Explain why anaerobic sediments increased the hazard of the inorganic mercury discharged at Minamata.", 2,
            ms=["Anaerobic microbes converted the inorganic mercury into organic methyl mercury",
                "Methyl mercury is liposoluble so it is absorbed, crosses into the brain and biomagnifies along the food chain to fish eaten by people"]),
          P("Explain why heavy metal wastes are stored under alkaline conditions.", 2,
            ms=["Most heavy metals are less soluble at high pH", "So they remain immobile and are not leached into water or absorbed by organisms"]),
      ]),

    # ---------------- 3.4.3.2.12 solid wastes (5) ----------------
    Q("SW-06", "solid-waste", "3.4.3.2.12", "279-285",
      parts=[
          P("Which of the following is the main advantage of composting organic waste rather than landfilling it? Tick <b>one</b> box.", 1,
            mcq=["Aerobic decomposition produces little methane and returns nutrients to the soil", "It produces more electricity", "It removes heavy metals", "It destroys asbestos fibres"],
            ms=["Aerobic decomposition produces little methane and returns nutrients to the soil"]),
          P("Explain why the ash from waste incinerators must be disposed of carefully.", 2,
            ms=["It may contain concentrated heavy metals / toxic residues", "It is stored in solid form at high pH / in hazardous-waste landfill so the metals stay insoluble"]),
          P("Give <b>two</b> features of a well-managed landfill site that reduce pollution.", 2, items=2,
            ms=["Impermeable polymer / clay liner to stop leachate escaping", "Collection and treatment of leachate", "Collection of methane and use as fuel", "Daily covering of waste / final capping and restoration"]),
      ]),
]

ESSAYS = [
    Essay("ESS-P1-ATMOS", 1,
          "Discuss how the atmosphere supports life on Earth and evaluate the extent to which human activities threaten these life-support functions.",
          "3.2.1", "86-113",
          ["Composition and structure: N<sub>2</sub>, O<sub>2</sub>, Ar, CO<sub>2</sub>, ozone; troposphere and stratosphere; pressure and liquid water; gases for biological molecules and industry",
           "Energy processes: UV absorbed by O / O<sub>2</sub> / O<sub>3</sub> dynamic equilibrium; visible light absorbed at the surface; infrared absorbed by greenhouse gases (33 &deg;C warming); heat distribution by winds and ocean currents; transport of water vapour; energy budget and albedo",
           "Global climate change: anthropogenic greenhouse gases, sources, feedback and tipping points, consequences for climate, sea level, currents, species; difficulties of monitoring and prediction; control strategies and agreements",
           "Ozone depletion: CFCs and halons, catalytic destruction, effects of UV, Montreal Protocol and replacements, recovery time",
           "Other threats: aerosols, smoke, land-use change; interconnection of processes",
           "Evaluation: which functions are most at risk; success of ozone controls vs slow progress on greenhouse gases; justified conclusion"]),
    Essay("ESS-P1-WATERSUPPLY", 1,
          "Discuss the strategies that can be used to provide sustainable supplies of water for a growing population.",
          "3.2.2.4-3.2.2.5", "114-127",
          ["Context: uneven distribution of water, growing population and per capita demand, unsustainable exploitation of rivers and aquifers, hydrological cycle links",
           "New sources: rainwater collection, rivers (discharge, fluctuations, contaminants), reservoirs and site selection, estuary barrages, desalination, unexploited aquifers",
           "Management: artificial aquifer recharge, river-regulation reservoirs, inter-basin transfers, afforestation",
           "Conservation: low-water appliances, xeriscaping, drip irrigation, grey water, leak reduction, metering; pollution control to protect sources",
           "Treatment: matching quality to use; screens, sedimentation, aeration, flocculation, filtration, sterilisation, pH adjustment, activated carbon, reverse osmosis",
           "Evaluation of costs, energy, environmental impacts (habitat loss, methane, inter-tidal habitats, conflicts) and justified conclusion"]),
    Essay("ESS-P1-SOLAR", 1,
          "Discuss how the properties of solar power and hydroelectric power affect their use, and evaluate how new technologies could increase their contribution to energy supplies.",
          "3.3.4.1", "196-203, 217-224",
          ["Problematic properties of solar: intermittency, unreliability from cloud, low energy density, changing angle; locational constraints (deserts, latitude)",
           "Harnessing solar: photothermal, thermal stores, passive architecture, heat pumps, PV principles and cell efficiencies, solar farms; environmental impacts of manufacture and land use",
           "New solar technologies: multijunction, anti-reflective surfaces, CSP with molten salt, PV-thermal hybrids, transparent PV, heliostats, self-cleaning",
           "HEP: gravitational potential energy, locational constraints (catchment, rainfall, turbidity, impermeable rock, seismic, topography, land use, distance), impacts on habitats, sediment, methane, communities",
           "Energy storage and matching supply to demand: pumped storage, batteries, grid links; combining resources",
           "Evaluation and justified conclusion on how far these resources can replace fossil fuels"]),
    Essay("ESS-P1-RESEARCH", 1,
          "Discuss how the design of a sampling programme and the choice of statistical analysis affect the validity of conclusions drawn from environmental investigations.",
          "3.7", "390-393, 420-423",
          ["Attributes: accuracy, precision, representative samples, reliability, anomalies, validity; hypothesis and null hypothesis; preliminary studies",
           "Sampling design: random vs systematic location and avoiding bias; timing (diurnal, seasonal, long-term, weather); sample size and number and the running mean; standardisation of technique and control of other variables",
           "Techniques for abiotic and biotic factors and their limitations (quadrats, transects, traps, mark-release-recapture assumptions, keys, meters and calibration)",
           "Statistics: variability, standard deviation and error bars, significance and p-values, correlation vs causation; choosing Spearman's rank, chi-squared, t-test, Mann-Whitney U",
           "Application to Paper 1 topics: monitoring pollution (noise, air quality, water), climate proxies, energy surveys, soil analysis",
           "Evaluation of trade-offs (cost, time, disturbance) and justified conclusion"]),
    Essay("ESS-P1-MONITORTECH", 1,
          "Evaluate the contribution of new technologies to the monitoring and understanding of environmental change in the physical environment.",
          "3.2, 3.7", "9, 89-107, 402-407",
          ["Historical data limitations; proxy data - ice cores, isotope ratios (O-18:O-16, C-14), Mg:Ca in calcite, tree rings, pollen, coral",
           "Satellite sensors: visible light imagery, infrared for vegetation and temperature, radar microwaves for wind, wave height, sea level and oil, weather monitoring; passing through cloud",
           "Sensor carriers: ROVs / drones, AUVs, balloons, aircraft, animals; data recorders for abiotic factors; GPS tracking of floats and sampling sites; Argo floats and ocean monitoring",
           "Climate models and their assumptions; monitoring atmospheric composition (Mauna Loa), ozone (Dobson units), sea level and ice",
           "Applications to hydrosphere, minerals (remote sensing surveys), soils, pollution monitoring",
           "Evaluation: improved coverage and resolution vs cost, calibration, interpretation, remaining uncertainty; justified conclusion"]),
]
