"""Physical environment: the hydrosphere (spec 3.2.2).  Genn pp. 114-128."""
from gen.model import Q, P, Table, Chart, Essay

QUESTIONS = [
    # ---------------- hydro-cycle: 3.2.2.1-3.2.2.3 ----------------
    Q("HYD-01", "hydro-cycle", "3.2.2.1", "115-116",
      intro="Table 1 shows the volume of water in some reservoirs of the hydrological cycle and the annual transfer rates through them.",
      figures=[Table(["Reservoir", "Volume / x 10^15 dm^3", "Annual transfer (inflow = outflow) / x 10^15 dm^3 yr^-1", "Percentage of global water / %"],
                     [["Oceans", "1 340 000", "425", "97"], ["Ice caps and glaciers", "24 000", "3", "1.7"], ["Groundwater", "23 000", "12", "1.7"], ["Lakes and rivers", "180", "40", "0.013"], ["Soil moisture", "17", "80", "0.001"], ["Atmosphere", "13", "480", "0.001"]])],
      parts=[
          P("The residence time of water in a reservoir is given by: residence time = volume in reservoir / annual transfer rate. Use Table 1 to calculate the residence time of water in the atmosphere. Give your answer to the nearest whole day.", 3, calc=True, unit="days",
            ms=["13 / 480 = 0.0271 years", "0.0271 x 365", "= 10 days (accept 9.9-10)"]),
          P("Calculate the residence time of water in the oceans.", 1, calc=True, unit="years", ms=["1 340 000 / 425 = 3153 years (accept 3100-3200)"]),
          P("Explain why the atmosphere is an important reservoir even though it holds only 0.001% of global water.", 2,
            ms=["It has a very short residence time / very rapid transfer rate (480 x 10^15 dm^3 per year)", "So it moves large volumes of water each year, delivering precipitation to land; small reservoirs with fast transfers respond quickly to change"]),
          P("Explain why human changes to a small reservoir such as soil moisture are more obvious than changes to the oceans.", 2,
            ms=["The ocean is so large that an added or removed volume is a tiny proportion of the total", "The same volume is a large proportion of a small reservoir so its level / residence time changes noticeably"]),
          P("Explain why the hydrological cycle is described as being in dynamic equilibrium.", 2,
            ms=["Water is constantly moving between reservoirs (evaporation, precipitation, runoff, infiltration, transpiration)", "But inflows and outflows for each reservoir balance so the volume in each reservoir stays constant over long periods"]),
      ]),

    Q("HYD-02", "hydro-cycle", "3.2.2.1", "116-117",
      parts=[
          P("Explain how each of the following human activities alters processes in the hydrological cycle.", 6,
            labels=["Deforestation", "Urban development", "Agriculture"],
            ms=["Deforestation: less interception so less evaporation from leaves; less transpiration so less water returned to the atmosphere and less precipitation downwind; more infiltration and surface runoff, higher river flows / flooding",
                "Urban development: impermeable concrete / tarmac reduce infiltration and aquifer recharge; runoff is faster and greater, increasing river flooding downstream; drains carry water quickly to rivers",
                "Agriculture: soil compaction by machinery / trampling reduces infiltration and soil moisture, increases runoff; irrigation increases evaporation; loss of soil biota (worms) reduces infiltration and water retention; drainage lowers water tables"]),
          P("Describe <b>two</b> ways in which global climate change alters the hydrological cycle.", 2, items=2,
            ms=["Higher temperatures increase evaporation and change the amount, timing, type (rain vs snow) and location of precipitation", "More rapid melting of snow and ice changes river regimes: more flooding after rain, lower flows in dry periods",
                "Changed wind patterns move humid air to different areas", "Sea level rise / salt incursion into coastal aquifers"]),
          P("Explain why the impact of industrial and domestic water use on the hydrological cycle is usually local.", 2,
            ms=["Most water abstracted is cleaned and returned to the river / sea so the main impact is on quality (pollution) not quantity",
                "Effects are noticeable only where large urban centres draw on restricted local supplies (aquifers, small rivers)"]),
      ]),

    Q("HYD-03", "hydro-cycle", "3.2.2.1-3.2.2.2", "117-118",
      intro="The Aral Sea in central Asia was once the fourth largest lake in the world. From the 1960s water from the two rivers feeding it (the Amu Darya and Syr Darya) was diverted to irrigate cotton and rice. Table 1 shows changes in the lake.",
      figures=[Table(["Year", "1960", "1980", "2000", "2015"], [["Lake area / km^2", "68 000", "52 000", "24 000", "7 000"], ["Salinity / g dm^-3", "10", "18", "45", "over 100"], ["Commercial fish catch / thousand tonnes", "40", "10", "0", "0"]])],
      parts=[
          P("Calculate the percentage reduction in the area of the Aral Sea between 1960 and 2015.", 2, calc=True, unit="%", ms=["(68 000 - 7 000) / 68 000 x 100", "= 89.7% (accept 90%)"]),
          P("Explain why the salinity of the lake increased as the area fell.", 2,
            ms=["Inflow from the rivers was reduced (sometimes to zero) so less water entered while evaporation continued", "Evaporation removes pure water leaving the dissolved salts behind, so they became concentrated in a smaller volume"]),
          P("Explain why the fish catch fell to zero, and describe <b>two</b> other environmental consequences of the shrinking of the lake.", 4,
            ms=["Salinity rose above the range of tolerance of the freshwater fish species / osmotic stress; pollution by pesticides, fertilisers and industrial waste concentrated in the lake",
                "Exposed lake bed of salt and pesticide-contaminated dust blown by wind onto farmland and settlements (health problems, soil salinisation)",
                "Loss of wetland habitats and wildlife; local climate more extreme (loss of the moderating effect of the water body)", "Loss of livelihoods; conflict between the countries sharing the rivers"]),
          P("Suggest why disagreements over the rivers continue between the countries of the region.", 2,
            ms=["Upstream abstraction for irrigation reduces the flow available downstream", "Upstream HEP dams hold water in summer for winter generation, reducing summer irrigation water downstream; growing populations increase demand"]),
      ]),

    Q("HYD-04", "hydro-cycle", "3.2.2.1-3.2.2.2", "119-121",
      intro="Figure 1 shows the depth of the water table below the ground surface in an aquifer beneath a coastal farming region between 1970 and 2020.",
      figures=[Chart("line", "Year", "Depth to water table / m", {"Depth to water table": [(1970, 8), (1980, 12), (1990, 19), (2000, 27), (2010, 36), (2020, 44)]}, y_min=0)],
      parts=[
          P("Calculate the mean rate at which the water table fell between 1970 and 2020.", 1, calc=True, unit="m yr^-1", ms=["(44 - 8) / 50 = 0.72 m yr^-1"]),
          P("Explain why the water table is falling.", 2, ms=["Abstraction (for irrigation) exceeds the rate of natural recharge by infiltration / percolation of precipitation", "The dynamic equilibrium between inflow and outflow has been upset so the stored volume declines"]),
          P("Explain the features a rock must have to form an aquifer.", 3,
            ms=["Porosity: a high proportion of the rock volume is space that can hold water (chalk, limestone, sandstone)", "Permeability: the spaces are interconnected and large enough for water to flow through (clay is porous but not permeable)",
                "Impermeable rock (granite, clay) beneath to stop water escaping, and permeable rock / soil above to allow recharge"]),
          P("Describe <b>four</b> consequences of over-exploiting this coastal aquifer.", 4, items=4,
            ms=["Salt water incursion: seawater flows into the aquifer to replace the fresh water, making it unusable for irrigation (osmotic dehydration of crops)",
                "Subsidence: emptied pore spaces no longer support the rock so it compacts, damaging buildings and pipes (eg Mexico City)",
                "Drying up of groundwater-fed rivers, lakes and wetlands as the water table falls below their beds", "Ecological impacts: plants needing high water availability die; wetland animals lost; food chain effects",
                "Reduced supplies: abstraction may suddenly have to stop after years of hidden decline"]),
      ]),

    Q("HYD-05", "hydro-cycle", "3.2.2.1-3.2.2.2", "119-121",
      parts=[
          P("Explain why abstraction from an aquifer containing 'fossil' (palaeo) water, such as the High Plains / Ogallala Aquifer in the USA, cannot be sustainable.", 3,
            ms=["The water was recharged during or before the last ice age (10 000-20 000 years ago) when the climate was wetter", "Current recharge is little or none so any abstraction reduces the stored volume",
                "The large volume means shortages take a long time to appear, but eventually the supply runs out; ancient water is often saline, causing soil salinisation"]),
          P("Describe how the GRACE satellites are used to monitor aquifer depletion and give <b>one</b> advantage over monitoring boreholes.", 3,
            ms=["Two satellites whose orbits are affected by the force of gravity", "The mass of water in aquifers below changes gravity, so changes in the orbit / distance between the satellites indicate changes in groundwater mass",
                "Advantage: the whole Earth is surveyed every 30 days, whereas borehole water-table measurements are slow and hard to coordinate over large areas"]),
          P("Describe <b>three</b> measures being introduced on the North China Plain to reduce aquifer depletion.", 3, items=3,
            ms=["Low-pressure irrigation pipes to reduce leaks", "Growing crops that need less water than wheat / maize", "Charging consumers by volume used (metering)", "Inter-basin transfer of water 450 km from the Yangtze"]),
          P("Suggest why large-scale afforestation on the North China Plain may reduce aquifer recharge even though trees reduce soil erosion.", 1,
            ms=["Trees intercept rainfall and transpire large volumes, reducing soil moisture and the water percolating down to the aquifer"]),
      ]),

    Q("HYD-06", "hydro-cycle", "3.2.2.1", "117",
      intro="A dam and reservoir are to be built on a river to supply water and regulate flow.",
      parts=[
          P("Explain <b>three</b> effects the reservoir may have on wildlife in and around the river.", 6,
            ms=["Habitat change: flooding destroys the previous terrestrial / river habitats but creates a wetland which may be valuable (wetlands are uncommon)",
                "Wildlife barrier: the dam blocks migrating fish (salmon, sturgeon) and prevents recolonisation along the river",
                "Changed river regime downstream: regulated flow removes low-flow periods needed by species such as river turtles nesting on sandbanks and high flows that wash sediment from gravel spawning beds",
                "Sedimentation: sediment settles in the reservoir instead of fertilising the floodplain and building river banks / coastlines downstream, increasing erosion",
                "Microclimate: water's high heat capacity reduces temperature fluctuations; higher wind speeds; more evaporation, humidity, cloud and precipitation downwind"]),
          P("Explain why decomposition of flooded vegetation in a new reservoir contributes to climate change.", 2,
            ms=["Vegetation / dead organic matter under water decays anaerobically", "Releasing methane, a powerful greenhouse gas"]),
          P("Explain how a river-regulation reservoir reduces both flooding and water shortages downstream.", 2,
            ms=["After heavy rain surplus water is stored, reducing peak flow / flooding downstream", "In dry periods the dam releases water to maintain river levels / supplies"]),
      ]),

    # ---------------- hydro-management: 3.2.2.4-3.2.2.5 ----------------
    Q("HYD-07", "hydro-management", "3.2.2.5", "122-124",
      parts=[
          P("Describe <b>four</b> factors that should be considered when choosing a site for a dam and reservoir.", 4, items=4,
            ms=["Topography: a narrow exit from a large deep basin so a small dam holds a large volume", "Geology: impermeable rock beneath (no seepage), strong enough to support the dam, no faults / seismic activity",
                "Catchment area: large enough with regular, reliable rainfall / river inflow; climate not too hot (evaporation losses)", "Catchment land use: low pollution risk (industry, pesticides); low soil erosion (sedimentation reduces capacity)",
                "Infrastructure / proximity to demand: access for construction, cost of transporting water", "Existing land use: value of what is lost (urban areas, conservation sites, farmland) - loss:benefit analysis"]),
          P("Give <b>one</b> advantage and <b>two</b> disadvantages of an estuary barrage compared with a reservoir on land.", 3,
            labels=["Advantage", "Disadvantage 1", "Disadvantage 2"],
            ms=["Advantage: fewer land-use conflicts as no land is flooded; large volume near coastal cities",
                "Disadvantages: destroys / changes important intertidal habitats (mudflats for wading birds); obstacle to shipping; collects pollution from the whole river catchment; sedimentation"]),
          P("Explain why desalination of seawater is only used in some countries.", 2,
            ms=["Very energy-intensive and expensive (reverse osmosis / distillation)", "Only worthwhile where seawater is available and freshwater supplies are inadequate (eg Malta, Middle East)"]),
          P("Explain how artificial recharge can make aquifer supplies sustainable.", 1,
            ms=["Surplus water in wet periods (when infiltration capacity is exceeded and runoff would go to the sea) is pumped underground or diverted into lagoons to infiltrate, so abstraction in dry periods is balanced by recharge"]),
      ]),

    Q("HYD-08", "hydro-management", "3.2.2.5", "124-126",
      intro="Table 1 shows the effect of installing water meters on the mean daily water use of households in a UK town.",
      figures=[Table(["", "Unmetered households (fixed charge)", "Metered households"], [["Mean water use / dm^3 per person per day", "150", "125"], ["Percentage with low-flush toilets", "35", "58"], ["Percentage using a garden hosepipe weekly in summer", "44", "20"]])],
      parts=[
          P("Calculate the percentage reduction in water use per person in metered households.", 1, calc=True, unit="%", ms=["(150 - 125) / 150 x 100 = 16.7% (accept 17%)"]),
          P("Explain why metering reduces water use.", 2,
            ms=["A fixed fee gives no incentive to save water because the bill is the same however much is used", "Metering matches the charge to the volume used so households save money by using less (fewer hosepipes, low-flow appliances)"]),
          P("Describe <b>three</b> ways in which domestic water use can be reduced other than metering.", 3, items=3,
            ms=["Low-water appliances: dual-flush toilets, low-flow shower heads, efficient washing machines / dishwashers, tap timers", "Greywater re-use: bath / shower water used to flush toilets or water gardens",
                "Rainwater collection / water butts for garden use", "Xeriscaping: planting drought-adapted species that need no watering", "Repairing leaks / dripping taps"]),
          P("Explain why about 20% of the water intended for public supply in the UK never reaches consumers, and how this could be reduced.", 2,
            ms=["Old infrastructure / pipes in poor condition leak", "Repair and good maintenance / pipe replacement / leak detection reduce wastage"]),
          P("Explain how drip irrigation reduces the water needed to grow a crop compared with spray irrigation.", 2,
            ms=["Water is delivered directly to the plant roots / soil around each plant", "Less evaporation loss from spray droplets and from wetting the whole soil surface; less runoff"]),
      ]),

    Q("HYD-09", "hydro-management", "3.2.2.4", "126-128",
      intro="Figure 1 lists the stages in a water treatment works supplying drinking water from a lowland river.",
      figures=[Table(["Stage", "Process"], [["1", "Screens"], ["2", "Sedimentation"], ["3", "Aeration"], ["4", "Flocculation and clarification"], ["5", "Filtration through sand and gravel"], ["6", "Activated carbon"], ["7", "Sterilisation"], ["8", "pH adjustment"]], caption="Figure 1")],
      parts=[
          P("Explain why clay particles do not settle out in the sedimentation stage, and describe how they are removed in stage 4.", 3,
            ms=["Clay particles are very small and carry electrostatic charges on their surfaces so they repel each other and stay suspended",
                "Flocculants (aluminium sulfate / alum or polyelectrolytes) are added and mixed to neutralise the charges", "The particles clump together (flocs) and settle in the clarifier tank"]),
          P("Explain the purpose of aeration (stage 3).", 2,
            ms=["Increases dissolved oxygen and removes hydrogen sulfide (bad-egg smell) from anaerobic sources", "Oxidises some dissolved metals (eg iron) so they become insoluble and can be removed; improves taste"]),
          P("Explain why ozone or UV light may be used for sterilisation instead of chlorine when water comes from peaty upland sources.", 2,
            ms=["Peaty water contains organic matter which reacts with chlorine to produce toxic substances (eg trihalomethanes)", "Ozone / UV kill pathogens without forming these by-products (though chlorine / chloramine keeps water sterile during distribution)"]),
          P("Describe how each of the following contaminants is removed from water.", 3, labels=["Toxic metal ions (lead, mercury, arsenic)", "Salt", "Odours and pesticides"],
            ms=["Ion exchange: toxic ions adsorb onto polymer resin beads or zeolite (also used to soften water by removing calcium / magnesium)", "Reverse osmosis / distillation (desalination) - expensive, energy-intensive",
                "Activated carbon: organic molecules causing odour / taste and pesticides adsorb onto the high-surface-area carbon particles"]),
      ]),

    Q("HYD-10", "hydro-management", "3.2.2.4-3.2.2.5", "122-128",
      parts=[
          P("Which of the following water sources is usually the most convenient for large communities? Tick one box.", 1,
            mcq=["Desalinated seawater", "River water", "Rainwater catchment", "Newly discovered aquifers"], ms=["B - rivers are accessible over a large area with few natural contaminants"]),
          P("Explain why the quality requirements for water differ between uses, using <b>two</b> named uses.", 2,
            ms=["Potable / public supply: no pathogens, low toxins, good appearance / taste / smell (public health)", "Industrial boiler / cooling water: soft water with low calcium so mineral deposits do not block pipes or reduce heat exchange; spray irrigation: low turbidity to avoid blocked pipes and low heavy metals"]),
          P("Explain why inter-basin transfers may be used and give <b>one</b> disadvantage.", 2,
            ms=["Canals / pipes move water from areas with a surplus to areas with a shortage (eg Wales to England, China's Yangtze transfers)",
                "Disadvantage: high cost / energy for pumping; ecological impacts on the donor river; transfer of pollutants or invasive species; political conflict"]),
      ]),
]

ESSAYS = [
    Essay("ESS-P1-WATER", 1,
          "Discuss how an understanding of the hydrological cycle can be used to develop strategies for the sustainable management of water resources.",
          "3.2.2", "114-128",
          ["Hydrological cycle processes and reservoirs; residence times; dynamic equilibrium; increasing demand (population, affluence, irrigation, industry)",
           "Human impacts on transfer rates: deforestation, agriculture, urbanisation, climate change, abstraction; consequences for rivers, aquifers (salt incursion, subsidence, wetland loss), reservoirs",
           "Case studies of unsustainable exploitation: Aral Sea, Nile, Tibetan rivers, Ogallala, North China Plain, Malta",
           "Sustainable strategies: metering, low-water appliances, greywater, xeriscaping, drip irrigation, leak repair; new sources: rainwater catchment, reservoirs and estuary barrages (site factors), unexploited aquifers, inter-basin transfers, artificial recharge, river regulation, afforestation, desalination",
           "Water treatment to make more water usable: sedimentation, flocculation, filtration, activated carbon, sterilisation, ion exchange, reverse osmosis; pollution control (sewage, AMD, buffer strips)",
           "Links to thermohaline circulation and climate; energy costs; circular economy principles (catchment management)",
           "Evaluation of which strategies are most sustainable in different regions; conclusion"]),
]
