"""Physical environment: mineral resources / the lithosphere (spec 3.2.3).  Genn pp. 130-147."""
from gen.model import Q, P, Table, Chart, Essay

T = "minerals"

QUESTIONS = [
    Q("MIN-01", T, "3.2.3.2", "132-134",
      parts=[
          P("Describe how hydrothermal deposition produces exploitable concentrations of metal ores.", 4,
            ms=["Igneous intrusions (batholiths) of magma cool within the crust, heating groundwater to produce superheated, pressurised water",
                "The hot water dissolves minerals from the surrounding rock and the mineral-rich solutions travel along fissures / cracks away from the batholith",
                "As the solutions cool the dissolved minerals crystallise in order of solubility (least soluble first) - fractional crystallisation",
                "So different metals are separated and concentrated in veins, eg tin, copper, lead, silver, gold, arsenic (SW England batholith)"]),
          P("Explain how Proterozoic marine sediments produced the world's major iron ore deposits.", 2,
            ms=["Dissolved iron compounds in ancient seas were oxidised by the oxygen released by early photosynthetic organisms (2.5-1.8 billion years ago)",
                "Iron oxides are insoluble so they were deposited as sediments (haematite, magnetite)"]),
          P("Explain how alluvial (physical sediment) processes separate and concentrate minerals such as gold and tin ore.", 2,
            ms=["Flowing water carries solid particles; the ability to carry them depends on the water velocity and the density of the solids",
                "As velocity falls, dense minerals (gold, tin ore) are deposited first while lighter material is carried further, concentrating the heavy minerals in particular places"]),
          P("Give <b>two</b> examples of mineral deposits formed by biological sedimentation and state their origin.", 2, items=2,
            ms=["Limestone / chalk from the shells of marine organisms", "Coal from terrestrial vegetation", "Crude oil and natural gas from marine organisms (plankton)"]),
      ]),

    Q("MIN-02", T, "3.2.3.3", "135-136",
      intro="Figure 1 shows the mass of copper contained in the Earth's crust at different ore purities, illustrating Lasky's principle.",
      figures=[Chart("bar", "Ore purity / % copper", "Mass of copper in deposits / million tonnes", {"Mass of copper": [("above 2.0", 40), ("1.0-2.0", 150), ["0.5-1.0", 600], ["0.25-0.5", 2400], ["0.1-0.25", 9500]]}, y_min=0)],
      parts=[
          P("State Lasky's principle.", 1, ms=["As the (linear) purity / grade of a mineral deposit decreases, the amount of the mineral present increases exponentially / logarithmically"]),
          P("Use Figure 1 to calculate how many times more copper is contained in deposits of 0.25-0.5% purity than in deposits above 2.0%.", 1, calc=True, unit="times", ms=["2400 / 40 = 60 times"]),
          P("Explain the difference between the <b>reserves</b> and the <b>resource</b> of a mineral.", 3,
            ms=["Reserves: the amount that can be exploited now, economically, with existing technology (deposits above the cut-off ore grade)",
                "Resource: all the material that could be exploited technically and economically now or in the future (with realistic price rises or new technology), including deep, low-grade or protected deposits",
                "The resource is finite but the reserves change: they rise if prices rise or technology improves, and fall if prices fall"]),
          P("Explain, using Lasky's principle, why the ability to exploit slightly lower grade ores greatly increases reserves.", 2,
            ms=["Lowering the cut-off ore grade includes deposits of lower purity in the reserves", "Because the amount of material rises exponentially as purity falls, a small drop in COOG adds a very large mass (eg 0.5-1.0% has 4x the copper of 1.0-2.0%)"]),
          P("Explain why the main problem for future mineral supplies is not the quantity that exists in the crust.", 3,
            ms=["The total quantity (stock / resource base) is far greater than could ever be used", "But most is at purities too low or in locations too inaccessible for current economic exploitation",
                "The challenge is developing technologies (low-energy extraction such as bioleaching, phytomining; better exploration) that make low-grade deposits exploitable; energy needs rise rapidly as ore grade falls"]),
      ]),

    Q("MIN-03", T, "3.2.3.4", "137",
      intro="Table 1 shows some techniques used to locate mineral deposits.",
      parts=[
          P("Complete Table 1 by adding the name of the technique or a description of how it works.", 4,
            table=Table(["Technique", "How it works"], [["Gravimetry", ""], ["", "Detects rocks that are more magnetic, such as magnetite iron ore or ores of tungsten and cobalt"], ["Seismic survey", ""], ["", "Measures how difficult it is for electricity to pass through rocks; sedimentary rocks with high water content have lower values than igneous rocks"]], blank=True, col_widths=[4.5, 10.5]),
            ms=["Gravimetry: gravimeters detect variations in gravity caused by differences in rock density / mass (metal ores usually denser than sedimentary rock)", "Magnetometry",
                "Seismic survey: sound / shock waves from controlled explosions or a seismic vibrator; echoes recorded by geophones give the depth, density and shape of rock strata", "Resistivity"]),
          P("Explain why trial drilling is usually carried out only after remote sensing surveys.", 3,
            ms=["Trial drilling is the most expensive technique per site", "Remote sensing (satellite, aircraft, ground surveys) covers large areas at low cost per unit area and identifies promising sites",
                "Drilling is then targeted where deposits are likely; it is the only method that produces actual rock samples for chemical analysis to confirm composition and purity (proven reserves)"]),
          P("Explain how infrared spectroscopy from satellites can help identify mineral deposits.", 2,
            ms=["Different minerals emit / reflect infrared at different wavelengths", "Multispectral sensors detect these wavelengths over the whole surface (eg Landsat 8 every 16 days) giving information on surface mineral composition"]),
          P("Give <b>one</b> advantage of portable field analysis equipment such as X-ray fluorescence.", 1, ms=["Results are available immediately in the field, saving time waiting for laboratory analysis"]),
      ]),

    Q("MIN-04", T, "3.2.3.5", "138-139",
      intro="Table 1 shows information about two copper deposits, X and Y, being assessed for mining. The current cut-off ore grade for copper is 0.4%.",
      figures=[Table(["Feature", "Deposit X", "Deposit Y"], [["Ore grade / % copper", "0.9", "0.35"], ["Depth of deposit / m", "350", "40"], ["Overburden", "Hard igneous rock", "Loose glacial sediment"], ["Distance to nearest railway / km", "120", "8"], ["Annual rainfall / mm", "2 100", "500"], ["Chemical form", "Copper sulfide", "Copper sulfide"]])],
      parts=[
          P("Explain what is meant by the <b>cut-off ore grade</b> and state which deposit is currently included in the copper reserves.", 2,
            ms=["The lowest ore purity that can be mined economically with existing technology", "Deposit X (0.9% is above 0.4%; Y at 0.35% is part of the resource, not the reserves)"]),
          P("Use Table 1 to discuss the factors that affect the viability of mining each deposit.", 6,
            ms=["X has higher grade so less rock mined, less spoil, less energy and pollution per tonne of copper",
                "But X is deep: costs rise more than proportionally with depth (sides cannot be vertical so much more rock removed; more water inflow and pumping)",
                "X has hard overburden requiring blasting (cost, noise, dust) and high rainfall increasing drainage costs", "X is far from transport infrastructure so transport costs are high",
                "Y is shallow with loose overburden (cheap to remove but landslide risk so gentler slopes / larger land take), near a railway, low rainfall",
                "Y's grade is below the COOG so it is not viable now but would become viable if copper prices rose or extraction technology improved (eg bioleaching); both sulfides risk acid mine drainage"]),
          P("State <b>two</b> changes that would decrease the cut-off ore grade.", 2, items=2, ms=["Higher market value / price of the metal", "Improved extraction technology", "Lower energy costs"]),
      ]),

    Q("MIN-05", T, "3.2.3.6", "139-142",
      parts=[
          P("Explain why mineral extraction causes more land-use conflict than most other human activities.", 2,
            ms=["Minerals can only be exploited where they were deposited (no choice of location), unlike housing, roads or ports",
                "Land take is larger than the mine void: buildings, access roads, overburden and spoil heaps, buffer zones; open-cast mines take far more land than deep mines"]),
          P("Describe how each of the following environmental impacts of an operating mine can be reduced.", 5,
            labels=["Dust", "Noise", "Turbid drainage water", "Acidic leachate from spoil", "Loss of amenity"],
            ms=["Dust: water sprays on roads / blasting areas make particles heavier and clump so they settle", "Noise: baffle mounds / embankments absorb and deflect; blasting at set, predictable daytime hours; quieter machinery",
                "Turbid water: sedimentation lagoons where water stands until solids settle before discharge", "Leachate: collect drainage water and pass through crushed limestone to neutralise acid and immobilise toxic metals",
                "Amenity: landscaping and tree planting to screen the mine; restoration plans agreed as a condition of planning permission"]),
          P("Explain how spoil heaps can be made stable and describe what happened at Aberfan in 1966.", 3,
            ms=["Landscaping to reduce gradients, compaction, drainage to prevent waterlogging, adding soil / nutrients and planting vegetation whose roots bind the surface",
                "At Aberfan a waterlogged coal-mine spoil heap became unstable and slid into the village", "Killing 144 people, mainly children in the primary school"]),
      ]),

    Q("MIN-06", T, "3.2.3.6", "140, 142",
      intro="A sand and gravel pit near a town is due to close. Three options for the site are proposed: a wetland nature reserve, housing, or return to farmland.",
      parts=[
          P("Explain why flooded sand and gravel pits are often developed as wetland nature reserves.", 2,
            ms=["The void fills with water naturally; wetlands are uncommon / valuable habitats in most regions", "The new habitat may have greater wildlife value than the farmland lost; low cost compared with filling and levelling"]),
          P("Explain the conditions that would need to be met for the site to be used for housing or farmland.", 2,
            ms=["Housing: ground must be stable (no subsidence), no toxic metal wastes (otherwise industrial use is safer)", "Farmland: landscape not too steep or uneven, no toxic materials, sufficiently fertile soil (topsoil replaced)"]),
          P("Explain why moving the wildlife from a site before mining begins is rarely completely successful.", 1,
            ms=["Species that cannot be caught / found, or whose habitat requirements are unknown or hard to recreate, are lost; transplanted plants often fail"]),
      ]),

    Q("MIN-07", T, "3.2.3.7", "143-145",
      parts=[
          P("Describe how bioleaching is used to extract copper from low-grade ores or spoil heaps, and explain why it may be more sustainable than smelting.", 5,
            ms=["Acidophilic bacteria (eg Acidithiobacillus) oxidise sulfide ores, producing sulfuric acid which dissolves the metal ions",
                "Leachate (rainwater / recirculated solution) percolating through the spoil heap is collected; recirculation increases the metal concentration",
                "Copper is recovered from solution by electrolysis or by displacement with scrap iron (iron is more reactive so copper is deposited as solid metal)",
                "Smelting needs chemical reduction at high temperatures; energy needed rises rapidly as ore grade falls, so low-grade ores are uneconomic",
                "Bioleaching works at low temperatures with low energy inputs, so it can exploit low-grade deposits and wastes (increasing reserves) - mimics natural low-temperature processes"]),
          P("Describe the process of phytomining.", 3,
            ms=["Plants (hyperaccumulators) absorb metal ions from soil / water and concentrate them in their leaves", "The vegetation is harvested and incinerated",
                "The concentrated metal in the ash is dissolved in acid and separated by electrolysis; also decontaminates polluted sites"]),
          P("Explain how polymer adsorption may provide a low-energy source of uranium in the future.", 2,
            ms=["Uranium ions dissolved in seawater adsorb onto the surface of synthetic or natural polymers (lignin from wood, chitin from shrimp shells)", "The polymers are collected and the uranium recovered, avoiding mining / high-energy extraction"]),
      ]),

    Q("MIN-08", T, "3.2.3.7", "145-146",
      parts=[
          P("Describe polymetallic (manganese) nodules and explain why they are not yet exploited on a large scale.", 3,
            ms=["Metal-rich lumps 5-10 cm across on the deep seabed (4000-5000 m), containing about 30% manganese plus nickel, copper, cobalt, iron, titanium",
                "Exploitation would be very expensive (remotely operated collectors, pumping to the surface) / no viable technology yet", "International agreement on ownership of the seabed and its resources is needed"]),
          P("Explain the environmental impacts of mining polymetallic nodules.", 3,
            ms=["Collectors disturb the seabed and kill benthic organisms living on it", "Separating nodules from sediment creates plumes that increase turbidity with unknown consequences",
                "Re-deposition of sediment covers and kills filter feeders and other benthic organisms; slow recovery in the deep sea"]),
          P("Explain why rare earth metals are a supply concern and describe one new extraction technique.", 4,
            ms=["Used in small amounts in many essential technologies (smartphones, hybrid vehicles, wind turbines, fibre optics, LEDs)", "Exploitable land deposits are limited and mainly in China; chemical separation is complex and produces large amounts of toxic waste",
                "Bacterial adsorption: dissolved rare earth ions adsorb onto the cell surfaces of bacteria (Bacillus subtilis) and are washed off at specific pHs to separate them",
                "Deep sea sediments contain relatively high concentrations but no viable extraction method yet"]),
      ]),

    Q("MIN-09", T, "3.2.3.7", "146-147",
      intro="Table 1 compares the energy used to produce 1 tonne of aluminium from bauxite ore with the energy used to produce 1 tonne from recycled aluminium cans.",
      figures=[Table(["Source", "Energy used / GJ per tonne", "CO_2 emitted / tonnes per tonne of aluminium"], [["Bauxite ore (extraction, refining, smelting)", "210", "12"], ["Recycled cans (collection, sorting, remelting)", "12", "0.7"]])],
      parts=[
          P("Calculate the percentage energy saving from recycling aluminium rather than extracting it from ore.", 2, calc=True, unit="%", ms=["(210 - 12) / 210 x 100", "= 94.3% (accept 94%)"]),
          P("Give <b>three</b> advantages of recycling metals other than energy saving.", 3, items=3,
            ms=["Conserves mineral reserves / extends their lifetime", "Reduces the environmental impacts of mining (land take, habitat loss, spoil, dust, noise, turbid water)", "Reduces mineral processing pollution (eg red mud from bauxite refining)",
                "Reduces waste disposal impacts / landfill volume", "Less CO2 / climate change"]),
          P("Explain <b>four</b> difficulties that reduce the effectiveness of recycling schemes.", 4,
            ms=["Identification of materials: slow, labour-intensive to determine composition where it matters (eg alloys, plastic types)", "Separation of mixed materials: alloys cannot easily be separated so recycled aluminium cannot be used where pure metal is needed; mixed wastes reduce quality",
                "Reduction in quality / contamination (eg paper mixed with food waste)", "Transport / collection: small dispersed quantities cannot use bulk transport so costs and energy per tonne are higher (may exceed savings)",
                "Lack of consumer cooperation in separating wastes; waste losses to litter and general waste; labour costs"]),
          P("Explain what is meant by <b>Cradle to Cradle</b> design.", 1,
            ms=["Designing products so that the materials can be re-used at the end of their lives - easy separation of components and identification of materials - extending the lifetime of mineral use"]),
      ]),

    Q("MIN-10", T, "3.2.3", "130-147",
      parts=[
          P("As high-grade mineral deposits become depleted, discuss the strategies that could be used to secure future supplies of metals.", 9, level=True,
            ms=["Context: Lasky's principle - vast quantities exist at low grade; reserves vs resource; COOG affected by price, technology, energy costs",
                "Improved exploration: higher resolution multispectral satellite sensors, IR spectroscopy, gravimetry, magnetometry, seismic, resistivity, portable field analysis, targeted trial drilling",
                "Mechanisation allowing deeper underground mines and larger open-cast mines",
                "Low-energy extraction of low-grade ores: bioleaching with acidophilic bacteria and fungi, phytomining, iron displacement, bacterial adsorption of rare earths, polymer adsorption from seawater",
                "Previously inaccessible deposits: polymetallic nodules, deep sea sediments, Antarctica (currently protected) - environmental and legal issues",
                "Extending use: recycling (advantages, difficulties), Cradle to Cradle design, product lifetime extension, substitution of scarce materials, circular economy",
                "Evaluation: environmental impacts vs benefits; energy costs; economics; which strategies are most sustainable; conclusion"]),
          P("State what is meant by the <b>stock</b> (resource base) of a mineral.", 1, ms=["All of the material that exists in the lithosphere, including that which will never be technologically or economically exploitable"]),
      ]),
]

ESSAYS = [
    Essay("ESS-P1-MINERALS", 1,
          "Mineral resources are non-renewable. Discuss how an understanding of geological processes and the development of new technologies can extend the period for which society can rely on mineral resources.",
          "3.2.3, 3.6.3-3.6.4", "130-147, 373-379",
          ["Why non-renewable: formed too slowly; geological concentration processes - hydrothermal, metamorphic, Proterozoic sediments, alluvial, evaporites, secondary enrichment, biological sediments",
           "Understanding processes guides exploration (batholith margins, river gravels, ancient seas) and remote sensing / geophysical techniques",
           "Reserves, resource, stock; Lasky's principle; cut-off ore grade and its drivers",
           "Extraction technologies: mechanisation, bioleaching, phytomining, polymer and bacterial adsorption, seabed nodules",
           "Reducing demand: recycling and its difficulties, Cradle to Cradle, design for disassembly, linear vs circular material flows, dispersal of metals in use",
           "Environmental limits: impacts of mining and their control; energy costs rising with lower grades; conflicts",
           "Judgement: technology can extend supplies substantially but only within energy and environmental constraints; circular economy essential"]),
]
