"""Pollution: inorganic and organic nutrient pollution, sewage treatment, acid mine drainage, monitoring water pollution
(spec 3.4.3.2.9-3.4.3.2.10).  Genn pp. 266-275."""
from gen.model import Q, P, Table, Chart, Essay

T = "nutrient-pollution"

QUESTIONS = [
    Q("NUT-01", T, "3.4.3.2.9", "266-268",
      intro="Figure 1 shows the dissolved oxygen concentration in a shallow lowland lake over 48 hours in late summer. The lake receives runoff from arable farmland and effluent from a sewage works.",
      figures=[Chart("line", "Time / hours", "Dissolved oxygen / mg dm^-3",
                     {"Dissolved oxygen": [(0, 6.0), (4, 3.5), (8, 4.5), (12, 11.0), (16, 13.5), (20, 9.0), (24, 5.5), (28, 2.5), (32, 3.8), (36, 10.5), (40, 13.0), (44, 8.5), (48, 5.0)]}, y_min=0)],
      parts=[
          P("Describe the pattern shown in Figure 1.", 2,
            ms=["Dissolved oxygen fluctuates daily / 24-hour cycle: highest in the afternoon (about 13-13.5 mg dm^-3 at 16 and 40 h) and lowest at night / early morning (2.5-3.5 mg dm^-3 at 4 and 28 h)",
                "The night-time minimum is lower on the second night (2.5 vs 3.5)"]),
          P("Explain the causes of the pattern shown in Figure 1.", 4,
            ms=["Nitrates (from fertiliser runoff) and phosphates (from sewage effluent) cause eutrophication: rapid growth of algae / cyanobacteria (algal bloom)",
                "During the day photosynthesis by the dense algae releases oxygen so concentrations rise (above the normal saturation level)",
                "At night there is no photosynthesis but respiration by algae / animals / bacteria continues, using oxygen",
                "Aerobic bacterial decomposition of dead algae / shaded macrophytes uses oxygen; warm summer water holds less oxygen and decay is rapid"]),
          P("Explain why fish kills in eutrophic lakes usually happen at night or at the end of summer.", 2,
            ms=["At night no photosynthesis replaces the oxygen used in respiration / decomposition so concentrations fall below the minimum fish can tolerate",
                "At the end of summer large amounts of dead vegetation decay rapidly in warm water causing severe deoxygenation"]),
          P("Give <b>two</b> other harmful effects of algal blooms.", 2, items=2,
            ms=["Cyanobacteria release toxins harmful to livestock, pets and people", "Floating algae shade submerged / rooted macrophytes which die, disrupting food webs",
                "Algae are an unreliable food source (die off rapidly) so food webs are poor", "Blocked filters / unpleasant taste and smell in water supplies"]),
      ]),

    Q("NUT-02", T, "3.4.3.2.9", "267-268",
      parts=[
          P("Explain why nitrates in drinking water can cause <b>blue baby syndrome</b> (methaemoglobinaemia).", 3,
            ms=["Bacteria in the gut convert nitrates to nitrites", "Nitrites react with haemoglobin so it cannot carry oxygen",
                "Infants are most at risk because they have more of the gut bacteria and their haemoglobin reacts faster; usually from shallow wells receiving arable drainage"]),
          P("Explain why the link between nitrates in drinking water and stomach cancer is uncertain.", 2,
            ms=["Nitrites may be converted in the gut to nitrosamines which are carcinogenic",
                "But most research has been on rats / the evidence in humans is not conclusive; nitrites are also ingested in processed food so the source cannot be isolated"]),
          P("Describe <b>three</b> ways farmers in a Nitrate Vulnerable Zone can reduce nitrate leaching into aquifers.", 3, items=3,
            ms=["Reduce use of nitrate fertilisers / match application to crop need", "Avoid ploughing / applying fertiliser at times of heavy rain (autumn / winter)",
                "Use low-solubility / slow-release fertilisers rather than soluble rapid-release ones", "Store manure / slurry where it cannot leach or wash into rivers",
                "Grow crops with lower nitrogen requirements (eg triticale instead of wheat)", "Grow legumes with nitrogen-fixing bacteria instead of relying on artificial fertiliser"]),
          P("Explain how phosphates are removed from sewage effluent and from lakes polluted in the past.", 2,
            ms=["Iron(III) sulfate is added to effluent: phosphates are precipitated as insoluble iron phosphate (a fine sediment that can be used as fertiliser)",
                "Lakes: dredging phosphate-rich sediments / adding iron(III) sulfate to reduce phosphate solubility (eg the Norfolk Broads)"]),
      ]),

    Q("NUT-03", T, "3.4.3.2.9", "269-272",
      intro="Figure 1 is a flow diagram of the main stages in a sewage treatment works using activated sludge treatment.",
      figures=[Table(["Stage", "Process"], [["Pre-treatment", "Screens and grit traps"], ["Primary treatment", "Primary sedimentation"], ["Secondary treatment", "Aeration tank then secondary sedimentation"], ["Tertiary treatment", "Phosphate stripping / micro-strainers / UV"], ["Sludge treatment", "Anaerobic digestion"]], caption="Figure 1")],
      parts=[
          P("Explain the purpose of screens and grit traps.", 2,
            ms=["Screens (metal grills) trap floating / suspended non-biodegradable items (paper, plastic) which are landfilled or incinerated",
                "Grit traps: the channel widens so flow slows and stones / road grit sink out because there is not enough kinetic energy to carry them"]),
          P("Explain why primary sedimentation is described as the most important process.", 2,
            ms=["The effluent stands in large tanks so the faecal / organic solids sink and are removed as sludge",
                "This removes over 95% of the organic matter from the fluid so the risk of deoxygenation of the river is greatly reduced"]),
          P("Describe what happens in the aeration tank and explain why the sludge from the secondary sedimentation tank is returned to it.", 3,
            ms=["Aerobic bacteria digest / break down the remaining dissolved and suspended organic matter",
                "Air (or pure oxygen) is mixed in by paddle wheels or air stones so oxygen shortage does not limit the aerobic process",
                "The suspended bacteria collected in the secondary sedimentation tank are the 'activated sludge'; returning them maintains a large bacterial population so digestion is rapid"]),
          P("Explain why tertiary treatment may be needed before effluent is discharged, and describe <b>one</b> tertiary process.", 3,
            ms=["Effluent from secondary treatment may still contain dissolved inorganic nutrients (phosphates, nitrates) that cause eutrophication, and some bacteria",
                "Needed where the discharge site is ecologically sensitive or used by many people (bathing water, drinking water abstraction)",
                "Phosphate stripping with iron(III) sulfate; micro-strainers (very fine sieves) then UV light or chlorine to kill remaining bacteria"]),
      ]),

    Q("NUT-04", T, "3.4.3.2.9", "270-273",
      parts=[
          P("Describe the process of anaerobic sludge digestion and give <b>two</b> benefits of the process.", 4,
            ms=["Sludge from primary sedimentation is digested by anaerobic microbes in a warm tank for about four weeks",
                "Kills most pathogens", "Reduces odour and volume of the sludge", "Produces biogas (mainly methane with some CO2) used as fuel to heat the digester / generate electricity",
                "Digested sludge has a better C:N ratio and can be used as agricultural fertiliser"]),
          P("Explain <b>two</b> problems of using sewage sludge as an agricultural fertiliser and how each can be reduced.", 4,
            ms=["Heavy metals from urban wastes / road runoff may be present and absorbed by crops - reduced by adding lime to lower metal solubility",
                "Remaining pathogens - destroyed by heat treatment of the sludge before use",
                "Timing: spreading in the growing season covers crops; in winter vehicles compact wet soils - apply at suitable times / when soils are dry",
                "Odour / public objection - digestion reduces odour"]),
          P("Explain why it is more efficient to have separate collection systems for foul sewage and for surface drainage water.", 2,
            ms=["Foul waste is a small volume needing full treatment so smaller, cheaper treatment works can be built; surface water needs little treatment",
                "The treatment works is not affected by weather-related fluctuations in flow (storms) so storm overflows of untreated sewage are avoided"]),
      ]),

    Q("NUT-05", T, "3.4.3.2.9-3.4.3.2.10", "273-275",
      intro="Table 1 shows measurements taken from a stream above and below the point where drainage water from an old metal-mine spoil heap enters it.",
      figures=[Table(["Site", "pH", "Dissolved zinc / mg dm^-3", "Dissolved oxygen / % saturation", "Number of invertebrate taxa", "Mayfly larvae present?"],
                     [["Upstream", "7.1", "0.02", "96", "18", "Yes"], ["50 m downstream", "3.4", "6.5", "94", "3", "No"], ["2 km downstream", "5.9", "1.1", "95", "9", "No"]])],
      parts=[
          P("Explain how the acidic drainage water is produced in the spoil heap.", 3,
            ms=["Spoil contains residual sulfide ores (eg iron pyrites, zinc sulfide)", "These react with oxygen in the air spaces between the waste particles (oxidation)",
                "Producing metal oxides and oxides of sulfur which dissolve in drainage water to form sulfuric acid"]),
          P("Use Table 1 to explain why the number of invertebrate taxa falls so sharply 50 m downstream, even though dissolved oxygen is unchanged.", 3,
            ms=["The low pH (3.4) directly damages exposed cells / denatures proteins and dissolves calcium-based exoskeletons",
                "Low pH increases the solubility of zinc (0.02 to 6.5 mg dm^-3) which is toxic (inhibits enzymes)",
                "Only a few tolerant taxa survive; the sensitive mayfly larvae (indicator of clean water) are eliminated; dissolved oxygen is not the limiting factor here"]),
          P("Suggest why the pH and zinc concentration have partly recovered 2 km downstream.", 2,
            ms=["Dilution by tributaries / more water", "Neutralisation by alkaline rocks (limestone) in the stream bed; zinc precipitates / adsorbs onto sediments as pH rises"]),
          P("Describe how acid mine drainage can be controlled.", 2,
            ms=["Collect the drainage water and pass it through crushed limestone / add lime to neutralise the acid", "Higher pH also reduces the solubility of toxic metals so they precipitate and can be removed"]),
      ]),

    Q("NUT-06", T, "3.4.3.2.9", "273-275",
      parts=[
          P("Explain why organic pollution of rivers is usually monitored by measuring Biochemical Oxygen Demand (BOD) rather than the concentrations of the pollutants themselves.", 3,
            ms=["Many different organic substances may be present, each with a different potential to cause deoxygenation, so it is difficult to measure or forecast them individually",
                "BOD measures the effect (amount of oxygen used by microbes decomposing the organic matter) under standardised conditions (eg 5 days, 20 &deg;C, dark)",
                "It gives a single measure directly related to the risk of deoxygenation"]),
          P("Explain why a coliform count is used to assess the health risk from sewage contamination rather than testing for pathogens such as typhoid.", 2,
            ms=["E. coli is a common gut bacterium so its presence confirms faecal contamination and its number indicates how serious the contamination is",
                "Pathogens are not always present so their absence would not prove the water is uncontaminated"]),
          P("Give <b>three</b> characteristics of species that make them useful in a biotic index.", 3, items=3,
            ms=["Different species have different sensitivities to pollution", "Easy to identify", "Easy to find / normally present / usually common", "Widely distributed"]),
          P("Give <b>one</b> advantage and <b>one</b> disadvantage of using a biotic index rather than chemical monitoring.", 2, labels=["Advantage", "Disadvantage"],
            ms=["Advantage: assesses the effect of pollution over a period of time (recent pollution events are detected even if the pollutant has gone); no expensive equipment needed",
                "Disadvantage: identification needs skill; does not identify which pollutant is present so further chemical tests are required; species may be absent for other reasons"]),
      ]),

    Q("NUT-07", T, "3.4.3.2.9", "266-272",
      parts=[
          P("Explain how organic wastes and inorganic nutrients cause water pollution and evaluate the effectiveness of the methods used to control them.", 9, level=True,
            ms=["Organic nutrients (sewage, manure, silage effluent, paper mill / tannery / food processing effluent) are food for aerobic microbes whose respiration deoxygenates the water, killing fish and invertebrates; bacterial growths cover the bed, blocking light",
                "Pathogens in sewage (cholera, typhoid, dysentery) spread via contaminated water; decay of organic matter releases inorganic nutrients",
                "Inorganic nutrients: nitrates (fertiliser / manure runoff, leaching) and phosphates (sewage effluent, detergents, eroded soil) cause cultural eutrophication: algal blooms, shading of macrophytes, cyanobacterial toxins, night-time and end-of-summer deoxygenation",
                "Human health: nitrites and methaemoglobinaemia; possible carcinogen via nitrosamines",
                "Control of organic wastes: sewage treatment (pre-treatment, primary sedimentation removing >95% organic matter, aeration / activated sludge or trickling filters, anaerobic digestion of sludge with biogas)",
                "Control of nutrients: tertiary phosphate stripping with iron(III) sulfate, denitrification in filter beds, micro-strainers / UV; Nitrate Vulnerable Zones, fertiliser timing / amount, low-solubility fertilisers, legumes, manure management; dredging sediments",
                "Evaluation: sewage treatment has virtually eliminated deoxygenation and waterborne disease in developed countries but storm overflows and combined sewers still discharge untreated sewage; tertiary treatment is expensive so only used at sensitive sites; diffuse agricultural nitrate is hard to control and aquifers respond slowly; phosphate legacy in sediments",
                "Judgement on point-source (sewage) control being more successful than diffuse-source (agriculture) control"]),
          P("Give <b>one</b> reason why algae cause eutrophication problems more quickly than rooted plants when nutrients are added to a lake.", 1,
            ms=["Algae / cyanobacteria absorb nutrients directly from the water (not the sediments) so they use dissolved nutrients more easily and grow rapidly"]),
      ]),
]

ESSAYS = []
