"""Pollution: noise (spec 3.4.3.2.13).  Genn pp. 286-295."""
from gen.model import Q, P, Table, Chart, Essay

T = "noise"

QUESTIONS = [
    Q("NOISE-01", T, "3.4.3.2.13", "286-287",
      intro="Table 1 shows typical noise levels of some sounds.",
      figures=[Table(["Sound", "Noise level / dB"], [["Threshold of human hearing (at 1000 Hz)", "0"], ["Leaves rustling", "20"], ["Library", "40"], ["Normal conversation", "60"], ["Busy road", "80"], ["Chain saw", "110"], ["Jet engine at 30 m", "140"]])],
      parts=[
          P("Explain why a logarithmic scale is used to measure sound.", 2,
            ms=["The human ear is sensitive to a very wide range of sound pressures / powers (about 10^12 range)",
                "A logarithmic scale compresses this into a convenient range of numbers: each 10 dB increase represents a ten-fold increase in sound intensity"]),
          P("Use Table 1 to calculate how many times greater the sound intensity of a chain saw is than that of a busy road.", 2, calc=True, unit="times",
            ms=["Difference = 30 dB = 3 x 10 dB", "= 10^3 = 1000 times"]),
          P("A machine produces 85 dB. A second identical machine is switched on next to it. State the new noise level and explain your answer.", 2,
            ms=["88 dB", "Doubling the sound intensity increases the level by 3 dB (logarithmic scale)"]),
          P("Explain what is meant by the statement that 0 dB does not mean there is no sound.", 1,
            ms=["0 dB is set as the quietest sound that can be heard (at 1000 Hz) - the threshold of human hearing; quieter sounds exist but cannot be heard"]),
          P("State the frequency range of hearing for a typical young person and explain why the dB(A) scale is used for human hearing.", 3,
            ms=["20 to 20 000 Hz", "dB(A) weights sounds between about 1000 and 4000 Hz more heavily",
                "Because the nerve cells / hair cells in the cochlea are more sensitive to these frequencies so they are heard more easily / cause more annoyance; range narrows with age or noise damage"]),
      ]),

    Q("NOISE-02", T, "3.4.3.2.13", "287",
      parts=[
          P("Describe <b>three</b> effects of noise on human health other than hearing damage.", 3, items=3,
            ms=["Stress-related illness: ulcers, high blood pressure, heart disease", "Behavioural changes: irritability, aggression, lack of concentration leading to accidents",
                "Communication problems / educational underperformance (eg schools under flight paths)", "Sleep disturbance"]),
          P("Explain how noise can damage non-living objects.", 3,
            ms=["Acoustic fatigue: objects exposed to sound at their natural resonant frequency vibrate, causing stress cracking / structural failure (eg early jet engine cowlings)",
                "Vibration damage: repetitive vibration from heavy vehicles damages buildings, bridges, underground pipes",
                "Shock impacts: the force of a sudden very loud noise (sonic boom) breaks windows / dislodges masonry"]),
          P("Explain how noise can reduce the breeding success of birds.", 2,
            ms=["Birds that sing to establish territories / attract mates cannot be heard against background noise",
                "Birds scared by sudden noise leave nests so predators take eggs / chicks; cliff-nesting seabirds knock eggs or chicks into the sea"]),
          P("Explain why military sonar is a threat to cetaceans.", 2,
            ms=["Whales / dolphins use hearing / echolocation to find food and communicate; loud sonar causes hearing damage if close to the source",
                "Behavioural changes / disorientation possibly linked to mass strandings; reduced feeding success"]),
      ]),

    Q("NOISE-03", T, "3.4.3.2.13", "288-292",
      intro="Table 1 shows the bypass ratio and first year of use of jet engines used on four airliners.",
      figures=[Table(["Engine", "Aircraft", "Bypass ratio", "First use"], [["RR Olympus", "Concorde", "0 : 1", "Early 1950s"], ["RR Conway", "Boeing 707", "0.25 : 1", "Late 1950s"], ["P&W JT9D", "Boeing 747", "5 : 1", "1969"], ["RR Trent 1000", "Boeing 787", "10 : 1", "2011"]])],
      parts=[
          P("Explain how a high bypass ratio reduces engine noise.", 3,
            ms=["A turbofan at the front forces bypass air around the inner cowling / core jet",
                "The bypass air smooths the flow of the turbulent hot exhaust gases, reducing the turbulence that creates noise",
                "The higher the ratio of bypass air to jet exhaust the quieter the engine (Trent 1000 quietest, Olympus noisiest)"]),
          P("Describe <b>two</b> other features of aircraft design that reduce noise.", 2, items=2,
            ms=["Chevron (serrated) nozzles mix bypass air with surrounding air more smoothly", "Acoustic liners in the engine cowlings absorb noise", "Hush kits fitted to older low-bypass engines",
                "Fairings on undercarriage and wing-flap hinges reduce turbulence; welded rather than riveted panels", "Lighter composite aircraft need less thrust", "Blended wing with engines on top so the body shields the ground"]),
          P("Explain how each of the following airport operating procedures reduces noise nuisance.", 4,
            labels=["Constant descent angle", "Night flight restrictions", "Noise-based landing charges / quota count", "Multiple runways"],
            ms=["Constant (3&deg;) descent avoids periods of high thrust in a stepped descent and keeps aircraft higher for longer",
                "Night flights (especially take-offs, which are noisier) are restricted / banned when people are sleeping and background noise is low",
                "Noisier aircraft pay higher charges / use up more quota points and fines for exceeding limits, so airlines are encouraged to buy quieter aircraft",
                "More time to slow down after landing so wheel brakes can be used instead of noisy reverse thrusters"]),
          P("Explain why aircraft are noisier on take-off than on landing.", 1,
            ms=["Engines run at higher power / maximum thrust and the steep climb angle needs full power (although the aircraft climbs quickly out of earshot)"]),
      ]),

    Q("NOISE-04", T, "3.4.3.2.13", "292-294",
      parts=[
          P("Complete Table 1 to show one method of controlling each source of railway noise.", 4,
            table=Table(["Source of railway noise", "Control method"], [["Wheel vibration on the track", ""], ["Pantograph turbulence", ""], ["Wheel squeal on corners", ""], ["Braking squeal", ""]], blank=True, col_widths=[6, 9]),
            ms=["Wheel vibration: track polishing / grinding, sound-absorbing ballast, sound-absorbing suspension", "Pantograph: aerodynamic fairing",
                "Wheel squeal: lubrication of wheels / track on corners", "Braking: composite-material brakes instead of cast iron"]),
          P("Explain why road traffic noise affects more people than any other form of noise pollution.", 1,
            ms=["Roads pass through / near almost all residential areas and traffic is continuous through the day, unlike airports or railways which affect limited areas"]),
          P("Describe <b>three</b> ways of reducing road traffic noise reaching residents.", 3, items=3,
            ms=["Sound-absorbing road surfaces (porous asphalt / rubber-crumb asphalt)", "Acoustic fences, embankments / baffle mounds, walls or dense tree planting",
                "Traffic management for free flow (less acceleration noise); re-routing traffic away from residential areas", "Double glazing / acoustic insulation of buildings",
                "Vehicle design: better aerodynamics, engine insulation, quieter exhausts, quieter tyres"]),
          P("Suggest how noise from pile-driving at sea for wind turbine foundations can be reduced to protect cetaceans.", 2,
            ms=["Air bubble curtains around the pile driver absorb noise", "Acoustic survey to detect cetaceans first and delay work if present; increase volume gradually (soft start) so animals can leave", "Drilling instead of pile-driving"]),
      ]),

    Q("NOISE-05", T, "3.4.3.2.13", "293-295, 418",
      intro="A motor-racing circuit has residents living 500 m away. The circuit operator wants to compare two designs of acoustic barrier: an earth baffle mound and a timber acoustic fence.",
      parts=[
          P("Describe how you would carry out an investigation to compare the effectiveness of the two barriers.", 5,
            ms=["Use a calibrated sound meter (dB(A)) at fixed distances (eg 10, 50, 100, 250, 500 m) from the track behind each barrier and at a control site with no barrier",
                "Standardise the noise source: same cars / same race or a standard test noise; same time of day, wind speed / direction, weather; same height of meter above ground",
                "Take repeated readings at each distance and calculate means (and standard deviation) to assess variability",
                "Use a measure such as LA10 or Leq over a set period rather than a single peak reading",
                "Compare reduction in dB relative to the control at each distance; plot noise level against distance for each barrier; statistical test (t-test) to assess significance"]),
          P("Explain why readings should be taken with the same wind direction.", 1, ms=["Wind carries sound / affects how far it travels so different wind directions would change readings independently of the barrier"]),
          P("Explain the difference between the LA10 and LA90 measures of traffic noise.", 2,
            ms=["LA10 is the noise level exceeded for 10% of the period - a measure of the noisiest periods", "LA90 is the level exceeded for 90% of the period - a measure of the quietest / background level"]),
          P("Outline <b>two</b> ways in which the residents' houses could be designed to reduce the noise reaching occupants.", 2, items=2,
            ms=["Double / triple glazing", "Acoustic insulation in walls / roof", "Bedrooms on the side facing away from the track", "Dense hedges / trees and earth mounds in gardens"]),
      ]),

    Q("NOISE-06", T, "3.4.3.2.13", "286-295",
      parts=[
          P("Using named examples, explain how the sources of noise pollution can be controlled by changes to design, operation and location.", 9, level=True,
            ms=["Principles: dB is logarithmic (10 dB = 10x; 3 dB = 2x) so small reductions in dB are large reductions in intensity; effects on humans (hearing, stress, behaviour) and wildlife (breeding birds, bats, cetaceans)",
                "Aircraft design: high bypass ratio engines, chevron nozzles, hush kits, acoustic liners, fairings, composites, blended wing",
                "Aircraft operation: take-off angle, flight paths avoiding urban areas, constant descent, reduced reverse thrust, night restrictions, Chapter noise limits, fines and noise charges, quota count",
                "Airport design / location: away from population centres, taxi and engine-test areas away from housing, acoustic walls, baffle mounds, land-use restrictions, free acoustic insulation",
                "Railway: track polishing, sound-absorbing ballast and suspension, pantograph fairings, wheel lubrication, composite brakes",
                "Road: porous / rubber asphalt, acoustic fences, embankments, tree planting, aerodynamics, engine insulation, traffic management and routing, double glazing",
                "Industrial: silencers on compressors, pressing instead of stamping, nylon rollers, drilling instead of pile-driving, bubble curtains, timing of blasting, acoustic mats / curtains, remote operation, ear protection",
                "Domestic: acoustic absorbers in appliances, volume limiters, selection of quieter appliances, ear defenders",
                "Evaluation: which approaches are most effective / cost-effective; conflicts (airports near cities for convenience); legislation and monitoring (Leq 57 dB contours) needed to enforce"]),
          P("State what is meant by the <b>Leq 57 dB</b> contour used around UK airports.", 1,
            ms=["The area within which the average (equivalent continuous) sound level between 07:00 and 23:00 in summer exceeds 57 dB - taken as the onset of significant community annoyance"]),
      ]),
]

ESSAYS = []
