"""Pollution: Pesticides (spec 3.4.3.2.8).  Genn pp. 262-266 (also 314-319 for pest control)."""
from gen.model import Q, P, Table, Chart, Essay

T = "pesticides"

QUESTIONS = [
    Q("PEST-01", T, "3.4.3.2.8", "262-263",
      intro="Figure 1 shows how the percentage mortality of a pest species and of a non-target bee species change with the dose of an insecticide applied to a crop.",
      figures=[Chart("line", "Dose / g ha^-1", "Mortality / %",
                     {"Pest species": [(0, 0), (10, 5), (20, 30), (30, 70), (40, 95), (50, 100), (60, 100)],
                      "Bee (non-target)": [(0, 0), (10, 0), (20, 0), (30, 4), (40, 20), (50, 55), (60, 90)]}, y_min=0, y_max=100)],
      parts=[
          P("Use Figure 1 to estimate the LD<sub>50</sub> of the insecticide for the pest species.", 1,
            ms=["25 g ha^-1 (accept 24-27)"], calc=True, unit="g ha^-1"),
          P("Define the term <b>MDNF</b> (maximum dose never fatal).", 1,
            ms=["The highest dose that can be applied without killing any members of the population / any individuals of the (non-target) species"]),
          P("Use Figure 1 to explain why it may not be possible to kill all of the pest species without harming bees.", 3,
            ms=["The MDAF (minimum dose always fatal) of the pest is about 50 g ha^-1",
                "This is higher than the MDNF of the bee (about 20 g ha^-1)",
                "So a dose that kills all pests kills some bees / the two curves overlap between about 20 and 50 g ha^-1",
                "A dose of 30-40 g ha^-1 would kill most pests with limited bee deaths (compromise)"]),
          P("Suggest how the farmer could reduce the harm to bees without reducing the dose applied.", 2,
            ms=["Spray at night / when bees are not flying", "Spray when the crop is not in flower",
                "Spray on still days to reduce spray drift", "Use a systemic pesticide / seed coating rather than spraying", "Use smaller droplets for more even coverage"]),
          P("Explain why a pesticide with high specificity is less likely to cause environmental damage.", 3,
            ms=["Specificity is the extent to which the pesticide is toxic only to the target species / range of species affected",
                "A highly specific pesticide has low toxicity to non-target species (eg bees, fish, mammals)",
                "So fewer non-target deaths / less loss of predators, pollinators",
                "Fewer indirect (food chain) effects / fewer inter-species relationships lost",
                "Example: pyrethroids have high insect toxicity but low mammal toxicity"]),
      ]),

    Q("PEST-02", T, "3.4.3.2.8", "263-265",
      intro="Table 1 shows some properties of four groups of insecticide.",
      figures=[Table(["Insecticide group", "Toxicity to insects", "Toxicity to mammals", "Persistence", "Liposolubility"],
                     [["Organochlorines (eg DDT)", "High", "Low", "High", "High"],
                      ["Organophosphates (eg malathion)", "High", "High", "Low", "Low"],
                      ["Pyrethroids", "High", "Low", "Low", "Low"],
                      ["Neonicotinoids", "High", "Low", "Moderate", "Low (water soluble)"]])],
      parts=[
          P("Use Table 1 to explain why organochlorine insecticides caused the decline of birds of prey such as the peregrine falcon in the 1950s and 1960s.", 4,
            ms=["High persistence means DDT remains in the environment for years / decades, so it has time to disperse and be taken up",
                "High liposolubility means it dissolves in fat and is stored in body tissues rather than excreted (bioaccumulation)",
                "Concentration increases at each trophic level as predators eat many contaminated prey (biomagnification)",
                "Birds of prey are at the top of the food chain so receive the highest concentrations",
                "Sub-lethal doses caused thin eggshells that broke / reduced breeding success; higher doses caused sterility or death"]),
          P("Organophosphates replaced organochlorines for many uses. Use Table 1 to give <b>one</b> advantage and <b>one</b> disadvantage of this change.", 2,
            labels=["Advantage", "Disadvantage"],
            ms=["Advantage: low persistence / low liposolubility so they do not bioaccumulate or biomagnify / break down quickly",
                "Disadvantage: high mammalian toxicity so farm workers / humans are at risk of acute poisoning (neurotoxin inhibiting acetylcholinesterase); chronic effects (memory loss, depression); suspected carcinogens"]),
          P("Explain why pyrethroids should not be used near rivers or fish farms.", 1,
            ms=["Pyrethroids are highly toxic to fish (even though mammal toxicity is low)"]),
          P("Describe how the properties of neonicotinoids allow them to be used as a seed coating, and explain why this method of application reduces harm to non-target species.", 3,
            ms=["Neonicotinoids are water soluble so they are absorbed by the roots (from the soil) and translocated through the plant (systemic)",
                "They are moderately persistent so remain in the soil long enough to be absorbed",
                "Seed coating avoids spraying so no spray drift / no dust onto flowers or surrounding habitats",
                "So bees / pollinators are less exposed than when the crop is sprayed"]),
      ]),

    Q("PEST-03", T, "3.4.3.2.8", "263-264, 266",
      intro="A pesticide was applied to a field of oilseed rape. Table 1 shows the concentration of the pesticide in organisms sampled from a pond next to the field.",
      figures=[Table(["Organism", "Trophic level", "Pesticide concentration / mg kg^-1"],
                     [["Pond water", "-", "0.002"], ["Phytoplankton", "1", "0.04"], ["Water fleas (Daphnia)", "2", "0.5"], ["Small fish", "3", "4.2"], ["Heron", "4", "38.0"]])],
      parts=[
          P("Calculate how many times more concentrated the pesticide is in the heron than in the pond water. Give your answer to two significant figures.", 2,
            calc=True, unit="times", ms=["38.0 / 0.002", "= 19 000 (19 000 times / 1.9 x 10^4)"]),
          P("Name the process shown by the data in Table 1.", 1, ms=["Biomagnification (accept bioaccumulation as part of the process only if biomagnification is also implied by increase up the food chain)"]),
          P("Explain the <b>two</b> properties of the pesticide that cause the pattern shown in Table 1.", 4,
            ms=["Persistence: the pesticide is not broken down (by light, microbes, enzymes) so it remains in the environment / organisms long enough to pass along the food chain",
                "Liposolubility: the pesticide dissolves in lipids / fat so it is stored in body tissue and not excreted in (water-based) urine",
                "Each organism eats many organisms from the level below and retains the pesticide so concentration rises at each trophic level",
                "Herons have long lives so accumulate over time"]),
          P("The pesticide was probably an organochlorine. Suggest why the use of organochlorines is now banned or heavily restricted in most countries, even though DDT is still used to control malaria mosquitoes in some houses.", 3,
            ms=["Organochlorines killed non-target insects (bees, butterflies) and top predators (birds of prey, otters) through biomagnification",
                "They persist for decades so the damage continued long after use",
                "Use in houses (on walls / nets) does not enter food chains / no runoff into water, so does not biomagnify",
                "Benefit of preventing malaria deaths outweighs the risk (risk:benefit)"]),
      ]),

    Q("PEST-04", T, "3.4.3.2.8", "265-266",
      parts=[
          P("Neonicotinoids are the most widely used group of insecticides. Explain how the properties of neonicotinoids affect their impact on bee populations and describe the methods used to reduce this impact.", 9, level=True,
            ms=["Neonicotinoids are neurotoxins similar to nicotine; they inhibit the neurotransmitter acetylcholine",
                "High toxicity to insects but low toxicity to vertebrates because they cannot cross the vertebrate blood-brain barrier",
                "Very toxic to bees: sub-lethal doses reduce navigation ability, foraging and immunity to disease; linked to colony decline",
                "Water soluble and moderately persistent: remain in soil, absorbed by roots and translocated (systemic), so present in pollen and nectar",
                "Persistence may allow build-up in aquifers / soil; broken down fastest in sunlight and by soil microbes",
                "Synergism with some fungicides increases toxicity to bees",
                "Exposure greatest when sprayed onto crops or when seed-coating dust is blown by wind",
                "Control: seed coating rather than spraying; spraying when crops are not in flower / at night; still days to reduce drift",
                "Restrictions on use (EU bans on outdoor use on flowering crops); use of alternative pest control (cultural, biological, integrated control)",
                "Evaluation: reduced pesticide use but neonicotinoid alternatives (pyrethroids) also harm pollinators; trade-off with crop yields"]),
          P("State <b>one</b> way in which pesticide use in agriculture may be reduced by using natural processes.", 1,
            ms=["Biological control (introduced predators / pathogens)", "Predator habitats (hedgerows, beetle banks)", "Crop rotation", "Companion / barrier crops", "Sterile male technique / pheromone traps", "Genetic resistance"]),
      ]),

    Q("PEST-05", T, "3.4.3.2.8", "262-264",
      intro="Two insecticides, X and Y, were tested on a pest insect and on a predatory ground beetle that feeds on the pest. Table 1 shows the results.",
      figures=[Table(["Insecticide", "LD<sub>50</sub> for pest / mg kg^-1", "LD<sub>50</sub> for ground beetle / mg kg^-1", "Half-life in soil / days", "Solubility in water"],
                     [["X", "5", "6", "180", "Low"], ["Y", "8", "150", "4", "High"]])],
      parts=[
          P("Explain what is meant by LD<sub>50</sub>.", 1, ms=["The dose that kills 50% of the (test) population"]),
          P("Using Table 1, explain which insecticide is more likely to cause indirect effects on the pest population through the food chain.", 3,
            ms=["Insecticide X: LD50 for the beetle (6) is very similar to that of the pest (5) so it has low specificity / kills the predator as well",
                "Loss of the predator removes natural control so the pest population may recover faster / increase (resurgence)",
                "Y has a much higher LD50 for the beetle (150) so few predators killed / more specific"]),
          P("Suggest <b>two</b> environmental problems that could be caused by insecticide Y that are less likely with insecticide X.", 2,
            items=2, ms=["High water solubility so it is leached into rivers / groundwater / runoff", "Toxic to aquatic organisms downstream", "Mobile so it can affect areas away from the field", "Washed off the crop quickly so more frequent application needed"]),
          P("Explain why the half-life of insecticide X makes it more likely to bioaccumulate.", 2,
            ms=["Long half-life = high persistence so it is not broken down quickly", "So it remains in the organism / environment long enough to build up in tissues (especially if liposoluble)"]),
          P("Give <b>two</b> reasons why a systemic insecticide may be preferred to a contact insecticide.", 2,
            items=2, ms=["Absorbed and translocated within the plant so protects new growth", "Not washed off by rain", "Does not need to cover all leaf surfaces / less spray needed", "Less spray drift so less harm to non-target species"]),
      ]),

    Q("PEST-06", T, "3.4.3.2.8", "263-266",
      parts=[
          P("Define the term <b>persistence</b> as applied to a pollutant.", 1, ms=["The length of time a pollutant remains in the environment before it is broken down / degraded (chemically or biologically)"]),
          P("Explain how the persistence of a pesticide is affected by <b>two</b> named environmental factors.", 4,
            ms=["Light: UV light degrades many pesticides (eg neonicotinoids break down fastest in sunlight) so persistence is shorter in bright conditions",
                "Temperature: higher temperatures increase the rate of chemical breakdown / microbial decomposition",
                "Soil microbes / oxygen: aerobic microbial activity breaks pesticides down so persistence is shorter in well-aerated, biologically active soils",
                "pH / presence of other chemicals may increase or decrease the rate of degradation",
                "Adsorption onto clay / organic matter may protect from degradation and increase persistence"]),
      ]),

    Q("PEST-07", T, "3.4.3.2.8", "262-266",
      intro="Figure 1 shows the number of breeding pairs of sparrowhawks in a study area in the UK between 1945 and 1985, and the years in which DDT use began and was banned.",
      figures=[Chart("line", "Year", "Breeding pairs", {"Sparrowhawk": [(1945, 210), (1950, 200), (1955, 140), (1960, 60), (1965, 25), (1970, 30), (1975, 70), (1980, 130), (1985, 190)]}, y_min=0)],
      parts=[
          P("Describe the trend shown in Figure 1.", 2,
            ms=["Numbers fell from about 210 pairs in 1945 to a minimum of about 25 in 1965 (steepest fall 1955-1960)",
                "Numbers then recovered / rose steadily after 1970, reaching about 190 by 1985 (not yet back to 1945 level)"]),
          P("Calculate the percentage decrease in breeding pairs between 1950 and 1965. Show your working.", 2, calc=True, unit="%",
            ms=["(200 - 25) / 200 x 100", "= 87.5%"]),
          P("DDT use in the UK began in the late 1940s and was restricted from the mid 1960s. Explain how the properties of DDT could account for the pattern in Figure 1.", 4,
            ms=["DDT is persistent (remains for decades) and liposoluble so it bioaccumulates in prey (small birds) and biomagnifies in sparrowhawks (top predator)",
                "Sub-lethal doses caused thin eggshells / reduced breeding success so the population declined even without adult deaths",
                "Higher doses caused sterility / death",
                "After restrictions, environmental concentrations slowly fell (persistence explains the delay before recovery)",
                "Breeding success recovered so the population rose"]),
          P("Suggest why the recovery after 1970 was slow.", 2,
            ms=["DDT persists in soil / sediments / food chains for many years so exposure continued", "Birds of prey are k-selected: few young per year, slow to mature so populations grow slowly", "Other pressures (habitat loss, persecution)"]),
      ]),

    Q("PEST-08", T, "3.4.3.2.8", "262-266",
      parts=[
          P("Which of the following properties would make a pesticide <b>least</b> likely to biomagnify? Tick one box.", 1,
            mcq=["High liposolubility and high persistence", "Low liposolubility and low persistence", "High liposolubility and low persistence", "Low liposolubility and high persistence"],
            ms=["B - Low liposolubility and low persistence"]),
          P("Explain the difference between <b>bioaccumulation</b> and <b>biomagnification</b>.", 2,
            ms=["Bioaccumulation: build-up of a pollutant in the tissues of an individual organism over time because uptake is faster than excretion / breakdown",
                "Biomagnification: increase in concentration of the pollutant at successive trophic levels of a food chain"]),
          P("Explain why pesticides are described as an unusual type of pollutant.", 2,
            ms=["They are intended to be toxic (to the target species)", "They are deliberately released / spread into the environment (rather than being an accidental or waste release)"]),
      ]),
]

ESSAYS = [
    Essay("ESS-P1-PEST", 1,
          "Discuss how knowledge of the properties of pesticides can be used to reduce their environmental impacts while maintaining food production.",
          "3.4.3.2.8, 3.5.1.1, 3.5.1.5", "236-240, 262-266, 314-320",
          ["Properties: toxicity (LD50, MDAF, MDNF), specificity, persistence, liposolubility/water solubility, mobility, mode of action (contact/systemic), synergism",
           "Bioaccumulation and biomagnification explained by persistence + liposolubility; DDT and birds of prey as a case study",
           "Comparison of organochlorines, organophosphates, pyrethroids, neonicotinoids with their relative advantages and disadvantages",
           "Reducing impact: restrictions/bans, choice of non-persistent and specific pesticides, systemic pesticides and seed coatings, application timing (night, still days, not in flower), droplet size",
           "Alternatives: cultural control (rotation, barrier/companion crops), biological control, predator habitats, sterile males, pheromone traps, genetic resistance, GM crops, integrated pest management",
           "Trade-offs: yield, cost, human health (organophosphates), resistance evolution, pollinator services; risk:benefit; sustainability and the circular economy",
           "Judgement: no pesticide is perfectly specific; combination of property-based selection and integrated control is most sustainable"]),
]
