"""Pollution: principles of control - CPA, CGM, emission location/timing, ALARA/BATNEEC, new technologies
(spec 3.4.3.1, 3.4.3.3).  Genn pp. 243-245, 303-304."""
from gen.model import Q, P, Table, Chart, Essay

T = "pollution-control"

QUESTIONS = [
    Q("PCON-01", T, "3.4.3.1", "243, 303-304",
      intro="A nuclear reprocessing plant on the coast discharges low-level liquid radioactive waste into the sea through a pipeline.",
      parts=[
          P("Explain what is meant by <b>Critical Pathway Analysis</b> (CPA).", 2,
            ms=["Predicting the route / movement a pollutant will take through the environment (based on its properties and features of the environment)",
                "To assess where it will become concentrated / which locations and organisms are most at risk, so monitoring can focus on those sites"]),
          P("Give <b>three</b> factors that would be considered in a CPA for this discharge.", 3, items=3,
            ms=["Sea current velocity and direction", "Properties of the radionuclides: half-life, solubility, tendency to adsorb onto sediments / bioaccumulate",
                "Food chain pathways, eg uptake by seaweed, shellfish, fish eaten by people", "Geology / hydrology of the coast; sediment deposition areas (mud flats)",
                "Human activities in the area: fishing, seaweed collection, beach use"]),
          P("Describe how <b>Critical Group Monitoring</b> (CGM) would be used to assess the risk to the public from this discharge.", 3,
            ms=["Identify the group of people whose lifestyle gives them the highest exposure (eg people who eat a lot of locally caught shellfish / fish, live near the mud flats, collect seaweed)",
                "Monitor their exposure / the concentration of radioactive material in the foods they eat or their body",
                "If their exposure / risk is acceptably low, everyone else is assumed to be at even lower risk; if not, emissions are controlled",
                "CGM assesses exposure before health effects occur (not used to detect damage)"]),
          P("Suggest <b>two</b> types of environmental sample that would be collected to check the CPA predictions.", 2, items=2,
            ms=["Seawater", "Sediment / mud", "Seaweed", "Shellfish / molluscs / fish", "Milk, vegetables or meat from nearby farms", "Atmospheric dust", "Soil"]),
      ]),

    Q("PCON-02", T, "3.4.3.1", "243-245",
      parts=[
          P("Explain how the control of emission <b>location</b> and emission <b>timing</b> can reduce the severity of pollution. Use examples.", 6,
            labels=["Emission location", "Emission timing"],
            ms=["Location: discharge into the sea / large water bodies where currents dilute and disperse the pollutant",
                "Location: chimneys / emissions sited downwind of urban areas so pollutants are not carried over populations; avoiding valleys and enclosed water bodies where pollutants concentrate",
                "Location: not discharging wastes onto permeable rock above an aquifer / not siting landfill on aquifers",
                "Timing: restrict polluting activities (industrial combustion, vehicle use) during temperature inversions when dispersal is poor",
                "Timing: discharge liquid effluent when river flow is high / on an ebb tide so it is diluted and carried away",
                "Timing: pesticide spraying at night / on still days; noisy operations restricted to daytime; night-flight restrictions"]),
          P("Explain the <b>polluter pays</b> principle and suggest why it encourages pollution prevention.", 2,
            ms=["The organisation / person that causes the pollution is responsible for (paying for) the damage caused",
                "If the cost of preventing the pollution is less than the cost of the damage / fines, there is a financial incentive to prevent it; works best when penalties are high and escape is unlikely"]),
          P("Explain the <b>precautionary principle</b> as applied to the release of a new chemical.", 2,
            ms=["It is assumed that the waste will cause pollution / harm until research shows it is unlikely to",
                "So release is not permitted until it has been tested; lack of knowledge of a problem is not an excuse / does not reduce responsibility"]),
      ]),

    Q("PCON-03", T, "3.4.3.1", "244-245",
      intro="Figure 1 shows the relationship between the cost of pollution control equipment at a factory and the percentage of a pollutant emission that is prevented.",
      figures=[Chart("line", "Pollution prevented / %", "Cost / &pound; million",
                     {"Control cost": [(0, 0), (20, 0.4), (40, 0.9), (60, 1.6), (80, 3.0), (90, 5.0), (95, 8.0), (99, 16.0)]}, y_min=0)],
      parts=[
          P("Describe the relationship shown in Figure 1.", 2,
            ms=["Cost increases as the percentage prevented increases", "The relationship is not linear: cost rises slowly at first then very steeply / exponentially above about 80-90%"]),
          P("Use Figure 1 to calculate the extra cost of increasing the pollution prevented from 90% to 99%.", 1, calc=True, unit="&pound; million",
            ms=["16.0 - 5.0 = 11.0 (&pound; million)"]),
          P("Explain what is meant by the terms <b>ALARA</b> and <b>BATNEEC</b> and how they would be applied by the factory.", 4,
            ms=["ALARA: emissions should be As Low As Reasonably Achievable",
                "It is rarely practical / affordable to reduce emissions to zero; low-level emissions may have acceptable impacts so an acceptable emission level is set",
                "BATNEEC: Best Available Technology Not Entailing Excessive Cost - choosing the most effective control equipment whose cost is not excessive",
                "The factory would install equipment that gives a high level of control (eg 80-90%) rather than paying &pound;16 million for 99%"]),
          P("Suggest why the control methods used originally by a factory may no longer be sufficient after several years.", 3,
            ms=["Industry / city may have expanded so there are more pollutant sources and total emissions have risen",
                "Better understanding of the health / environmental effects so stricter standards are set",
                "Improved technology becomes available (BATNEEC changes) / cost of better control falls", "Pollutant may have accumulated (persistent) so background levels are higher"]),
      ]),

    Q("PCON-04", T, "3.4.3.1, 3.4.3.3", "244, 303-304",
      intro="Table 1 shows four general approaches to pollution control.",
      parts=[
          P("Complete Table 1 by giving one example of each approach.", 4,
            table=Table(["Approach", "Example"], [["Production prevention", ""], ["Prevention of release", ""], ["Post-release remediation", ""], ["Alternative processes", ""]], blank=True),
            ms=["Production prevention: desulfurisation of fuels before combustion; low-temperature (fluidised bed) combustion to prevent NOx; smokeless fuels",
                "Prevention of release: electrostatic precipitators / bag filters / cyclones for smoke; catalytic converters; flue gas desulfurisation; bund walls; landfill liners",
                "Post-release remediation: oil spill clean-up (booms, skimmers, dispersants, bioremediation); phytoremediation of metal-contaminated land; liming of acidified lakes",
                "Alternative processes: electric vehicles instead of petrol / diesel; renewable energy instead of fossil fuels; pyrethroids instead of organochlorines; fuel cells instead of internal combustion engines"]),
          P("Explain why prevention of production is generally preferable to post-release remediation.", 2,
            ms=["Remediation is often incomplete / cannot recover all the pollutant (eg oil spills, dispersed pollutants), so some damage still occurs",
                "Prevention avoids the damage entirely and is usually cheaper than clean-up / avoids polluter-pays costs; moving from post-production treatment to non-release is a circular economy principle"]),
          P("Describe how each of the following new technologies helps to control pollution.", 4,
            labels=["Satellite monitoring of oil spills", "GPS ship tracking", "Polymer adsorption of heavy metals", "Phytoremediation"],
            ms=["Satellites detect and track the extent / movement of oil slicks over large areas, quickly and repeatedly, so clean-up can be directed and polluters identified",
                "GPS tracking monitors ship positions so navigation errors / collisions / groundings are reduced and offshore shipping routes are enforced",
                "Polymers with a high surface area adsorb metal ions from contaminated water / effluent so they can be removed and recovered",
                "Plants that absorb heavy metals (hyperaccumulators) are grown on contaminated land, harvested and disposed of / metals recovered, cleaning the soil"]),
      ]),

    Q("PCON-05", T, "3.4.3.1", "243-245",
      parts=[
          P("Which of the following best describes the purpose of Critical Group Monitoring? Tick one box.", 1,
            mcq=["To detect health damage in the population most affected by a pollutant", "To predict the route a pollutant will take through the environment",
                 "To assess exposure of the people most at risk so that everyone else can be assumed to be safe", "To measure the concentration of a pollutant at the point of release"],
            ms=["C"]),
          P("Explain why CPA can reduce the cost of an environmental monitoring programme.", 2,
            ms=["Monitoring can be focused on the sites predicted to be most at risk / where the pollutant will concentrate",
                "No need to sample sites that were never likely to be polluted; sampling also checks the accuracy of the predictions"]),
          P("A new chemical has properties similar to PCBs (persistent, liposoluble chlorinated organic compounds). Explain how knowledge of PCBs helps decisions about the new chemical.", 2,
            ms=["Behaviour of new chemicals can be predicted from similar existing chemicals: it is likely to persist, bioaccumulate and biomagnify",
                "So acceptable emission limits, control methods and monitoring programmes can be set before release (precautionary principle)"]),
      ]),
]

ESSAYS = [
    Essay("ESS-P1-CONTROL", 1,
          "Discuss how knowledge of the properties of pollutants can be used to reduce the severity of their impact on the environment.",
          "3.4.1-3.4.3", "236-245, 262-266, 275-285, 295-304",
          ["Properties: state of matter, density, persistence, toxicity, specificity, reactivity, adsorption, solubility, bioaccumulation / biomagnification, synergism, mutagenic / carcinogenic / teratogenic action, mobility",
           "How properties predict behaviour: dispersal (gases vs solids, density - Bhopal), how far and how long (persistence, mobility), where they concentrate (adsorption on sediments, food chains)",
           "Environmental features interacting with properties: temperature inversions, currents, pH, oxygen, light, adsorbent materials",
           "Control based on properties: persistent / liposoluble pesticides banned (organochlorines) and replaced by non-persistent / specific ones; systemic pesticides and seed coatings",
           "Heavy metals: lead uses discontinued, storage at high pH to reduce solubility; mercury chemical form; radioactive waste categorised by half-life / activity and contained (encapsulation, sealed storage)",
           "Reactive primary pollutants controlled to prevent secondary pollutants (catalytic converters, FGD, urea sprays); oil properties (floats, insoluble) exploited by booms and skimmers; density in cyclone separators",
           "Principles: CPA and CGM based on properties; emission location / timing; ALARA and BATNEEC; polluter pays; precautionary principle",
           "New technologies: satellite oil-spill monitoring, GPS, polymer adsorption, phytoremediation, bioremediation",
           "Evaluation: prevention better than cure; limits of remediation; cost-effectiveness; contrast success of ozone (Montreal) with climate change; judgement"]),
]
