"""Pollution: properties of pollutants and environmental factors (spec 3.4.1-3.4.2).  Genn pp. 236-242, 254-255."""
from gen.model import Q, P, Table, Chart, Essay

T = "pollutant-properties"

QUESTIONS = [
    Q("PPRO-01", T, "3.4.1", "236-240",
      intro="Table 1 shows some properties of three pollutants.",
      figures=[Table(["Pollutant", "State at 20 &deg;C", "Solubility in water", "Solubility in lipids", "Environmental half-life"],
                     [["DDT (insecticide)", "Solid", "Very low", "High", "About 15 years in soil"],
                      ["Nitrate ions", "Dissolved ion", "Very high", "Very low", "Not applicable (not degraded)"],
                      ["Hydrogen cyanide", "Gas (denser than air)", "High", "Low", "Hours"]])],
      parts=[
          P("Define the term <b>environmental half-life</b>.", 1,
            ms=["The time taken for half of a pollutant (released into the environment) to break down / degrade"]),
          P("Use Table 1 to explain why DDT is more likely than nitrate ions to biomagnify in a food chain.", 3,
            ms=["DDT is liposoluble so it is stored in fat / can pass through phospholipid cell membranes and is not excreted (nitrates are water soluble and excreted easily)",
                "DDT is persistent (long half-life) so it is not broken down before it is passed to the next trophic level",
                "So DDT bioaccumulates in each organism and becomes more concentrated at each successive trophic level"]),
          P("Suggest why the release of hydrogen cyanide at Bhopal, India, in 1984 caused deaths very close to the source rather than over a wide area.", 2,
            ms=["The gas is denser than air so it settled close to the ground / did not rise and disperse",
                "Low wind velocity (at night) meant it was not dispersed / diluted", "Short half-life so it broke down before travelling far"]),
          P("Explain how the high water solubility of nitrate ions affects the area over which they cause pollution and the concentration of the pollution.", 2,
            ms=["High solubility means nitrates are easily dispersed / leached / carried by water so they affect a larger area (eg rivers, aquifers, the sea)",
                "But dispersal dilutes the pollutant so the concentration at any one point may be lower"]),
          P("Give <b>two</b> examples of pollutants that are forms of energy rather than substances.", 2, items=2,
            ms=["Noise / sound", "Heat / thermal pollution", "Ionising radiation", "Light"]),
      ]),

    Q("PPRO-02", T, "3.4.1", "239-240",
      parts=[
          P("Explain the difference between a <b>mutagen</b>, a <b>carcinogen</b> and a <b>teratogen</b>.", 3,
            ms=["Mutagen: an agent that changes the chemical structure / base sequence of DNA (causes mutations), eg ionising radiation, UV, PCBs, cadmium, asbestos",
                "Carcinogen: a mutagen that causes cancer / uncontrolled cell division producing a tumour",
                "Teratogen: an agent that causes birth abnormalities by preventing normal gene expression (inhibiting proteins / enzymes) without changing DNA structure, eg mercury, 2,4,5-T"]),
          P("Explain why a birth abnormality caused by a teratogen cannot be inherited by future generations, whereas one caused by a mutagen may be.", 2,
            ms=["Teratogens do not change the DNA structure, so the abnormality is not in the genes and cannot be passed on",
                "Mutagens change DNA; if the mutation is in a gamete / egg / sperm (gonadic effect) it can be inherited"]),
          P("Distinguish between <b>somatic</b> and <b>gonadic</b> effects of a mutagen.", 2,
            ms=["Somatic: mutation in a general body cell, affecting the individual only (eg cancer / tumour)",
                "Gonadic: mutation in cells of the ovaries or testes / gametes / embryo, which may cause abnormalities in offspring"]),
          P("Explain what is meant by <b>synergism</b> and give an example.", 3,
            ms=["Two or more pollutants whose effects interact to produce a different (usually more serious) effect",
                "The pollutants themselves do not react to form a new pollutant (that would be a secondary pollutant)",
                "Example: ozone damages leaf cuticles so sulfur dioxide can cause more damage to the exposed cells; smoke and sulfur dioxide in smogs; neonicotinoids with fungicides"]),
      ]),

    Q("PPRO-03", T, "3.4.2.2", "241-242",
      intro="Figure 1 shows how air temperature changes with altitude above a city in a valley on two different nights. Line A shows normal conditions. Line B shows the conditions on a still, cloudless night.",
      figures=[Chart("line", "Temperature / &deg;C", "Altitude / m",
                     {"A (normal)": [(14, 0), (11, 300), (8, 600), (5, 900), (2, 1200)],
                      "B (still, cloudless night)": [(2, 0), (6, 200), (9, 400), (7, 600), (4, 900), (1, 1200)]}, y_min=0, y_max=1200)],
      parts=[
          P("Name the atmospheric condition shown by line B in Figure 1.", 1, ms=["Temperature inversion"]),
          P("Use Figure 1 to explain why pollutants released at ground level would disperse on night A but not on night B.", 4,
            ms=["On night A, temperature falls with altitude; warm effluent gases are less dense / more buoyant than the surrounding air so they rise",
                "As they rise they cool but the surrounding air is also cooler so they stay buoyant and continue to rise, dispersing and diluting",
                "On night B the air near the ground is colder / denser than the air above (inversion layer at about 400 m)",
                "Pollutants cool as they rise and become denser than the warmer air above so they are trapped below the inversion layer and become concentrated"]),
          P("Explain why the conditions on night B (still, cloudless) allowed an inversion to form.", 3,
            ms=["Cloudless sky allows infrared energy to be radiated from the ground so the ground cools rapidly",
                "The cold ground cools the air in contact with it, producing a cold dense layer near the ground",
                "Low wind velocity means the air layers of different temperatures do not mix",
                "Valley allows cold dense air to collect / drain into the low ground"]),
          P("Give <b>two</b> types of pollution event that are made more severe by temperature inversions.", 2, items=2,
            ms=["Smoke smogs (eg London 1952)", "Photochemical smogs (eg Los Angeles, Mexico City)", "Build-up of NOx / carbon monoxide / PM10 in cities"]),
      ]),

    Q("PPRO-04", T, "3.4.2.2", "240-242, 255",
      parts=[
          P("Explain how each of the following environmental factors affects the rate of degradation of pollutants. Give a named example of a pollutant for each factor.", 6,
            labels=["Temperature", "Light", "Oxygen"],
            ms=["Temperature: most chemical / biological reactions are faster at higher temperature so degradable pollutants (eg sewage) break down faster; but faster decomposition may increase deoxygenation",
                "Light: provides the activation energy for chemical reactions; photodegradation of pesticides (eg neonicotinoids break down fastest in sunlight); light drives photochemical smog reactions producing secondary pollutants",
                "Oxygen: needed for aerobic bacterial decomposition of organic wastes / sewage; oxidation of sulfide ores produces sulfur dioxide / acid mine drainage; oxidation state affects the solubility of metals"]),
          P("Explain how the presence of adsorbent materials such as clay can reduce the severity of pollution by heavy metals or radioactive caesium-137.", 2,
            ms=["Pollutant ions adsorb onto (the surface of) clay particles / organic matter in soil or sediment",
                "So they are immobilised and cannot be absorbed by organisms / leached into water; radiation is absorbed in the ground",
                "But they may be released later if conditions change (eg storms disturbing sediment, low pH)"]),
          P("Explain why a fall in pH increases the harm caused by many heavy metals.", 2,
            ms=["Many heavy metals (eg lead, aluminium) are more soluble at low pH",
                "So they are mobilised / leached from soil or sediments and can be absorbed by organisms / enter water bodies"]),
      ]),

    Q("PPRO-05", T, "3.4.1, 3.4.2.1", "236-241, 254-255",
      intro="A factory discharges a persistent, water-soluble pollutant into a river. Table 1 shows the concentration of the pollutant measured at sites along the river on a day with normal river flow.",
      figures=[Table(["Site", "Distance downstream of discharge / km", "Pollutant concentration / mg dm^-3", "River flow / m^3 s^-1"],
                     [["A (upstream)", "-2", "0.0", "12"], ["B", "0.5", "4.8", "12"], ["C", "5", "3.9", "15"], ["D (below tributary)", "12", "1.6", "36"], ["E", "30", "1.4", "38"]])],
      parts=[
          P("Calculate the percentage decrease in pollutant concentration between site B and site E.", 2, calc=True, unit="%",
            ms=["(4.8 - 1.4) / 4.8 x 100", "= 70.8% (accept 71%)"]),
          P("Explain the large decrease in concentration between sites C and D.", 2,
            ms=["A tributary joins the river, more than doubling the flow (15 to 36 m^3 s^-1)", "So the pollutant is diluted by the extra water (dispersal), not broken down"]),
          P("Explain why the concentration changes very little between sites D and E.", 2,
            ms=["The pollutant is persistent so it is not degraded / broken down as it travels", "Little extra water joins the river (flow 36 to 38) so little further dilution"]),
          P("Suggest why the pollution might be more serious if the same discharge entered a lake instead of a river.", 2,
            ms=["Lake has a long residence time / water does not flow away so the pollutant accumulates rather than being carried away",
                "Smaller volume of water / less dilution / less dispersal by currents", "Persistent pollutant gradually becomes more concentrated (eg by evaporation)"]),
          P("Explain why the factory might be permitted to discharge the effluent into the sea near a strong current but not into the river.", 2,
            ms=["Marine discharge: large volume of water and currents dilute and disperse the pollutant to acceptably low concentrations (control of emission location)",
                "River: small volume so concentrations stay high / drinking water abstraction / sensitive wildlife downstream"]),
      ]),

    Q("PPRO-06", T, "3.4.1", "237-238",
      parts=[
          P("Which of the following is a <b>secondary</b> pollutant? Tick one box.", 1,
            mcq=["Sulfur dioxide from a coal-fired power station", "Tropospheric ozone", "Carbon monoxide from a car exhaust", "Nitrogen monoxide from a diesel engine"],
            ms=["B - Tropospheric ozone (formed by reactions of NOx in sunlight)"]),
          P("Explain the difference between a primary pollutant and a secondary pollutant, using acid rain as an example.", 4,
            ms=["Primary pollutant: released directly by human activities, eg sulfur dioxide from burning coal / smelting sulfide ores; NOx from high-temperature combustion",
                "Secondary pollutant: produced by chemical reactions between primary pollutants, often with non-pollutants (water, oxygen, sunlight)",
                "Sulfur dioxide is oxidised by ozone to sulfur trioxide which dissolves to form sulfuric acid; NOx dissolve to form nitric acid",
                "The acids (sulfurous, sulfuric, nitric) are secondary pollutants; ozone itself is a secondary pollutant of NOx photochemistry"]),
      ]),

    Q("PPRO-07", T, "3.4.1", "236-240",
      parts=[
          P("Discuss how an understanding of the properties of pollutants can be used to predict their behaviour in the environment and to plan strategies to control them.", 9, level=True,
            ms=["State of matter: solids deposit near the source, gases disperse widely in the atmosphere; density (lead dust, hydrogen cyanide at Bhopal) controls how far particles/gases travel",
                "Persistence / half-life: persistent pollutants (organochlorines, CFCs, heavy metals, radioactive wastes with long half-lives) travel further, accumulate and need containment rather than dilution; non-persistent pollutants (sewage, organophosphates) can be allowed to degrade",
                "Toxicity, specificity, mode of action (enzyme inhibition, neurotoxins) determine acceptable concentrations and which species are at risk; LD50 / MDAF / MDNF used to set doses",
                "Solubility in water (nitrates disperse and leach - control by nitrate vulnerable zones) vs liposolubility (DDT, mercury bioaccumulate and biomagnify - control by bans / restrictions)",
                "Reactivity: reactive pollutants may degrade quickly or form secondary pollutants (ozone, acid rain, PANs) - controlling primary pollutants (catalytic converters, FGD) prevents secondary pollutants",
                "Adsorption onto clay / sediments immobilises metals and caesium; can be used deliberately (activated carbon filters, polymer adsorption)",
                "Mutagenic / carcinogenic / teratogenic action means no safe dose; exposure kept As Low As Reasonably Achievable (ALARA)",
                "Synergism (ozone + SO2; smoke + SO2) means pollutants must be considered together",
                "Environmental features (temperature inversions, currents, pH, oxygen) interact with properties: Critical Pathway Analysis uses properties + environment to predict where pollutants go and to focus monitoring",
                "Evaluation: properties of new chemicals can be predicted from similar ones (precautionary principle); understanding allows prevention rather than clean-up"]),
          P("State what is meant by <b>bioaccumulation</b>.", 1,
            ms=["The increase in the amount / concentration of a substance within an (individual) organism over time, because intake exceeds excretion or breakdown"]),
      ]),

    Q("PPRO-08", T, "3.4.1, 3.4.2", "238-242",
      intro="Mercury released into a lake from a factory was in the inorganic form. Fish in the lake were later found to contain high concentrations of methyl mercury, an organic form.",
      parts=[
          P("Suggest how the inorganic mercury was converted to methyl mercury.", 2,
            ms=["Inorganic mercury sank into the sediments / deep water where conditions are anaerobic / low oxygen",
                "It was chemically reduced / converted by (anaerobic) bacteria to methyl mercury"]),
          P("Explain why methyl mercury is a more hazardous pollutant than inorganic mercury.", 3,
            ms=["Methyl mercury is liposoluble so it passes through cell membranes and is stored in fat / not excreted",
                "So it bioaccumulates in organisms and biomagnifies along the food chain (eg in fish, then humans eating fish)",
                "It is a neurotoxin / teratogen causing brain damage and birth abnormalities (eg Minamata)"]),
          P("Explain why the health risk from eating fish from the lake may remain for many years after the discharges stop.", 2,
            ms=["Mercury is persistent / not degraded; it is an element so cannot be broken down",
                "It remains in the sediments and continues to be released / converted and taken up by the food chain; long-lived fish continue to accumulate it"]),
          P("Suggest <b>three</b> factors that should be included in a Critical Pathway Analysis of a proposed mercury discharge.", 3, items=3,
            ms=["Water current velocity and direction (dispersal)", "Properties of the pollutant: solubility, persistence, liposolubility / potential to bioaccumulate",
                "Food chain pathways to humans (fish, shellfish) / the critical group", "Sediment type / adsorption onto clay", "Volume of the water body / residence time / dilution", "Sensitive locations downstream (fisheries, drinking water abstraction)"]),
      ]),
]

ESSAYS = []
