"""Energy resources: renewable energy technologies - solar, HEP, wind, wave, biofuels, geothermal, tidal (spec 3.3.4.1).  Genn pp. 196-217."""
from gen.model import Q, P, Table, Chart, Essay

T = "renewables"

QUESTIONS = [
    Q("REN-01", T, "3.3.4.1", "199-203",
      intro="Table 1 shows the efficiency and cost of four types of solar photovoltaic (PV) cell.",
      figures=[Table(["PV cell type", "Efficiency / %", "Relative cost per m^2"], [["Amorphous silicon (thin film)", "8", "1"], ["Polycrystalline silicon", "16", "2"], ["Monocrystalline silicon with anti-reflective surface", "22", "3"], ["Multi-junction cell", "40", "25"]])],
      parts=[
          P("Describe how a photovoltaic cell generates electricity.", 2,
            ms=["Photons of light absorbed by the (n-type silicon) upper layer dislodge electrons, making it negatively charged", "Electrons flow through an external conductor / circuit to the relatively positive lower layer; the current powers appliances"]),
          P("Explain how anti-reflective surfaces and multi-junction cells increase efficiency.", 3,
            ms=["Smooth cells reflect about 30% of the light; grooved / textured surfaces (mimicking moth eyes) reflect light into the cell rather than away",
                "Multi-junction cells have several layers of different materials, each absorbing different wavelengths", "So a greater proportion of the available light is absorbed and converted to electricity"]),
          P("Use Table 1 to suggest which cell type would be chosen for a large solar farm on cheap desert land and which for a satellite. Justify your choices.", 3,
            ms=["Solar farm: polycrystalline / thin film - lowest cost per unit electricity where land area is not limiting (efficiency per m^2 matters less)",
                "Satellite: multi-junction - highest efficiency where mass / area is critical and cost is less important",
                "Cost per watt = cost / efficiency: thin film 0.125, poly 0.125, mono 0.136, multi-junction 0.625 per unit"]),
          P("Explain why solar PV output is intermittent <b>and</b> unpredictable.", 2,
            ms=["Intermittent: no output at night and low in winter (daily and seasonal cycles) - predictable", "Unpredictable: cloud cover, dust and smoke reduce intensity and scatter light and cannot be forecast accurately"]),
      ]),

    Q("REN-02", T, "3.3.4.1", "200-202",
      parts=[
          P("Explain how a ground-source heat pump can deliver more heat energy to a building than the electrical energy used to run it.", 3,
            ms=["A fluid in a buried ground loop absorbs low-temperature heat from the ground; at the expansion valve the fluid boils at low pressure absorbing this heat",
                "A compressor raises the pressure so the gas condenses, releasing heat at a higher temperature inside the building",
                "The electricity only moves heat rather than creating it, so up to four times as much heat is delivered as electricity used (less if the source is colder)"]),
          P("Explain how Concentrating Solar Power (CSP) with thermal storage overcomes the intermittency of solar power.", 3,
            ms=["Parabolic reflectors focus sunlight onto tubes of oil, increasing the energy density and reaching high temperatures",
                "The heat is transferred to molten salt (potassium nitrate) stored in large insulated tanks at up to 550 &deg;C", "The stored heat boils water to drive steam turbines whenever electricity is required, including at night"]),
          P("Explain why CSP can only be used in areas with little cloud, whereas PV can be used anywhere.", 2,
            ms=["Reflectors can only focus parallel rays of direct sunlight; cloud, dust and smoke scatter light so it cannot be concentrated", "PV cells convert diffuse as well as direct light, though output is lower"]),
          P("Describe <b>two</b> environmental impacts of solar PV.", 2, items=2,
            ms=["Manufacture: extraction / processing of silicon, metals and plastics; toxic wastes (silicon tetrachloride, cadmium)", "Land take by large solar farms competing with other uses / affecting desert flora and fauna", "Water for cleaning panels in arid areas", "Disposal of old panels"]),
      ]),

    Q("REN-03", T, "3.3.4.1", "203-205",
      intro="A rural community in Pakistan is considering a low-head helical (Archimedes screw) turbine on a river rather than joining a high-head dam scheme.",
      parts=[
          P("Explain why low-head turbines are more suitable than high-head HEP schemes for many rural areas.", 5,
            ms=["No large dam / reservoir needed so no flooding of farmland, homes or habitats and no barrier across the whole river (run-of-river / micro-hydro diverts part of the flow)",
                "Suitable for rivers with a small drop in height and lower flow rates that are common in lowland rural areas", "Small scale matches local demand; electricity used locally without long transmission lines / grid connection",
                "Low construction cost and simple technology maintained by the community", "Helical turbines tolerate high turbidity / debris without damage and fish pass through unharmed; Kaplan turbines with adjustable blades cope with variable flow"]),
          P("Suggest <b>one</b> reason why such schemes may not be installed even at suitable sites.", 1,
            ms=["Lack of capital / finance, technical knowledge or grid access; seasonal drying of rivers; conflicts with irrigation water; planning / land ownership"]),
          P("The maximum flow rate at the site is 6.5 m<sup>3</sup> s<sup>-1</sup> giving an output of 100 kW at 90% turbine efficiency. At 10% of maximum flow the efficiency falls to 40%. Calculate the output at 10% of maximum flow.", 2, calc=True, unit="kW",
            ms=["Output is proportional to flow x efficiency: 100 x 0.10 x (40 / 90)", "= 4.4 kW (accept 4.4-4.5)"]),
          P("Outline <b>two</b> ways a high-head reservoir can affect the river downstream.", 2, items=2,
            ms=["Constant regulated flow removes seasonal extremes: dry-season sandbanks used by nesting birds / turtles lost; high flows that clear gravel spawning beds lost; floodplain no longer flooded",
                "Sudden flow increases for peak generation raise turbidity, wash away species, reduce light for photosynthesis", "Sediment trapped so less nutrient replenishment downstream; barrier to migrating fish (salmon, sturgeon) and isolation of populations"]),
      ]),

    Q("REN-04", T, "3.3.4.1", "206-209",
      intro="The kinetic energy available to a wind turbine is proportional to the cube of the wind velocity. Table 1 shows mean wind velocities at four possible wind farm sites.",
      figures=[Table(["Site", "Mean wind velocity / m s^-1", "Distance to grid / km", "Other features"], [["A: upland ridge", "9", "12", "Migrating bird route; peat bog"], ["B: coastal farmland", "8", "3", "Near village"], ["C: offshore shallow sea", "10", "15", "Sandbanks"], ["D: inland plain", "6", "2", "Arable farmland"]])],
      parts=[
          P("Calculate how many times more kinetic energy is available at site C than at site D.", 2, calc=True, unit="times", ms=["10^3 / 6^3 = 1000 / 216", "= 4.6 times (accept 4.63)"]),
          P("Use Table 1 to evaluate the four sites for a large wind farm.", 5,
            ms=["C has the highest velocity (most energy, and energy rises with the cube of velocity), strong reliable winds over water, few land-use conflicts, but long expensive cable and offshore installation / maintenance costs",
                "A is windy but on a migration route (bird strikes) and peat bog (foundations / tracks damage hydrology; carbon release); far from grid; scenic objections",
                "B is close to the grid with good wind but near a village (noise, visual objection, shadow flicker) - possible with careful siting", "D is cheap to connect and land can still be farmed between turbines, but low velocity gives little energy",
                "Judgement, eg C or B; turbines spaced 3-5 blade diameters apart to avoid wind shadow"]),
          P("Give <b>two</b> advantages of vertical axis wind turbines (VAWTs) over horizontal axis turbines (HAWTs).", 2, items=2,
            ms=["Driven by wind from any direction so no motor to turn them; suitable for turbulent urban sites", "Generator can be at ground level so a lighter tower", "Quieter", "Operate at lower wind velocities", "Blades more visible so fewer bird deaths"]),
          P("Explain how direct-drive turbines improve on turbines with a gearbox.", 1,
            ms=["No gearbox: fewer breakdowns, less friction so start generating at lower wind speeds, quieter, lighter nacelle (DC converted to AC by an inverter)"]),
      ]),

    Q("REN-05", T, "3.3.4.1", "210-211, 214-217",
      parts=[
          P("Explain the locational requirements for harnessing wave power.", 2,
            ms=["High mean wind velocities that are consistent in strength and direction", "A long fetch (distance of open water) over which waves build up, eg Atlantic coasts of the UK"]),
          P("Describe how <b>one</b> named wave power device generates electricity.", 2,
            ms=["Oscillating water column (eg Islay Limpet): waves force water up and down in a submerged chamber; the air forced in and out drives a turbine",
                "Or point absorber (floating buoy moving relative to a fixed base turns a generator); surface attenuator (Pelamis - hinged sections push pistons pumping fluid over a turbine); overtopping device (Wave Dragon - waves fill a reservoir above sea level which drains through turbines); oscillating wave surge converter (Oyster)"]),
          P("Give <b>two</b> design problems that have delayed the development of wave power.", 2, items=2,
            ms=["Equipment must withstand storms and corrosion", "Difficult to anchor off stormy coasts / in deep water", "Expensive to transmit electricity from isolated coasts to consumers", "Competition with established technologies"]),
          P("Compare the environmental impacts of tidal barrages, tidal lagoons and in-stream tidal turbines.", 4,
            ms=["Barrage: huge quantities of construction materials; reduces tidal range so intertidal mudflats used by wading birds are lost; changes sedimentation (erosion near turbines, deposition elsewhere), lower turbidity; pollutants concentrate in the lagoon; blocks migratory fish and shipping",
                "Lagoon: similar but smaller scale; only part of the estuary enclosed so the most sensitive areas and main channel can be avoided",
                "In-stream turbines: do not block the tidal flow so little impact on range or sediment; but noise affects cetaceans and many dispersed turbines could have a larger total impact; harness less energy"]),
      ]),

    Q("REN-06", T, "3.3.4.1", "214-215",
      intro="Figure 1 shows the water level inside and outside a tidal barrage over one 12.5-hour tidal cycle and the periods when electricity is generated.",
      figures=[Chart("line", "Time / hours", "Water level / m", {"Sea level": [(0, 0), (1.5, 2.5), (3, 4), (4.5, 2.5), (6.25, 0), (8, 2.5), (9.5, 4), (11, 2.5), (12.5, 0)], "Level behind barrage": [(0, 3), (1.5, 3), (3, 4), (4.5, 4), (6.25, 4), (8, 1.5), (9.5, 4), (11, 4), (12.5, 4)]}, y_min=0, y_max=5)],
      parts=[
          P("Use Figure 1 to explain when electricity is generated by the barrage.", 2,
            ms=["When there is a difference in level between the sea and the basin: on the ebb (about 6-8 hours) water flows out through the turbines", "Also possible on the flood when the sea is higher than the basin; no generation when levels are equal (slack water)"]),
          P("Explain why tidal power is intermittent but predictable.", 2,
            ms=["Two periods of slack water in each 12.5-hour cycle (twice in about 25 hours) give no flow; the timing does not match demand", "Tides depend on the positions of the Moon and Sun which are known, so output can be forecast years ahead and alternative supplies planned"]),
          P("Explain the difference between spring and neap tides and why this affects output.", 2,
            ms=["Spring tides: Sun and Moon aligned so their gravitational effects combine giving a large tidal range; neap: effects oppose giving a small range", "Energy depends on the mass of water and height difference, so output is much greater at springs"]),
          P("Explain how a tidal lagoon can be used to generate electricity when there is no tidal flow.", 2,
            ms=["When demand is low, surplus electricity pumps water into the lagoon above sea level", "The stored water is released through the turbines later when demand is high (pumped storage)"]),
          P("Give <b>two</b> coastal features that make a site suitable for tidal power.", 2, items=2, ms=["Large tidal range (eg Severn Estuary)", "Estuaries, bays or headlands / channels that focus the flow and increase velocity"]),
      ]),

    Q("REN-07", T, "3.3.4.1", "212-214",
      parts=[
          P("Explain <b>three</b> advantages of biofuels over other renewable energy resources.", 3,
            ms=["Supply rate of energy crops can be controlled and fuels stored so supply matches demand (not intermittent)", "Liquid biofuels (alcohol, biodiesel) can replace petrol / diesel in vehicles",
                "Carbon neutral in principle: CO2 released equals CO2 absorbed in photosynthesis", "Energy density of alcohol / biodiesel nearly as high as fossil fuels; wastes (straw, sewage, landfill gas) are cheap"]),
          P("Explain <b>three</b> disadvantages of biofuel crops.", 3,
            ms=["Large areas of farmland compete with food production or cause clearance of wildlife habitats (eg palm oil)", "Intensive farming inputs (fertiliser, pesticide, machinery fuel) may release nearly as much CO2 as using fossil fuels directly",
                "Low energy density of straw, wood, Miscanthus makes transport uneconomic - must be used locally", "Supply from wastes limited to the amount produced"]),
          P("Describe <b>two</b> new biofuel technologies.", 2, items=2,
            ms=["Hydrogen from algae: some algae deprived of sulfur produce hydrogen during photosynthesis", "Anaerobic digestion extended to crop wastes and marine algae; small-scale digesters (eg one cow's manure supplying a family's cooking gas)", "Biofuels from microorganisms (eg oil-producing microalgae)"]),
          P("Explain how new low-temperature turbine technology could allow geothermal electricity generation in the UK.", 2,
            ms=["Conventional geothermal steam turbines need rocks above 150 &deg;C (recent volcanic activity), too deep to reach economically in the UK",
                "New turbines use fluids such as butane / pentane that boil at low temperatures, so water as cool as 60 &deg;C from deep boreholes / hot dry rock systems can drive them"]),
      ]),

    Q("REN-08", T, "3.3.4.1", "196-217",
      parts=[
          P("Evaluate the potential contribution of renewable energy resources to future energy supplies in a country such as the UK.", 9, level=True,
            ms=["Properties of renewables: intermittency, predictability, low energy density, storage, applicability, locational constraints, impacts, technology level, economics",
                "Wind: large offshore resource in shallow seas, falling costs, HAWT / VAWT / direct drive developments; intermittent, needs storage and grid; land-use conflicts",
                "Solar: PV costs falling rapidly, roof space, but low winter insolation in the UK; CSP unsuitable; heat pumps and photothermal for heating",
                "HEP: most large sites used; low-head, helical and micro-hydro extend use; pumped storage vital", "Tidal: large range (Severn, Mersey), predictable; barrages costly with high impact, lagoons and in-stream turbines lower impact",
                "Wave: long Atlantic fetch, but technology immature", "Biofuels: wastes, anaerobic digestion, energy crops vs food / habitat", "Geothermal: limited to low-temperature schemes / heat pumps",
                "Systems issues: storage (pumped HEP, batteries, hydrogen, P2G, V2G), grid management, diversity of sources, energy conservation reducing demand, electrification of transport",
                "Judgement: renewables could supply most electricity with storage and a diverse mix, but heat and transport are harder; transition needs investment and lifestyle change"]),
          P("State the factor by which the kinetic energy of wind increases when wind velocity doubles.", 1, ms=["Eight times (energy proportional to velocity cubed)"]),
      ]),
]

ESSAYS = [
    Essay("ESS-P1-RENEW", 1,
          "To what extent can renewable energy resources replace fossil fuels in meeting the energy needs of a modern society?",
          "3.3.2-3.3.4", "175-235",
          ["Fossil fuel features that shaped society: energy density, storage, transport, high temperatures, liquid vehicle fuels, established infrastructure",
           "Renewable features: intermittent / unpredictable (wind, solar) vs predictable (tidal) vs controllable (HEP, biofuel, geothermal); low energy density; location; low pollution but manufacturing impacts",
           "Technologies and developments for each resource with examples; new technologies improving usability",
           "Storage and grid management: pumped storage, batteries, hydrogen economy, P2G, V2G, thermal storage, peak shaving; the role of electricity as a secondary fuel",
           "Economics and politics: development costs, interest, subsidies, external costs of fossil fuels, falling renewable costs",
           "Energy conservation as part of the solution; sustainability principles - natural systems run on low-density renewable energy",
           "Judgement: electricity largely yes; heat, aviation, shipping and high-temperature industry harder; transition period with nuclear / CCS"]),
]
