"""Physical environment: soils - fertility, erosion, USLE, management (spec 3.2.5).  Genn pp. 158-169 (soil analysis 410-413)."""
from gen.model import Q, P, Table, Chart, Essay

T = "soils"

QUESTIONS = [
    Q("SOIL-01", T, "3.2.5.1", "158-160, 412",
      intro="Table 1 shows the textural composition of four soil samples.",
      figures=[Table(["Soil sample", "Sand / %", "Silt / %", "Clay / %"], [["A", "85", "10", "5"], ["B", "40", "40", "20"], ["C", "20", "25", "55"], ["D", "10", "80", "10"]])],
      parts=[
          P("Identify the sample that is a loam and explain why loams are ideal for cultivating most crops.", 3,
            ms=["B (about 40:40:20 sand:silt:clay)", "Balanced mix gives good drainage and aeration from the sand fraction", "Water retention and nutrient (ion) retention from the clay fraction; easy root penetration and cultivation"]),
          P("Explain why sample A is likely to have the highest permeability but the lowest nutrient retention.", 3,
            ms=["Large sand particles leave large pore spaces so water drains rapidly (high permeability / aeration)", "Nutrient ions adsorb onto the (charged) surfaces of clay particles but not onto sand",
                "With only 5% clay there is little surface to hold ions so nutrients are leached; low water retention too"]),
          P("Compare the thermal capacity and root penetration of soils A and C.", 2,
            ms=["C (clay) holds much water so has a high thermal capacity: warms and cools slowly; A warms rapidly after cold weather", "Clay particles held together by capillary water so roots find it hard to push between them; penetration is easy in sandy A"]),
          P("Describe how the texture of a soil sample could be determined by sedimentation.", 2,
            ms=["Shake a known mass of soil with water in a measuring cylinder and leave to settle; particles settle in order of size (sand first, then silt, then clay; organic matter floats)",
                "Measure the depth / volume of each layer to calculate the percentage of each fraction, then use the soil triangle to name the textural class"]),
      ]),

    Q("SOIL-02", T, "3.2.5.1", "158-161",
      parts=[
          P("Explain the roles of <b>three</b> named groups of soil organisms in maintaining soil fertility.", 6,
            ms=["Detritivores (worms, beetle larvae, millipedes, woodlice) physically break up dead organic matter, increasing its surface area, and release nutrients; worms create tunnels improving drainage and aeration",
                "Decomposers (bacteria, fungi) secrete enzymes that break down dead organic matter, releasing nutrient ions (ammonification) and forming humus which binds particles into crumb peds",
                "Nitrogen-fixing bacteria convert nitrogen gas to ammonium ions; nitrifying bacteria oxidise ammonium to nitrite then nitrate for root absorption",
                "Mycorrhizal fungi form symbiotic associations with roots increasing phosphate uptake"]),
          P("Explain why a soil pH between 5.5 and 7.0 is best for fertility.", 2,
            ms=["This is the range of tolerance of most plants and soil biota; acidic soils leach nutrients and mobilise toxic aluminium, damaging root membranes", "In alkaline soils phosphates become insoluble / unavailable"]),
          P("Explain how soil compaction by heavy machinery reduces fertility.", 2,
            ms=["Interstitial spaces are reduced so aeration falls (aerobic processes such as nitrification and decomposition slow) and roots cannot penetrate", "Infiltration falls so waterlogging is more likely and runoff / erosion increase"]),
      ]),

    Q("SOIL-03", T, "3.2.5.2", "162-164",
      intro="Figure 1 shows the annual soil loss measured on experimental plots with different vegetation cover on a 10% slope in a region with heavy seasonal rain.",
      figures=[Chart("bar", "Land cover", "Soil loss / t ha^-1 yr^-1", {"Soil loss": [("Forest", 0.5), ("Grassland", 2), ("Wheat, contour ploughed", 9), ("Wheat, ploughed downslope", 25), ("Bare soil", 60)]}, y_min=0)],
      parts=[
          P("Describe the pattern shown in Figure 1.", 2,
            ms=["Soil loss increases as vegetation cover decreases: forest lowest (0.5), bare soil highest (60 t ha^-1 yr^-1) - over 100 times more",
                "Ploughing downslope loses nearly three times as much as contour ploughing for the same crop"]),
          P("Explain <b>four</b> ways in which vegetation reduces the rate of soil erosion.", 4,
            ms=["Leaves / leaf litter intercept raindrops so soil particles are not dislodged by rain splash", "Roots bind soil particles together",
                "Vegetation acts as a windbreak reducing wind velocity and the kinetic energy available to carry particles", "Plants increase infiltration (root channels, organic matter) so less surface runoff",
                "Organic matter / humus from vegetation binds particles into stable peds"]),
          P("Explain why ploughing up and down a slope causes more erosion than contour ploughing.", 2,
            ms=["Furrows running downslope act as channels / gulleys that increase the velocity (kinetic energy) of runoff", "Furrows along the contour trap the water so it loses energy, deposits particles and infiltrates"]),
          P("Explain why the region's climate makes the soil vulnerable to <b>both</b> wind and water erosion.", 2,
            ms=["In the dry season the soil (especially low-clay soils) is loose and dry with little cohesion so wind blows it away", "In the wet season heavy rain causes rain splash and surface runoff when infiltration capacity is exceeded"]),
      ]),

    Q("SOIL-04", T, "3.2.5.2", "162-164",
      parts=[
          P("Explain how each of the following human activities increases soil erosion.", 4, labels=["Overgrazing", "Reducing soil biota"],
            ms=["Overgrazing: vegetation is eaten faster than it grows so soil is exposed; hooves disturb the soil, damage roots and compact it, reducing infiltration and increasing runoff",
                "Reduced biota (ploughing, agrochemicals, less organic matter): less humus so less adhesion between particles; fewer worms so less aeration and lower infiltration capacity; fewer nutrients released so less vegetation cover"]),
          P("Explain why landslides become more likely on steep slopes some years after deforestation.", 2,
            ms=["Tree roots that held the soil together decompose so the soil is bound less strongly", "Heavy rain adds mass and lubricates particles; without interception more water enters the soil, making slumping more likely"]),
          P("Describe <b>four</b> environmental impacts of accelerated soil erosion away from the field where it occurs.", 4, items=4,
            ms=["Sedimentation in rivers reduces flow capacity so flooding downstream is more likely", "Sedimentation in reservoirs reduces their storage volume", "Coastal sedimentation covering reefs / seagrass; turbidity reducing light for aquatic plants",
                "Increased atmospheric particulates from wind erosion worsening asthma; dust covering crops / urban areas", "Desertification as vegetation cannot re-establish; reduced rainfall", "Nutrients (phosphates) carried on soil particles causing eutrophication"]),
      ]),

    Q("SOIL-05", T, "3.2.5.2", "167-169",
      intro="The Universal Soil Loss Equation (USLE) is A = R x K x LS x C x P. Table 1 gives factor values for a farm.",
      figures=[Table(["Factor", "Description", "Value"], [["R", "Rainfall erosivity for the farm", "110"], ["K", "Soil erodibility: loam", "0.67"], ["LS", "Slope length and gradient: 120 m, 6%", "1.35"],
                     ["C (crop type x tillage)", "Beans (0.50) with spring ploughing (0.90); or wheat (0.35) with mulch tillage (0.60)", "see question"], ["P", "Ploughing up and down slope 1.0; contour ploughing 0.50; strip cropping with contour ploughing 0.25", "see question"]]),
               Table(["Soil erosion class", "Rate of soil loss / t ha^-1 yr^-1"], [["Low", "under 5"], ["Moderate", "5-10"], ["High", "10-20"], ["Very high", "20-30"], ["Severe", "over 30"]])],
      parts=[
          P("Calculate the annual soil loss for beans with spring ploughing, ploughed up and down the slope. Give your answer to one decimal place.", 2, calc=True, unit="t ha^-1 yr^-1",
            ms=["110 x 0.67 x 1.35 x (0.50 x 0.90) x 1.0", "= 44.8 t ha^-1 yr^-1 (accept 44.7-44.8)"]),
          P("Calculate the annual soil loss for wheat with mulch tillage and strip cropping with contour ploughing.", 2, calc=True, unit="t ha^-1 yr^-1",
            ms=["110 x 0.67 x 1.35 x (0.35 x 0.60) x 0.25", "= 5.2 t ha^-1 yr^-1"]),
          P("The natural rate of soil formation on the farm is 1 t ha<sup>-1</sup> yr<sup>-1</sup>. Use your answers and Table 2 to evaluate the sustainability of the two farming systems.", 3,
            ms=["Beans / up-and-down ploughing: severe class (over 30) and about 45 times the formation rate - clearly unsustainable, soil depth will fall",
                "Wheat / mulch / strip cropping: moderate class, reduced by about 88% but still 5 times the formation rate so not fully sustainable",
                "Further measures (long-term crops, terracing, windbreaks, more organic matter) or grazing land (C = 0.02) needed to bring loss below 1 t ha^-1 yr^-1"]),
          P("Explain why the USLE gives only an estimate of soil loss.", 2,
            ms=["Factors are averages / arbitrary values for typical conditions; rainfall erosivity varies between years / storms", "Does not include gully erosion, landslides, wind erosion or local variation in soil; based on data from particular regions"]),
          P("Suggest which single factor in the USLE a farmer can change most easily.", 1, ms=["C (crop / tillage) or P (erosion control practice) - R, K and LS are fixed by climate, soil and topography"]),
      ]),

    Q("SOIL-06", T, "3.2.5.3", "164-166",
      parts=[
          P("Complete Table 1 to explain how each method reduces soil erosion.", 5,
            table=Table(["Method", "How it reduces erosion"], [["Terracing", ""], ["Tied ridging", ""], ["Windbreaks / hedgerows", ""], ["Mulching", ""], ["Strip cropping", ""]], blank=True, col_widths=[4.5, 10.5]),
            ms=["Terracing: sloping land divided into narrow level fields held by retaining walls along contours; water slows as it crosses each terrace and infiltrates instead of running off",
                "Tied ridging: on nearly flat land a criss-cross of intersecting ridges retains rainwater, increasing infiltration and preventing runoff",
                "Windbreaks: hedgerows / tree rows reduce wind velocity (for up to 30 times their height) so the wind has less kinetic energy to carry particles; protect bare fields after harvest",
                "Mulching: organic matter on the surface protects soil from raindrop impact and wind; decomposes to humus which binds particles; retains moisture",
                "Strip cropping: strips of different crops harvested at different times (at 90&deg; to the wind) so there is always a crop protecting part of the field; slows runoff"]),
          P("Explain why long-term crops such as tea, coffee or orchards reduce erosion compared with annual arable crops.", 2,
            ms=["No frequent replanting / soil disturbance (ploughing) that breaks up soil structure and exposes particles", "Permanent root systems and canopy cover protect the soil all year"]),
          P("Describe <b>three</b> ways livestock can be managed to reduce soil erosion.", 3, items=3,
            ms=["Control stocking density so vegetation regrows faster than it is eaten", "Restrict access to vulnerable areas such as river banks (fencing)", "Move / remove livestock at high-risk times, eg after heavy rain when soil is wet", "Rotational grazing to rest pastures"]),
      ]),

    Q("SOIL-07", T, "3.2.5.1, 3.7.2.1", "158-159, 412",
      intro="A student determined the water and organic matter content of a soil sample. Table 1 shows the results.",
      figures=[Table(["Measurement", "Mass / g"], [["Empty crucible", "25.0"], ["Crucible + fresh soil", "65.0"], ["Crucible + soil after drying at 105 &deg;C to constant mass", "55.0"], ["Crucible + soil after heating in a furnace at 550 &deg;C", "52.6"]])],
      parts=[
          P("Calculate the percentage water content of the fresh soil.", 2, calc=True, unit="%", ms=["Water = 65.0 - 55.0 = 10.0 g; fresh soil = 40.0 g", "10.0 / 40.0 x 100 = 25.0%"]),
          P("Calculate the percentage organic matter content of the dry soil.", 2, calc=True, unit="%", ms=["Organic matter = 55.0 - 52.6 = 2.4 g; dry soil = 30.0 g", "2.4 / 30.0 x 100 = 8.0%"]),
          P("Explain why the soil is dried to constant mass before the organic matter is burnt off.", 2,
            ms=["So all water is removed and the mass loss on burning is due to organic matter only", "Heating until mass no longer changes shows all water has evaporated"]),
          P("Explain how the organic matter content affects the fertility and erosion risk of this soil.", 3,
            ms=["Organic matter releases nutrients as it decomposes and provides food for soil biota", "Increases water retention and, as humus, binds particles into crumb peds improving structure / aeration",
                "Surface organic matter / humus adhesion reduce rain splash and wind erosion"]),
          P("Suggest <b>one</b> reason why two students measuring the same field might get different organic matter results.", 1,
            ms=["Samples taken from different depths / locations (organic matter is concentrated near the surface); incomplete burning; different heating times"]),
      ]),

    Q("SOIL-08", T, "3.2.5", "158-169",
      parts=[
          P("Which soil property is most directly responsible for capillary rise of water from below? Tick one box.", 1,
            mcq=["High sand content", "High clay content", "Crumb peds", "High pH"], ms=["B - tiny pores between clay particles allow capillary rise; none in sand"]),
          P("Distinguish between hygroscopic, capillary and gravitational water in soil and state which are available to plants.", 3,
            ms=["Hygroscopic: held tightly by adhesive forces on particle surfaces; cannot drain and cannot be absorbed by plants", "Capillary: held in pores by surface tension; does not drain but can be absorbed by plants",
                "Gravitational: drains freely through large pores; available to plants only briefly as it passes"]),
          P("Explain why crumb peds produce more fertile soil than platy peds.", 1, ms=["Small round crumbs leave spaces giving good drainage, aeration and easy root penetration; large flat platy peds pack together reducing all three"]),
      ]),
]

ESSAYS = [
    Essay("ESS-P1-SOIL", 1,
          "Soil is often described as a non-renewable resource. Discuss the causes and consequences of soil degradation and evaluate the strategies that can be used to manage soils sustainably.",
          "3.2.5, 3.5.1.3, 3.5.1.5", "158-169, 328-337",
          ["Features of fertile soil: water, nutrients, air, organic matter, pH, biota, texture, structure, depth; slow rate of soil formation vs rapid erosion (dynamic equilibrium broken)",
           "Causes of degradation: vegetation removal, ploughing vulnerable soils, overgrazing, reduced organic matter and biota, cultivating steep slopes, compaction, salinisation from irrigation, nutrient depletion, pollution",
           "Types of erosion: rain splash, runoff, wind, slumping; consequences: reduced productivity, river and reservoir sedimentation, flooding, coastal sedimentation, particulates, desertification, landslides",
           "USLE as a tool for estimating loss and testing management",
           "Management: long-term crops, low / zero tillage, contour ploughing, tied ridging, terracing, stone rows, windbreaks, multicropping / strip cropping, mulching, organic matter, livestock control, drainage / pH / nutrient management, conservation of soil biota",
           "Links to sustainable agriculture, carbon storage, hydrological cycle, circular economy",
           "Evaluation and judgement on which strategies are most effective in different environments"]),
]
