"""Pollution: thermal pollution and oil pollution (spec 3.4.3.2.6-3.4.3.2.7).  Genn pp. 254-262."""
from gen.model import Q, P, Table, Chart, Essay

T = "water-pollution"

QUESTIONS = [
    Q("WPOL-01", T, "3.4.3.2.6", "256-257",
      intro="Figure 1 shows the maximum concentration of dissolved oxygen in fresh water at different temperatures. A power station discharges warm cooling water into a river. The lowest dissolved oxygen concentration that trout can tolerate is 6.5 mg dm^-3.",
      figures=[Chart("line", "Water temperature / &deg;C", "Maximum dissolved oxygen / mg dm^-3",
                     {"100% saturation": [(0, 14.6), (5, 12.8), (10, 11.3), (15, 10.1), (20, 9.1), (25, 8.3), (30, 7.6), (35, 7.0), (40, 6.4)]}, y_min=0, y_max=16)],
      parts=[
          P("Describe the relationship shown in Figure 1.", 1, ms=["As temperature increases the maximum dissolved oxygen concentration decreases (non-linear: falls faster at low temperatures)"]),
          P("Use Figure 1 to determine the highest water temperature at which trout could survive if the water were fully saturated with oxygen.", 1, calc=True, unit="&deg;C",
            ms=["About 39 &deg;C (accept 38-40)"]),
          P("In summer the river upstream of the power station is at 20 &deg;C and the effluent raises the temperature by 7 &deg;C. Use Figure 1 to calculate the reduction in maximum dissolved oxygen concentration caused by the effluent.", 2, calc=True, unit="mg dm^-3",
            ms=["9.1 - 7.9 (value at 27 &deg;C, accept 7.8-8.0)", "= 1.2 mg dm^-3 (accept 1.1-1.3)"]),
          P("Explain why the actual dissolved oxygen concentration downstream may be much lower than the values in Figure 1.", 2,
            ms=["Figure 1 shows the maximum / saturation values; processes that remove oxygen (aerobic decomposition of organic matter / respiration) can give values below the line",
                "Higher temperature increases the metabolic rate of organisms and the rate of bacterial decomposition so oxygen is used faster; values above the line are impossible"]),
          P("Describe <b>three</b> effects of warmer water on aquatic organisms other than reduced dissolved oxygen.", 3, items=3,
            ms=["Increased metabolic rate so more energy used / less surplus for growth", "Eggs develop faster / hatch earlier (out of step with food supply)",
                "Non-indigenous warm-water species may thrive and out-compete indigenous species", "Toxicity of other pollutants is greater as toxins are metabolised faster",
                "Reduced resistance to disease", "Proteins / enzymes denatured if temperature is very high (above about 40 &deg;C)"]),
          P("Describe how a cooling tower reduces the temperature of power station effluent water.", 1,
            ms=["Hot water is sprayed from a shower floor in a tall hollow tower; air absorbs the heat and rises, drawing in more air (updraught), so the water returned is cooler (and saturated with oxygen)"]),
      ]),

    Q("WPOL-02", T, "3.4.3.2.7", "258-259",
      parts=[
          P("Give <b>three</b> sources of oil pollution of the sea other than tanker accidents.", 3, items=3,
            ms=["Discharge of tank-washing water from tankers", "Oil rig / drilling accidents / leakage during drilling", "Pipeline leaks", "Leakage from storage tanks / refinery spills",
                "Waste lubricating oil from vehicles / industry washed into drains", "Other ship accidents (fuel oil)"]),
          P("Explain how an oil spill at sea can kill seabirds.", 3,
            ms=["Oil sticks feathers together so they lose their insulating properties and birds die of hypothermia",
                "Feathers lose buoyancy / waterproofing so heavily oiled birds drown",
                "Birds swallow toxic oil when preening; time spent cleaning feathers reduces time for feeding themselves / their young"]),
          P("Explain <b>two</b> ways in which an oil slick can harm organisms that live in the water beneath it.", 2,
            ms=["The surface film reduces the diffusion of oxygen from the atmosphere into the water, so aerobic organisms suffer from low dissolved oxygen",
                "Toxic components (benzene, xylene) dissolve and poison plankton near the surface", "Oil blocks light so algae / phytoplankton cannot photosynthesise",
                "Oil masks odours / narcotises so animals cannot find mates or food by smell", "Shore organisms (molluscs, crustaceans) are covered and asphyxiated"]),
          P("Explain why oil pollution is most serious when it occurs inshore or in an enclosed body of water.", 2,
            ms=["Dispersal / dilution by currents and waves is prevented so oil stays concentrated; in open water most spills disperse in days or weeks",
                "Inshore areas have more sensitive ecosystems (shores, reefs, mangroves, breeding sites) and more human activities (fishing, tourism) to be affected"]),
      ]),

    Q("WPOL-03", T, "3.4.3.2.7", "259-260",
      intro="Table 1 shows features of oil tanker design and operation that reduce the risk of oil pollution.",
      parts=[
          P("Complete Table 1 by explaining how each feature reduces oil pollution.", 5,
            table=Table(["Feature", "How it reduces oil pollution"],
                        [["Double hull", ""], ["Inert gas system", ""], ["Separate oil and ballast tanks", ""], ["Twin engines / rudders", ""], ["Recirculation of oil during unloading (crude oil washing)", ""]],
                        blank=True, col_widths=[5.5, 9.5]),
            ms=["Double hull: a gap of up to 2 m between the hulls so damage to the outer hull in a collision / grounding does not release oil",
                "Inert gas system: cooled engine exhaust gas (no oxygen) fills the space above the oil so an explosive oil vapour / air mixture cannot form",
                "Separate ballast tanks: ballast water is not carried in oil tanks so no residual oil is discharged when ballast is pumped out",
                "Twin engines / rudders: if one fails the ship can still be steered / propelled and is not carried onto rocks by currents or wind",
                "Crude oil washing: sludges are mixed and removed with the cargo so tanks do not need washing with seawater that was then discharged; oily water is unloaded at the terminal"]),
          P("Explain how each of the following reduces the risk of tanker accidents.", 2, labels=["Offshore shipping routes", "GPS / Automatic Identification System"],
            ms=["Offshore routes keep tankers further from the coast so if there is engine failure there is more time to deal with it before the ship is carried ashore",
                "GPS gives accurate navigation; AIS lets ship positions be monitored and coordinated to avoid collisions and groundings"]),
          P("Describe how a <b>bund wall</b> prevents oil pollution from a storage tank.", 2,
            ms=["The tank stands on an impermeable base surrounded by a wall", "The volume enclosed by the wall is greater than the tank volume so all the oil is contained if the tank splits / cannot overflow"]),
          P("Explain the purpose of an oil interceptor on the drainage system of a car park.", 1,
            ms=["Separates floating oil from drainage water so the oil is retained (for later treatment) and only water flows to the drains / river"]),
      ]),

    Q("WPOL-04", T, "3.4.3.2.7", "261-262",
      intro="In 2020 the tanker MV Wakashio ran aground on a coral reef off Mauritius and leaked about 1000 tonnes of fuel oil into a shallow lagoon near mangroves and a marine park.",
      parts=[
          P("Explain why inflatable booms were deployed immediately, and give <b>one</b> limitation of booms.", 3,
            ms=["Booms are floating tubes with a skirt that restrict the movement of floating oil, keeping it near the source / away from sensitive sites (mangroves, reef, marine park)",
                "They work best in sheltered / calm water such as the lagoon",
                "Limitation: they do not work in open water where currents or waves are strong; oil can flow under the skirt in a strong current"]),
          P("Describe how skimmers and absorbent materials remove oil, and state how the collected oil is disposed of.", 3,
            ms=["Skimmers: rotating (metal) discs / belts pick up floating oil which is scraped off and stored",
                "Absorbent materials (high surface area, eg textile mops, straw, human hair) soak up oil and are then removed",
                "Collected oil / absorbents are incinerated or sent to landfill (or oil recycled)"]),
          P("Explain why dispersants were <b>not</b> used in the lagoon.", 2,
            ms=["Dispersants break the oil into an emulsion of droplets, making it more mobile so it spreads through the water column (to the reef / seabed organisms) rather than staying on the surface",
                "They do not reduce the amount of oil; the dispersant / oil mixture may be toxic to corals and plankton in shallow, enclosed water"]),
          P("Explain how bioremediation could help remove the oil that remained on the mangrove sediments, and suggest how it could be accelerated.", 2,
            ms=["Bacteria that break down hydrocarbons digest the residual oil (most rapid where temperature, oxygen and nutrients are high)",
                "Accelerated by adding nutrients (nitrates / phosphates) and aerating (ploughing) / irrigating the sediment"]),
      ]),

    Q("WPOL-05", T, "3.4.3.2.7", "258-262",
      intro="Figure 1 shows the number of large oil spills (over 700 tonnes) from tankers worldwide and the amount of oil transported by sea between 1975 and 2015.",
      figures=[Chart("bar", "Five-year period beginning", "Number of large spills",
                     {"Large spills per year": [("1975", 24), ("1980", 9), ("1985", 8), ("1990", 8), ("1995", 4), ("2000", 3), ("2005", 4), ("2010", 2)]}, y_min=0),
               Table(["Year", "1975", "1985", "1995", "2005", "2015"], [["Oil transported by sea / million tonnes", "1 400", "1 200", "1 800", "2 400", "2 900"]], caption="Table 1")],
      parts=[
          P("Calculate the percentage increase in oil transported by sea between 1975 and 2015.", 2, calc=True, unit="%",
            ms=["(2900 - 1400) / 1400 x 100", "= 107% (accept 107.1)"]),
          P("Describe the trend in the number of large oil spills shown in Figure 1.", 2,
            ms=["Large decrease from 24 per year (1975-79) to 2 per year (2010-14)", "Steepest fall between the late 1970s and 1980s; slower decline / levelling off after 1995"]),
          P("Suggest <b>three</b> reasons for the decline in the number of large spills despite the increase in oil transported.", 3, items=3,
            ms=["Double-hulled tankers required for all large tankers", "Improved navigation (GPS, AIS) and offshore shipping routes", "Inert gas systems reducing explosions",
                "Twin engines / rudders reducing groundings after mechanical failure", "Stricter regulation, inspection and polluter-pays liability (eg after Exxon Valdez)", "Separate ballast tanks / crude oil washing"]),
          P("Explain why the total amount of oil pollution entering the sea may not have fallen as much as the number of large tanker spills.", 3,
            ms=["Most oil pollution comes from dispersed / diffuse sources not tanker accidents: waste lubricating oil, industrial oil in drains, road runoff",
                "Routine operations: small spills, pipeline leaks, storage tank leakage, oil rig accidents (eg Deepwater Horizon)",
                "Growth in oil use and transport means more small releases even if large accidents are rarer"]),
      ]),

    Q("WPOL-06", T, "3.4.3.2.6-3.4.3.2.7", "254-262",
      parts=[
          P("Which of the following oil spill treatments is most likely to kill organisms living deep in beach sediments that were not affected by the oil? Tick one box.", 1,
            mcq=["Absorbent mops", "Steam washing", "Inflatable booms", "Polymerising agents"], ms=["B - Steam washing (hot water / steam jets kill organisms in the sediment)"]),
          P("Explain how polymerising agents make an oil spill easier to clean up.", 2,
            ms=["Chemicals cause the oil molecules to join together / solidify", "Producing more solid material that can be collected / lifted more easily than liquid oil"]),
          P("Explain why deoxygenation is a more common problem in water than in air.", 2,
            ms=["Air contains about 210 cm^3 of oxygen per litre whereas water at 20 &deg;C holds a maximum of about 6 cm^3 per litre (less than 3% of the amount in air)",
                "So a small amount of oxygen-consuming activity (decomposition, respiration) or warming can remove most of the oxygen; many aquatic organisms are near the lower end of their range of tolerance"]),
      ]),
]

ESSAYS = []
