"""Biological resources: agriculture - agroecosystems (3.5.1.1), manipulation of food species and energetics (3.5.1.2),
impacts, social / economic / political factors and sustainability (3.5.1.3-3.5.1.5).  Genn pp. 306-337."""
from gen.model import Q, P, Table, Chart, Essay

QUESTIONS = [
    # ---------------- agroecosystems 3.5.1.1 ----------------
    Q("AGR-01", "agroecosystems", "3.5.1.1", "306-309",
      intro="Table 1 shows climate data for two sites where a farmer is considering growing maize, a frost-sensitive crop that needs a thermal growing season of at least 120 days.",
      figures=[Table(["Feature", "Site A: valley floor", "Site B: south-facing slope"], [["Frost-free period / days", "110", "150"], ["Days with mean temperature above 5 &deg;C", "160", "175"], ["Mean summer rainfall / mm", "180", "150"], ["Gradient / %", "1", "8"]])],
      parts=[
          P("Use Table 1 to explain which site is more suitable for maize.", 3,
            ms=["B: frost-free period (150 days) exceeds the 120 needed whereas A (110) is too short - late frosts would kill seedlings", "B is warmer / longer thermal growing season because south-facing slopes receive more insolation; valley floors are frost pockets where cold dense air collects",
                "But B has lower rainfall and a steeper slope (erosion / machinery difficulties) so irrigation / contour cultivation may be needed"]),
          P("Describe <b>three</b> ways in which temperature can be controlled to increase crop productivity.", 3, items=3,
            ms=["Greenhouses / polytunnels heated by solar gain or burning gas / paraffin (ventilated to prevent overheating)", "Woven plastic cloches / fleece over rows to retain warm air near the ground", "Burning oil / gas or using large fans in orchards to prevent frost damage to blossom", "Site selection (aspect, avoiding frost pockets); heated buildings and shelter for livestock"]),
          P("Explain why keeping livestock warm increases the amount of food converted to growth.", 2,
            ms=["Mammals and birds use food energy to maintain a constant body temperature (thermoregulation)", "Reducing heat loss (shelter, heated buildings) means less food energy is used for heat and more is available for growth"]),
          P("Explain how day length affects livestock production and how it can be manipulated.", 2,
            ms=["Long days increase milk production and egg laying; poultry grow best with short days; sheep mate as days shorten in autumn", "Artificial lighting extends the growing season for greenhouse crops or simulates autumn in spring to give sheep a second mating / lambing season"]),
      ]),

    Q("AGR-02", "agroecosystems", "3.5.1.1", "308-310, 313",
      parts=[
          P("Explain why a moderate water shortage reduces crop productivity even though the plants survive.", 3,
            ms=["Plants close their stomata to reduce transpiration losses", "Closed stomata stop the absorption of carbon dioxide so photosynthesis and growth stop",
                "Less water for nutrient absorption / transport and cell turgidity; severe shortage dehydrates cells and inhibits biochemical reactions"]),
          P("Explain the problems caused by waterlogged soils and describe <b>two</b> ways farmers reduce soil water levels.", 4,
            ms=["Anaerobic soil favours denitrifying bacteria and inhibits nitrifying bacteria so nitrate is lost faster than it forms; higher risk of fungal disease; root respiration inhibited",
                "Drainage ditches or pipes", "Deep ploughing; avoiding compaction by machinery / livestock; adding organic matter to encourage worms"]),
          P("Explain how irrigating with groundwater can cause soil salinisation and how this harms crops.", 2,
            ms=["Groundwater often contains dissolved salts; when the water evaporates from the soil the salts are left behind and accumulate", "High soil salinity causes osmotic dehydration of roots / crop death; washing out with extra water uses more water and salinises rivers"]),
          P("State how a farmer could raise the pH of an acidic soil and explain why a low pH reduces fertility.", 1,
            ms=["Add crushed lime (calcium carbonate / hydroxide); low pH increases leaching, inhibits nutrient uptake and mobilises toxic aluminium and lead"]),
      ]),

    Q("AGR-03", "agroecosystems", "3.5.1.1", "310-312",
      intro="Table 1 compares organic and inorganic fertilisers.",
      parts=[
          P("Complete Table 1 by giving two advantages and two disadvantages of each type of fertiliser.", 6,
            table=Table(["Fertiliser", "Advantages", "Disadvantages"], [["Organic (manure, sewage sludge, compost)", "", ""], ["Inorganic (eg ammonium nitrate, NPK)", "", ""]], blank=True, col_widths=[4, 5.5, 5.5]),
            ms=["Organic advantages: often waste products, locally available and cheap; add humus improving structure and water retention; increase soil biota; slow release reduces leaching",
                "Organic disadvantages: nutrient composition cannot be controlled; released slowly so needs long-term planning; bulky with high water content so expensive to transport; cannot be applied to a growing crop; odour / pathogens",
                "Inorganic advantages: composition controlled to match crop needs; nutrients released rapidly; concentrated and easy to apply",
                "Inorganic disadvantages: high energy (fossil fuel) manufacture (Haber process); no organic matter so humus and biota decline; some toxic to worms; high solubility so leached causing eutrophication; raw materials (phosphate rock) finite"]),
          P("Explain how hydroponic cultivation maximises productivity and give <b>two</b> disadvantages.", 4,
            ms=["Crops grown in a circulating nutrient solution (inert medium) in greenhouses; nutrient concentrations monitored and adjusted so nutrients are never limiting; abiotic factors controlled",
                "Roots are small (all in contact with nutrients) so more growth goes into the harvested crop; no soil-borne pathogens or weeds; crop stays fresh with roots",
                "Disadvantages: high inputs of nutrients and energy (heating, lighting, pumping); high level of technical knowledge; only economic for high-value crops"]),
      ]),

    Q("AGR-04", "agroecosystems", "3.5.1.1", "314-318",
      intro="Table 1 shows the yield of a vegetable crop under different pest control methods over three years on one farm.",
      figures=[Table(["Method", "Mean yield / t ha^-1", "Pesticide applications per year", "Non-target insect species recorded in field margins"], [["Chemical insecticide only", "18.5", "6", "8"], ["Crop rotation + beetle banks + hedgerows", "16.2", "0", "31"], ["Integrated control", "18.1", "1-2", "26"]])],
      parts=[
          P("Explain how crop rotation and beetle banks reduce pest damage.", 4,
            ms=["Rotation: each crop has its own pests; growing a different crop each year (4-5 year cycle) means pests left at the end of a season die before that crop returns, so populations cannot build up early",
                "Beetle banks / hedgerows provide habitat and overwintering sites for natural predators (ground beetles, ladybirds) that eat aphids", "Rotation also evens out nutrient demands and includes legumes"]),
          P("Use Table 1 to evaluate integrated control compared with the other two methods.", 3,
            ms=["Integrated control gives almost the same yield as chemical control (18.1 vs 18.5) with far fewer applications (1-2 vs 6)", "It retains most of the biodiversity of cultural control (26 vs 31 species) whereas chemical control alone leaves only 8",
                "Cultural control alone loses about 12% yield; integrated control combines cultural methods, resistant varieties and carefully timed specific non-persistent pesticides only when essential - best balance of yield, cost and impact"]),
          P("Describe how the sterile male technique controls insect pests and explain why it is species-specific.", 3,
            ms=["Large numbers of males are sterilised with gamma radiation and released", "Females of many insects mate only once and store sperm, so mating with a sterile male produces no offspring; enough sterile males reduce fertile matings below replacement level (screw worm fly, Mediterranean fruit fly)",
                "Only the target species' females mate with them so non-target species are unaffected; fails if sterilised males behave abnormally or re-colonisation occurs"]),
      ]),

    Q("AGR-05", "agroecosystems", "3.5.1.1", "316-320",
      parts=[
          P("Describe <b>two</b> case studies of biological control, one successful and one that caused problems.", 4,
            ms=["Success: Cactoblastis moth introduced from South America controlled prickly pear cactus in Australia; Encarsia parasitic wasps control greenhouse whitefly",
                "Problems: cane toads introduced to Australia to control sugar cane beetles did not control them but ate many other species and are toxic to predators; rosy wolfsnail introduced to Polynesia to control African land snails ate endemic Partulid snails (48 species extinct); harlequin ladybirds introduced to Europe eat native ladybirds",
                "Lesson: control agents should be specialist feeders on the pest"]),
          P("Explain how pheromone traps can be used in pest control.", 2,
            ms=["Release an artificial sex scent attracting males (or females) of the pest species", "Used to monitor when the pest arrives so pesticide is timed correctly, or (in enclosed greenhouses) to trap enough of one sex to prevent breeding"]),
          P("Explain why the use of antibiotics as growth promoters in livestock is a concern for human health.", 3,
            ms=["Regular low doses kill only the most sensitive bacteria so resistant strains survive and multiply", "Agricultural use exceeds medical use, so resistance spreads",
                "Resistant zoonotic bacteria (E. coli, Salmonella, Campylobacter) can transfer to humans and are harder to treat; hence reduced use of antibiotics is a sustainability goal"]),
          P("Give <b>one</b> way farmers can support crop pollinators.", 1, ms=["Grow nectar-rich flowering plants alongside crops; restrict pesticides harmful to bees / spray when not in flower; introduce bee hives"]),
      ]),

    # ---------------- food-species 3.5.1.2 ----------------
    Q("FS-01", "food-species", "3.5.1.2", "321-323",
      parts=[
          P("Compare selective breeding, asexual reproduction and cross-breeding as methods of improving livestock or crops.", 6,
            ms=["Selective breeding: parents chosen for desirable genetic characteristics (Limousin muscle growth, Merino wool, Cheviot hardiness); combines genes but characteristics of offspring not fully predictable; many generations needed; risk of inbreeding",
                "Asexual reproduction (cuttings, runners, tissue culture, cloning): offspring genetically identical to the parent so characteristics are predictable and survival high; but no variation so no improvement and vulnerability to the same disease; cloning of animals (nucleus transfer into an enucleated egg, surrogate) still developing",
                "Cross-breeding: two breeds combined to give a mix of characteristics with hybrid vigour (heterosis) and lower inbreeding risk, eg Zebu (heat tolerant) x Ayrshire (high milk yield)"]),
          P("Explain how artificial insemination and embryo transfer increase the rate at which desirable characteristics spread through a livestock population.", 4,
            ms=["AI: semen from a male with desirable characteristics can fertilise many more females than natural mating; frozen semen stored and transported easily and used after the male dies",
                "Embryo transfer: FSH stimulates a superior female to release many eggs, which are fertilised (IVF) with sperm from a superior male", "Each embryo is implanted in a different surrogate female",
                "So the donor produces many offspring per year rather than one per pregnancy"]),
      ]),

    Q("FS-02", "food-species", "3.5.1.2", "323-324",
      intro="Table 1 describes three genetically modified (GM) crops.",
      figures=[Table(["GM crop", "Gene source", "Characteristic"], [["Bt maize / cotton", "Bacillus thuringiensis bacterium", "Produces a toxin that kills insect pests"], ["Roundup Ready soya", "Agrobacterium", "Resistant to the herbicide glyphosate"], ["Golden rice", "Daffodil and Erwinia bacterium", "Produces vitamin A in the grain"]])],
      parts=[
          P("Explain the main advantage of GM over conventional selective breeding.", 2,
            ms=["Single genes can be transferred from any species, not just closely related ones that produce fertile hybrids", "Desired characteristics introduced without linked unwanted ones; faster"]),
          P("For each crop in Table 1, explain one potential benefit.", 3, labels=["Bt crops", "Roundup Ready soya", "Golden rice"],
            ms=["Bt: reduces insecticide spraying so fewer non-target deaths, lower cost / energy", "Roundup Ready: weeds controlled by spraying glyphosate without harming the crop, so higher yields with less cultivation / tillage",
                "Golden rice: provides vitamin A in the staple diet, reducing about 500 000 cases of blindness a year in India / sub-Saharan Africa"]),
          P("Explain <b>four</b> concerns about GM crops.", 4,
            ms=["Gene transfer by pollen to conventional / organic crops or wild relatives (eg Bt gene killing insects feeding on wild plants)", "Antibiotic-resistance marker genes could transfer to pathogenic bacteria; possible allergies; gene transfer to gut bacteria",
                "Detection in the human food chain from crops approved only for animal feed", "Economic: seeds must be bought each year from patent-holding companies, raising costs and reducing local crop diversity and seed saving in LEDCs; herbicide-resistant crops may increase herbicide use"]),
          P("Give <b>one</b> reason why GM crops have been slow to enter cultivation in Europe.", 1, ms=["Public / political concern that risks are not fully assessed - more evidence needed (precautionary principle)"]),
      ]),

    Q("FS-03", "food-species", "3.5.1.2", "324-327",
      intro="Table 1 shows the energy inputs and food energy outputs of three farming systems.",
      figures=[Table(["System", "Energy input / GJ ha^-1 yr^-1", "Food energy output / GJ ha^-1 yr^-1"], [["Extensive cereal farming (low inputs)", "4", "20"], ["Intensive cereal farming (fertiliser, pesticide, machinery)", "20", "60"], ["Intensive beef (grain-fed)", "40", "4"]])],
      parts=[
          P("Calculate the energy ratio (output / input) for each system.", 2, calc=True, unit="", ms=["Extensive cereal 5.0; intensive cereal 3.0", "Intensive beef 0.1"]),
          P("Use your answers to explain the difference between productivity and efficiency.", 3,
            ms=["Intensive cereal is most productive per hectare (60 GJ) but less efficient (3.0) than extensive (5.0)", "Each extra unit of input gives a smaller extra yield (law of diminishing returns)",
                "Beef has very low productivity and efficiency because energy is lost at an extra trophic level"]),
          P("Explain what is meant by an <b>energy subsidy</b> and give <b>three</b> examples.", 3,
            ms=["Any input that increases productivity but requires the use of energy (usually fossil fuel)", "Manufacture of nitrate fertiliser (Haber process) and pesticides; fuel for machinery; pumping irrigation water; grain drying; food processing and transport; embodied energy of machinery"]),
          P("Explain why spreading the same total inputs over a larger area would increase total food production.", 2,
            ms=["Because of diminishing returns, the first units of input on unfertilised land give the largest yield increases", "Moving inputs from intensively farmed land (where extra input adds little) to extensively farmed land gives a greater total yield - though land, cost and distribution limit this"]),
      ]),

    Q("FS-04", "food-species", "3.5.1.2", "326-328",
      intro="Table 1 shows food conversion ratios (FCR) for livestock: the mass of feed needed to produce 1 kg of live mass gain.",
      figures=[Table(["Livestock", "FCR / kg feed per kg gain"], [["Farmed salmon", "1.2"], ["Chicken", "1.8"], ["Pork", "3.0"], ["Beef (feedlot)", "7.0"], ["Sheep", "8.0"]])],
      parts=[
          P("Use Table 1 to explain why intensive poultry and fish production convert feed to food more efficiently than beef.", 3,
            ms=["Chicken and salmon need far less feed per kg gained (1.2-1.8 vs 7.0)", "Fish are ectotherms so no energy is used for thermoregulation and water supports their mass; poultry grow fast and are kept warm indoors with movement restricted",
                "Cattle are large endotherms, use energy in movement, and lose energy in methane from cellulose digestion"]),
          P("Explain <b>three</b> ways farmers reduce food chain energy losses in livestock production.", 3,
            ms=["Control of movement (housing / restricted grazing) so less energy is used in muscle activity", "Temperature control (heated / insulated buildings) so less energy is used in maintaining body temperature",
                "Species selection: choose species with low FCRs (poultry, fish); high-energy easily digested diets; slaughter at the fastest growth stage"]),
          P("Explain why growing crops for direct human consumption usually produces more food per hectare than rearing livestock, and describe <b>one</b> situation where livestock is the better option.", 4,
            ms=["Only about 10% of the energy at one trophic level is passed to the next; most is lost as heat in respiration / metabolism or in undigested material",
                "Humans eating plants (primary consumers) receive more of the energy captured by photosynthesis than eating animals fed on those plants (secondary consumers)",
                "Livestock better where land cannot grow crops (upland, semi-arid, steep, thin soils): grazing animals with symbiotic gut bacteria digest cellulose in grass that humans cannot", "Omnivores (pigs) convert food wastes (dairy by-products, catering waste) into meat"]),
      ]),

    # ---------------- agri-impacts 3.5.1.3-3.5.1.5 ----------------
    Q("AGI-01", "agri-impacts", "3.5.1.3", "328-330",
      parts=[
          P("Explain how each of the following agricultural changes affects wildlife habitats.", 6,
            labels=["Drainage of wet grassland", "Application of fertiliser to a species-rich meadow", "Removal of hedgerows to enlarge fields"],
            ms=["Drainage makes soils aerobic and drier, increasing grass growth but wetland plants and the animals they support (waders, amphibians, invertebrates) cannot survive",
                "Fertiliser increases nutrient availability so vigorous species (grasses, nettles) grow taller and out-compete smaller wildflowers for light; diversity falls",
                "Hedgerow removal destroys habitat / corridors and nesting sites; loss of natural pest predator habitats increases pest damage; larger fields increase wind erosion; genetic contamination and introduced species also accepted"]),
          P("Explain why some farmland habitats are valuable for wildlife conservation.", 2,
            ms=["Long-continued traditional farming has created plagioclimax habitats colonised by many species: hay meadows, chalk grassland, grazed heath / moorland, hedgerows", "These communities depend on the farming continuing"]),
          P("Describe how agriculture contributes to climate change.", 2,
            ms=["CO2 from fossil fuel use in machinery and embodied energy of fertiliser (Haber process) and machinery; ploughing increases soil respiration", "Methane from livestock intestines and rice paddies; nitrous oxide from manure and nitrogen fertilisers"]),
      ]),

    Q("AGI-02", "agri-impacts", "3.5.1.3-3.5.1.4", "329-333",
      parts=[
          P("Describe how agriculture alters the hydrological cycle.", 3,
            ms=["Irrigation depletes rivers and aquifers (eg Aral Sea, Ogallala); increases evaporation", "Soil erosion and compaction reduce water retention and infiltration so runoff and river flow fluctuations increase",
                "Evapotranspiration changes: increased in irrigated arid areas, decreased where forests were cleared"]),
          P("Explain how each of the following consumer choices can reduce the environmental impact of food production.", 4, labels=["Seasonal / local food", "Organic food"],
            ms=["Seasonal / local: avoids energy for heating, lighting greenhouses out of season and long-distance transport (food miles) and the pollution this causes",
                "Organic: uses natural processes (rotation, legumes, manure, biological control, predator habitats) instead of artificial fertilisers and pesticides, so less pollution, energy use and harm to non-target species; free-range and Fairtrade also accepted for welfare / social reasons"]),
          P("Explain why post-war European governments introduced grants and guaranteed prices, and describe <b>one</b> environmental consequence.", 3,
            ms=["Food shortages after 1945 (dependence on US food aid); farmers could not afford loans to invest so grants funded machinery, drainage, hedgerow removal, liming, improved livestock",
                "Guaranteed market / price support: government bought surpluses to hold prices up (and sold stores in poor years) giving farmers security to increase output",
                "Consequences: loss of hedgerows and wetlands, intensification, pesticide and fertiliser pollution; later food surpluses (butter mountains) that could not be sold without harming LEDC producers"]),
      ]),

    Q("AGI-03", "agri-impacts", "3.5.1.4", "332-334",
      parts=[
          P("Explain why food surpluses produced in MEDCs in the 1970s could not easily be sold.", 3,
            ms=["Other MEDCs (USA, Canada, Australia) also had surpluses; Japan already had suppliers", "Eastern Europe / USSR needed food but could not pay",
                "Selling cheaply in LEDCs would undercut local farmers, put them out of business and reduce their long-term food production"]),
          P("Describe <b>four</b> methods used to reduce over-production while maintaining farm incomes.", 4, items=4,
            ms=["Quotas limiting production (eg milk)", "Set-aside payments for taking land out of production", "Farm diversification (recreation, farm shops, specialised products) and alternative crops / livestock (biofuels, pharmaceutical poppies, llamas, deer, bees)",
                "Agri-environmental schemes (ESA, CSS, ESS, CS) paying for environmentally beneficial farming"]),
          P("Describe <b>three</b> features that farmers may be paid for under an agri-environmental scheme and the conservation purpose of each.", 3, items=3,
            ms=["Hedgerows at least 1.5 m tall cut at 2-year intervals outside the breeding season - bird / insect habitat and landscape", "Buffer strips / field margins (no cultivation, fertiliser or pesticide within 2 m) - protect ditches and rivers, habitat",
                "Beetle banks of tussocky grass - natural pest predators", "Skylark nesting plots; wild bird seed / nectar plants - winter food and pollinators", "In-field tree protection; controlled stocking density to reduce compaction; ditch management; dry-stone walls; woodland management"]),
      ]),

    Q("AGI-04", "agri-impacts", "3.5.1.5", "335-337",
      parts=[
          P("Discuss the strategies that can be used to increase the sustainability of agriculture.", 9, level=True,
            ms=["Why needed: growing population (to 12 billion), land degradation since the fertile crescent, reliance on artificial fertilisers, pesticides and unsustainable irrigation; limits to new land and imports",
                "Pest control: cultural methods (weeding, mulching, rotation, barrier / companion crops, predator habitats, biological control, sterile males, pheromones), resistant varieties, integrated control, reduced antibiotics",
                "Nutrients: natural processes - nitrogen-fixing legumes, decomposition, recycling organic matter (manure, compost), crop rotation, permaculture, conservation of soil biota and mycorrhizae, reduced artificial fertiliser; phosphate recycling",
                "Energy: natural processes instead of Haber-process fertiliser, low tillage, less machinery, renewable energy, low food miles, reduced methane (cattle diets, rice varieties)",
                "Water: low water-use crops, drip irrigation, reservoirs and aquifer recharge, avoiding saline water; soil: organic matter maintenance, erosion control",
                "Biodiversity: retaining hedgerows, ditches, ponds, woodlands; CWR conservation and seed banks; agri-environment schemes",
                "Social: control of impacts on rural communities, Fairtrade, local food; consumer choices",
                "Evaluation: yields vs sustainability, cost, need for policy support; judgement"]),
          P("State what is meant by <b>permaculture</b>.", 1, ms=["Agricultural systems designed to mimic natural ecosystems - perennial crops, mixed species, recycling of nutrients, minimal external inputs"]),
      ]),
]

ESSAYS = [
    Essay("ESS-P2-AGRI", 2,
          "Agriculture involves the control of abiotic and biotic factors to maximise food production. Discuss how this control can be achieved and evaluate its environmental impacts.",
          "3.5.1", "306-337",
          ["Species selection: market, range of tolerance, controllability",
           "Abiotic control: temperature, light, water, soil fertility / nutrients, aeration, salinity, pH, CO2, topography, relief, wind - methods and examples",
           "Biotic control: pest groups, cultural control, biological control (successes and failures), sterile males, pheromones, genetic resistance, pesticides (properties), antibiotics, pollinators, soil biota",
           "Manipulation of food species: population density, monocultures, selective breeding, asexual reproduction, cross-breeding, AI / embryo transfer, GM; energetics - intensive vs extensive, energy subsidies, ratios, FCR, food chain losses",
           "Impacts: habitat loss / change, reduced biodiversity, introduced species, pesticide and nutrient pollution, GHGs, hydrological changes, soil erosion; positive: plagioclimax habitats",
           "Social, economic and political influences shaping methods",
           "Sustainable strategies and evaluation; conclusion"]),
]
