"""Biological resources: aquatic food production - marine productivity and fishing (3.5.2.1-3.5.2.2), aquaculture (3.5.2.3).
Genn pp. 338-359."""
from gen.model import Q, P, Table, Chart, Essay

QUESTIONS = [
    # ---------------- fishing 3.5.2.1-3.5.2.2 ----------------
    Q("FISH-01", "fishing", "3.5.2.1", "338-339",
      intro="Figure 1 shows the seasonal changes in light intensity, nutrient concentration and phytoplankton biomass in the surface water of a temperate ocean in the northern hemisphere.",
      figures=[Chart("line", "Month", "Relative value", {"Light": [(1, 10), (3, 40), (5, 80), (7, 100), (9, 60), (11, 15), (12, 10)], "Nutrients": [(1, 90), (3, 85), (5, 30), (7, 10), (9, 20), (11, 70), (12, 85)], "Phytoplankton": [(1, 5), (3, 20), (5, 95), (7, 30), (9, 45), (11, 10), (12, 5)]}, y_min=0, y_max=100)],
      parts=[
          P("Use Figure 1 to explain the spring peak and summer decline in phytoplankton biomass.", 4,
            ms=["In winter nutrients are high (storms disturb sediments, deep mixing) but light is too low for photosynthesis", "In spring light rises while nutrients are still high so growth is rapid - the spring bloom (peak about May)",
                "The bloom uses up nutrients (falling to 10 by July); dead plankton sink out of the photic zone carrying nutrients to the seabed", "So nutrients become limiting in summer despite high light; a smaller autumn bloom follows when storms return nutrients while light is still adequate"]),
          P("Explain why tropical open oceans have low productivity all year despite high light and temperature.", 2,
            ms=["Warm surface water is stable (no seasonal mixing / storms) so nutrients lost to deep water in sinking dead organisms are not replaced", "Nutrient (especially phosphate) concentrations in the photic zone remain very low - the limiting factor"]),
          P("Explain why areas of upwelling and coastal waters are the most productive parts of the sea.", 3,
            ms=["Upwelling (offshore winds, seamounts, currents deflected upwards) brings cold nutrient-rich deep water into the photic zone",
                "Coastal waters receive nutrients washed off the land in rivers and storms disturb shallow sediments", "Nutrients plus light in the shallow photic zone allow high algal productivity supporting rich food webs and fisheries (eg Peru anchovy)"]),
          P("Explain why phosphate is often the limiting nutrient in the sea.", 1, ms=["Phosphates have low solubility and no atmospheric reservoir; they are only added by river runoff or upwelling and are lost to sediments"]),
      ]),

    Q("FISH-02", "fishing", "3.5.2.2", "340-343",
      intro="Table 1 shows features of some fishing methods.",
      parts=[
          P("Complete Table 1.", 6,
            table=Table(["Method", "Target species", "One environmental disadvantage"], [["Demersal trawling", "", ""], ["Purse seining", "", ""], ["Pelagic long-lining", "", ""]], blank=True, col_widths=[4, 4.5, 6.5]),
            ms=["Demersal trawl: seabed species - cod, haddock, plaice, shrimps, scampi; chains / weights damage the seabed (mix aerobic and anaerobic layers, destroy sea fans, corals, seagrass); high by-catch in mixed fisheries; high fuel use",
                "Purse seine: shoaling pelagic species - tuna, sardines, herring, anchovy; can remove whole shoals; dolphins associated with tuna shoals may be caught",
                "Pelagic long-line: tuna, squid; albatrosses (long-lived, low breeding rate) drown on baited hooks; sharks and turtles caught"]),
          P("Explain why by-catch is a particular problem with shrimp trawling and drift netting.", 2,
            ms=["Shrimp trawls use very small mesh so crabs, molluscs, sea urchins, starfish, juvenile fish cannot escape - by-catch can be 99% of the catch",
                "Drift nets are non-selective curtains near the surface catching whales, dolphins, turtles, sharks"]),
          P("Explain what is meant by <b>ghost fishing</b> and describe <b>two</b> ways it can be reduced.", 2,
            ms=["Lost or discarded nets and traps continue to catch and kill organisms; dead animals act as bait attracting more", "Biodegradable ropes / panels so lost traps fall apart; radio transmitters on traps so they can be recovered; net recovery schemes"]),
      ]),

    Q("FISH-03", "fishing", "3.5.2.2", "341-342, 348-349",
      intro="Table 1 shows life-history features of three fish species and the age at which they reach a catchable size.",
      figures=[Table(["Species", "Age at catchable size / years", "Age at first breeding / years", "Eggs per female per year", "Maximum lifespan / years"], [["Atlantic cod", "2", "4", "Millions", "25"], ["Orange roughy", "20", "30", "Thousands", "150"], ["Herring", "2", "2", "Tens of thousands", "20"]])],
      parts=[
          P("Use Table 1 to explain why orange roughy populations collapsed within ten years of large-scale fishing beginning in the late 1970s.", 4,
            ms=["k-selected: very slow growth, does not breed until 30, few eggs, so the population cannot replace losses", "Fish reach catchable size (20) before they breed (30) so fishing can remove the entire future breeding population",
                "Deep-water aggregations easily located and caught by trawling", "Recovery takes decades so fisheries have had to be closed"]),
          P("Explain why herring populations recover from overfishing much faster than cod.", 2,
            ms=["Herring breed at 2 years - the same age they become catchable - so there is always a breeding population and many young", "Cod are catchable at 2 but do not mature until 4, so heavy fishing removes most fish before they breed"]),
          P("Explain why the total mass of fish landed can stay the same while a population is being overfished.", 2,
            ms=["Larger numbers of smaller / younger fish are caught, or bigger boats, nets and sonar increase catch effort", "Masks the decline of the breeding population until a sudden collapse"]),
          P("Describe how the Greenland shark and blue (common) skate illustrate the threat of by-catch to k-selected species.", 2,
            ms=["Neither is a target species but both are caught in demersal trawls; skate now extinct in the Baltic and critically endangered elsewhere", "Very late maturity (skate 11 years, Greenland shark 100-150 years, living over 400) and few young mean even low by-catch mortality exceeds replacement"]),
      ]),

    Q("FISH-04", "fishing", "3.5.2.2", "349-351",
      intro="The Russell formula describes changes in a fish stock: S<sub>2</sub> = S<sub>1</sub> + (A + G) - (C + M), where S<sub>1</sub> and S<sub>2</sub> are the stock biomass at the start and end of the year, A = recruitment of young fish, G = growth, C = catch and M = natural mortality. Table 1 gives estimates for a cod stock.",
      figures=[Table(["Term", "Biomass / thousand tonnes"], [["S_1", "600"], ["A", "90"], ["G", "150"], ["C", "220"], ["M", "80"]])],
      parts=[
          P("Calculate S<sub>2</sub> and state whether the stock is being fished sustainably.", 2, calc=True, unit="thousand tonnes", ms=["600 + (90 + 150) - (220 + 80) = 540", "Stock fell by 60 so the catch exceeds the MSY / unsustainable"]),
          P("Calculate the maximum catch that would have kept the stock constant.", 1, calc=True, unit="thousand tonnes", ms=["A + G - M = 90 + 150 - 80 = 160"]),
          P("Explain why the catch is the only term in the formula that is easy to measure, and why the others are difficult.", 3,
            ms=["Catch is landed and weighed at ports so it is recorded", "Other terms need data on fish in the sea: populations are mobile (crossing national boundaries), very unevenly distributed",
                "Representative sampling of a large enough proportion of the area is impractical / expensive; survival of eggs and larvae varies greatly between years"]),
          P("Describe how each of the following measures obtained from commercial catches can indicate overfishing.", 4,
            labels=["Catch per unit fishing effort", "Mean fish size and mean age"],
            ms=["CPUE: if more effort (boat-days, engine power, net size) is needed to land the same catch, the population is declining even though total catch is maintained; a better measure than catch size which technology can prop up",
                "Falling mean size / age (from scale or otolith growth rings) shows older adults are being removed faster than replaced and the catch depends on small young fish"]),
      ]),

    Q("FISH-05", "fishing", "3.5.2.2", "344-348",
      parts=[
          P("Explain how each of the following reduces the environmental impact of fishing.", 8,
            labels=["Square-mesh escape panels", "Minimum and maximum catchable sizes", "No-take zones", "Closed seasons"],
            ms=["Normal diagonal mesh closes as the net fills / stretches so small fish cannot escape; square-mesh panels do not close so juveniles escape to grow and breed; TEDs let turtles out; larger mesh sizes generally",
                "Minimum size lets fish reach breeding age before capture (eg UK lobster minimum carapace above breeding size, cod 35 cm); maximum size / V-notching egg-carrying females protects large, highly fecund breeding adults (Hebridean lobsters over 145 mm, Nassau grouper)",
                "NTZs (Lundy, Lamlash Bay, Chagos, Great Barrier Reef) protect breeding populations and habitats; surplus young spill over and increase surrounding catches; damaged communities recover",
                "Closed seasons, ideally in the breeding season, let fish grow and breed; fishermen may oppose because shoaling breeders are easy to catch"]),
          P("Explain why catch quotas work well for pelagic species such as mackerel but poorly in mixed demersal fisheries.", 2,
            ms=["Pelagic species form single-species shoals so fishing stops when the quota is reached", "In mixed fisheries many species are caught together; once one species' quota is reached it must be discarded (dead) while fishing for others continues"]),
      ]),

    Q("FISH-06", "fishing", "3.5.2.2", "344-348",
      parts=[
          P("Describe <b>three</b> methods of reducing seabird by-catch in long-line fisheries.", 3, items=3,
            ms=["Sinkers / weighted lines so hooks sink quickly below the reach of albatrosses", "Setting lines at night when birds are not feeding", "Bird-scaring streamers / decoys", "Curved hooks that catch tuna but not birds"]),
          P("Explain how restricting fishing effort and restricting fishing methods reduce overfishing.", 3,
            ms=["Effort: limits on boat size, engine power, days at sea, number of licences; decommissioning payments to reduce fleet size where overfishing is unavoidable",
                "Methods: bans or length limits on drift nets; bans on demersal trawling over sensitive seabed (Rockall Bank, Hatton Bank deep-water reefs)", "Shorter trawl tows so turtles / by-catch survive (over 99% survive under 10 minutes)"]),
          P("Describe how captive rearing and release ('population seeding') can increase wild populations of lobsters or oysters.", 2,
            ms=["Eggs / larvae are reared in captivity through the planktonic stage when most die (predation, failure to find habitat)", "Juveniles are released when survival chances are good, increasing recruitment to the adult population"]),
          P("Explain why collecting data on planktonic fish eggs and larvae helps to prevent population collapse.", 2,
            ms=["Egg / larval survival varies greatly between years so adult numbers do not predict recruitment", "Several poor years would lower the MSY; egg surveys allow catches to be reduced in advance rather than after a sudden collapse"]),
      ]),

    # ---------------- aquaculture 3.5.2.3 ----------------
    Q("AQUA-01", "aquaculture", "3.5.2.3", "352-355",
      parts=[
          P("Explain why carnivorous species such as salmon dominate aquaculture in MEDCs while herbivores such as carp and tilapia dominate in LEDCs.", 3,
            ms=["MEDCs: market demand and higher prices for the flavour of carnivorous fish (salmon, trout) justify high inputs (fishmeal, cooler climates suit them)",
                "LEDCs: herbivores / omnivores feed on natural vegetation, phytoplankton and wastes so need low inputs; warm climates suit tilapia", "Herbivores are more energy-efficient (lower trophic level) so more food per unit area"]),
          P("Describe how all-female rainbow trout are produced and explain why this is done.", 3,
            ms=["Some genetically female (XX) fish are treated with testosterone so they become functional males producing only X-carrying sperm", "Crossed with normal females (XX) all offspring are XX females",
                "Female trout meat has a better flavour; in tilapia the reverse (all males) because males grow larger / more efficiently"]),
          P("Explain how each of the following abiotic factors is controlled in an intensive salmon farm.", 4, labels=["Dissolved oxygen", "Water flow", "Day length", "Temperature"],
            ms=["Salmon need high oxygen: water sprays / weirs aerate; wastes removed to prevent deoxygenation", "Constant circular flow keeps fish swimming the same way - fewer collisions / injuries, more muscular fish, higher stocking density",
                "Artificial lighting delays maturation (salmon stop growing at maturity) so larger fish; controls smoltification", "Cool sites (Scotland, Norway) because warm water holds less oxygen although warmth increases growth"]),
      ]),

    Q("AQUA-02", "aquaculture", "3.5.2.3", "352-356",
      intro="Table 1 compares extensive oyster farming with intensive salmon farming.",
      figures=[Table(["Feature", "Extensive oyster farm", "Intensive salmon farm"], [["Food input", "None - filter natural plankton", "Fishmeal / plant pellets"], ["Stocking density", "Low, spaced on seabed", "High, in sea cages / tanks"], ["Breeding", "Wild spat settle on cleared seabed or hatchery", "Selected adults stripped of eggs and milt"], ["Disease / pest control", "Removal of predatory crabs", "Antibiotics, pesticides, wrasse, removal of diseased fish"], ["Yield per hectare", "Low", "Very high"]])],
      parts=[
          P("Use Table 1 to explain the relative merits of extensive and intensive aquaculture.", 4,
            ms=["Extensive: low inputs of energy, food and chemicals so low cost and low environmental impact; sustainable; but low yield per area and dependent on natural productivity",
                "Intensive: control of all limiting factors gives very high yield and profit per area; but high inputs (fishmeal from wild fish, energy), disease and lice at high density, pollution from wastes, antibiotic / pesticide use, escapes", "Judgement depends on species, market and site"]),
          P("Describe the stages in breeding and rearing salmon in an intensive farm.", 3,
            ms=["Adults with desirable characteristics (fast growth, shape, colour) stripped of eggs and milt which are mixed for fertilisation", "Eggs raised in aerated freshwater tanks, dead / diseased eggs removed daily; fry fed fishmeal pellets and moved through tanks as they grow",
                "After 12-18 months smolts transferred to seawater cages, fed pellets until harvest at 3-5 kg"]),
          P("Explain how shrimp farming has affected mangroves and how disease is controlled in shrimp lagoons.", 3,
            ms=["About 10% of the world's mangroves have been cleared for coastal shrimp lagoons (up to 100 ha), removing nurseries and coastal protection",
                "Lagoons need water exchange to remove wastes and aeration to prevent deoxygenation as wastes decompose", "Eyestalk ablation stimulates breeding; high densities increase disease so antibiotics / pesticides used"]),
      ]),

    Q("AQUA-03", "aquaculture", "3.5.2.3", "356-359",
      parts=[
          P("Explain how each of the following environmental impacts of salmon farming arises and how it can be reduced.", 8,
            labels=["Overfishing of wild fish for feed", "Sea lice and disease", "Escapes affecting wild gene pools", "Organic waste pollution"],
            ms=["Carnivores fed pellets of sandeels, herring, anchovy; overfishing sandeels reduces puffins and terns; reduced by more plant protein / vegetable oil in pellets or farming herbivores (tilapia)",
                "High density spreads lice (which spread to wild fish) and infections; pesticides (organophosphates, pyrethroids, hydrogen peroxide) kill wildlife; antibiotics breed resistant bacteria; reduced by lower densities, single-age tanks with flow from young to old, wrasse as biological control, warm-water washes, circulating flow",
                "Escaped farmed fish breed with wild fish introducing disadvantageous genes (bright colour), or non-indigenous escapees colonise as predators / competitors; reduced by better cage design, sterile triploid fish (pressure-treated eggs), species that cannot breed locally (Japanese oysters in UK)",
                "Faeces and uneaten food decompose causing deoxygenation under cages; reduced by monitored feeding, siting cages in strong currents, effluent treatment / reed beds for freshwater farms, IMTA with seaweed and shellfish absorbing wastes"]),
          P("Explain why culling seals and cormorants near fish farms is controversial and give an alternative.", 2,
            ms=["Predators are killed under licence to protect stock, reducing wild populations of protected / valued species", "Better cage designs, netting, fencing, bird scarers exclude predators without killing"]),
      ]),

    Q("AQUA-04", "aquaculture", "3.5.2.3", "357-358",
      parts=[
          P("Describe a polyculture system using several species of carp and explain how it increases total productivity.", 4,
            ms=["Silver carp eat phytoplankton, bighead carp zooplankton, grass carp and tilapia vegetation, common carp bottom-feed on molluscs / insects, catfish or perch eat small fish",
                "Species occupy different niches / trophic levels so they do not compete and all food sources are used", "Bottom feeders re-suspend nutrients boosting plankton / plant growth",
                "Predators control over-breeding species (tilapia) so remaining fish grow larger; total yield exceeds any single species"]),
          P("Explain how integrated multi-trophic aquaculture (IMTA) and aquaponics reduce pollution while increasing food production.", 4,
            ms=["IMTA: fed species (salmon, shrimp) alongside inorganic extractive species (seaweeds absorbing ammonia and phosphate) and organic extractive species (filter-feeding mussels eating waste particles / plankton)",
                "Wastes of one species become nutrients for another so less pollution and extra harvests", "Aquaponics: aquaculture water rich in nutrients / organic matter feeds hydroponic salad crops (lettuce, herbs, watercress)",
                "Plants remove the nutrients that would cause deoxygenation and cleaned water returns to the fish (tilapia, carp, catfish); rice-fish paddies similar"]),
          P("Explain why tuna aquaculture cannot yet replace tuna fishing.", 2,
            ms=["Bluefin tuna do not breed well in captivity so young fish are caught from the wild and fattened in sea cages", "Production still depends on (and removes juveniles from) the wild population; carnivores need large fish inputs"]),
      ]),

    Q("AQUA-05", "aquaculture", "3.5.2", "338-359",
      parts=[
          P("Evaluate the extent to which aquaculture can replace fishing as a source of aquatic food.", 9, level=True,
            ms=["Context: wild catches have not increased since about 1990 as stocks are fully or over-exploited; aquaculture output growing rapidly and approaching the wild catch; fish are the last large-scale hunted food",
                "Advantages of aquaculture: control of limiting factors, selective breeding, gender control, high yields per area; fish have low FCRs (no thermoregulation / support) compared with livestock; herbivores (tilapia, carp) and molluscs very efficient; polyculture, IMTA, aquaponics, rice-fish",
                "Limits: carnivorous species (salmon, shrimp) need fishmeal from wild fish so still depend on fishing and deplete forage fish (sandeels - puffins); some species (bluefin tuna) will not breed in captivity; consumer preference for carnivores",
                "Environmental impacts: habitat loss (mangroves), organic pollution, pesticides, antibiotics and resistance, lice, escapes and gene pool contamination, predator control; and how they can be reduced",
                "Fishing can be sustainable with quotas, gear design, NTZs, size limits, effort limits; MSY management needs good data",
                "Judgement: aquaculture can supply much of the growth in demand, especially herbivores and shellfish, but cannot fully replace fishing; both need sustainable management"]),
          P("State what is meant by a <b>fed</b> aquaculture species.", 1, ms=["A species that is given artificial food (pellets) rather than relying on natural food in the water, eg salmon, shrimp"]),
      ]),
]

ESSAYS = [
    Essay("ESS-P2-FISH", 2,
          "Fishing is the last large-scale human hunting activity. Discuss the environmental impacts of fishing and evaluate the methods used to make the exploitation of fish populations sustainable.",
          "3.5.2", "338-351",
          ["Marine productivity: light, nutrients, upwelling; where fisheries occur",
           "Methods: demersal / pelagic trawling, purse seining, drift nets, long lines, shellfish traps - effectiveness, selectivity, energy, impacts",
           "Impacts: overfishing (r vs k selection, catchable vs breeding size), changed age structure, by-catch (albatross, porpoise, turtles, shrimp), ghost fishing, seabed / reef / seagrass damage, dynamite, food web effects (sandeels, tritons)",
           "Population dynamics and MSY: Russell formula, difficulties of data, indicators from catches (CPUE, mean size, age), research on eggs and larvae",
           "Management: quotas, mesh design, escape panels, TEDs, pingers, hook design, effort limits, method bans, NTZs, closed seasons, size limits, protected individuals, population seeding, biodegradable gear; EU CFP, IWC, CCAMLR",
           "Evaluation with examples (cod, orange roughy, herring recovery, NTZ spillover); role of aquaculture; judgement"]),
]
