"""Living environment: setting conservation priorities, legislation and protocols (3.1.2.3.1-3.1.2.3.2);
captive breeding and release, habitat creation and management, plagioclimax and population control (3.1.2.3.3-3.1.2.3.4, 3.1.3.3-3.1.3.4).
Genn pp. 26-49."""
from gen.model import Q, P, Table, Chart, Essay

QUESTIONS = [
    # ---------------- conservation-priorities ----------------
    Q("PRI-01", "conservation-priorities", "3.1.2.3.1", "26-27",
      intro="Table 1 shows some of the IUCN criteria used to place species in Red List categories.",
      figures=[Table(["Category", "Population decline over 10 years or 3 generations", "Area of habitat", "Number of mature adults", "Probability of extinction in the wild"],
                     [["Vulnerable", "over 40%", "under 2000 km^2", "under 10 000", "over 10% in 100 years"], ["Endangered", "over 60%", "under 500 km^2", "under 2500", "over 20% in 20 years or 5 generations"], ["Critically endangered", "over 80%", "under 10 km^2", "under 250", "over 50% in 10 years or 3 generations"]])],
      parts=[
          P("State <b>three</b> roles of the IUCN.", 3, items=3,
            ms=["Coordinating global data on biodiversity conservation (Red List)", "Increasing understanding of the importance of biodiversity", "Deploying nature-based solutions to global challenges in climate, food and sustainable development"]),
          P("A species of lemur has declined from 12 000 to 2 100 mature adults in three generations and occupies 400 km<sup>2</sup> of forest. Use Table 1 to determine its Red List category. Explain your answer.", 3,
            ms=["Decline = (12 000 - 2100) / 12 000 x 100 = 82.5%", "Decline over 80% meets the Critically Endangered criterion even though habitat area (400 km^2) and adults (2100) only meet Endangered",
                "A species is placed in the highest category for which it meets any one criterion, so Critically Endangered"]),
          P("Explain why only a small proportion of species have been assessed for the Red List, and give <b>two</b> criteria used to decide which species to assess.", 3,
            ms=["Categorising a species requires a great deal of research (population, range, trends) and resources; about 85 000 of millions of species assessed",
                "Key species in habitats under particular threat (eg lemurs indicating the state of Madagascar's forests)", "Evolutionarily unique species / EDGE species; endemic species; keystone species; flagship species; species with fragmented populations"]),
          P("Give <b>one</b> example of a species whose Red List category improved because of conservation and state the actions responsible.", 1,
            ms=["Iberian lynx: Critically Endangered to Endangered after captive breeding and protection of two habitat areas (population trebled in 15 years); Fregate Island beetle after rat eradication"]),
      ]),

    Q("PRI-02", "conservation-priorities", "3.1.2.3.1", "28-29",
      parts=[
          P("Explain the meaning of each of the following terms and explain why such species are given conservation priority.", 8,
            labels=["EDGE species", "Endemic species", "Keystone species", "Flagship species"],
            ms=["EDGE: Evolutionarily Distinct and Globally Endangered - few close relatives, often the last species of their genus / family (Bactrian camel, pygmy hippo, northern bald ibis); loss would remove a unique branch of evolution / genes",
                "Endemic: found in only one area (often islands - Galapagos, Madagascar, Seychelles: Aldabra giant tortoise, red ruffed lemur); if lost locally there is no population elsewhere to recolonise",
                "Keystone: disproportionately important for the structure of the community relative to its abundance - predation of dominant species, seed dispersal, habitat creation (jaguar, forest elephants keeping paths and water holes open, wolves, beavers); losing them causes loss of many other species",
                "Flagship: high public profile (tiger, panda, elephant, orang-utan) raising funds and support that also protects the whole habitat and less charismatic species (fungi, bats, moths)"]),
          P("Explain why the degree of population dispersal is considered when setting priorities.", 2,
            ms=["A fragmented population may consist of isolated groups each too small to be viable (resources, inbreeding) even if total numbers are large",
                "A species confined to a single area (eg bonobos in one country) is vulnerable to any local change / conflict, unlike chimpanzees spread across many countries"]),
      ]),

    Q("PRI-03", "conservation-priorities", "3.1.2.3.2", "30-31",
      parts=[
          P("Describe <b>four</b> ways in which the Wildlife and Countryside Act (1981) protects wildlife in the UK.", 4, items=4,
            ms=["Designation of protected areas (SSSIs, MCZs)", "Protection of wild birds and their nests (except some pests / game birds)", "Protection of named mammals such as otters, dormice, red squirrels, badgers and their setts",
                "Uprooting wild plants generally illegal", "Bats must not be disturbed; roof timber treatments must be non-toxic to bats"]),
          P("Explain the difference between CITES Appendix I and Appendix II, giving an example species for each.", 4,
            ms=["Appendix I: species threatened with extinction - all international (commercial) trade banned, except movement for conservation breeding", "Examples: great apes, big cats, rhinos, blue whale",
                "Appendix II: species that may become threatened if trade is not closely controlled - trade permitted under licence from countries where the species is well protected", "Examples: Honduras mahogany, hippopotamus, green iguana, great white / basking shark, Venus fly trap"]),
          P("Explain why controlling international trade can be more effective than trying to stop collection of a species in its own country.", 2,
            ms=["Collection may be hard to police in remote areas / poor countries, but if the animals or products cannot be exported / imported there is no market", "Removing the profit removes the incentive to collect"]),
      ]),

    Q("PRI-04", "conservation-priorities", "3.1.2.3.2", "30, 38-39",
      intro="Table 1 shows some designated protected areas in the UK.",
      parts=[
          P("Complete Table 1 to show the legislation under which each area is designated and its key feature.", 4,
            table=Table(["Designation", "Designated under", "Key feature"], [["Site of Special Scientific Interest (SSSI)", "", ""], ["Special Protection Area (SPA)", "", ""], ["Ramsar site", "", ""], ["Marine Conservation Zone (MCZ)", "", ""]], blank=True, col_widths=[4.5, 4, 6.5]),
            ms=["SSSI: UK legislation (Wildlife and Countryside Act); best examples of UK flora, fauna, geological features; management plan agreed with owner who must notify Operations Likely to Damage (ploughing, drainage, pesticides, tree planting / removal)",
                "SPA: EU Birds Directive; places of international importance for birds (with SACs under the Habitats Directive form the Natura 2000 network; may restrict activities in surrounding areas)",
                "Ramsar: Ramsar Convention (intergovernmental agreement); internationally important wetlands, originally for waterfowl, now wetland conservation and wise use generally",
                "MCZ: UK marine legislation (Marine and Coastal Access Act) under the W&CA framework; protects marine habitats / species by restricting activities such as fishing and dredging; NNR: best SSSIs with complete communities"]),
          P("Explain how designating a protected area protects habitats and species.", 3,
            ms=["Legal status: restrictions on damaging activities within the area (and sometimes in surrounding areas, eg drainage)", "Management agreements between owners and statutory bodies to maintain suitable conditions",
                "But it does not protect against external influences such as air pollution or climate change; very few sites are state-owned so protection depends on owner cooperation"]),
          P("Explain why voluntary agri-environmental schemes are needed in addition to legislation.", 3,
            ms=["Much of the UK's wildlife lives in habitats created by farming (hay meadows, hedgerows) which only survive if the farming continues", "Managing land for wildlife costs money / reduces income so farmers need payments (points for beetle banks, hedgerows, buffer strips, wild bird seed, low-input grassland)",
                "Benefits everyone so society pays through central funding; legislation cannot compel positive management"]),
      ]),

    Q("PRI-05", "conservation-priorities", "3.1.2.3.2", "31-32",
      intro="Table 1 shows the estimated population of blue whales and the number killed by whaling in selected years.",
      figures=[Table(["Year", "1900", "1930", "1960", "1986", "2020"], [["Estimated population", "240 000", "100 000", "5 000", "2 000", "15 000"], ["Whales killed that year", "200", "30 000", "1 200", "0", "0"]])],
      parts=[
          P("Calculate the percentage decline in the blue whale population between 1900 and 1986.", 1, calc=True, unit="%", ms=["(240 000 - 2 000) / 240 000 x 100 = 99.2%"]),
          P("Explain why whale populations were so easily over-exploited.", 3,
            ms=["Whales are k-selected: slow growing, late maturing, one calf every few years, so populations recover very slowly", "Technology (harpoon cannons, steam / factory ships) allowed catches far above the sustainable yield within decades",
                "No regulation / open access to the ocean; whales were valuable (oil, spermaceti) and easily found"]),
          P("Describe how the International Whaling Commission regulates whaling.", 4,
            ms=["Moratorium on commercial whaling since 1986 until populations recover", "Total protection for certain species; whale sanctuaries", "Limits on numbers and sizes taken; protection of suckling mothers and calves",
                "Research into whale biology and threats (ship strikes, net entanglement); exceptions: aboriginal subsistence quotas (eg Inuit bowheads), 'scientific' permits (Japan - ruled not research in 2014), Norway / Iceland set their own quotas"]),
          P("Explain why the ITTO has been less successful than the IWC in achieving sustainable exploitation.", 2,
            ms=["ITTO's 1990 target of trade only from sustainably managed forests by 2000 was not met and little progress since", "Timber comes from many countries / private land with weak enforcement, high demand and alternative land uses; whaling involves few nations and a single treaty body"]),
      ]),

    # ---------------- cbr-habitat ----------------
    Q("CBR-01", "cbr-habitat", "3.1.2.3.3", "32-34",
      parts=[
          P("Explain the difference between in-situ and ex-situ conservation and state when ex-situ conservation is needed.", 2,
            ms=["In-situ: conserving species in their natural habitat with the whole community; ex-situ: away from the natural habitat, eg zoos, botanic gardens, seed banks, captive breeding",
                "Needed when conservation in the wild is impossible or insufficient to prevent extinction (habitat gone, population too small, poaching)"]),
          P("Give <b>four</b> criteria used to select species for captive breeding and release programmes.", 4, items=4,
            ms=["Is the wild population threatened?", "Is there a genetically diverse captive population?", "Is in-situ conservation failing?", "Is keeping a captive population realistic (habitat size, food, relationships, cost)?", "Is release likely to be successful now or in future (suitable habitat, threats removed)?"]),
          P("Explain why each of the following species would be difficult to keep or breed in captivity.", 4, labels=["Blue whale", "Large blue butterfly"],
            ms=["Blue whale: habitat size far too large to provide; food (huge quantities of krill / plankton) cannot be supplied; cost",
                "Large blue butterfly: complex inter-species relationship - larvae are taken into ant nests where they overwinter feeding on ant grubs; requires specific ant species and thyme food plant"]),
      ]),

    Q("CBR-02", "cbr-habitat", "3.1.2.3.3", "33-35",
      intro="The Hawaiian goose (nene) was reduced by hunting, habitat loss and introduced predators to about 30 birds. A captive breeding programme started with just seven individuals and has increased the wild population to over 2000.",
      parts=[
          P("Explain why starting the programme with seven individuals caused problems, and describe how these problems are managed.", 4,
            ms=["Very small gene pool so individuals are closely related and inbreeding is likely", "Harmful recessive genes are expressed when both parents carry them: some goslings had thin hair-like feathers with poor insulation so survival in cold weather was low",
                "A stud book records family trees so breeding is arranged between the least related individuals (often coordinated by a specialist zoo)", "Exchange of individuals / semen between zoos; avoid hybridisation with related species / subspecies"]),
          P("Explain <b>three</b> reasons, other than gene pool size, why species kept in captivity may fail to breed.", 3,
            ms=["Breeding is triggered by stimuli (day length, light, temperature, food, body fat) which may be unknown / not provided", "Population interactions: mixing breeding and non-breeding individuals causes conflict; some need a choice of partners, others pair for life",
                "Breeding habitat needed: courtship display sites, nest sites, social groups (flamingos only breed in large groups - mirrors used)", "Stress / disturbance"]),
          P("Describe how artificial insemination and embryo transfer increase breeding success in captive mammals.", 3,
            ms=["AI: semen collected (and can be stored / cryopreserved for years) and inserted into the female, so animals need not be transported or meet; avoids dangerous mating (elephants, rhinos) and partner rejection",
                "Embryo transfer: a female of the endangered species (eg bongo) is treated with hormones to release many eggs, which are fertilised and implanted into surrogate females of a common related species (eland)",
                "So many offspring are produced per cycle instead of one calf per year, overcoming the shortage of breeding females"]),
      ]),

    Q("CBR-03", "cbr-habitat", "3.1.2.3.3", "36-37",
      parts=[
          P("Explain the difference between hard and soft release and state the types of species for which each is suitable.", 3,
            ms=["Hard release: individuals released with no post-release support - suitable for species whose behaviour is instinctive and need no learned skills (insects, fish, amphibians, reptiles)",
                "Soft release: gradual release into larger areas with food provided while they learn to find food, avoid predators - needed for mammals and birds",
                "Problems faced: finding / recognising food and poisonous foods, hunting skills (captive-born predators never learned), avoiding predators, acceptance into wild social groups"]),
          P("Describe <b>five</b> features of a suitable release site.", 5, items=5,
            ms=["Large enough suitable habitat for a viable population", "Reliable food supply", "Low predation risk / original threat removed", "Suitable breeding sites", "Water",
                "Support of the local human population", "Official / legal protection of habitat and species"]),
          P("Explain the importance of post-release monitoring.", 2,
            ms=["Tracking (radio / GPS tags, rings) shows survival, dispersal and breeding of released animals so the success of the project can be assessed", "Identifies causes of failure so future releases can be improved / extra support given"]),
      ]),

    Q("CBR-04", "cbr-habitat", "3.1.2.3.3", "35-37",
      parts=[
          P("Describe how cloning could be used to conserve the northern white rhinoceros, and explain why success has been limited.", 3,
            ms=["The nucleus of a stem cell from the endangered species is transferred into an empty egg of a closely related species (southern white rhino)", "The embryo is implanted into a surrogate female of the related species which gives birth to a northern white rhino",
                "Very low success rates with wildlife so far; deep-frozen cells could allow clones even after the last individuals die"]),
          P("Explain how micro-propagation and cloning are used to conserve rare plants such as the Atlantic black poplar.", 3,
            ms=["Micro-propagation: tissue culture producing many cell clusters from one plant, each grown into a genetically identical plant", "Black poplar: cuttings / pollarded stems of pure native trees are rooted to produce many identical trees",
                "Needed because the flowers are pollinated by introduced subspecies producing hybrids, so cloning maintains the pure gene pool (but no genetic diversity)"]),
          P("Describe the purpose and methods of the Millennium Seed Bank.", 4,
            ms=["Stores seeds of wild plants (especially threatened species and crop wild relatives) so species are not lost if extinct in the wild", "Seeds collected worldwide; target of 10 000 seeds per species to maintain a diverse gene pool",
                "Stored dry and refrigerated / frozen in an underground reinforced vault to reduce risk of accident", "Seeds germinated periodically to check viability and replenish stocks; can be used for reintroduction / breeding"]),
      ]),

    Q("CBR-05", "cbr-habitat", "3.1.2.3.4", "40-42",
      intro="A conservation organisation is converting 700 ha of arable farmland on the coast into a wetland reserve for breeding and wintering birds (as at Wallasea Island).",
      parts=[
          P("Explain why habitat area and shape are important in the design of the reserve.", 4,
            ms=["Area must be large enough to support viable populations (breeding numbers high enough, gene pool large enough to avoid inbreeding); species higher up food chains need larger areas (lower density)",
                "Large areas contain a full range of resources (eg different fruiting trees / feeding areas through the year)", "Shape: the perimeter has edge conditions (a mix of neighbouring habitats); a compact shape maximises core habitat for species needing core conditions",
                "Some species benefit from edges (higher light) or small isolated habitats (ponds too small for predatory fish suit amphibians)"]),
          P("Explain how the reserve could be designed to provide a range of niches.", 3,
            ms=["Varied topography: banks, lagoons, islands, ditches created with machinery give a range of water depths (emergent, floating-leaved, submerged plant zones)", "Islands provide roosting / nesting sites safe from terrestrial predators (foxes)",
                "Control of salinity (eg intertidal conditions for opossum shrimps feeding dunlin and avocet); scrapes for skylarks; different water depths for waders and ducks"]),
          P("Explain why some species may need to be deliberately introduced while others colonise naturally.", 2,
            ms=["Mobile species (birds, flying insects) colonise easily", "Less mobile species (many plants, amphibians, invertebrates) may not reach an isolated site so must be introduced; keystone species especially"]),
          P("Explain the value of a biological corridor linking the reserve to other wetlands.", 1,
            ms=["Allows dispersal of surplus young, mixing of gene pools (less inbreeding) and recolonisation if a population dies out; avoids hazards (eg rope bridges for howler monkeys over roads)"]),
      ]),

    Q("CBR-06", "cbr-habitat", "3.1.2.3.4, 3.1.3.1", "43-46",
      parts=[
          P("Describe how each of the following abiotic factors can be managed to increase biodiversity in a nature reserve.", 6,
            labels=["Light", "Dissolved oxygen", "Nutrients"],
            ms=["Light: selective felling to create clearings for plants needing high light while retaining dense canopy for shade species; clearings also give warm sand / soil for lizard eggs; leave dead wood; woodland floor plants (bluebells) grow before the canopy leafs",
                "Dissolved oxygen: narrowing a slow river increases flow and turbulence so more oxygen dissolves, suiting trout and mayfly larvae; shallow water warms quickly for egg development",
                "Nutrients: removing fertile topsoil / not fertilising allows plants of nutrient-poor soils (eg sundew on acidic nitrate-deficient soils) that cannot compete on fertile ground; dung patches add local nutrients"]),
          P("Explain how biotic factors can be managed to increase the survival of a species. Give <b>four</b> examples.", 4,
            ms=["Food: wildflower grasslands for seed-eating birds; providing food species", "Control of predation: island nest sites unreachable by foxes; trapping / culling / eradicating introduced rats (Scilly Isles - Manx shearwater and storm petrel breeding success increased)",
                "Control of competitors: removing rhododendron so wildflowers get light", "Pollination: a range of flowering plants with different flowering times so pollinators have food all season", "Seed dispersal species (hippos, elephants, monkeys) conserved; control of introduced pathogens"]),
      ]),

    Q("CBR-07", "cbr-habitat", "3.1.3.3", "47-49",
      intro="Table 1 shows the number of plant species per m<sup>2</sup> in a chalk grassland reserve under different management, ten years after management began.",
      figures=[Table(["Management", "Mean plant species per m^2", "Percentage of area covered by scrub / bushes"], [["No management (abandoned)", "8", "55"], ["Sheep grazing", "24", "5"], ["Annual mowing (August)", "19", "0"], ["Winter burning", "14", "10"]])],
      parts=[
          P("Explain what is meant by a <b>plagioclimax</b> community and why chalk grassland is an example.", 2,
            ms=["A community maintained at a stage before the climax by regular human activity (grazing, mowing, burning, coppicing) that deflects succession", "Chalk grassland was produced by centuries of sheep grazing; without it succession to scrub and woodland resumes"]),
          P("Use Table 1 to explain why grazing produced the highest plant diversity.", 4,
            ms=["Grazing removes taller / dominant grasses and prevents scrub establishing (5% cover) so small plants are not shaded out", "Trampling creates bare ground for wildflower seed germination and warm patches for invertebrates / reptiles",
                "Dung creates small nutrient-rich patches supporting different plants and invertebrates; sheep eat short grasses and some bushes", "Mowing removes everything at once including plants grazers avoid, and removes flowers / seeds before setting; burning removes vegetation but also kills invertebrates and allows scrub regrowth; abandoned plot dominated by scrub (55%) so few species"]),
          P("Explain why different grazing animals are chosen for different plagioclimax habitats.", 2,
            ms=["Sheep eat short grass (some breeds eat scrub); ponies avoid flowers but eat bracken; cattle remove long rough grass", "Choice depends on the vegetation to be controlled and the plants to be protected"]),
          P("Explain how burning maintains heathland.", 2,
            ms=["Removes mature heather bushes and young trees that grazers will not eat, creating open unshaded ground", "Heat stimulates dormant heather seeds to germinate so young heather re-establishes"]),
      ]),

    Q("CBR-08", "cbr-habitat", "3.1.3.3-3.1.3.4", "47-49",
      parts=[
          P("Describe coppicing and explain how it increases the biodiversity of a woodland.", 4,
            ms=["Trees (hazel, oak) are cut to ground level every 3-30 years and allowed to regrow from the stump", "About 0.5 ha cut each year on a rotation (eg 8 years) so the wood is a patchwork of areas of different ages",
                "Each age has its own community: newly cut areas get high light for wildflowers and butterflies; older areas give dense cover for nesting birds / dormice", "Pollarding cuts above browsing height so deer / livestock cannot eat the regrowth"]),
          P("Explain how the reintroduction of grey wolves to Yellowstone National Park increased biodiversity.", 4,
            ms=["Wolves (top predator, exterminated by 1926) reduced deer populations and changed their behaviour", "Fewer young trees eaten so trees and riverside vegetation recovered",
                "More trees allowed beaver populations to increase; beaver dams increased wetland area", "Wetland species (birds, fish, invertebrates) became more common; overall biodiversity rose, though wolves cause problems for livestock farmers"]),
          P("Explain why culling or removing species may be necessary in habitat management.", 2,
            ms=["Undesirable species (introduced predators / competitors, or natural succession species such as scrub, conifers in the New Forest heathland) reduce survival of the target species", "Removal restores suitable conditions (eg heathland for sand lizards and smooth snakes) or reduces predation / competition"]),
      ]),

    Q("CBR-09", "cbr-habitat", "3.1.2.3.3-3.1.2.3.4", "32-49",
      parts=[
          P("Evaluate the relative importance of ex-situ and in-situ methods in the conservation of endangered species.", 9, level=True,
            ms=["In-situ: species remain in natural conditions with the whole community and inter-species relationships; protected areas (SSSI, NNR, SAC, SPA, Ramsar, MCZ), land ownership, agri-environment schemes, habitat creation and design (area, shape, corridors, diversity), management of abiotic and biotic factors, plagioclimax maintenance, population control, reintroductions and rewilding (Yellowstone wolves, Scottish beavers)",
                "Limits of in-situ: external threats (pollution, climate change), enforcement, cost, conflicts with land use, small fragmented populations",
                "Ex-situ: captive breeding when in-situ is impossible or insufficient; selection criteria; difficulties keeping and breeding (habitat size, food, relationships, breeding triggers, group dynamics, gene pool / inbreeding, hybridisation); techniques (stud books, cryopreservation, AI, embryo transfer, micropropagation, cloning); seed banks; successes (Hawaiian goose, Iberian lynx, red kite, large blue)",
                "Limits of ex-situ: expensive, few species, loss of wild behaviour, small gene pools, release requires suitable habitat and post-release support (hard vs soft release, monitoring)",
                "Judgement: ex-situ is a temporary safeguard / support that only succeeds if in-situ habitat exists to return to; both needed, in-situ fundamental"]),
          P("State what is meant by <b>rewilding</b>.", 1, ms=["Restoring natural processes / communities to a habitat changed by humans, often by reintroducing missing (keystone) species and removing human management such as grazing"]),
      ]),
]

ESSAYS = [
    Essay("ESS-P2-CONSERVE", 2,
          "Discuss the methods that can be used to conserve biodiversity and evaluate their effectiveness.",
          "3.1.2.3", "26-71",
          ["Setting priorities: IUCN Red List criteria, EDGE, endemic, keystone, flagship species, population dispersal",
           "Legislation and protocols: Wildlife and Countryside Act, designated areas (SSSI to MCZ), CITES Appendices, IWC, EU CFP, ITTO - successes and limits of enforcement",
           "Captive breeding and release: selection, difficulties, techniques, release site criteria, hard / soft release, monitoring; seed banks",
           "Habitat conservation: creation, design (area, shape, corridors, age structure, colonisation), abiotic and biotic management, plagioclimax maintenance, population control, reintroductions",
           "Habitat case studies (woodland, rainforest, coral reefs, islands, mangroves, Antarctica) illustrating threats and conservation efforts",
           "Monitoring and new technologies informing decisions",
           "Evaluation: examples of success (Iberian lynx, Hawaiian goose, Scilly rats, Yellowstone) and failure (ITTO, tigers); cost, politics, climate change; judgement on the most effective combination"]),
]
