"""Paper 2 additions (second batch): conditions for life, value of biodiversity, ecological
monitoring, sustainability principles, food species / energetics, agricultural impacts, fishing
and coral reefs.  Mostly 5- and 15-mark questions so mock papers can use the real AQA
(2 x 15, 5 x 10, 3 x 5) pattern.  Genn pp. 5-19, 57-62, 321-345, 370-374, 402-407."""
from gen.model import Q, P, Table, Chart, Essay

QUESTIONS = [
    # ---------------- 3.1.1 conditions for life ----------------
    Q("LIFE-04", "life-conditions", "3.1.1.1", "5-7",
      parts=[
          P("Which feature of the Earth prevents most atmospheric gases from escaping into space? Tick <b>one</b> box.", 1,
            mcq=["Its mass", "Its magnetic field", "Its distance from the Sun", "Its speed of rotation"], ms=["Its mass"]),
          P("Explain how the speed of rotation of the Earth and the tilt of its axis affect the conditions for life.", 2,
            ms=["The 24-hour rotation period means the surface is not exposed to sunlight for long, so temperature extremes / excessive heating and cooling are reduced",
                "The axis is tilted relative to the orbit so the amount of insolation at each latitude changes through the year, producing seasonal variations in conditions"]),
          P("Explain why the presence of liquid water on Earth depends on <b>both</b> the distance from the Sun <b>and</b> atmospheric pressure.", 2,
            ms=["The distance from the Sun gives surface temperatures between 0 and 35 &deg;C in most areas: too close and water would boil / evaporate, too far and it would freeze",
                "Atmospheric pressure (produced by the mass of gases held by gravity) is high enough to stop the water boiling / evaporating away; at much lower pressure there would be no liquid water"]),
      ]),

    Q("LIFE-05", "life-conditions", "3.1.1.2", "6-8",
      intro="Table 1 shows some events in the history of life on Earth.",
      figures=[Table(["Event", "Time before present / billion years"],
                     [["Formation of the Earth", "4.6"], ["First life (Archaea) on Earth", "3.5"], ["First photosynthetic organisms", "2.7"],
                      ["Oxygen concentration in the atmosphere starts to rise", "2.45"], ["End of the period of oxygen build-up (Proterozoic)", "0.54"]])],
      parts=[
          P("Use Table 1 to calculate how many <b>million</b> years passed between the appearance of photosynthetic organisms and the start of the rise in atmospheric oxygen.", 1,
            calc=True, unit="million years", ms=["2.7 - 2.45 = 0.25 billion = 250 million years"]),
          P("Explain why atmospheric oxygen did not start to rise as soon as photosynthesis began.", 2,
            ms=["For millions of years all the oxygen produced reacted with (dissolved) iron in the oceans",
                "Only when all the iron had reacted did surplus dissolved oxygen build up in the oceans and then escape into the atmosphere"]),
          P("Explain how the rise in atmospheric oxygen made life on the land surface possible.", 3,
            ms=["Oxygen in the atmosphere absorbed ultraviolet light", "A dynamic equilibrium of reactions between O, O<sub>2</sub> and O<sub>3</sub> (the ozone layer) developed",
                "Less UV reached the surface so organisms were no longer restricted to water (which had absorbed the UV)",
                "Aerobic respiration became possible so more complex / larger organisms (plants and animals) evolved; many anaerobic Archaea and bacteria died out"]),
          P("Explain how early photosynthetic organisms helped to prevent a long-term rise in the Earth's temperature.", 2,
            ms=["Photoautotrophs absorbed carbon dioxide, a greenhouse gas, and some of the carbon was stored in geological sediments such as carbonate rocks and fossil fuels (carbon sequestration)",
                "The lower CO<sub>2</sub> concentration reduced the retention of heat, offsetting the increase in the brightness of the Sun (about 10% per billion years)"]),
          P("Give <b>two</b> other ways in which living organisms changed the conditions on Earth.", 2, items=2,
            ms=["Biogeochemical cycles developed so small amounts of nutrient elements could support life for long periods without depletion",
                "Transpiration by land plants returned water vapour to the atmosphere and increased rainfall in other areas", "Regulation of atmospheric composition (eg oxygen / CO<sub>2</sub> by photosynthesis and respiration)"]),
      ]),

    Q("LIFE-06", "life-conditions", "3.1.1.1-3.1.1.3", "6-9",
      parts=[
          P("Explain why <b>proxy data</b> are needed to study the early conditions on Earth.", 1,
            ms=["Direct measurements of past conditions cannot be taken, so indirect evidence that is related to the condition must be used"]),
          P("Complete Table 1 to show what each analytical technique can be used to estimate.", 4,
            table=Table(["Technique", "What it estimates"],
                        [["Ratio of carbon-12 to carbon-14 in a sample", ""], ["Ratio of oxygen-18 to oxygen-16", ""], ["Analysis of air bubbles trapped in ice cores", ""], ["Ratio of magnesium to calcium in calcite deposits", ""]],
                        blank=True, col_widths=[7, 8]),
            ms=["Age / date of the sample (radioisotope dating)", "Past temperatures", "Composition of the past atmosphere (eg CO<sub>2</sub> / methane concentrations)",
                "Temperature: more magnesium is incorporated into calcite at higher temperatures"]),
          P("Explain why an understanding of continental drift and ocean currents has been important in explaining past changes in conditions.", 2,
            ms=["Movement of continents changed the position of land masses / latitude and therefore the climate and habitats present",
                "Ocean currents redistribute heat and nutrients; changes in currents (eg as continents moved) altered climates, so past conditions cannot be explained without knowing how the systems worked"]),
          P("Life probably first developed around volcanic vents on the seabed. Explain why the conditions in the oceans were more suitable than those on land 3.5 billion years ago.", 3,
            ms=["There was no oxygen / ozone layer so high levels of UV radiation reached the land surface; water absorbed the UV and protected organisms in the oceans",
                "Warm temperatures around the vents and a rich mix of chemicals / increasingly complex organic molecules in the sea made biological reactions more likely",
                "The atmosphere contained toxic gases such as ammonia; the early Archaea were anaerobic so did not need oxygen",
                "Water acted as the solvent for reactions / transport"]),
      ]),

    # ---------------- 3.1.2.1 value of biodiversity ----------------
    Q("BIOV-05", "biodiversity-value", "3.1.2.1.1", "11",
      parts=[
          P("Give <b>two</b> wild species with potential as new food species and, for each, one characteristic that makes it useful.", 2, items=2,
            ms=["Potato bean (N America): high protein content", "Morama bean (southern Africa): protein content similar to soya, drought resistant",
                "Yeheb tree (Somalia): edible nuts, drought resistant, grows on poor soils", "Perennial maize (Mexico) / Kernza: no need to buy seed each year, less ploughing so less soil erosion",
                "American bison: graze grassland too poor for cattle", "Common eland: browse and graze so can be kept with cattle without severe competition"]),
          P("Explain why indigenous species may be better for domestication than introduced livestock or crops.", 2,
            ms=["Indigenous species are better adapted to local conditions such as climate, pests / diseases and soil",
                "So they have higher survival rates / productivity is not reduced, as it is when introduced species are kept in areas to which they are not adapted"]),
          P("Explain how species of the spinach family could help to solve a problem caused by irrigation.", 1,
            ms=["They grow in soils with a high salt content, so their genes could be used in breeding programmes to increase the salt tolerance of crops grown on soils salinised by irrigation"]),
      ]),

    Q("BIOV-06", "biodiversity-value", "3.1.2.1.1", "11-14",
      intro="Biomimetics uses knowledge of the adaptations of other species to improve the design of manufactured items.",
      parts=[
          P("Complete Table 1 by adding the missing adaptation or application.", 4,
            table=Table(["Species and adaptation", "Design application"],
                        [["Tubercles (bumps) on the flippers of humpback whales", ""], ["", "Self-cleaning glass"], ["Shark skin scales that reduce friction", ""], ["", "Velcro"]],
                        blank=True, col_widths=[7.5, 7.5]),
            ms=["Ship rudders that turn in tighter circles / aerogenerator blades that start turning at lower wind speeds", "Water-repelling surface of lotus flowers",
                "Coatings for aircraft and ships that reduce fuel consumption / hospital coatings that bacteria cannot stick to", "Hooked burrs on seeds that stick to animal fur"]),
          P("Explain how the design of termite mounds has been copied to reduce the environmental impact of large buildings.", 3,
            ms=["The mound absorbs sunlight and warms; hot air inside rises, creating a convection current that draws stale air out of the lower parts (solar-driven ventilation)",
                "Air blowing over the mound has a lower pressure which also draws air out",
                "Copied in shopping complexes / office blocks to give natural ventilation and cooling without air conditioning, so less energy / electricity is used"]),
          P("Describe <b>two</b> ways in which studying the physiology of other species could help to solve human health problems.", 2, items=2,
            ms=["Marsupials: young develop in the pouch so are easier to study than a human foetus, helping understanding of developmental problems",
                "Hippopotamus skin secretes hipposudoric acid (natural sunscreen and antimicrobial) which may improve treatment of burns",
                "Marine sponges produce proteins that prevent rejection of grafts, being developed to prevent rejection of transplanted organs"]),
          P("Explain why bird wing bones are a useful model for engineers.", 1,
            ms=["They are light but strong: hollow with internal struts that prevent bending / breaking, copied in lightweight bridges and roofs"]),
      ]),

    Q("BIOV-07", "biodiversity-value", "3.1.2.1.3", "18-19",
      parts=[
          P("Explain why the ecosystem services provided by other species are often given a low conservation priority.", 2,
            ms=["The processes (eg regulation of atmospheric gases by photosynthesis and respiration) act in a dynamic equilibrium and cancel each other out",
                "Because there is no overall change their actions go unnoticed / their importance is not appreciated until they are lost"]),
          P("Explain how soil organisms provide services that humans depend on.", 3,
            ms=["Invertebrates, fungi and bacteria break down / decompose dead organic matter, releasing nutrients for plant growth",
                "The organic matter and humus produced hold the soil together (reducing erosion) and regulate the water cycle, giving more even river flow and less flooding",
                "Organic acids from decomposition aid the weathering of rock, producing more soil and releasing more nutrients",
                "Microbes carry out the processes of the carbon, nitrogen and phosphorus cycles so wastes do not build up and nutrients are not depleted"]),
          P("Explain why pollination by insects is more useful than wind pollination to plants growing in forests.", 2,
            ms=["Trees reduce wind velocity so wind pollination would be ineffective / unreliable over long distances",
                "Insects search over long distances for flowers so dispersed populations can be pollinated, and less pollen needs to be produced (energy saving); specialised flowers reduce pollen being wasted on other species"]),
          P("Explain how seed dispersal by animals increases the survival of a plant's offspring.", 3,
            ms=["Dispersal is not haphazard: animals live in the same habitat as the plant so are likely to carry seeds to locations where they can survive",
                "Seeds can be carried longer distances than by wind and can be larger, containing more nutrients for the seedling",
                "Seeds passing through the gut are deposited in faecal material which acts as a fertiliser, and passage through the intestine may stimulate germination"]),
      ]),

    # ---------------- 3.1.2.3.5-6 ecological monitoring & new technologies ----------------
    Q("MON-04", "eco-monitoring", "3.1.2.3.6", "404-405",
      parts=[
          P("Which technique would be most suitable for detecting whether great crested newts are present in a pond without catching them? Tick <b>one</b> box.", 1,
            mcq=["Environmental DNA (eDNA) analysis", "Radio tracking", "Lincoln index (mark-release-recapture)", "Leg rings"], ms=["Environmental DNA (eDNA) analysis"]),
          P("Explain why geolocator tags, rather than radio or GPS transmitters, are used to track the migrations of small birds.", 2,
            ms=["Transmitters are too heavy for small birds / their batteries would not last for a long-term study",
                "Geolocator tags are small and only record time and light levels; latitude and longitude for each day are worked out when the bird is recaptured and the data downloaded"]),
          P("Explain how DNA databases could help to control the illegal trade in elephant ivory.", 2,
            ms=["Each separate (regional) population has its own unique gene pool",
                "DNA from seized ivory can be compared with the database to identify where the elephant came from, so poaching hotspots / trade routes can be targeted"]),
      ]),

    Q("MON-05", "eco-monitoring", "3.1.2.3.6", "402-403, 406-407",
      parts=[
          P("Complete Table 1 to show the environmental information that can be collected by satellite sensors detecting each type of radiation.", 3,
            table=Table(["Radiation detected", "Environmental information collected"], [["Reflected visible light", ""], ["Infrared emitted by the Earth's surface", ""], ["Reflected radar microwaves emitted by the satellite", ""]], blank=True, col_widths=[6, 9]),
            ms=["Images / maps of large areas; land-use change, deforestation, flooding", "Vegetation density and surface temperature",
                "Wind velocity, sea-surface altitude, wave height, oil pollution"]),
          P("Explain why radar surveys are not interrupted by cloudy weather.", 1, ms=["Microwaves pass through clouds (unlike visible light)"]),
          P("Explain <b>two</b> advantages of satellite surveys over ground surveys for monitoring deforestation.", 2,
            ms=["Very large / remote areas can be surveyed quickly and repeatedly so changes over time are detected",
                "No need for researchers to visit inaccessible areas, reducing cost and disturbance; data are standardised across the whole area"]),
          P("Describe how motion-sensitive cameras and image databases could be used together to estimate the size of a tiger population.", 4,
            ms=["Motion-sensitive cameras placed along trails record animals passing, using visible light by day and infrared at night",
                "Each tiger has a unique pattern of facial / body stripes", "Images are compared with the database so individuals are recognised rather than counted twice",
                "The number of different individuals recorded gives a minimum population; repeated captures give territory size, movements, lifespans and social groupings",
                "Limitation: only works for species with unique visible features"]),
      ]),

    Q("MON-06", "eco-monitoring", "3.1.2.3.5-3.1.2.3.6", "402, 405, 407",
      parts=[
          P("Explain why an electronic meter used to measure dissolved oxygen must be calibrated, and what should be done if the reading cannot be adjusted.", 2,
            ms=["Its reading is adjusted to match a meter known to be accurate so that the results are accurate / comparable",
                "If it cannot be adjusted the percentage error should be recorded so the results can be corrected"]),
          P("Give <b>three</b> types of indirect evidence of the presence of an animal and the information each can provide.", 3, items=3,
            ms=["Droppings: diet, gender, territory size", "Owl pellets: diet", "Feeding marks (eg chewed hazel nuts): presence of species such as dormice",
                "Nests / burrows: presence and breeding", "Tracks / footprints: presence, movements", "Territorial marks (scratching posts): presence and territory"]),
          P("Explain how auditory monitoring can be used to study bats.", 2,
            ms=["Bat detectors / sonograms record the ultrasonic sounds bats produce, which differ between species",
                "The recordings provide evidence of presence, abundance and activity of species that cannot easily be seen"]),
          P("Explain <b>three</b> assumptions of the mark-release-recapture method that may not be met.", 3,
            ms=["Marked individuals mix freely with the rest of the population", "Marks do not fall off or wear away, and marking does not affect survival",
                "The population does not change during the study (no births, deaths or migration)", "All individuals have an equal chance of being caught / animals are mobile and can be caught"]),
      ]),

    # ---------------- 3.6.1 sustainability principles ----------------
    Q("SUS-10", "dynamic-equilibria", "3.6.1", "370",
      parts=[
          P("Explain the difference between approaches to sustainable lifestyles based on <b>moral belief</b> and on <b>enlightened self-interest</b>.", 2,
            ms=["Moral belief: protecting the environment is the 'right' thing to do regardless of benefit to people",
                "Enlightened self-interest: protecting the environment is done because it causes fewer difficulties (for people) than not doing so"]),
          P("Explain why the overall environmental impact of humans depends on two main factors.", 2,
            ms=["Total impact = population size x the individual (per capita) impact of each person",
                "Per capita impact rises with affluence / access to energy, so both a larger population and a more affluent population increase the total impact"]),
          P("Give <b>one</b> activity that is sustainable with a small population but unsustainable if the population is too large.", 1,
            ms=["Slash and burn agriculture", "Fishing", "Discharge of sewage / biodegradable pollutants"]),
      ]),

    Q("SUS-11", "dynamic-equilibria", "3.6.1", "371-372",
      intro="Table 1 lists some feedback mechanisms that affect the Earth's climate.",
      parts=[
          P("Complete Table 1 by stating whether each mechanism is an example of <b>negative</b> or <b>positive</b> feedback.", 4,
            table=Table(["Mechanism", "Type of feedback"],
                        [["Higher temperatures increase cloud cover, raising albedo", ""], ["Melting permafrost releases methane", ""],
                         ["Higher CO<sub>2</sub> levels increase photosynthesis and carbon sequestration", ""], ["Melting ice reduces albedo", ""]], blank=True, col_widths=[10, 5]),
            ms=["Negative", "Positive", "Negative", "Positive"]),
          P("Explain why natural systems regulated by negative feedback rarely reach tipping points.", 2,
            ms=["The response to a change acts to re-establish / return the system to the previous equilibrium",
                "So the change does not become self-sustaining unless a large unusual event overwhelms the negative feedback"]),
          P("Using an example, explain how a large unusual event can cause a tipping point.", 2,
            ms=["eg the possible release of methane hydrate at the end of the Permian era",
                "Overwhelmed the negative feedback mechanisms, causing climate change and a mass extinction / a new equilibrium"]),
          P("Explain how the human response to negative feedback in agriculture can make food production less sustainable.", 2,
            ms=["Soil degradation, reduced water availability and loss of natural pest predators would reduce yields (negative feedback curtailing the activity)",
                "Instead of reducing the activity, farmers use fertilisers, irrigation and pesticides, which further damage the natural systems that support food production"]),
      ]),

    Q("SUS-12", "dynamic-equilibria", "3.6.1", "370-371",
      parts=[
          P("Explain <b>three</b> reasons why the development of new human activities has rarely been restricted by their environmental impacts.", 3,
            ms=["The new opportunity is overwhelmingly attractive (economic benefit)", "Lack of knowledge / understanding of the impacts",
                "The impacts occur elsewhere or much later, so are not evident to those who benefit"]),
          P("Explain why sedentary rural communities often exploit resources sustainably.", 2,
            ms=["Cultural belief that resources should be exploited to satisfy needs only",
                "Problems of over-exploitation become obvious quickly as local supplies dwindle, so behaviour changes"]),
          P("Explain why urban populations are often unaware that the resources they use are being depleted.", 2,
            ms=["Resources are brought in from other areas", "If one area is depleted, exploitation moves to another area (eg timber, fish, metals, energy) without the consumers noticing"]),
          P("Explain why the growth of affluence has increased per capita environmental impacts.", 3,
            ms=["Easier access to energy has made many new activities possible", "The scale of activities has greatly increased",
                "Toxic wastes are produced that cannot be decontaminated by natural processes"]),
      ]),

    # ---------------- 3.6.2-3.6.3 natural systems ----------------
    Q("SUS-13", "natural-systems", "3.6.2", "373",
      parts=[
          P("Give <b>two</b> natural processes that are driven by solar energy.", 2, items=2,
            ms=["Hydrological cycle", "Carbon cycle", "Nitrogen cycle", "Atmospheric circulation", "Thermohaline circulation", "Photosynthesis"]),
          P("Explain why natural processes can take place at low temperatures.", 2,
            ms=["Enzymes reduce the activation energy of reactions", "So reactions such as photosynthesis, decomposition and nitrogen fixation do not need high temperatures"]),
          P("Give <b>one</b> human activity that uses high temperatures to achieve a result that natural systems achieve at low temperature.", 1,
            ms=["Haber process (nitrogen fixation)", "Incineration of wastes (decomposition)", "Many manufacturing processes"]),
      ]),

    Q("SUS-14", "natural-systems", "3.6.2-3.6.3", "373-374",
      parts=[
          P("Complete Table 1 to compare natural systems with typical linear human systems.", 4,
            table=Table(["Feature", "Natural systems", "Linear human systems"],
                        [["Energy source", "", ""], ["Use of materials", "", ""], ["Nature of wastes", "", ""], ["Temperature of processes", "", ""]], blank=True, col_widths=[4, 5.5, 5.5]),
            ms=["Energy: low energy-density renewable (solar) / non-renewable fossil fuels", "Materials: cyclic - wastes of one process are raw materials of the next / linear - used once then discarded, depletion",
                "Wastes: biodegradable, non-toxic or do not build up / toxic, persistent (eg PCBs, organochlorines, toxic metals) that bioaccumulate", "Temperature: low / high (Haber process, incineration)"]),
          P("Explain why natural systems can be sustained using a relatively small number of elements.", 2,
            ms=["Abundant simple raw materials build into monomers and then a wide range of polymers (carbohydrates, proteins)",
                "They are re-used in cycles so there is no depletion of raw materials or build-up of wastes"]),
          P("Explain why the human use of minerals makes them difficult to recover and re-use.", 2,
            ms=["Use often disperses the minerals (eg in products spread over the world / corrosion)", "Or produces mixtures of materials that are difficult to separate, so sustainable exploitation is reduced"]),
          P("Explain why toxic metals in electronic products cause problems that the wastes of natural systems do not.", 2,
            ms=["They cannot easily be removed from end-of-life appliances and are not biodegradable",
                "Natural wastes are non-toxic / broken down to raw materials for other processes, whereas persistent toxins may bioaccumulate and biomagnify"]),
      ]),

    Q("SUS-15", "natural-systems", "3.6.2-3.6.3", "373",
      parts=[
          P("Which of the following is a feature of natural systems? Tick <b>one</b> box.", 1,
            mcq=["Reactions that require high temperatures", "Reliance on non-renewable energy", "Waste products that are the raw materials for other processes", "Dispersal of elements so they cannot be re-used"],
            ms=["Waste products that are the raw materials for other processes"]),
          P("Explain why nitrogen fixation by bacteria is more sustainable than the Haber process.", 2,
            ms=["Bacteria fix nitrogen at low temperature using enzymes and energy ultimately from sunlight (renewable)",
                "The Haber process needs high temperature and pressure powered by non-renewable fossil fuels, releasing CO<sub>2</sub>"]),
          P("Explain why incineration of wastes is less sustainable than natural decomposition.", 2,
            ms=["Incineration uses high temperatures / fuel and releases pollutants; nutrients are not returned as usable raw materials",
                "Decomposition at low temperature recycles nutrients as the raw materials for other natural processes (material cycle)"]),
      ]),

    # ---------------- 3.5.1.2 manipulation of food species & energetics ----------------
    Q("FS-05", "food-species", "3.5.1.2", "321-322",
      parts=[
          P("State what is meant by <b>hybrid vigour</b>.", 1,
            ms=["Cross-bred offspring are healthier / more productive because the problems caused by homozygous recessive genes in inbred varieties are reduced (heterosis)"]),
          P("Explain how cross-breeding Zebu and Ayrshire cattle produced a breed suited to hot climates.", 2,
            ms=["Zebu tolerate heat but have a low milk yield; Ayrshire have a high milk yield but are not heat tolerant",
                "Cross-breeding combined the desirable characteristics: heat tolerance with a high milk yield"]),
          P("Give <b>two</b> potential applications of cloning to livestock farming.", 2, items=2,
            ms=["Replacement of valuable animals that die with genetically identical individuals", "Replacement of herds culled during a disease outbreak",
                "Production of large numbers of individuals with desirable characteristics"]),
      ]),

    Q("FS-06", "food-species", "3.5.1.2", "326-328",
      intro="Table 1 shows typical energy values for an agroecosystem. Values are units of energy remaining from 100 000 units of solar energy.",
      figures=[Table(["Stage", "Energy / arbitrary units"], [["Solar energy reaching the crop", "100 000"], ["Energy captured during photosynthesis", "4 000"], ["Energy stored in crop biomass", "1 000"]])],
      parts=[
          P("Calculate the percentage of the solar energy reaching the crop that is stored in crop biomass.", 1, calc=True, unit="%", ms=["1000 / 100 000 x 100 = 1%"]),
          P("Explain why so little of the solar energy is stored in the crop.", 3,
            ms=["Some light is reflected by the leaves", "Some light is transmitted (passes through the leaves without being absorbed) or is of wavelengths not absorbed",
                "Much of the energy captured is used in the plant's metabolic processes and released as low energy-density heat (respiration)"]),
          P("Explain why few food chains have more than four trophic levels.", 2,
            ms=["Less energy is passed to each trophic level than was received from the previous one (heat losses in respiration)",
                "After four levels too little energy remains to support a further population"]),
          P("Explain why rearing sheep or cattle is the best option for food production in upland and semi-arid areas.", 2,
            ms=["Permanent grassland is a more sustainable land use than arable crops in these areas (soil / rainfall unsuitable for crops)",
                "Grazing animals can digest grass cellulose using symbiotic bacteria in their stomachs, producing food that humans can eat"]),
          P("Explain how pigs can increase the efficiency of a food production system.", 2,
            ms=["Pigs are omnivores that can eat food wastes not wanted by people (eg cheese-making wastes, catering leftovers)",
                "So edible meat is produced from material that would otherwise be wasted, without using land / crops that could feed people"]),
      ]),

    Q("FS-07", "food-species", "3.5.1.2", "324-325",
      intro="Figure 1 shows the effect of increasing inputs (fertiliser, water and pesticides) on the yield of a crop.",
      figures=[Chart("line", "Inputs / arbitrary units", "Yield / arbitrary units", {"Yield": [(0, 20), (1, 50), (2, 70), (3, 82), (4, 90), (5, 94)]}, y_min=0, y_max=100)],
      parts=[
          P("Describe the relationship shown in Figure 1.", 2,
            ms=["Yield increases as inputs increase", "But each extra unit of input produces a smaller increase in yield than the previous one (the curve flattens / law of diminishing returns)"]),
          P("Calculate the extra yield produced by the second unit of input and by the fifth unit of input.", 2, calc=True, unit="units",
            ms=["Second unit: 70 - 50 = 20 units", "Fifth unit: 94 - 90 = 4 units"]),
          P("Explain why, if enough land is available, spreading inputs evenly over a large area gives a greater total yield than concentrating them on a small area.", 2,
            ms=["The first units of input on each area give the largest yield increases",
                "Concentrating inputs means later units add very little, whereas the same inputs spread thinly all work at the steep part of the curve"]),
          P("Suggest why inputs are nevertheless often used unevenly across the world.", 2,
            ms=["Some areas have much greater potential productivity so investment there is sensible",
                "Affluent societies can afford to buy more inputs while poorer communities that would benefit most cannot afford them (economic reasons)"]),
          P("Explain why intensive agriculture may be very productive but not very efficient.", 2,
            ms=["Yield per unit area is very high because of large inputs", "But the extra yield per unit of input is small, so efficiency (yield per unit input / energy ratio) is low"]),
      ]),

    # ---------------- 3.5.1.3-3.5.1.5 impacts of agriculture & sustainability ----------------
    Q("AGI-05", "agri-impacts", "3.5.1.3", "328-329",
      parts=[
          P("Give <b>two</b> habitats created by farming that support important wildlife communities.", 2, items=2,
            ms=["Hedgerows", "Hay meadows", "Grazed moorland / heathland", "Chalk grassland"]),
          P("Explain how drainage and nutrient enrichment of farmland reduce biodiversity.", 2,
            ms=["Drainage produces more aerobic soils so wetland plants and the animals they support cannot survive",
                "Fertilisers increase growth of tall species such as grasses which out-compete smaller plants such as wildflowers"]),
          P("Explain <b>one</b> problem that can be caused by introducing a biological control species.", 1,
            ms=["The introduced (non-indigenous) predator may eat other species as well as the pest"]),
      ]),

    Q("AGI-06", "agri-impacts", "3.5.1.3-3.5.1.4", "329-332",
      parts=[
          P("Explain how GPS mapping, drone surveys and computer-based yield monitoring can reduce the environmental impacts of agriculture.", 3,
            ms=["Surveys monitor photosynthesis rates, biomass, soil water content and the spread of pests / diseases so inputs are applied only where needed",
                "Yield mapping of different parts of a field controls fertiliser application in each area for future crops",
                "This maximises yield while avoiding wastage / reducing leaching and nutrient pollution"]),
          P("Explain why productive agricultural technologies are less available in LEDCs.", 2,
            ms=["Machinery, pesticides, fertilisers, improved breeds and infrastructure (transport, refrigeration) are expensive",
                "They are mainly available in affluent societies; poorer farmers cannot afford the inputs"]),
          P("Explain how buying fairtrade food affects producers.", 1,
            ms=["Provides an income that allows producers to afford basic rights such as water, education, health care and food"]),
          P("Explain how nitrate from farmland can threaten human health.", 2,
            ms=["Nitrates are leached into water bodies used as sources of potable water",
                "High nitrate levels cause blue baby syndrome (methaemoglobinaemia) and nitrates may be carcinogenic"]),
          P("Give <b>two</b> agricultural sources of methane.", 2, items=2,
            ms=["Anaerobic digestion by microbes in rice padi fields", "Livestock intestines (ruminant digestion)", "Anaerobic decay of manure / slurry"]),
      ]),

    Q("AGI-07", "agri-impacts", "3.5.1.5", "335-337",
      parts=[
          P("Explain why the potential to increase food supplies by cultivating new land is limited.", 2,
            ms=["About 10% of land is already cultivated and 25% grazed", "Most remaining land is too dry, wet, cold, hot or steep, is covered in ice, or has no soil"]),
          P("Explain why importing food may reduce the availability of food in the area where it is produced.", 2,
            ms=["Land becomes too expensive for local people to rent / is used to grow export crops for more affluent societies",
                "So people with less money lose access to the land and food they used to produce"]),
          P("Explain why organic agriculture is more than simply 'not using pesticides and artificial fertilisers'.", 2,
            ms=["It uses natural processes to supply nutrients (legumes, recycled organic matter, soil biota), control pests and provide ecological services",
                "So that pesticides and artificial fertilisers become unnecessary rather than just being banned"]),
          P("Evaluate the strategies that could be used to make agriculture more sustainable.", 9, level=True,
            ms=["Unsustainable features: reliance on chemical pesticides (resistance, non-target impacts, bans), non-renewable rock phosphate, fossil-fuel-intensive nitrate manufacture, over-exploitation of rivers / groundwater, salinisation, loss of soil organic matter, greenhouse gases from fuel, rice and livestock, loss of species providing ecosystem services",
                "Pest control: cultural methods (weeding, mulching, crop rotation, barrier crops, culling), biological control, predator habitats, polyculture / companion crops, integrated control, reduced antibiotic use",
                "Nutrients: recycling organic matter, crop rotation, cultivation of legumes, conservation of soil biota, reduced artificial fertiliser especially nitrate, low tillage",
                "Water: low water-use crops, reservoirs and aquifer recharge, drip irrigation rather than sprays",
                "Soil and carbon: low-tillage farming to maintain organic matter, reduced machinery, renewable energy, drought-tolerant rice varieties so fields are drained earlier, high-carbohydrate ground feed for cattle reduces methane",
                "Biodiversity: conserve habitats of crop wild relatives, seed banks, retain hedgerows, ditches, ponds, woodland; agri-environment schemes",
                "Evaluation: growing population (perhaps 12 billion) needs more food; lower trophic level diets; obstacles - cost, need for support, gaining acceptance of new techniques; learning from past land degradation (fertile crescent, US mid-west)",
                "Judgement: no single strategy sufficient; combination of ecological principles and new technology; justified conclusion"]),
      ]),

    # ---------------- 3.5.2.2 fishing ----------------
    Q("FISH-07", "fishing", "3.5.2.2", "341-345",
      intro="Table 1 shows the catch made by a shrimp trawler during one fishing trip.",
      figures=[Table(["Component of catch", "Mass / tonnes"], [["Shrimps (target species)", "0.6"], ["Crabs, sea urchins, molluscs and starfish", "5.9"], ["Immature fish of commercial species", "1.9"]])],
      parts=[
          P("Calculate the percentage of the total catch that was by-catch.", 2, calc=True, unit="%",
            ms=["By-catch = 5.9 + 1.9 = 7.8 t; total = 8.4 t", "7.8 / 8.4 x 100 = 92.9% (accept 93%)"]),
          P("Explain why shrimp trawling produces such a high proportion of by-catch.", 1,
            ms=["The nets have a very small mesh size so few non-target animals can escape"]),
          P("Explain why k-selected species such as the common skate and the Greenland shark are especially vulnerable to overfishing.", 3,
            ms=["They breed at an old age (skate about 11 years; Greenland shark 100-150 years) and produce few young",
                "They may reach a catchable size before they are sexually mature, so fishing can remove the whole breeding population before it has bred",
                "Populations recover slowly, unlike r-selected species (herring, mackerel) which breed young and produce many young; they are caught as by-catch in demersal trawls so fishing continues even though they have no commercial value"]),
          P("Evaluate the methods that can be used to reduce the environmental impacts of fishing.", 9, level=True,
            ms=["Impacts: population decline of k-selected species, by-catch (immature target fish, over-quota fish, non-commercial species; drift nets - whales, dolphins, turtles; longlines - albatrosses; pair trawls - porpoises), ghost fishing, seabed damage by demersal trawls, coral and seagrass damage, dynamite fishing, food-web effects",
                "Catch quotas: limit weight landed; work well for single-species pelagic shoals but in mixed fisheries over-quota fish are discarded dead so the quota fails to protect them",
                "Gear design: mesh size and square-mesh escape panels let small fish escape (diagonal mesh closes under drag); turtle exclusion devices; acoustic pingers for dolphins; curved hooks, decoys, sinkers and night setting to protect albatrosses; biodegradable / radio-tracked traps to reduce ghost fishing",
                "Restricted effort: limits on boat size, engine power and days at sea; decommissioning; restricted methods - drift-net bans, demersal trawling bans on sensitive seabeds (Rockall Bank, Hatton Bank)",
                "Evaluation: enforcement at sea is difficult; some methods reduce catch or raise costs; quotas need reliable stock data; effectiveness depends on species (single vs mixed shoals) and on international cooperation as fish migrate; as local stocks decline fishing moves to more distant waters",
                "Justified conclusion weighing effectiveness of different methods"]),
      ]),

    # ---------------- 3.1.2.3.4 coral reefs ----------------
    Q("HAB-14", "habitats", "3.1.2.3.4", "57-62",
      parts=[
          P("Explain how the relationship between coral polyps and zooxanthellae allows a high biomass of life in nutrient-poor tropical seas.", 4,
            ms=["Zooxanthellae are photosynthetic algae living inside the polyp cells", "The algae absorb CO<sub>2</sub> and excretory wastes from the polyp for photosynthesis and growth (efficient nutrient recycling)",
                "They supply the polyp with oxygen and glucose - over 95% of its food energy", "In return the algae gain a protected habitat and nutrients they could not absorb from the nutrient-deficient water",
                "Polyps also feed on plankton captured by cilia and nematocysts"]),
          P("Explain why growing coral reefs help to resist climate change.", 2,
            ms=["Corals deposit a skeleton of calcium carbonate (calcite)", "Each carbonate molecule requires the absorption of a molecule of carbon dioxide, so reefs are a carbon sink"]),
          P("Discuss the importance of tropical coral reefs and evaluate the methods used to conserve them.", 9, level=True,
            ms=["Importance: cover 1% of ocean area but support over a quarter of marine species; fisheries (fish, lobsters, conch); medicines (AZT, Ara-C, dolastatin, secosteroids, bryostatin, trabectedin, bone grafts); climate control as carbon sink; erosion protection of low-lying islands; tourism income",
                "Threats: physical damage (anchors, divers, litter, coral extraction), collection of ornaments (CITES Appendix II), sedimentation from rivers and coastal development, pollution (oil, nutrients causing algal shading, sewage, pesticides, sunscreen), ocean acidification, bleaching from warming, overfishing (giant triton / crown of thorns starfish), introduced species (red lionfish), loss of mangroves and seagrass nurseries",
                "Conservation: marine protected areas / national parks (Great Barrier Reef, Belize, Chagos), mooring buoys, diver education, No Take Zones which can increase catches elsewhere, sustainable ecotourism and fishing, protection of mangroves and seagrass, erosion and pollution control, planning control of ports and resorts",
                "Fishing controls: closed seasons, minimum and maximum catchable sizes, bans on dynamite, trawling and small-mesh nets",
                "Evaluation: local measures cannot control global threats (warming, acidification) which need international action; enforcement in remote areas is difficult; conflicts with local livelihoods; large vs small NTZs",
                "Justified conclusion"]),
      ]),
]

ESSAYS = [
    Essay("ESS-P2-CONDITIONS", 2,
          "Explain how the physical features of the Earth and the activities of living organisms have combined to create and maintain conditions suitable for life.",
          "3.1.1", "5-9",
          ["Physical features: mass / gravity retaining an atmosphere and giving pressure for liquid water; distance from the Sun and the Goldilocks zone; speed of rotation reducing temperature extremes; tilt producing seasons; magnetic field deflecting the solar wind; the Moon stabilising the orbit and producing tides",
           "Importance of liquid water: solvent, transport, temperature control, anomalous expansion, high specific heat capacity, habitats, absorption of UV before the ozone layer",
           "Development of life: Archaea at vents; photosynthesis; oxygen reacting with iron then accumulating; ozone layer allowing colonisation of land; aerobic organisms",
           "Life changing conditions: carbon sequestration offsetting solar brightening, biogeochemical cycles, transpiration and rainfall, regulation of atmospheric gases",
           "Methods of studying past conditions: proxy data, isotope ratios, ice cores, Mg:Ca ratios; understanding of continental drift and ocean currents",
           "Links to current threats (climate change, ozone depletion) and a justified conclusion about the interdependence of physical and biological factors"]),
    Essay("ESS-P2-BIOVALUE", 2,
          "Discuss the extent to which the resources and services provided by other species justify the conservation of biodiversity.",
          "3.1.2.1", "10-19",
          ["Resources: wood, fibres, oils, fuels, food; new food species (morama bean, yeheb, perennial maize, Kernza, bison, eland) and their adaptations",
           "Biomimetics: wing-tip feathers, whale tubercles, shark skin, termite mounds, bird bones, gecko adhesion, burrs, lotus, spider silk",
           "Medicines: poppies, cinchona, willow, yew (taxol), Mexican yam, sponges (AZT), sharks; few species yet studied; physiological research (marsupials, hippo, sponges)",
           "Genetic resources: crop wild relatives, Vavilov centres, gene pools and inbreeding",
           "Ecosystem services: atmospheric regulation, hydrological cycle, biogeochemical cycles, soil maintenance; interspecies relationships - food, pollination (Darwin's orchid), seed dispersal, habitat provision",
           "Evaluation: economic vs intrinsic / moral arguments; services unnoticed because of dynamic equilibrium; unknown future value; justified conclusion"]),
    Essay("ESS-P2-ENERGETICS", 2,
          "Discuss how an understanding of energy flow and the manipulation of food species can be used to increase food production sustainably.",
          "3.5.1.2", "321-328",
          ["Energy flow: autotrophs and heterotrophs; losses by reflection, transmission, respiration; 100 000 to 1 000 units; few food chains beyond four levels; plant food most productive; grazing animals where crops impossible; pigs on wastes",
           "Energetics: intensive vs extensive, law of diminishing returns, energy subsidies (fertiliser, pesticides, irrigation, machinery, drying, processing, transport), energy ratios, food conversion ratios, dependence on fossil fuels",
           "Control of genetics: asexual reproduction / cuttings / cloning, selective breeding and breeds, cross-breeding and hybrid vigour, AI and embryo transfer",
           "GM: Roundup Ready soya, Bt crops, golden rice, omega-3 oilseed rape; advantages; risks (gene transfer, antibiotic markers, allergies, costs to LEDC farmers, loss of local diversity)",
           "Sustainability links: energy dependence, trophic level of diet, feeding 12 billion people",
           "Justified conclusion on the balance between productivity, efficiency and sustainability"]),
    Essay("ESS-P2-REEFS", 2,
          "Using tropical coral reefs as an example, discuss how the ecological features of a habitat determine both its importance and its vulnerability to human activities.",
          "3.1.2.3.4", "57-62",
          ["Ecological features: cnidarian polyps, cilia, nematocysts, zooxanthellae symbiosis, limestone skeletons building reefs, complex structure and food web; specific abiotic requirements (temperature, light, salinity, low turbidity)",
           "Importance: quarter of marine species, fisheries, medicines, carbon sink, erosion protection, tourism",
           "Vulnerability: narrow abiotic tolerance means sensitivity to warming, acidification, sedimentation, nutrient pollution, oil, bleaching; slow growth so slow recovery; physical damage; overfishing and food-web effects (crown of thorns); introduced species; dependence on mangroves and seagrass",
           "Conservation: MPAs, No Take Zones, fishing controls, tourism management, protection of linked habitats, CITES",
           "Comparison with other habitats (rainforests, mangroves, Antarctica) where relevant",
           "Evaluation of local vs global threats and justified conclusion"]),
    Essay("ESS-P2-FEEDBACK", 2,
          "Discuss how feedback mechanisms, tipping points and diversity influence the stability of natural systems, and how human activities affect them.",
          "3.6.1", "370-372",
          ["Sustainability definitions; population and per capita impact; attitudes of rural and urban societies",
           "Negative feedback: cloud cover and albedo, CO<sub>2</sub> and photosynthesis, evaporation and precipitation, density-dependent population regulation",
           "Positive feedback driven by human activities: permafrost, acidification, albedo decline, methane hydrates, fires, cirrus clouds, decomposition",
           "Tipping points: rare under negative feedback; large events (Permian methane hydrate); self-sustaining change from human activities",
           "Diversity and resistance: reefs and rainforests vs low-diversity agroecosystems lacking detritivores, pollinators and predators",
           "Human responses that override feedback (fertilisers, irrigation, pesticides); links to climate change chapter; justified conclusion"]),
    Essay("ESS-P2-SUSFOOD", 2,
          "Discuss the extent to which agriculture can be made sustainable while feeding a growing human population.",
          "3.5.1.3-3.5.1.5", "328-337",
          ["Need: population possibly 12 billion; humans raise carrying capacity; trophic level of diet",
           "Impacts to be reduced: habitat loss, drainage, nutrient enrichment, introduced species, pesticide and nutrient pollution, nitrate toxicity, greenhouse gases, hydrological changes, soil erosion",
           "Social, economic and political influences: consumer choices, technology availability, grants, guaranteed markets, surpluses, quotas, set-aside, agri-environment schemes",
           "Strategies: cultural and biological pest control, integrated control, organic nutrient supply, legumes, low tillage, water conservation, CWR conservation, renewable energy, methane reduction, habitat retention",
           "Limits: little new land, imports reducing local availability, cost and acceptance of new techniques, past land degradation",
           "Justified conclusion"]),
]
