"""Living environment: habitat case studies - temperate broadleaf woodland, tropical rainforest, tropical and deep-water coral reefs,
oceanic islands, mangroves, Antarctica (spec 3.1.2.3.4).  Genn pp. 50-71."""
from gen.model import Q, P, Table, Chart, Essay

T = "habitats"

QUESTIONS = [
    Q("HAB-01", T, "3.1.2.3.4", "50-52",
      parts=[
          P("Describe the ecological features of temperate broadleaf woodland and explain how woodland floor plants such as bluebells are adapted to them.", 4,
            ms=["No major temperature extremes; regular water supply with no pronounced dry season; deep fertile soils built by leaf litter and root binding; strong seasonality",
                "Deciduous canopy present spring to autumn shades the floor during the best growing temperatures", "Bluebells, snowdrops, lesser celandine grow and flower early in spring before the trees leaf",
                "Winter food shortage causes animals to hibernate (dormice), store food or migrate"]),
          P("Explain why an ancient woodland (existing before 1600) usually has higher biodiversity than a recently planted woodland.", 3,
            ms=["Long time for species to colonise; some woodland plants colonise very slowly so their presence (ancient woodland indicators) shows the wood is old",
                "Natural woodland has trees of all ages with clearings where old trees died, giving varied light and dead wood habitats", "A new plantation has a single-age dense canopy with low light and few niches until trees start to die (over 200 years)"]),
          P("Describe <b>three</b> threats to UK broadleaf woodland.", 3, items=3,
            ms=["Clearance for farmland, plantations, urban development, roads, mineral extraction", "Fragmentation isolating remaining woods so populations cannot move between them and are vulnerable",
                "Management change: end of coppicing so woods become uniform and dark; replacement by conifer monocultures", "Overgrazing by deer preventing regeneration; introduced pathogens (ash dieback)"]),
      ]),

    Q("HAB-02", T, "3.1.2.3.4", "50-52",
      intro="Table 1 shows the number of bird species and butterfly species recorded in three woodlands in the same region.",
      figures=[Table(["Woodland", "Management", "Bird species", "Butterfly species"], [["A", "Ancient oak wood, coppiced on rotation with clearings", "42", "23"], ["B", "Ancient oak wood, unmanaged for 60 years, dense canopy", "28", "9"], ["C", "40-year-old conifer plantation", "14", "3"]])],
      parts=[
          P("Use Table 1 and your knowledge to explain the differences in biodiversity between the three woodlands.", 5,
            ms=["A: coppice rotation creates a patchwork of different ages / light levels - clearings with wildflowers for butterflies, dense regrowth for nesting birds; oak supports many invertebrates",
                "B: same tree species but the closed canopy shades the floor so few flowering plants, fewer invertebrates and butterflies; fewer niches",
                "C: non-indigenous single-species, single-age conifers support few native invertebrates; dense shade; no clearings or dead wood; needles acidify soil",
                "Habitat diversity / structural variety increases the range of niches and hence species"]),
          P("Describe <b>three</b> conservation efforts used to protect UK woodlands.", 3, items=3,
            ms=["Designated protected areas: SSSIs, NNRs (Sherwood Forest), SACs (Epping Forest), National Parks", "Legal protection of ancient woodland: planning permission refused for developments destroying irreplaceable habitats (2012 NPPF)",
                "Conservation management: coppicing, creating clearings, planting mixed native species, leaving dead wood, controlling deer", "Planting new native woodlands linking fragments (corridors); Woodland Trust / National Trust ownership"]),
          P("Explain why a high biodiversity increases the ecological stability of a woodland.", 2,
            ms=["No species is completely dominant and food webs have many alternative links", "So a change in the population of one species has a relatively small impact on the whole community"]),
      ]),

    Q("HAB-03", T, "3.1.2.3.4", "52-55",
      parts=[
          P("Explain why tropical rainforests have such high biodiversity.", 4,
            ms=["Stable tropical climate over long periods gave time for species to evolve and adapt to local abiotic and biotic factors; many rare species with small ranges",
                "High light, warm temperatures and high rainfall all year allow continuous photosynthesis and growth, supporting rich food webs with no seasonal food shortage (no hibernation / migration)",
                "Stratification (emergent, canopy, understorey, shrub, ground layers) and epiphytes create many niches; intense competition for light drives specialisation",
                "Biotic pressures (predation, inter-species relationships) drive evolution of specialised pollination / seed dispersal relationships; plants flower and fruit at different times"]),
          P("Explain why rainforest species may be particularly vulnerable to environmental change.", 2,
            ms=["Adapted to stable conditions so they have narrow ranges of tolerance; a small change can move conditions outside the range", "Many species are rare with small ranges / small populations"]),
          P("Explain why rainforest plants and animals such as frogs are a rich source of medicines.", 2,
            ms=["No cold winter kills herbivores so plants defend themselves with toxic chemicals (alkaloids) that are medicinally active in controlled doses (quinine, diosgenin, curare)",
                "Animals without teeth / claws (frogs, reptiles) rely on chemical defences or venoms (fer-de-lance venom - captopril)"]),
          P("Explain the importance of tropical rainforest for the hydrological cycle and for soils.", 2,
            ms=["Over half the Amazon's rainfall comes from transpiration within the forest; clearance reduces downwind rainfall", "Rapid decay recycles nutrients so soils are shallow / poor; canopy and roots prevent erosion of the thin soil - clearance leads to rapid erosion and infertility"]),
      ]),

    Q("HAB-04", T, "3.1.2.3.4", "55-57",
      intro="Figure 1 shows the main causes of tropical rainforest loss in a South American country between 2000 and 2020.",
      figures=[Chart("bar", "Cause", "Percentage of forest loss / %", {"Percentage": [("Cattle ranching", 45), ("Soya / cash crops", 22), ("Subsistence farming", 12), ("Timber", 10), ("Mining", 5), ("Reservoirs / roads", 4), ("Fires", 2)]}, y_min=0)],
      parts=[
          P("Explain why traditional 'slash and burn' subsistence agriculture was sustainable but has become a threat.", 3,
            ms=["Small clearings were farmed for a few years then abandoned as nutrients declined; the forest recolonised and soil fertility recovered before the area was cleared again",
                "Population growth shortens the gap between clearances so the forest and soil do not recover", "Clearings enlarge and degrade; less regrowth"]),
          P("Explain why clearance for cattle ranching or cash crops is usually unsustainable.", 2,
            ms=["Rainforest soils are thin and nutrient-poor (nutrients held in the biomass); once cleared, fertility falls in a few years and yields drop, so more land is cleared", "Abandoned land may not be recolonised if no forest survives nearby; erosion of exposed soil"]),
          P("Describe how each of the following threatens rainforest.", 3, labels=["Mineral extraction", "HEP reservoirs", "Climate change"],
            ms=["Mining (aluminium, iron, gold, copper) destroys habitat directly and pollutes rivers with turbid drainage, cyanide and mercury from processing",
                "Reservoirs (eg Tucurui, 2850 km^2) flood large areas, block migratory fish and river dolphins; decomposing vegetation produces acidic, deoxygenated water; fluctuating downstream flows",
                "Droughts increase frequency, area and duration of fires (long fires boil sap and kill trees); cloud forests lose humidity as clouds form higher so frogs and epiphytes decline; some models predict replacement by savannah"]),
          P("Describe how a debt-for-nature swap works.", 2,
            ms=["A creditor country or conservation charity cancels / buys part of a debtor country's foreign debt", "In return the country guarantees to protect an area of rainforest (eg USA - Guatemala, Brazil; WWF - Costa Rica, Philippines)"]),
      ]),

    Q("HAB-05", T, "3.1.2.3.4", "56-57",
      parts=[
          P("Describe the conservation efforts used to protect tropical rainforests and evaluate their effectiveness.", 9, level=True,
            ms=["Protected areas: Korup NP Cameroon (1260 km^2, 600 tree species, endemic Ancistrocladus korupensis with anti-HIV / antimalarial alkaloids); Tumucumaque NP Brazil (39 000 km^2, adjoining French Guiana reserve); Alto Maues; Rio Bravo Belize funded by charities, companies and ecotourism",
                "Debt for nature swaps; sustainable exploitation: selective logging of high-value timber (mahogany) funding conservation; ITTO aims (largely unmet); CITES listing of timber species (Honduras mahogany Appendix II)",
                "Ecotourism income (but visitor damage in Costa Rica, Malaysia); community projects and employment; carbon sequestration payments",
                "Effectiveness: protected areas work where enforced but face illegal logging, mining, poaching, roads, conflict; drivers (population growth, demand for beef, soya, palm oil, timber, minerals) originate outside the forest; climate change cannot be controlled locally",
                "Judgement: combination of large protected areas, economic alternatives for local people and reduced international demand needed; overall loss continues"]),
          P("State <b>one</b> reason why rainforest conservation is important to countries far from the tropics.", 1,
            ms=["Carbon sequestration reducing climate change; genetic resources / medicines; rainfall regulation; global biodiversity"]),
      ]),

    Q("HAB-06", T, "3.1.2.3.4", "57-60",
      parts=[
          P("Explain how the relationship between coral polyps and zooxanthellae allows reefs to support a high biomass in nutrient-poor tropical seas.", 4,
            ms=["Zooxanthellae are photosynthetic algae living inside polyp cells (up to 30 000 per mm^2)", "They use the polyp's CO2 and excretory wastes (nitrogen, phosphorus) for photosynthesis and growth, so nutrients are recycled efficiently",
                "They supply the polyp with glucose and oxygen - over 95% of its food energy; the polyp provides a protected habitat and nutrients", "Polyps also trap plankton with cilia and stinging nematocysts; surplus CO2 is used to build the calcium carbonate skeleton"]),
          P("Describe the abiotic conditions needed by reef-building corals and explain why these make reefs vulnerable.", 3,
            ms=["High light (shallow, clear water) for the algae; warm stable temperatures (about 18-30 &deg;C); low turbidity; constant salinity; well-oxygenated water", "Found only where all these coincide (about 1% of ocean area)",
                "Small changes (warming, sediment, freshwater runoff) move conditions outside the narrow range of tolerance"]),
          P("Explain <b>three</b> ways in which coral reefs are important to humans.", 3, items=3,
            ms=["Fisheries: support over a quarter of marine species including fish, lobsters, conch", "Erosion protection: complex structure dissipates wave energy protecting low coral islands; coral sand builds shores",
                "Medicinal discoveries: AZT and Ara-C from sponges, dolastatin from sea hares, bryostatin from Bugula, trabectedin from sea squirts, secosteroids, coral for bone grafts", "Climate control: carbonate skeletons sequester CO2", "Tourism (diving, snorkelling)"]),
      ]),

    Q("HAB-07", T, "3.1.2.3.4", "60-63",
      intro="Figure 1 shows the percentage of live coral cover on a reef near a growing coastal resort between 1990 and 2020, and the years of two major bleaching events.",
      figures=[Chart("line", "Year", "Live coral cover / %", {"Coral cover": [(1990, 62), (1995, 58), (1998, 35), (2002, 42), (2006, 45), (2010, 40), (2016, 18), (2020, 22)]}, y_min=0, y_max=70)],
      parts=[
          P("Describe the changes in coral cover shown in Figure 1.", 2,
            ms=["Overall decline from 62% to 22%", "Sharp falls in 1998 (to 35%) and 2016 (to 18%) coinciding with bleaching events, with partial recovery after each"]),
          P("Explain what coral bleaching is and give <b>three</b> causes.", 4,
            ms=["The polyps expel their symbiotic zooxanthellae so the coral loses colour; bleached corals are alive but grow very slowly and may die if algae do not return",
                "Raised water temperature (climate change / El Ni&ntilde;o)", "Pollution: sewage, pesticides, cyanide, sunscreen; low oxygen from zooplankton blooms after overfishing", "High light / solar activity; ocean acidification hinders skeleton formation"]),
          P("Explain how the growing resort could threaten the reef other than through bleaching.", 3,
            ms=["Coastal construction and dredging increase sedimentation / turbidity covering and killing polyps", "Sewage and fertiliser nutrients cause algal growth that shades corals and prevents egg release",
                "Physical damage from anchors, divers, souvenir collection; loss of mangroves / seagrass nurseries that trap sediment"]),
          P("Explain why a no-take zone on the reef could increase fish catches in surrounding areas.", 1,
            ms=["Protected breeding populations grow larger and produce surplus young / adults that spill over into fished areas"]),
      ]),

    Q("HAB-08", T, "3.1.2.3.4", "61-64",
      parts=[
          P("Explain how overfishing of the giant triton mollusc damaged coral reefs in Australia.", 2,
            ms=["Giant tritons are predators of the crown-of-thorns starfish which eats coral polyps", "Removing tritons allowed starfish populations to explode, destroying large areas of reef (food web / trophic cascade)"]),
          P("Describe <b>four</b> management practices used in marine protected areas to protect coral reefs.", 4, items=4,
            ms=["Fixed mooring buoys so boats do not anchor on coral", "Education of divers / snorkellers not to touch coral or kick up sediment; bans on spear fishing and souvenir collection",
                "Fishing controls: no-take zones (Chagos, Great Barrier Reef, Lundy, Lamlash Bay), seasons, minimum and maximum catch sizes, bans on dynamite / small-mesh nets / trawling",
                "Protection of turtle nesting beaches; control of coastal development; protection of mangroves and seagrass; artificial reefs (reef balls, sunk ships / oil rigs)"]),
          P("Explain why deep-water coral reefs recover much more slowly from trawling damage than tropical reefs.", 2,
            ms=["No sunlight so no symbiotic algae; polyps rely only on captured food so have far less energy and grow very slowly", "Damage from trawls takes hundreds of years to repair; the slow-growing, low-fecundity fish (orange roughy) they support are easily over-exploited"]),
          P("Give <b>two</b> threats to deep-water reefs and <b>one</b> conservation measure.", 2,
            ms=["Deep-water trawling (also by-catch); oil and gas exploration in deeper water; ocean acidification", "Protected areas banning trawling, eg Darwin Mounds SAC off NW Scotland, Oculina Bank off Florida"]),
      ]),

    Q("HAB-09", T, "3.1.2.3.4", "64-65",
      intro="Table 1 shows the numbers of breeding pairs of two seabird species on an island before and after a rat eradication programme.",
      figures=[Table(["Species", "Breeding pairs before eradication", "Breeding pairs 8 years after eradication"], [["Manx shearwater", "45", "310"], ["Storm petrel", "12", "140"]])],
      parts=[
          P("Explain why oceanic islands have many endemic species but low overall biodiversity.", 4,
            ms=["Isolation makes colonisation difficult: only marine species, seabirds, plants with floating seeds or chance arrivals (tortoises on logs, wind-blown birds) reach them",
                "Whole taxa (terrestrial mammals, amphibians) may be absent so few original colonists", "Colonists evolve in isolation under different selection pressures to fill the empty niches, producing unique species (Galapagos, Madagascar lemurs, Hawaii)",
                "Endemics have small ranges and populations so are vulnerable to extinction"]),
          P("Use Table 1 to explain why introduced rats had such a severe effect on these birds.", 3,
            ms=["The birds evolved without mammal predators so nest on the ground / in burrows with no defence", "Rats eat eggs and chicks; numbers fell to very low levels (45 and 12 pairs)",
                "After eradication breeding success rose about 7-12 fold, confirming predation was the main limiting factor"]),
          P("Explain how avian malaria threatens Hawaiian birds and how climate change worsens the threat.", 2,
            ms=["Introduced mosquitoes carry avian malaria to which endemic birds have no resistance; birds survive only above about 1500 m where it is too cold for malaria",
                "Warming allows mosquitoes / malaria to spread to higher altitudes, shrinking the safe range"]),
          P("Give <b>one</b> other conservation measure for oceanic islands besides eradicating introduced species.", 1,
            ms=["Control of developments and visitor numbers (biosecurity, quarantine of imports); protected areas; captive breeding of endemics"]),
      ]),

    Q("HAB-10", T, "3.1.2.3.4", "66-67",
      parts=[
          P("Describe the ecological features of mangroves and the adaptations of mangrove trees.", 3,
            ms=["Tropical intertidal coastal forests of halophytic (salt-tolerant) trees in saline, oxygen-deficient (anaerobic) mud", "Prop / aerial roots for support in soft sediment and for gas exchange (pneumatophores); salt excretion",
                "Seeds germinate on the parent tree and float, rooting where they touch sand - rapid natural regeneration"]),
          P("Explain <b>four</b> reasons why mangroves are important.", 4, items=4,
            ms=["Coastal erosion / storm protection: roots and vegetation absorb wave energy (least tsunami damage in 2004 where mangroves were intact)", "Fisheries: nursery grounds where dense roots protect young fish that later live on reefs / open sea",
                "Protection of coral reefs: slow river water so suspended solids settle and nutrients are absorbed before reaching reefs", "Resources: timber, fuel; medicines (antimicrobials against MRSA, cyanobacterium for lung cancer); high biodiversity (crabs, shrimps, sponges, birds)"]),
          P("Describe the main threats to mangroves and the conservation efforts used.", 3,
            ms=["Clearance for aquaculture (shrimp ponds), urban development, ports, tourism; pollution; sea level rise / climate change; destruction of coral reefs that shelter the coast",
                "Legal protection / designated areas (eg Sri Lanka protected all remaining mangroves in 2015)", "Replanting and natural regeneration; control of damaging activities; Ramsar sites"]),
      ]),

    Q("HAB-11", T, "3.1.2.3.4", "67-71",
      intro="Figure 1 shows a simplified Antarctic food web.",
      figures=[Table(["Trophic level", "Organisms"], [["Producers", "Phytoplankton, ice algae"], ["Primary consumers", "Zooplankton, krill"], ["Secondary consumers", "Small fish, squid, baleen whales, crabeater seals, penguins"], ["Higher consumers", "Toothfish, albatross, leopard seal, killer whale"]], caption="Figure 1")],
      parts=[
          P("Explain why the sea around Antarctica is so productive despite the cold.", 3,
            ms=["Upwelling currents bring nutrients from the seabed to surface waters", "24-hour daylight in summer allows a huge phytoplankton bloom", "Algae also grow under sea ice where krill shelter and feed; krill support most of the food web"]),
          P("Use Figure 1 to explain why fishing for krill and for Patagonian toothfish threatens other species.", 3,
            ms=["Krill is the main food of baleen whales, penguins, seals and fish so over-harvesting removes food from most of the web", "Toothfish overfishing removes the food of sperm whales and elephant seals",
                "Long-lining for toothfish catches and drowns albatrosses on the hooks (by-catch)"]),
          P("Explain the importance of Antarctica in controlling global natural cycles.", 3,
            ms=["Ice on land stores 70% of the Earth's fresh water, keeping sea levels low", "High albedo of ice reflects sunlight, limiting warming (reduction in ice area causes further warming)",
                "Carbon sequestration: carbon in algae eaten by krill sinks to the seabed in krill faeces"]),
          P("Explain why the area of winter sea ice around Antarctica has increased in recent years even though air and sea are warming.", 1,
            ms=["Stronger winds spreading ice; more snowfall from warmer, moister air freezing onto slush; fresh meltwater from land forming a surface layer that freezes more easily (long-term trend still expected to be a decline)"]),
      ]),

    Q("HAB-12", T, "3.1.2.3.4", "69-71",
      parts=[
          P("Describe how each of the following threatens Antarctica.", 4, labels=["Global climate change", "Ozone depletion", "Tourism", "Future mineral exploitation"],
            ms=["Warming melts ice shelves that hold back glaciers and lubricates ice flow so land ice reaches the sea faster (Antarctic Peninsula most affected); sea ice loss removes krill habitat and lowers albedo",
                "Raised UV harms planktonic algae, krill and fish / sea urchin larvae in surface waters (land animals protected by fur / feathers)", "Disturbance of wildlife, introduction of non-indigenous species and pathogens, fuel and sewage pollution; visitor numbers rising rapidly at a few landing sites",
                "Reserves of coal, oil, gold, uranium, platinum etc; pressure to exploit will rise as reserves elsewhere deplete though currently banned and operations extremely difficult"]),
          P("Describe the main features of the Antarctic Treaty (1959) and the regulations that protect Antarctica.", 6,
            ms=["Treaty signed by 52 countries including all active there; no military activity (except supporting research), no nuclear explosions or radioactive waste dumping", "No commercial mineral exploitation",
                "Fisheries regulated by CCAMLR: krill and some fish exploited, fisheries closed if over-exploited; no commercial exploitation of mammals",
                "Tourism control: no accommodation on land (wastes stay on ships), one ship per site with maximum 100 ashore, trained guides, keep 5 m from wildlife, no litter, cleaned protective clothing to prevent introductions",
                "Waste management: all wastes removed (fuel containers, batteries, plastics, oil); sewage only discharged where sea currents disperse it; old waste removed unless removal causes more damage",
                "Only long-term residents are research scientists and support staff; strict regulation of research impacts"]),
      ]),

    Q("HAB-13", T, "3.1.2.3.4", "50-71",
      parts=[
          P("Which of the following habitats has low biodiversity but a high proportion of endemic species? Tick one box.", 1,
            mcq=["Tropical rainforest", "Oceanic islands", "Temperate broadleaf woodland", "Mangroves"], ms=["B"]),
          P("Compare the ecological features of tropical rainforest and Antarctica that explain their very different biodiversity.", 4,
            ms=["Rainforest: high light, warm, wet all year, stable conditions for long periods, continuous productivity, many niches (stratification)", "Antarctica: very low temperatures, low precipitation, extreme seasonal light, 98% ice cover so almost no terrestrial life",
                "Antarctic biodiversity is marine, supported by upwelling nutrients and the summer bloom; rainforest supports over half of terrestrial species on 10% of land", "Both are important carbon stores / climate regulators but rainforest species are specialists vulnerable to small changes; Antarctic species adapted to extreme fluctuation"]),
      ]),
]

ESSAYS = [
    Essay("ESS-P2-HABITATS", 2,
          "Using named examples, discuss how the ecological features of a habitat determine its importance, the threats it faces and the conservation strategies that are appropriate.",
          "3.1.2.3.4", "50-71",
          ["Temperate broadleaf woodland: seasonality, deep soils, high biodiversity, resources, climate and soil regulation; deforestation, fragmentation, management change; SSSIs, ancient woodland protection, coppicing, mixed planting",
           "Tropical rainforest: stable warm wet climate, stratification, very high biodiversity, carbon and hydrological roles, thin soils; fuelwood, timber, agriculture, mining, reservoirs, climate change; protected areas, debt-for-nature swaps, sustainable exploitation",
           "Tropical coral reefs: cnidarian-zooxanthellae symbiosis, light, temperature, turbidity, salinity; fisheries, erosion protection, medicines, tourism; damage, souvenirs, sedimentation, pollution, bleaching, fishing, introduced species; MPAs, no-take zones, control of activities",
           "Deep-water reefs: cold, dark, slow growth; research, fisheries; trawling, oil / gas, acidification; SACs",
           "Oceanic islands: isolation, endemism, no mammal predators; exploitation, introduced species, habitat change, sea level; eradications, control of development and visitors",
           "Mangroves: halophytes, anaerobic mud; erosion protection, fisheries nurseries, sediment trapping; clearance for aquaculture / urban / ports, pollution, climate change; protection, replanting",
           "Antarctica: extreme cold, seasonality, marine nutrients, ice; water store, albedo, carbon, research; climate change, ozone, tourism, fishing, minerals; Antarctic Treaty, CCAMLR, tourism and waste rules",
           "Synthesis: features -> importance -> threats -> strategy; evaluation of success; conclusion"]),
]
