"""Living environment: conditions for life on Earth (3.1.1); importance of biodiversity (3.1.2.1); human influences (3.1.2.2).
Genn pp. 5-25."""
from gen.model import Q, P, Table, Chart, Essay

QUESTIONS = [
    # ---------------- 3.1.1 conditions for life ----------------
    Q("LIFE-01", "life-conditions", "3.1.1.1", "5-7",
      intro="Table 1 shows some features of Earth, Mars and Venus.",
      figures=[Table(["Feature", "Venus", "Earth", "Mars"], [["Mean distance from Sun / million km", "108", "150", "228"], ["Mass relative to Earth", "0.82", "1.0", "0.11"], ["Atmospheric pressure relative to Earth", "92", "1.0", "0.006"], ["Mean surface temperature / &deg;C", "460", "15", "-60"], ["Magnetic field", "Very weak", "Strong", "Very weak"], ["Rotation period / hours", "5 800", "24", "25"]])],
      parts=[
          P("Use Table 1 to explain why liquid water cannot exist on the surface of Mars.", 3,
            ms=["Mars has low mass so weak gravity and could not retain a dense atmosphere", "Very low atmospheric pressure means water would boil / evaporate away even at low temperatures",
                "Greater distance from the Sun gives low insolation and a mean temperature of -60 &deg;C so water is frozen"]),
          P("Explain how the Earth's mass and its distance from the Sun created suitable conditions for life.", 3,
            ms=["Mass great enough for gravity to retain an atmosphere containing the elements needed (C, H, O, N as CO2, methane, ammonia, water vapour) and to maintain pressure so liquid water does not boil",
                "Distance from the Sun (the 'Goldilocks zone') gives insolation producing temperatures at which water is liquid (0-35 &deg;C over most of the surface) and proteins are not denatured",
                "Too close (Venus) - too hot; too far (Mars) - too cold"]),
          P("Explain the importance of the Earth's magnetic field and its speed of rotation for living organisms.", 2,
            ms=["The molten core produces a magnetosphere that deflects the solar wind / charged particles, preventing biologically damaging radiation reaching the surface",
                "The 24-hour rotation limits heating by day and cooling by night, reducing temperature extremes (Venus' slow rotation gives extreme conditions)"]),
          P("Explain how the tilt of the Earth's axis affects living organisms.", 2,
            ms=["The tilted axis causes seasonal variation in insolation as the Earth orbits the Sun", "Producing seasons (temperature, day length) to which species' life cycles (breeding, migration, dormancy) are adapted; the Moon's gravity keeps the tilt stable and creates tides"]),
      ]),

    Q("LIFE-02", "life-conditions", "3.1.1.1-3.1.1.2", "7-8",
      parts=[
          P("Explain <b>four</b> properties of water that make it essential for life.", 4,
            ms=["General physiological solvent: most biological reactions take place between substances dissolved in water", "Transport medium in blood / sap carrying gases, sugars, amino acids, nutrients, wastes",
                "High specific heat capacity moderates temperature changes; evaporation absorbs heat (cooling)", "Anomalous expansion: ice floats so water bodies do not freeze solid; absorbs UV protecting early marine life; provides aquatic habitats"]),
          P("Describe how photosynthetic organisms changed the atmosphere and explain how this allowed life to colonise the land.", 4,
            ms=["From about 2.7 billion years ago photosynthetic archaea / bacteria (then algae and plants) released oxygen; at first it reacted with dissolved iron (forming iron ore deposits) then built up in the oceans and atmosphere (from about 2.45 billion years ago)",
                "Oxygen in the stratosphere absorbed UV, forming ozone (O3) in a dynamic equilibrium of O, O2 and O3", "The ozone layer reduced UV reaching the surface so organisms could survive out of the water",
                "Oxygen allowed aerobic respiration releasing more energy so complex multicellular organisms evolved; many anaerobic archaea died out"]),
          P("Explain how carbon sequestration by early photoautotrophs helped maintain a suitable temperature on Earth.", 2,
            ms=["Photosynthesis removed CO2 (a greenhouse gas) from the atmosphere, storing carbon in sediments, carbonate rocks and fossil fuels", "This reduced infrared retention, offsetting the increasing brightness of the Sun (about 10% per billion years) so temperatures did not rise excessively"]),
      ]),

    Q("LIFE-03", "life-conditions", "3.1.1.2-3.1.1.3", "8-9",
      parts=[
          P("Explain how the development of biogeochemical cycles and of transpiration by land plants helped to maintain stable conditions for life.", 3,
            ms=["Interconnected biological processes recycle nutrient elements so small amounts support life indefinitely without depletion; waste products of one process are raw materials of another so wastes do not build up",
                "Transpiration returned water vapour to the atmosphere increasing rainfall elsewhere", "Allowing more plant growth, further stabilising climate and soils"]),
          P("Describe <b>three</b> limitations of early methods of studying past conditions on Earth.", 3, items=3,
            ms=["Lack of ancient historical / instrumental data", "Reliance on proxy data (tree rings, pollen) of limited reliability for ancient conditions", "Lack of sophisticated equipment / inability to measure many factors",
                "Limited coordination between researchers; lack of data collection in many areas (oceans, poles)"]),
          P("Describe how each of the following modern techniques provides information about past conditions.", 4,
            labels=["Isotope analysis of ice cores", "Gas analysis of ice cores", "Radiocarbon dating", "Magnesium : calcium ratio in calcite"],
            ms=["The ratio of oxygen-18 to oxygen-16 in the ice indicates the temperature when the snow fell", "Air bubbles trapped in ice give the composition of the past atmosphere (CO2, methane)",
                "Ratio of carbon-14 to carbon-12 dates organic material (eg pollen in sediments)", "More magnesium is incorporated into calcite at higher temperatures, so the ratio estimates past sea temperature"]),
      ]),

    # ---------------- 3.1.2.1 importance of biodiversity ----------------
    Q("BIOV-01", "biodiversity-value", "3.1.2.1.1-3.1.2.1.2", "10-15",
      parts=[
          P("Explain what is meant by <b>biomimetics</b> and describe <b>three</b> examples.", 4,
            ms=["Copying the structural / functional adaptations of living organisms in the design of manufactured items",
                "Aircraft wingtip fins copied from splayed wingtip feathers of soaring birds, reducing turbulence and fuel use", "Humpback whale flipper tubercles copied on ship rudders and wind turbine blades (tighter turns, rotation at lower wind speeds)",
                "Shark skin ridges reducing friction / bacterial adhesion (surface coatings, hospital surfaces)", "Termite mound convection copied for natural ventilation of buildings; hollow strutted bird bones in lightweight roofs; gecko toe adhesion; burr hooks - Velcro; lotus leaf self-cleaning glass; spider silk for airbags / body armour; bat / dolphin echolocation - ultrasound scanners"]),
          P("Explain why many plants produce chemicals that are useful as human medicines, and give <b>two</b> examples.", 3,
            ms=["Plants produce toxic chemicals (eg alkaloids) to defend themselves against herbivores; in controlled doses these affect human physiology",
                "Examples: morphine / codeine from poppies; quinine from cinchona bark (malaria); aspirin from willow bark; taxol from yew (cancers); diosgenin from Mexican yam (contraceptives, cortisone)",
                "Animal examples accepted: AZT from a marine sponge (HIV), shark liver lipids (tumours)"]),
          P("Explain why the discovery of medicines is a strong argument for conserving whole habitats rather than individual species.", 2,
            ms=["Only a very small proportion of species have been studied for medicinal substances so unknown species may contain valuable chemicals", "Conserving the habitat protects all its species, including those not yet investigated (and their interdependent relationships)"]),
          P("Give <b>one</b> example of a wildlife species used in physiological research and the human health issue it helps to understand.", 1,
            ms=["Squid giant nerve cells - nerve function / heart disease, stroke; marsupials (kangaroo, wallaby pouch) - embryo development; hippo skin secretion - sunscreen / burns; sea urchin embryos - teratogen testing; armadillo - leprosy; marine sponge proteins - transplant rejection"]),
      ]),

    Q("BIOV-02", "biodiversity-value", "3.1.2.1.2", "15-17",
      intro="Table 1 shows characteristics introduced into commercial crops from crop wild relatives (CWRs).",
      figures=[Table(["Crop", "Wild relative source", "Characteristic introduced"], [["Sugar cane", "Wild sugar cane, Indonesia", "Resistance to mosaic virus"], ["Tomato", "Single wild species", "Resistance to nine major diseases"], ["Rice / barley", "Wild salt-marsh varieties", "Salt tolerance"], ["Oil palm", "Wild palms, central Africa", "25% higher yield"], ["Wheat", "Wild wheat", "Better mycorrhizal associations / phosphate uptake"]])],
      parts=[
          P("Explain why commercial crop varieties often lack the characteristics shown in Table 1.", 3,
            ms=["Domesticated crops were bred from a small number of original plants so they have a small gene pool / low genetic diversity",
                "Selective breeding for yield, appearance or shelf life may have lost other useful genes (eg taste, disease resistance)", "Genetically similar plants share the same susceptibilities so a new disease or environmental change can affect the whole crop"]),
          P("Explain what is meant by a <b>Vavilov centre</b> (centre of diversity) and why these areas are conservation priorities.", 3,
            ms=["A region with a high concentration of the wild relatives of important crops - usually where the crop was first domesticated (eg wheat / barley in the Middle East; potato, tomato in South America; rice in India; maize in Central America)",
                "They hold the largest gene pools / most genetic variety for future crop breeding (disease resistance, drought and salt tolerance, yield)", "Many are in regions where environmental degradation / habitat loss threatens the wild plants"]),
          P("Explain why a large population does not necessarily have a large gene pool, and why a small gene pool is a problem.", 3,
            ms=["A large population may all descend from a few closely related individuals so they are genetically similar", "Similar adaptations mean all are susceptible to the same change (disease, climate)",
                "Greater risk of inbreeding so disadvantageous recessive genes are expressed (eg amelanism, poor muscle development in lion cubs); so species should be protected across their whole range to retain regional genes"]),
          P("Give <b>one</b> wild plant species with potential as a new commercial food crop and the characteristic that makes it valuable.", 1,
            ms=["Morama bean (drought resistant, soya-like protein); yeheb tree (drought resistant nuts, poor soils); potato bean (high protein); perennial maize / Kernza (no annual replanting, less ploughing / erosion); salt-tolerant spinach relatives"]),
      ]),

    Q("BIOV-03", "biodiversity-value", "3.1.2.1.3", "18-19",
      parts=[
          P("Explain how living organisms provide each of the following ecosystem services.", 6,
            labels=["Regulation of atmospheric composition", "Soil maintenance", "Interspecies relationships"],
            ms=["Photosynthesis and aerobic respiration balance O2 and CO2 in a dynamic equilibrium; evapotranspiration adds water vapour forming clouds and rain; microbes drive the nitrogen and other biogeochemical cycles so wastes do not accumulate and nutrients are recycled",
                "Detritivores, fungi and bacteria decompose dead organic matter releasing nutrients and forming humus that binds soil; organic acids weather rock forming new soil; roots bind soil, reducing erosion and regulating water flow / flooding",
                "Species provide food, pollination (bees, moths, birds, bats - more reliable than wind, especially in forests), seed dispersal (animals carry larger seeds to suitable sites, faeces as fertiliser, gut passage stimulates germination) and habitat provision (trees as nest sites and canopy microclimate; mollusc shells for hermit crabs)"]),
          P("Explain why Darwin's orchid of Madagascar depends on a single moth species, and why such specialisation is both an advantage and a risk.", 2,
            ms=["Its nectar is at the end of a 30 cm tube reached only by the long tongue of the sphinx moth, which carries pollen only between orchids of the same species",
                "Advantage: no pollen wasted on other species and the moth has an exclusive food source; risk: if either species declines the other cannot survive"]),
          P("Explain why elephants are particularly important seed dispersers.", 2,
            ms=["They are not ruminants so seeds are not destroyed by repeated chewing / pass through intact; they eat the fruit of most tree species", "Not territorial so they carry seeds over large distances / areas"]),
      ]),

    Q("BIOV-04", "biodiversity-value", "3.1.2.1", "10-19",
      parts=[
          P("Discuss the reasons why the conservation of biodiversity is important for human society.", 9, level=True,
            ms=["Resources: wood, fibres (cotton, wool, silk), oils, fuels (wood, biofuels), food; new food species (morama bean, perennial cereals, eland, bison) better adapted to local conditions",
                "Biomimetics: vehicle design, architecture, structures, adhesion, materials, ultrasound", "Medicines from plants and animals (examples); most species unstudied - argument for habitat conservation",
                "Physiological research using wildlife species; wildlife as pest control agents (ladybirds, Encarsia, Cactoblastis, Bt)", "Genetic resources: crop wild relatives, Vavilov centres, gene pools",
                "Ecosystem services: atmospheric composition, hydrological and biogeochemical cycles, soil maintenance, pollination, seed dispersal, habitat provision",
                "Ethical / aesthetic / recreational arguments; the unknown value of species not yet investigated (precautionary principle)",
                "Evaluation: which arguments are most persuasive to decision makers; economic valuation vs intrinsic value; judgement"]),
          P("State what is meant by <b>biodiversity</b>.", 1, ms=["The variety and abundance of life (species, genes, habitats) in an area / on Earth"]),
      ]),

    # ---------------- 3.1.2.2 human influences ----------------
    Q("HUM-01", "human-impacts", "3.1.2.2", "20-21",
      parts=[
          P("For each of the following forms of direct exploitation, give a named species whose population has been reduced.", 5,
            labels=["Food", "Fashion", "Entertainment / pets", "Furniture and ornaments", "Traditional medicines"],
            ms=["Food: cod, tuna, swordfish, sharks, turtles; extinct - dodo, great auk, passenger pigeon", "Fashion: leopard, snow leopard, tiger, ocelot fur; fur seals; crocodile / alligator leather; kingfisher, parrot, ostrich feathers",
                "Entertainment / pets: parrots, lizards, snakes, tortoises, tropical marine fish (most wild-caught), dolphins / orcas for marine parks, wild-collected air plants", "Furniture / ornaments: mahogany, teak, ramin timber; ebony and ivory piano keys; turtle shell, shark teeth, coral and shells as souvenirs",
                "Traditional medicines: tiger (bones, claws), rhinoceros horn, seahorses"]),
          P("Explain why species are deliberately eradicated. Give <b>three</b> categories with examples.", 3, items=3,
            ms=["Threat to humans: sharks, venomous snakes, crocodiles", "Disease vectors: malaria mosquitoes, tsetse flies", "Predators of livestock: wolves, puma, birds of prey, herons, seals",
                "Agricultural / forestry pests and competitors: rabbits, deer, wood-boring beetles, squirrels, beavers"]),
          P("Explain why legal protection alone rarely prevents the decline of a species exploited for traditional medicine.", 2,
            ms=["High demand and prices make illegal trade / poaching profitable; laws are hard to enforce across borders", "Belief in the medicine persists despite little scientific evidence; species become rarer and more valuable"]),
      ]),

    Q("HUM-02", "human-impacts", "3.1.2.2", "22-23",
      parts=[
          P("Explain how each of the following changes in abiotic factors caused by human activities can make a habitat unsuitable for species living there.", 6,
            labels=["Water availability", "Dissolved oxygen", "pH"],
            ms=["Drainage of wetlands / lowering water tables by groundwater abstraction dries out wetlands; HEP schemes alter river levels flooding sandbank nests of turtles / birds; species with narrow tolerance (specialists) affected first; sundews lost when drained soil becomes aerobic / nitrogen-rich and taller competitors invade",
                "Hot water discharges and organic wastes (sewage) reduce dissolved oxygen, killing aerobic organisms such as fish and insect larvae",
                "Acid mine drainage and acid rain gases lower pH, denaturing proteins of exposed tissues (fish eggs, gills) and dissolving calcium exoskeletons (crayfish)"]),
          P("Explain how increased water turbidity caused by ploughing, mining or dredging harms aquatic organisms.", 2,
            ms=["Reduces light penetration so submerged plants cannot photosynthesise", "Blocks the gills of filter feeders such as bivalve molluscs; sediment smothers the bed"]),
          P("Explain why species that were already rare are most likely to be lost when abiotic conditions change.", 2,
            ms=["Rare species often have very specialised habitat requirements / narrow ranges of tolerance", "A small change moves conditions outside their range while generalists survive; small populations cannot recover"]),
      ]),

    Q("HUM-03", "human-impacts", "3.1.2.2", "23-25",
      intro="Figure 1 shows the estimated populations of sea otters, sea urchins and the area of kelp forest along part of the coast of California between 1960 and 2010.",
      figures=[Chart("line", "Year", "Index (1960 = 100)", {"Sea otters": [(1960, 100), (1970, 60), (1980, 20), (1990, 25), (2000, 60), (2010, 90)], "Sea urchins": [(1960, 100), (1970, 180), (1980, 350), (1990, 330), (2000, 200), (2010, 120)], "Kelp area": [(1960, 100), (1970, 70), (1980, 25), (1990, 30), (2000, 65), (2010, 90)]}, y_min=0)],
      parts=[
          P("Describe the relationship between the three variables shown in Figure 1.", 3,
            ms=["As sea otters declined (1960-1980) sea urchins increased (to 350) and kelp area fell (to 25)", "As otters recovered after 1990 urchins declined and kelp recovered", "Otter and kelp trends are positively correlated; urchins negatively correlated with both"]),
          P("Explain the relationships shown in Figure 1.", 3,
            ms=["Sea otters are predators of sea urchins so fewer otters allowed the urchin population to rise", "Sea urchins graze kelp so the kelp forest was over-grazed and destroyed",
                "Kelp forests are habitat / food for many species including otters (keystone species / trophic cascade); otter recovery restored the balance"]),
          P("Give <b>two</b> other examples of human over-exploitation of one species affecting the population of another.", 2, items=2,
            ms=["Over-fishing of sandeels reduced puffins", "Over-collection of turtle eggs reduced turtles so jellyfish (their food) increased; over-fishing of sardines / herring (competitors) also increased jellyfish",
                "Loss of pollinating bees (pesticides, wild flower loss) reduces plant reproduction; loss of elephants / large herbivores reduces seed dispersal of trees"]),
          P("Explain why the loss of beavers or forest elephants can cause the decline of many other species.", 2,
            ms=["They control abiotic features: beaver dams create ponds colonised by aquatic species; elephants create clearings and keep water holes open",
                "Species that depend on these features (light, water, minerals) cannot survive in their absence"]),
      ]),

    Q("HUM-04", "human-impacts", "3.1.2.2", "24-25",
      parts=[
          P("Explain why introduced species often have a greater effect on island communities than on mainland communities.", 2,
            ms=["Island communities evolved from few colonising species in isolation, often without mammal predators or large herbivores", "So indigenous species lack adaptations (eg ground-nesting birds, flightlessness) to survive introduced cats, rats, pigs, goats"]),
          P("For each of the following, describe an example of an introduced species and explain its effect on an indigenous species.", 6,
            labels=["Introduced competitor", "Introduced predator", "Introduced pathogen"],
            ms=["Competitor: grey squirrel (North America) out-competes red squirrel - digests acorns, larger, wins nest sites; rhododendron shades ground and releases toxins preventing native regrowth",
                "Predator: American mink (escaped fur farms) reduced water vole range; cane toads in Australia; cats / rats / pigs on islands eating ground-nesting birds; Nile perch in Lake Victoria ate cichlids to extinction",
                "Pathogen: squirrel pox virus carried by grey squirrels kills red squirrels; crayfish plague carried by signal crayfish kills white-clawed crayfish; Dutch elm disease, ash dieback, sudden oak death imported on plants / soil"]),
          P("Explain how hybridisation with an introduced species threatens the red deer and the Scottish wildcat.", 2,
            ms=["Closely related introduced species (sika deer; domestic cats) cross-breed producing fertile hybrids", "The natural gene pool is changed / diluted with genes it would not naturally contain, so the pure indigenous species may disappear"]),
      ]),

    Q("HUM-05", "human-impacts", "3.1.2.2", "20-26",
      parts=[
          P("Which of the following is an example of habitat destruction rather than a change in abiotic factors? Tick one box.", 1,
            mcq=["Thermal pollution of a river by a power station", "Flooding a valley to create a reservoir", "Lowering the water table by groundwater abstraction", "Acid mine drainage entering a stream"], ms=["B"]),
          P("Give <b>four</b> human activities that cause complete habitat destruction.", 4, items=4,
            ms=["Deforestation", "Ploughing of grassland / expansion of farmland", "Reservoir creation / flooding", "Mineral extraction, especially open-cast mining", "Urban expansion"]),
      ]),
]

ESSAYS = [
    Essay("ESS-P2-HUMANIMPACT", 2,
          "Discuss how human activities influence biodiversity, using examples from a range of different contexts.",
          "3.1.2.2, 3.5.1.3, 3.5.2.2, 3.5.3.3", "20-26, 328-330, 341-344, 367-369",
          ["Direct exploitation: food (fisheries, bushmeat), fashion, entertainment / pets, furniture and ornaments, traditional medicines, other products (whale oil); deliberate eradication of predators, competitors, vectors, pests",
           "Changes in abiotic factors: water availability (drainage, abstraction, HEP), light (forest clearance), oxygen (organic pollution, thermal), nutrients (eutrophication), pH (acid mine drainage, acid rain), temperature (thermal pollution, climate change), turbidity, physical damage; inactivity (stopping plagioclimax management)",
           "Changes in biotic factors: introduced competitors, predators, pathogens, hybridisation; loss of pollinators, seed dispersers, keystone species; food chain impacts (sea otters, puffins, jellyfish)",
           "Habitat destruction: deforestation, farmland expansion, urbanisation, mining, reservoirs; fragmentation and edge effects",
           "Contexts: temperate woodland, rainforest, coral reefs, oceanic islands, mangroves, Antarctica; agriculture, fishing, forestry",
           "Positive influences: habitat creation, conservation management, reintroductions, legislation",
           "Evaluation of which influences are most damaging and hardest to reverse; conclusion"]),
]
