"""Sustainability: dynamic equilibria (3.6.1), energy and material cycles in natural vs human systems (3.6.2-3.6.3),
the circular economy, biocapacity and ecological footprints (3.6.4).  Genn pp. 370-389."""
from gen.model import Q, P, Table, Chart, Essay

QUESTIONS = [
    # ---------------- dynamic-equilibria 3.6.1 ----------------
    Q("SUS-01", "dynamic-equilibria", "3.6.1", "370-372",
      parts=[
          P("State the Brundtland Commission (1987) definition of sustainable development.", 1,
            ms=["Development that meets the needs of the present generation without compromising the ability of future generations to meet their own needs"]),
          P("Explain why activities such as slash-and-burn agriculture, fishing and sewage discharge can be sustainable with a small human population but not with a large one.", 3,
            ms=["Impact depends on total population x per capita impact", "With few people, natural processes (forest regrowth, fish recruitment, aerobic decomposition / dilution) recover faster than the resource is used or the waste added",
                "Larger populations exceed the rate of natural recovery: forest and soil do not regenerate, catches exceed MSY, water deoxygenates"]),
          P("Explain why urban populations are often less aware of unsustainable exploitation than rural communities.", 2,
            ms=["Urban areas are supported by resources brought in from elsewhere; when one area is depleted, exploitation simply moves (timber, fish, minerals, energy) so consumers see no shortage",
                "Rural communities exploit local resources directly so the effects of over-exploitation become obvious quickly, encouraging cultural limits to need"]),
          P("Describe <b>two</b> negative feedback mechanisms in natural systems and explain how human responses can override them.", 4,
            ms=["Climate: warming increases evaporation, cloud and albedo; higher CO2 increases photosynthesis and sequestration; hydrological cycle: more evaporation gives more precipitation; populations: density-dependent factors return numbers to carrying capacity",
                "In agriculture soil degradation, water shortage and loss of predators would reduce yields (negative feedback limiting the activity)", "Humans respond with fertilisers, irrigation and pesticides to maintain yields, further damaging the natural systems that support production"]),
      ]),

    Q("SUS-02", "dynamic-equilibria", "3.6.1", "371-372",
      parts=[
          P("Explain why natural systems regulated by negative feedback rarely reach tipping points, and give an example of a natural tipping point in the geological past.", 3,
            ms=["Negative feedback responds to any change by re-establishing the previous equilibrium", "Only large unusual events overwhelm the feedback so a new equilibrium forms",
                "Example: methane hydrate release at the end of the Permian causing climate change and mass extinction"]),
          P("Explain why diverse systems are more resistant to change than simple systems, using a natural and a human example.", 4,
            ms=["In a diverse system each component is relatively less important so the loss / change of one has a small effect; alternative food sources and relationships buffer the change",
                "Natural: coral reefs and tropical rainforests with complex food webs are stable; simple polar / desert systems fluctuate", "Human: agroecosystems focus on a few crops and remove detritivores, pollinators and predators so are vulnerable to pests, disease, weather",
                "Diverse technical systems: a society using a range of renewable energy resources is more secure than one relying on a single source"]),
          P("Give <b>three</b> positive feedback mechanisms by which human-induced warming may become self-sustaining.", 3, items=3,
            ms=["Melting permafrost releasing methane", "Reduced albedo as ice / snow melt", "Methane hydrate release", "Forest and peat fires", "Faster soil decomposition", "Ocean acidification reducing sequestration", "Cirrus cloud formation"]),
      ]),

    # ---------------- natural-systems 3.6.2-3.6.3 ----------------
    Q("SUS-03", "natural-systems", "3.6.2", "373",
      intro="Table 1 compares nitrogen fixation by Rhizobium bacteria in legume root nodules with the Haber process.",
      figures=[Table(["Feature", "Biological fixation", "Haber process"], [["Energy source", "Sunlight captured by the plant (carbohydrates)", "Fossil fuels (natural gas / coal)"], ["Temperature", "Soil temperature (10-30 &deg;C)", "About 450 &deg;C"], ["Pressure", "Atmospheric", "200 atmospheres"], ["Catalyst", "Nitrogenase enzyme", "Iron"], ["Energy density of input", "Low", "High"], ["Waste products", "None - all products used", "CO_2, NOx"]])],
      parts=[
          P("Use Table 1 to explain how natural processes differ from human industrial processes in their use of energy.", 4,
            ms=["Natural processes are driven by renewable, low energy-density solar energy captured by photosynthesis; human processes usually use high energy-density non-renewable fossil fuels",
                "Natural processes occur at low temperatures because enzymes lower the activation energy of reactions; human processes need high temperatures and pressures",
                "Natural processes produce no toxic wastes / their products are raw materials for other processes; industrial processes emit CO2 and NOx", "So natural fixation is sustainable indefinitely with a low carbon footprint"]),
          P("Give <b>three</b> other natural processes driven by solar energy that human society depends on.", 3, items=3,
            ms=["Hydrological cycle (evaporation, precipitation)", "Carbon cycle / photosynthesis", "Atmospheric circulation / winds", "Thermohaline circulation (density differences from heating / evaporation)", "Decomposition"]),
          P("Explain how the principle of low-temperature natural processes is being applied in human systems.", 3,
            ms=["Bioleaching and phytomining extract metals at low temperature instead of high-temperature smelting", "Anaerobic digestion and composting treat wastes; enzymes in industry (biological washing powders, biofuels from algae / microorganisms)",
                "Heat pumps and solar thermal capture low-density heat; low-temperature manufacturing using biological polymers; fuel cells instead of combustion"]),
      ]),

    Q("SUS-04", "natural-systems", "3.6.3", "373-374",
      parts=[
          P("Explain how natural material cycles differ from linear human systems of material use.", 4,
            ms=["Natural cycles use a small number of abundant elements (C, H, O, N, P) built into monomers and polymers (carbohydrates, proteins); wastes of one process are raw materials for another so nothing is depleted or accumulates",
                "Natural wastes are biodegradable / non-toxic and are broken down by decomposers into raw materials", "Human systems are linear: extract - process - manufacture - use - discard; minerals are dispersed after use or mixed so recovery is difficult",
                "Human wastes are often persistent and toxic (organochlorines, PCBs, heavy metals in electronics) and build up; fossil fuel use is inherently linear and unsustainable"]),
          P("Explain why the use of toxic metals in electronic products is a particular problem for sustainability.", 2,
            ms=["Metals are dispersed in small amounts within complex mixed products so they cannot easily be separated / recovered at end of life", "They leach from landfill or are released by incineration; persistent, bioaccumulating"]),
          P("Describe how the design of a product can move it from a linear to a cyclical system.", 4,
            ms=["Design for durability, repair and re-use (replaceable parts, no built-in batteries, spare parts and support, no planned obsolescence)", "Easy identification of materials (coding) and separation of components so they can be recycled",
                "Separation of technical materials (metals, plastics) from biological materials (which can be composted / digested)", "Use of recycled and recyclable / biodegradable materials; reduced packaging and material use (Cradle to Cradle)"]),
      ]),

    # ---------------- circular-economy 3.6.4 ----------------
    Q("SUS-05", "circular-economy", "3.6.4.1", "374-375",
      parts=[
          P("Describe the main principles of the circular economy.", 6,
            ms=["Cycling of materials (like biogeochemical cycles) - recycling, re-use", "Energy from renewable sources", "Human activities should support ecosystems / conserve biodiversity",
                "Separation of technical and biological materials; connected systems where the waste of one process feeds another (industrial symbiosis)", "Diverse systems are more resistant to change",
                "Design of products for extended use and end-of-life re-use; optimum rather than maximum production; technologies that improve efficiency and enable dismantling"]),
          P("Explain what is meant by 'optimum production rather than maximum production', using a comparison between a natural ecosystem and an agroecosystem.", 2,
            ms=["Natural systems over-produce so the surplus supports the processes the system relies on: plant products feed pollinators, seed dispersers, decomposers, mycorrhizae",
                "Agroecosystems aim for maximum harvested yield, removing the surplus that would maintain soil biota, pollinators and pest predators, so they need artificial inputs"]),
          P("Explain why international cooperation (eg through the EU or UN) is needed to implement circular economy initiatives.", 2,
            ms=["Costs of environmental measures could put companies in one country at a disadvantage against competitors in countries without them", "A common approach gives a level playing field, coordinated monitoring and support for less successful countries"]),
      ]),

    Q("SUS-06", "circular-economy", "3.6.4.1", "375-379",
      parts=[
          P("Evaluate the extent to which the principles of the circular economy can be applied to <b>three</b> of the following: water supplies, mineral supplies, waste management, pollution control, energy supplies, food production.", 9, level=True,
            ms=["Water: catchment management, conservation, metering, greywater, re-use of treated effluent, aquifer recharge, sustainable urban drainage - largely cyclical already; limits in arid regions",
                "Minerals: exploiting low-grade ores with low-temperature processes (bioleaching), extending product lifespans, repair / re-use / repurpose / recycle, design for disassembly, reduced packaging; limits: dispersal, alloys, energy of collection",
                "Waste management: repair, re-use, refurbish, recycle, composting and anaerobic digestion returning nutrients, minimal landfill, energy from residual waste; EU targets on packaging, batteries, WEEE",
                "Pollution control: shift from post-production treatment to non-release - fuel desulfurisation not FGD, fuel cells / electric vehicles not combustion, industrial symbiosis (Kalundborg: waste heat, gypsum, fly ash, yeast used by neighbours); limits for legacy pollution",
                "Energy: renewables, storage, energy density technologies, low-temperature manufacturing, CHP; limits of intermittency, transport fuels",
                "Food: natural processes for nutrients (legumes, organic matter), pest control (IPM), soil biota, agri-environment schemes, IMTA aquaculture; tension with maximum yield for a growing population",
                "Land uses supporting ecosystems: urban green infrastructure, gardens, permeable surfaces, habitat in redeveloped docks / lagoons",
                "Judgement: high applicability in some sectors (water, waste), partial in others (minerals, energy for transport); needs policy support"]),
          P("State what is meant by <b>industrial symbiosis</b>.", 1, ms=["Locating industries so that the wastes of one (heat, gases, by-products) become the raw materials of another, mimicking natural cycles (eg Kalundborg eco-industrial park)"]),
      ]),

    Q("SUS-07", "circular-economy", "3.6.4.2", "379-380",
      intro="Table 1 shows the ecological footprint and biocapacity per person for four countries and the world in 2016.",
      figures=[Table(["", "Ecological footprint / gha per person", "Biocapacity / gha per person", "Human Development Index"], [["USA", "8.1", "3.6", "0.92"], ["UK", "4.4", "1.4", "0.92"], ["China", "3.6", "1.0", "0.75"], ["Bangladesh", "0.8", "0.4", "0.61"], ["World", "2.8", "1.7", "0.72"]])],
      parts=[
          P("Define <b>ecological footprint</b> and <b>biocapacity</b>.", 2,
            ms=["Ecological footprint: the area of the Earth's surface (global hectares) needed to provide the resources used by a person / population / activity and to absorb the wastes produced",
                "Biocapacity: the biological productivity of an area (forests, cropland, grazing, fisheries, built land) - its ability to supply resources and absorb wastes, expressed in global hectares"]),
          P("Explain what is meant by a <b>global hectare</b> and why it is used.", 2,
            ms=["A hectare of land / sea with the world-average biological productivity", "Biocapacities of real areas vary widely so a standard unit allows footprints and biocapacities of different places to be compared"]),
          P("Use Table 1 to calculate how many Earths would be needed if everyone lived like the average US citizen.", 1, calc=True, unit="Earths", ms=["8.1 / 1.7 = 4.8 (accept 4.7-4.8)"]),
          P("Use Table 1 to describe the relationship between development and ecological footprint, and explain the concept of Earth Overshoot Day.", 3,
            ms=["Higher HDI is associated with a larger footprint (USA 8.1 vs Bangladesh 0.8), though the UK achieves the same HDI as the USA with about half the footprint",
                "Global footprint (2.8) exceeds global biocapacity (1.7) so humanity uses resources faster than they regenerate and CO2 accumulates (overshoot)",
                "Earth Overshoot Day is the date each year when a year's worth of resources / waste absorption has been used up; it falls earlier each year (8 August in 2016)"]),
          P("Suggest <b>two</b> ways a country such as the UK could reduce its footprint without reducing its HDI.", 2, items=2,
            ms=["Renewable energy and energy conservation (carbon footprint is the largest component)", "Reduced meat consumption / food waste; local seasonal food", "Circular economy: repair, re-use, recycling; longer product lives", "Public transport, efficient buildings"]),
      ]),

    Q("SUS-08", "circular-economy", "3.6.4.2", "380-383",
      parts=[
          P("Explain what a carbon footprint should include when calculated for a car.", 3,
            ms=["All greenhouse gases expressed as CO2 equivalent (allowing for different warming strengths)", "Direct emissions from fuel combustion plus indirect: manufacture of components, maintenance items, final disposal (life-cycle analysis)",
                "A fair share of the infrastructure: roads, car parks, signals, street lighting"]),
          P("Describe what the WWF Living Planet Index measures and how it is used.", 2,
            ms=["Compares the populations of over 18 000 populations of 3700 vertebrate species (terrestrial, freshwater, marine) with 1970 levels", "Published in the Living Planet Report as a measure of the state of the planet's ecosystems / biodiversity loss over time"]),
          P("Describe how the Ol Pejeta reserve in Kenya combines commercial cattle ranching with wildlife conservation.", 5,
            ms=["Hardy, disease-resistant Boran cattle; regular tick dipping reduces ticks for wild herbivores too", "Mobile bomas (night enclosures) protect cattle from lions and leave dung that enriches soil and plant growth",
                "Electric fences keep game in and poachers out; biological corridors let animals (except rhinos) move to other reserves; problem elephants relocated", "Monitoring: radio-collared lions, drones, camera traps, track surveys; endangered species (Grevy's zebra, northern white rhino) protected",
                "Community links: ecotourism income funds health, education and water projects; local employment; cattle breeding help for local farmers"]),
      ]),

    Q("SUS-09", "circular-economy", "3.6.4", "384-389",
      intro="The Isle of Eigg (area 31 km<sup>2</sup>, population about 100) is not connected to the national grid. Table 1 shows its electricity sources.",
      figures=[Table(["Source", "Capacity / kW"], [["Hydroelectric (3 generators)", "110"], ["Solar PV", "50"], ["Wind (4 turbines)", "24"], ["Diesel generators (back-up)", "160"]])],
      parts=[
          P("Explain why Eigg uses a mix of three renewable resources rather than one, and why diesel back-up is still needed.", 3,
            ms=["Diversity: HEP (wet winters), solar (summer) and wind peak at different times so supply is more reliable - diverse systems resist change", "No single source could meet demand all year; battery storage on the island grid smooths fluctuations",
                "Calm, dry, dull periods still leave gaps so diesel generators provide security (fossil fuel use minimised, not yet eliminated)"]),
          P("Describe <b>three</b> other ways in which the Eigg community has increased its sustainability.", 3, items=3,
            ms=["Community ownership (Isle of Eigg Trust with Scottish Wildlife Trust) managing the island for people and wildlife", "Wood biomass heating; insulation such as straw-bale housing; some electric vehicles",
                "Habitat protection and creation: fencing rare plants from grazing, planting indigenous woodland (rowan, birch, willow); eagles and hen harriers nesting", "Recyclables shipped off; garden / food waste composted; low-impact food production; beach litter collection"]),
          P("Explain why small self-contained communities often find it easier to adopt sustainable lifestyles than large cities.", 2,
            ms=["Small groups can organise, agree and act quickly; decisions benefit people who see the results directly", "Resources and wastes are local and visible so feedback is immediate, unlike cities supplied from far away"]),
          P("Explain how large-scale DC electricity grids such as Desertec could increase the use of renewable energy.", 2,
            ms=["Renewable energy is abundant but geographically and temporally variable; a continental grid moves electricity from areas of surplus (desert solar, offshore wind) to areas of demand", "DC grids do not need every generator synchronised in phase as AC grids do, so coordination across many countries is easier"]),
      ]),
]

ESSAYS = [
    Essay("ESS-P2-CIRCULAR", 2,
          "Discuss the extent to which the principles of the circular economy could be used to develop sustainable lifestyles.",
          "3.6", "370-389",
          ["Definition of sustainability (Brundtland); population x per capita impact; dynamic equilibria, feedback, tipping points, diversity",
           "Principles of natural systems: renewable low-density energy, low temperatures, material cycles, non-toxic wastes; contrast with linear human systems",
           "Circular economy principles: cycling materials, renewable energy, supporting ecosystems, separation of technical and biological materials, diversity, connected systems, design for extended use and re-use, optimum production, new technologies",
           "Application to land use, water, minerals, waste, pollution, energy, food with examples (Kalundborg, Eigg, Ol Pejeta, Rio Bravo, EU initiatives, DC grids)",
           "Measuring progress: ecological footprint, biocapacity, global hectares, Earth Overshoot Day, carbon footprint, Living Planet Index",
           "Barriers: economics, competition, consumer behaviour, need for international agreement, existing infrastructure",
           "Judgement on the extent achievable"]),
    Essay("ESS-P2-NATURAL", 2,
          "Natural systems have remained sustainable over very long periods. Discuss how the features of natural systems could be copied to make human systems more sustainable.",
          "3.6.1-3.6.4", "370-379",
          ["Dynamic equilibria and negative feedback in climate, hydrological cycle and populations; positive feedback and tipping points caused by humans",
           "Energy: solar-driven, low energy density, low temperature (photosynthesis, enzymes, nitrogen fixation vs Haber process); renewable energy, heat pumps, bioleaching, fuel cells",
           "Materials: cycles, few abundant elements, biodegradable non-toxic wastes vs fossil fuels and dispersed minerals; recycling, Cradle to Cradle, industrial symbiosis",
           "Diversity and stability: rainforests / reefs vs agroecosystems; diverse energy mixes",
           "Optimum vs maximum production; supporting ecosystems in agriculture, forestry, fisheries, urban design",
           "Case studies and metrics; limits and judgement"]),
]
