"""Research methods (spec 3.7): methodologies, sampling techniques, abiotic measurement, specialist techniques, statistics.
Genn pp. 390-423.  Examined in BOTH papers."""
from gen.model import Q, P, Table, Chart, Essay

QUESTIONS = [
    # ---------------- methodology 3.7.1 ----------------
    Q("RM-01", "methodology", "3.7.1", "390-393",
      intro="A student investigated whether the number of earthworms per m<sup>2</sup> changes with distance from a hedge across an arable field.",
      parts=[
          P("Explain why systematic sampling along a transect is more appropriate than random sampling for this investigation.", 2,
            ms=["There is an environmental gradient (distance from the hedge / changing conditions) so samples must be taken at regular intervals along it to detect the change",
                "Random sampling might leave gaps / miss the pattern; systematic sampling avoids bias while covering the gradient"]),
          P("Describe how a preliminary study could be used to decide the distance between sampling sites and the number of samples at each site.", 4,
            ms=["Sample at close intervals (eg every 1 m) first and see at what spacing the variations are still detected without unnecessary data; wider intervals (eg 4 m) may miss peaks and troughs",
                "Take increasing numbers of samples at one site and calculate the running mean; the number needed is where the mean stops fluctuating / stabilises",
                "Calculate standard deviation to assess scatter: more variable data need more samples", "Test the method (extraction technique, timing) for reliability before the main study"]),
          P("Describe how earthworms could be extracted from a 0.5 m x 0.5 m sample area and give <b>two</b> limitations of the method.", 4,
            ms=["Remove surface vegetation; pour an irritant solution (dilute mustard / detergent in water) onto the area until saturated (and around it), keep adding as it infiltrates",
                "Collect worms that come to the surface for a standardised time; count / identify / weigh", "Limitations: solution may not percolate impermeable soils or reach deep worms; worms may move sideways or downwards; some may die or not respond; slow-moving worms missed"]),
      ]),

    Q("RM-02", "methodology", "3.7.1", "390-393",
      intro="Table 1 shows the running mean of moth catches as a student increased the number of nights of light-trapping at one site.",
      figures=[Table(["Number of nights", "1", "2", "4", "6", "8", "10", "12", "14"], [["Running mean catch per night", "31", "18", "24", "21", "22", "22", "21", "22"]])],
      parts=[
          P("Use Table 1 to suggest the minimum number of nights needed to obtain a reliable mean. Explain your answer.", 2,
            ms=["About 8 nights", "The running mean fluctuates widely with few samples but stabilises at 21-22 from 8 nights onwards; extra samples do not change it significantly"]),
          P("Explain why moth surveys must be carried out at standardised times and weather conditions.", 3,
            ms=["Moth activity varies with temperature, wind, rain and season (adults only fly for part of the year) so catches vary independently of population size",
                "Sampling at different conditions / times would make results not comparable", "Timing between samples should be chosen to detect the temporal variation of interest (eg weekly through the season)"]),
          P("Distinguish between <b>accuracy</b> and <b>precision</b> of measurements.", 2,
            ms=["Accuracy: how close a recorded result is to the real value", "Precision: the smallest interval between possible recorded values (eg a ruler marked in mm is more precise than one in cm)"]),
          P("Explain the importance of a null hypothesis and standardised techniques in a scientific investigation.", 3,
            ms=["A null hypothesis (eg no difference / no correlation) can be tested statistically and accepted or rejected at a stated confidence level",
                "Standardised techniques ensure results collected at different times, places or by different people are comparable", "Other variables are controlled or monitored so their effect can be assessed; allows the study to be repeated / checked (reliability)"]),
      ]),

    Q("RM-03", "methodology", "3.7.1, 3.7.2.2", "390-393, 419-420",
      intro="A group of students wants to investigate the effect of vegetation cover on rain-splash soil erosion.",
      parts=[
          P("Describe how they could carry out the investigation in the laboratory.", 5,
            ms=["Trays of the same soil (texture, compaction, organic matter, depth) with different percentage vegetation cover (eg 0, 25, 50, 75, 100% grass), replicated",
                "Same slope / gradient; simulated rain from a standard height at a standard rate and drop size (eg watering can / sprinkler) for a standard time",
                "Collect the soil splashed / washed off (eg onto a sheet or into a trough at the base), dry and weigh it",
                "Repeat each treatment several times and calculate means (and standard deviation)", "Plot soil loss against cover; statistical test (Spearman's rank / t-test) for significance"]),
          P("Give <b>three</b> variables, other than those you have standardised, that affect rain-splash erosion in the field.", 3, items=3,
            ms=["Rainfall intensity / raindrop size / height", "Soil texture, compaction, organic matter, depth", "Permeability of the material beneath", "Gradient", "Root binding"]),
          P("Explain why it is easier to obtain valid results in the laboratory than in the field, and give <b>one</b> disadvantage of laboratory studies.", 2,
            ms=["All variables except the independent variable can be standardised in the laboratory; in the field uncontrollable variables (weather) must be measured instead",
                "Laboratory conditions may not represent natural conditions so results may not apply directly to real ecosystems"]),
      ]),

    Q("RM-04", "methodology", "3.7.1", "391-393",
      parts=[
          P("Which of the following best describes a <b>representative</b> sample? Tick one box.", 1,
            mcq=["A sample taken from the most convenient location", "A sub-sample that accurately reflects the complete data set", "The largest sample that can be collected", "A sample that supports the hypothesis"], ms=["B"]),
          P("Describe how random sampling sites would be selected in an irregularly shaped meadow.", 2,
            ms=["Number all possible sampling sites (eg on a grid map)", "Select the sites using a random number generator / table; (regular shape: grid coordinates from random numbers)"]),
          P("Explain why deliberately choosing sampling sites introduces bias.", 2,
            ms=["Sites may be chosen for convenience or because they appear to support (or dismiss) the hypothesis", "So the sample does not represent the whole area and conclusions are invalid"]),
      ]),

    # ---------------- sampling 3.7.2.1-3.7.2.2 ----------------
    Q("RM-05", "sampling", "3.7.2.1", "394-395, 401-402",
      intro="A student used 0.5 m x 0.5 m grid quadrats to survey ground flora in two meadows, one grazed and one ungrazed. Table 1 shows the results for the grazed meadow (10 quadrats).",
      figures=[Table(["Species", "Number of individuals"], [["Ribwort plantain", "48"], ["Perennial ryegrass", "120"], ["White clover", "36"], ["Daisy", "24"], ["Creeping buttercup", "12"]])],
      parts=[
          P("Explain why a 0.5 m x 0.5 m quadrat was chosen rather than a 10 cm x 10 cm or 100 m x 100 m quadrat.", 2,
            ms=["Quadrat size depends on the size / spacing of the organisms: 0.5 m x 0.5 m is typical for ground flora", "10 cm x 10 cm is for lichens (too small to contain a representative sample of plants); 100 m x 100 m is for trees (impractical, too much work)"]),
          P("Calculate Simpson's Index of Biodiversity (D) for the grazed meadow using D = N(N-1) / &Sigma;n(n-1). Show your working.", 3, calc=True, unit="",
            ms=["N = 240; N(N-1) = 240 x 239 = 57 360", "&Sigma;n(n-1) = 48x47 + 120x119 + 36x35 + 24x23 + 12x11 = 2256 + 14280 + 1260 + 552 + 132 = 18 480", "D = 57 360 / 18 480 = 3.10 (accept 3.1)"]),
          P("The ungrazed meadow had D = 1.8 with the same number of species. Explain what this shows.", 2,
            ms=["Lower D means lower biodiversity: the ungrazed meadow is dominated by one or a few species (eg tall grass) with the others rare (less even)",
                "Grazing (plagioclimax management) prevents dominance by vigorous species so abundance is more evenly spread"]),
          P("Explain why a point quadrat would be better than a frame quadrat in tall vegetation.", 2,
            ms=["A frame quadrat flattens tall plants, making percentage cover estimates inaccurate and hiding shorter plants", "Point quadrat pins are lowered through the vegetation; each touch counts (10 pins = 10% each) without flattening"]),
          P("Give <b>one</b> limitation of using the DAFOR abundance scale.", 1, ms=["Subjective judgement varies between recorders; results are not quantitative so statistical analysis is not possible (but quick for many areas)"]),
      ]),

    Q("RM-06", "sampling", "3.7.2.1", "395-396, 415-416",
      intro="A student compared the invertebrates in a stream above and below a sewage outfall using kick sampling.",
      parts=[
          P("Describe how kick sampling is carried out so that the samples from the two sites are comparable.", 3,
            ms=["Net held with its straight edge on the river bed facing the current (open to the flow)", "The bed in front is disturbed by kicking / scraping a boot for a standard number of kicks and time (eg 30 s)",
                "Same substrate type, water depth and flow rate at both sites; same net mesh; repeat samples; invertebrates identified with a key and counted"]),
          P("Give <b>three</b> limitations of kick sampling.", 3, items=3,
            ms=["Difficult to standardise the vigour / area kicked", "Buried organisms or those fixed to stones are not dislodged", "Some organisms swim and avoid the net", "Flow rate varies and affects capture", "Fragile organisms destroyed"]),
          P("Explain how a Surber sampler improves on kick sampling.", 2,
            ms=["A fixed area of bed is enclosed by a frame so the sampled area is standardised; side nets reduce escapes", "But only works in fast enough flow and is hard to set on rough substrates / deep water"]),
          P("Explain why the invertebrates found give a better indication of long-term sewage pollution than a single measurement of dissolved oxygen.", 2,
            ms=["Pollutant / oxygen levels fluctuate (eg with flow, time of day) so one reading may miss a pollution event", "Sensitive taxa (stonefly, mayfly larvae) disappear and tolerant ones (midge larvae, hoglouse) remain, integrating conditions over weeks / months (biotic index)"]),
      ]),

    Q("RM-07", "sampling", "3.7.2.1", "397-399",
      parts=[
          P("Complete Table 1 to show a suitable sampling technique for each group of organisms and one limitation of the technique.", 6,
            table=Table(["Organisms", "Technique", "One limitation"], [["Invertebrates active on the ground surface at night", "", ""], ["Invertebrates living in leaf litter", "", ""], ["Invertebrates on tree branches", "", ""]], blank=True, col_widths=[5, 4, 6]),
            ms=["Ground surface: pitfall trap (container sunk level with the surface, cover, checked after 24 h) - only mobile surface animals; trapped predators eat others; preservative attracts / repels; escapes",
                "Leaf litter: Tullgren funnel (sample on mesh under a light; heat / light drive invertebrates down into a container for a standard time) - only species repelled by heat / light; some die or stop moving; large ones cannot pass the mesh",
                "Branches: beating tray (branch beaten a set number of times over a sheet) - hard to standardise vigour; some species not dislodged / fly away; high branches unreachable"]),
          P("Explain why a light trap cannot be used to prove that a moth species is absent from a site.", 2,
            ms=["Moths only fly as adults for part of the year and activity depends on weather / season, so a species may be present but not caught", "Brightness / wavelength of the lamp affects attractiveness so catches vary between traps"]),
          P("Explain how a motor-driven suction sampler can give a population density, whereas a pooter cannot.", 2,
            ms=["The area of ground covered by the suction pipe is known so invertebrates per m^2 can be calculated", "A pooter is only a handling / collection device for individuals already found, not a sampling method"]),
      ]),

    Q("RM-08", "sampling", "3.7.2.1", "401-402",
      intro="A student estimated the population of ground beetles in a field using the Lincoln Index. 60 beetles were caught in pitfall traps, marked with a spot of paint and released. Three days later 45 beetles were caught, of which 9 were marked.",
      parts=[
          P("Calculate the estimated population size.", 2, calc=True, unit="beetles", ms=["(60 x 45) / 9", "= 300"]),
          P("State <b>four</b> assumptions of the Lincoln Index method.", 4, items=4,
            ms=["Marked individuals mix freely / randomly with the rest of the population", "No births, deaths, immigration or emigration between samples", "Marking does not affect survival or behaviour (eg make them more visible to predators)",
                "Marks do not wear off / fall off", "All individuals have the same chance of being caught (traps do not attract or repel marked animals)"]),
          P("Explain how the estimate would be affected if the paint made the beetles more likely to be eaten by birds.", 2,
            ms=["Fewer marked beetles would survive to be recaptured", "So the proportion marked in the second sample would be too low and the population would be overestimated"]),
          P("Suggest why the second sample was taken after three days rather than the next day or after a month.", 2,
            ms=["Enough time for marked beetles to mix with the population", "Not so long that births / deaths / migration or loss of marks change the population"]),
      ]),

    Q("RM-09", "sampling", "3.7.2.1", "407-410, 413",
      parts=[
          P("Explain why electronic meters must be calibrated before use and describe how a pH meter is calibrated.", 3,
            ms=["Readings drift so they may not be accurate; calibration adjusts the meter to match a known standard so results are accurate and comparable between meters / occasions",
                "pH meter placed in buffer solutions of known pH (eg 4, 7, 10) and adjusted to read correctly", "If a meter cannot be adjusted, record the percentage error and correct the results"]),
          P("Describe how wind velocity measurements with an anemometer should be standardised.", 3,
            ms=["Same height above the ground", "No obstacles to air flow; impeller type facing into the wind", "Axis of rotation horizontal (impeller) or vertical (cup); same time period / averaging"]),
          P("Describe how a whirling hygrometer is used to measure humidity.", 2,
            ms=["Two thermometers, one with a wet bulb, are spun until the wet bulb stops cooling", "Evaporation cools the wet bulb more when humidity is low; the temperature difference is compared with a table to find humidity"]),
          P("Describe <b>two</b> methods of measuring nitrate concentration in water.", 2, items=2,
            ms=["Test strips with reagent bands compared with a colour chart (semi-quantitative)", "Electronic colourimeter: reagent added and colour intensity measured at a specific wavelength", "Ion-selective electrode measuring electrode potential (other ions can interfere)"]),
      ]),

    Q("RM-10", "sampling", "3.7.2.1-3.7.2.2", "410-413, 417",
      parts=[
          P("Describe how soil texture is determined using a stack of sieves.", 3,
            ms=["Sieves assembled with the coarsest mesh on top; a dried, crushed soil sample is placed in the top sieve", "Stack shaken (about 2 minutes) until no more particles pass; each fraction weighed",
                "Percentages of sand (0.02-2 mm), silt (0.002-0.02 mm) and clay (base pan, below 0.002 mm) calculated; material over 2 mm (stones, twigs) is not soil; plotted on a soil triangle"]),
          P("Explain why a soil auger gives a more representative sample than a trowel.", 2,
            ms=["Auger collects a core of known cross-sectional area and depth", "So samples from different sites are directly comparable (also needed for bulk density = dry mass / volume)"]),
          P("Explain why the organic matter content will be overestimated if a soil sample is heated above 550 &deg;C.", 2,
            ms=["Minerals such as calcium carbonate break down releasing carbon dioxide", "So mass is lost that is not organic matter"]),
          P("Describe how a turbidimeter measures water turbidity and explain how quantitative results are obtained.", 3,
            ms=["A beam of light passes through the sample in a dark chamber; a light sensor at 90&deg; measures light scattered by suspended particles - more turbid, more scatter",
                "Standardise bulb brightness / colour, distance and container", "A calibration curve is produced using samples with known amounts of suspended matter so readings convert to concentrations; Secchi discs / turbidity bottles give only semi-quantitative results"]),
      ]),

    Q("RM-11", "sampling", "3.7.2.2", "416-418",
      intro="A student investigated the effect of pH on the germination of cress seeds.",
      parts=[
          P("Explain why cress is a suitable species for this investigation but the results may not apply directly to natural ecosystems.", 2,
            ms=["Small seeds, genetically uniform, high and rapid germination rate so results are quick and reliable", "Wild species have different ranges of tolerance so cress results cannot be applied directly"]),
          P("Describe how the student should decide the range of pH values to test.", 2,
            ms=["Preliminary study with widely spaced pH values to find where germination occurs", "Final range from below the lowest pH giving germination to above the highest, with closer intervals"]),
          P("Give <b>three</b> variables that should be standardised and explain how long the experiment should continue.", 4,
            ms=["Temperature (constant, natural germination temperature)", "Light, water volume, number of seeds per dish, seed source", "Growth medium (filter paper; soil would alter pH); nutrients not needed for germination",
                "Continue until it is clear that ungerminated seeds will not germinate, so that a delay in germination is not mistaken for failure"]),
          P("The student wants to compare the effect of nutrient concentration on the growth of duckweed. Explain why leaf area is a better measure of growth than fresh mass.", 2,
            ms=["Surface water affects fresh mass and drying damages the plants; dry mass requires killing the plants so the same plants cannot be re-measured", "Leaf area is a reasonable estimate of biomass that allows repeated measurement of the same plants over time"]),
      ]),

    # ---------------- stats / specialist 3.7.2.3 ----------------
    Q("RM-12", "stats", "3.7.2.3", "402-407",
      intro="Table 1 lists some techniques used in ecological monitoring.",
      parts=[
          P("Complete Table 1 by giving one application and one limitation of each technique.", 6,
            table=Table(["Technique", "Application", "Limitation"], [["Image databases of unique markings", "", ""], ["eDNA sampling", "", ""], ["Geolocator tags", "", ""]], blank=True, col_widths=[4.5, 5.5, 5]),
            ms=["Image databases: identifying individuals (tiger stripes, whale shark spots, dolphin fins) to find territory size, movements, lifespan, social groups - few species have unique recognisable features",
                "eDNA: detecting the presence of a species from DNA shed into water (great crested newt, invasive carp) - shows presence not abundance; contamination / DNA transport by water",
                "Geolocator tags: tracking small birds on migration where transmitters are too heavy - only record light and time so position is approximate; animal must be recaptured to download data"]),
          P("Explain how satellite radar (microwave) sensors are useful for monitoring oil pollution and sea conditions.", 2,
            ms=["Microwaves emitted by the satellite reflect off the surface giving data on wave height, wind velocity, sea surface altitude and oil slicks (which smooth the surface)", "Microwaves pass through cloud so monitoring is not interrupted by weather"]),
          P("Give <b>two</b> types of indirect evidence of an animal's presence and the information each can give.", 2, items=2,
            ms=["Droppings: diet, gender, territory size", "Owl pellets: diet", "Feeding marks (chewed hazel nuts - dormouse), tracks / footprints, nests / burrows, scratching posts (territory)"]),
      ]),

    Q("RM-13", "stats", "3.7.2.3", "420-423",
      intro="Table 1 shows the mean dry mass of wheat plants grown with two fertiliser treatments (10 replicates each).",
      figures=[Table(["Treatment", "Mean dry mass / g", "Standard deviation / g"], [["Organic manure", "14.2", "3.9"], ["Inorganic NPK fertiliser", "16.1", "4.1"]])],
      parts=[
          P("Explain what the standard deviation values tell you about the data.", 2,
            ms=["The scatter / variability of results around each mean; about 68% of values lie within one SD of the mean", "The SDs are large relative to the difference in means (1.9 g) so the ranges overlap greatly"]),
          P("Name the statistical test that should be used to decide whether the difference between the two means is significant, and justify your choice.", 2,
            ms=["t-test", "Comparing two means of measured (continuous) data"]),
          P("The test gave a probability p = 0.30. State what this means and what the student should conclude.", 2,
            ms=["There is a 30% probability that the difference occurred by random chance", "Above the 0.05 (5%) level so the difference is not significant; the null hypothesis (no difference) is accepted"]),
          P("Explain why a statistically significant correlation does not prove a causal relationship.", 2,
            ms=["Two correlated variables may both be caused by a third variable that was not investigated", "Significance only shows the result is unlikely to be chance; a mechanism / controlled experiment is needed for causation"]),
          P("Suggest how the student could increase the chance of detecting a real difference if one exists.", 2,
            ms=["Increase the number of replicates (reduces the effect of variability)", "Standardise other variables (soil, water, light) more closely to reduce scatter"]),
      ]),

    Q("RM-14", "stats", "3.7.2.3", "422-423",
      parts=[
          P("For each of the following investigations, name the most appropriate statistical test.", 4,
            labels=["Whether noise level decreases as distance from a road increases", "Whether the numbers of dormice differ between woodlands with different management", "Whether mean dissolved oxygen differs between two streams", "Whether crop yield increases with fertiliser application (ranked data)"],
            ms=["Spearman's rank correlation coefficient", "Chi-squared test (frequencies / counts in categories)", "t-test (two means of measured data)", "Spearman's rank correlation coefficient"]),
          P("Explain why the chi-squared test cannot be used for data such as wind speed or plant height.", 1,
            ms=["Chi-squared compares frequencies / counts in categories; it cannot be used for continuously variable measured data"]),
          P("A Spearman's rank test on 12 pairs of data gave r<sub>s</sub> = -0.72. The critical value at p = 0.05 for n = 12 is 0.59. Explain what can be concluded.", 3,
            ms=["The value (ignoring sign) exceeds the critical value so the correlation is significant at the 5% level", "The negative sign shows a negative correlation: one variable decreases as the other increases",
                "There is less than a 5% probability the correlation arose by chance; reject the null hypothesis (but correlation is not proof of causation)"]),
          P("Explain the purpose of error bars on a graph of mean values.", 2,
            ms=["Show the standard deviation / range of the original values around each mean", "If the bars of two means overlap greatly the difference is probably not significant; little overlap suggests a significant difference"]),
      ]),

    Q("RM-15", "stats", "3.7.2.3", "404-406",
      parts=[
          P("Describe how DNA databases are used to control the illegal trade in tropical timber and ivory.", 3,
            ms=["Each regional population has its own unique gene pool / DNA profile", "DNA from seized timber or ivory is compared with the database of regional populations",
                "This identifies where the material came from, showing whether it was legally harvested and where poaching occurs"]),
          P("Explain the difference between radio / GPS tracking and acoustic tracking and state when each is used.", 2,
            ms=["Radio / GPS transmitters use radio waves - work in air and fresh water, giving positions (GPS stores or transmits location)", "Radio waves do not travel through seawater so acoustic transmitters (sound) are used for marine animals, giving real-time positions"]),
          P("Give <b>three</b> types of carrier system used to move sensors to study areas and one advantage of drones for ecological monitoring.", 3,
            ms=["Drones / ROVs, AUVs (eg Autosub), balloons, aircraft, satellites, animals (tags)", "Drones: cheap, low disturbance, high-resolution images of areas hard to reach (cliffs, canopy, ice), repeated surveys; infrared cameras detect animals at night"]),
          P("Explain how motion-sensitive cameras and CCTV reduce disturbance to wildlife compared with direct observation.", 2,
            ms=["Cameras record automatically (visible light by day, infrared at night) without researchers being present", "So animals behave naturally and nests are not deserted; monitoring continues 24 hours"]),
      ]),
]

ESSAYS = []
