"""Key terms and definitions for the definitions drill (Question 1 in every real paper is a
5-mark 'complete the table of terms and definitions').  Grouped by subtopic slug; the book
pages are those of the subtopic in bank/topics.py unless given here."""

TERMS = {
    # ---------------- Paper 1: physical environment ----------------
    "atm-energy": [
        ("Dynamic equilibrium", "A state in which opposing processes (eg gases added and removed) balance so the overall composition stays constant although the rates vary"),
        ("Albedo", "The proportion of incoming solar radiation reflected by a surface (or the whole planet); high albedo surfaces such as ice reflect most light"),
        ("Greenhouse gas", "Any gas that absorbs infrared radiation better than the average for the atmosphere, eg carbon dioxide, water vapour, methane"),
        ("Troposphere", "The lowest layer of the atmosphere, where weather occurs and most greenhouse-gas warming takes place"),
        ("Stratosphere", "The layer above the troposphere containing the ozone layer, which absorbs most ultraviolet light"),
        ("Ozone layer", "A dispersed layer of monatomic, diatomic and triatomic oxygen in the stratosphere that absorbs ultraviolet light in a dynamic equilibrium of reactions"),
    ],
    "climate-change": [
        ("Enhanced greenhouse effect", "The extra warming caused by human activities increasing the concentration of gases that absorb infrared radiation"),
        ("Global warming potential", "The warming effect of a gas over a given period relative to the same mass of carbon dioxide"),
        ("Residence time", "The average time a molecule of a substance remains in a reservoir such as the atmosphere"),
        ("Positive feedback", "A mechanism in which a change causes further change in the same direction, eg melting ice lowering albedo and causing more warming"),
        ("Negative feedback", "A mechanism that resists change and returns a system towards its original state, eg warming increasing cloud cover and albedo"),
        ("Tipping point", "The point at which a change becomes self-sustaining and a system moves to a new equilibrium that cannot easily be reversed"),
        ("Proxy data", "Indirect evidence of past conditions, eg tree rings, ice cores, isotope ratios, used where direct measurements do not exist"),
        ("Thermohaline circulation", "Global ocean currents driven by differences in water density caused by temperature and salinity"),
        ("Carbon sequestration", "The removal of carbon dioxide from the atmosphere and its long-term storage, eg in growing forests, soils or geological formations"),
    ],
    "ozone": [
        ("Ozone depletion", "The reduction in stratospheric ozone caused mainly by chlorine and bromine released from CFCs and halons"),
        ("CFC (chlorofluorocarbon)", "A very stable, non-toxic, non-flammable synthetic gas used in aerosols, refrigerants and foams that releases chlorine in the stratosphere"),
        ("Dobson unit", "The unit used to measure the total amount of ozone in a column of atmosphere"),
        ("Montreal Protocol", "The 1987 international agreement that phased out the production of ozone-depleting substances"),
        ("Rowland-Molina hypothesis", "The 1974 proposal that CFCs would break down in the stratosphere and the chlorine released would catalyse the destruction of ozone"),
        ("Photochemical reaction", "A chemical reaction driven by light, eg the breakdown of CFCs and of ozone by ultraviolet light"),
    ],
    "hydro-cycle": [
        ("Hydrological cycle", "The continuous movement of water between the oceans, atmosphere and land by evaporation, condensation, precipitation and flow"),
        ("Aquifer", "A body of permeable rock that holds groundwater, eg chalk or sandstone, from which water can be abstracted"),
        ("Residence time (water)", "The average time water stays in a reservoir such as the atmosphere, a lake or an aquifer"),
        ("Infiltration", "The movement of water from the surface into the soil and rock"),
        ("Evapotranspiration", "The combined loss of water to the atmosphere by evaporation from surfaces and transpiration from plants"),
        ("Unsustainable exploitation", "Abstracting water from a river or aquifer faster than it is replaced by recharge"),
        ("Saltwater incursion", "The movement of seawater into a coastal aquifer when over-abstraction lowers the water table"),
    ],
    "hydro-management": [
        ("Potable water", "Water that is safe to drink: free of pathogens, with toxins at acceptable levels, and that looks, smells and tastes acceptable"),
        ("Flocculation", "The addition of chemicals such as aluminium sulfate that neutralise the charges on clay particles so they clump together and settle"),
        ("Artificial recharge", "Pumping or diverting surplus surface water underground to refill an aquifer"),
        ("Inter-basin transfer", "Moving water by pipe or canal from a river catchment with a surplus to one with a shortage"),
        ("Estuary barrage", "A dam across an estuary that creates a freshwater reservoir"),
        ("Xeriscaping", "Landscaping with drought-adapted plants so that little or no watering is needed"),
        ("Grey water", "Water that has already been used, eg from baths and showers, but is clean enough to re-use for flushing toilets or watering gardens"),
        ("Desalination", "The removal of salt from seawater by reverse osmosis or distillation to produce fresh water; very energy-intensive"),
    ],
    "minerals": [
        ("Ore", "A rock containing a metal or mineral in high enough concentration to be worth extracting"),
        ("Cut-off ore grade (COOG)", "The lowest concentration of mineral in a rock that can be exploited economically at current prices and technology"),
        ("Reserve", "The amount of a mineral that can be exploited economically with existing technology"),
        ("Resource", "The total amount of a mineral in the Earth's crust, including deposits that cannot currently be exploited"),
        ("Lasky's principle", "As ore grade falls arithmetically, the amount of ore available increases geometrically"),
        ("Hydrothermal deposit", "A mineral deposit formed when hot water carrying dissolved minerals cooled in cracks in the rock"),
        ("Bioleaching", "The use of bacteria to extract metals from low-grade ores by dissolving them at low temperature"),
        ("Phytomining", "Growing plants that absorb metals from the soil, then harvesting and burning them to recover the metal"),
        ("Overburden", "The rock and soil that must be removed to reach a mineral deposit in open-cast mining"),
    ],
    "biogeochem": [
        ("Biogeochemical cycle", "The movement of an element between living organisms, the atmosphere, water and rock through interconnected biological and physical processes"),
        ("Nitrogen fixation", "The conversion of nitrogen gas into ammonium or nitrate by bacteria (eg Rhizobium), lightning or the Haber process"),
        ("Nitrification", "The conversion of ammonium to nitrite and nitrate by aerobic bacteria in the soil"),
        ("Denitrification", "The conversion of nitrate to nitrogen gas by bacteria in anaerobic conditions, eg waterlogged soil"),
        ("Decomposition", "The breakdown of dead organic matter by microbes and detritivores, releasing carbon dioxide and nutrients"),
        ("Photosynthesis", "The process by which plants and algae use light energy to convert carbon dioxide and water into carbohydrates, releasing oxygen"),
        ("Haber process", "The industrial fixation of nitrogen using high temperature and pressure and fossil-fuel energy to make ammonia for fertiliser"),
        ("Mycorrhizae", "Fungi associated with plant roots that increase the uptake of phosphate and other nutrients"),
    ],
    "soils": [
        ("Soil texture", "The proportions of sand, silt and clay particles in a soil"),
        ("Soil structure", "The way soil particles are grouped into aggregates (peds), affecting drainage, aeration and root growth"),
        ("Humus", "Decomposed organic matter in soil that holds water and nutrients and binds particles together"),
        ("Cation exchange capacity", "The ability of clay and humus to hold positively charged nutrient ions and release them to plant roots"),
        ("Field capacity", "The amount of water a soil holds after excess water has drained away by gravity"),
        ("Contour ploughing", "Ploughing across a slope rather than up and down it so furrows hold water and reduce runoff and erosion"),
        ("Salinisation", "The build-up of salts in soil when irrigation water evaporates, reducing fertility"),
        ("Soil erosion", "The removal of soil by wind or water faster than it is formed, often after vegetation cover is lost"),
        ("Leaching", "The washing of soluble nutrients down through the soil by percolating water"),
    ],
    # ---------------- Paper 1: energy ----------------
    "energy-features": [
        ("Energy density", "The amount of energy stored per unit mass or volume of a resource"),
        ("Renewable resource", "A resource that is naturally replaced as fast as it is used, so it will not run out if managed sustainably"),
        ("Non-renewable resource", "A resource that is not replaced on a human timescale, so its use depletes the stock"),
        ("Intermittency", "Variation in the availability of an energy resource over time, eg solar power stopping at night"),
        ("Locational constraint", "A feature of a resource that limits where it can be exploited, eg wind speed, tidal range, geothermal heat"),
        ("Embodied energy", "The energy used to extract, manufacture and install the equipment needed to harness a resource"),
        ("Base load", "The minimum continuous electricity demand that must always be met"),
        ("Energy security", "The ability of a country to obtain reliable supplies of energy at an acceptable price"),
    ],
    "fossil-nuclear": [
        ("Fossil fuel", "A fuel formed from the remains of organisms buried and altered over millions of years: coal, oil and natural gas"),
        ("Fracking", "Hydraulic fracturing: pumping water, sand and chemicals at high pressure into rock to release trapped oil or gas"),
        ("Carbon capture and storage", "Removing carbon dioxide from power-station exhaust gases and storing it, eg in depleted oil fields"),
        ("Nuclear fission", "The splitting of heavy atomic nuclei such as uranium-235, releasing large amounts of energy"),
        ("Nuclear fusion", "The joining of light nuclei such as hydrogen isotopes at very high temperatures, releasing energy; not yet commercial"),
        ("Breeder reactor", "A reactor that converts non-fissile material (eg uranium-238 or thorium) into fissile fuel, greatly extending fuel supplies"),
        ("Secondary / tertiary recovery", "Techniques such as water or gas injection and steam or solvents that increase the proportion of oil recovered from a reservoir"),
    ],
    "renewables": [
        ("Photovoltaic cell", "A device that converts light directly into electricity when photons dislodge electrons"),
        ("Photothermal panel", "A solar panel that absorbs sunlight to heat water or another fluid"),
        ("Concentrating solar power", "Using parabolic reflectors to focus sunlight, heating a fluid to drive a steam turbine"),
        ("Heat pump", "A device that moves low-temperature heat from the ground or air into a building using a compressor and refrigerant"),
        ("Tidal range", "The vertical difference between high and low tide; large ranges are needed for tidal barrages"),
        ("Biofuel", "A fuel produced from recently living biomass, eg biodiesel, bioethanol, biogas, wood"),
        ("Anaerobic digestion", "The breakdown of organic waste by microbes without oxygen, producing methane-rich biogas"),
        ("Geothermal energy", "Heat from within the Earth used directly or to generate electricity"),
    ],
    "energy-storage": [
        ("Pumped-storage HEP", "Using surplus electricity to pump water uphill, then releasing it through turbines at peak demand"),
        ("Peak shaving", "Meeting short periods of very high demand from stored energy rather than extra generating capacity"),
        ("Fuel cell", "A device that combines hydrogen and oxygen to produce electricity and water without combustion"),
        ("Electrolysis", "Using electricity to split water into hydrogen and oxygen"),
        ("Power-to-gas", "Converting surplus electricity into hydrogen or methane that can be stored in the gas grid"),
        ("Vehicle-to-grid", "Using the batteries of parked electric vehicles as distributed storage for the electricity grid"),
        ("Thermal store", "An insulated mass of water, sand, concrete or molten salt that stores heat for later use"),
    ],
    "energy-conservation": [
        ("U-value", "A measure of how much heat passes through a material; a lower U-value means better insulation"),
        ("Thermal mass", "The ability of dense building materials to absorb and slowly release heat, evening out temperature changes"),
        ("Combined heat and power (CHP)", "Generating electricity and using the waste heat for heating, greatly increasing overall efficiency"),
        ("Regenerative braking", "Recovering the kinetic energy of a vehicle as electricity when it slows down"),
        ("Passive solar design", "Designing buildings to be heated by sunlight without active equipment, eg south-facing glazing"),
        ("Smart grid", "An electricity network using ICT to match supply and demand and reduce waste"),
        ("Energy efficiency", "The proportion of energy input that is converted into useful output"),
    ],
    # ---------------- Paper 1: pollution ----------------
    "pollutant-properties": [
        ("Pollutant", "A substance or form of energy released by human activity that causes harm in the environment"),
        ("Persistence", "The length of time a pollutant remains in the environment before being broken down"),
        ("Bioaccumulation", "The build-up of a persistent, liposoluble pollutant within the body of an organism over its lifetime"),
        ("Biomagnification", "The increase in concentration of a pollutant at each successive trophic level of a food chain"),
        ("Liposolubility", "The ability of a substance to dissolve in fats, causing it to be stored in fatty tissue"),
        ("Synergism", "When two pollutants together have a greater effect than the sum of their separate effects"),
        ("Secondary pollutant", "A pollutant formed by reactions between primary pollutants in the environment, eg ozone, acid rain"),
        ("LD50", "The dose of a substance that kills 50% of a test population"),
        ("Mutagen / carcinogen / teratogen", "Substances that cause mutations, cancers or birth defects respectively; there is no safe dose"),
        ("Temperature inversion", "A layer of warm air above cooler air that traps pollutants near the ground"),
    ],
    "pollution-control": [
        ("Critical Pathway Analysis", "Predicting the routes a pollutant will take through the environment to identify where it may concentrate and where to monitor"),
        ("Critical Group Monitoring", "Monitoring the exposure of the people most at risk from a pollutant because of their lifestyle; if their risk is acceptable everyone else's is lower"),
        ("Polluter pays principle", "The organisation or person responsible for pollution must pay for the damage or its prevention"),
        ("Precautionary principle", "A waste is assumed to cause harm until research shows it is unlikely to, so it is controlled before release"),
        ("ALARA", "As Low As Reasonably Achievable - the standard to which emissions should be reduced"),
        ("BATNEEC", "Best Available Technology Not Entailing Excessive Cost - the equipment chosen to achieve ALARA"),
        ("Post-release remediation", "Cleaning up a pollutant after it has been released, eg oil-spill booms and skimmers"),
    ],
    "air-pollution": [
        ("Particulate matter (PM10)", "Solid particles suspended in the air less than 10 micrometres in diameter, small enough to be inhaled"),
        ("Smog", "A mixture of smoke and fog, or a photochemical smog formed from vehicle exhaust in sunlight"),
        ("Acid rain", "Precipitation with a pH below about 5.6 caused by sulfur dioxide and nitrogen oxides forming acids"),
        ("Flue-gas desulfurisation", "Removing sulfur dioxide from power-station exhaust by reacting it with lime or limestone"),
        ("Catalytic converter", "A device in a vehicle exhaust that converts carbon monoxide, nitrogen oxides and hydrocarbons into carbon dioxide, nitrogen and water"),
        ("Electrostatic precipitator", "A device that removes smoke particles by giving them an electric charge and attracting them to plates"),
        ("Photochemical smog", "Smog formed when sunlight causes reactions between nitrogen oxides and hydrocarbons, producing ozone and PANs"),
        ("Tropospheric ozone", "Ozone at ground level, a secondary pollutant that damages lungs and plants"),
    ],
    "water-pollution": [
        ("Thermal pollution", "The release of heated water, eg from power-station cooling, which lowers dissolved oxygen and alters aquatic communities"),
        ("Dissolved oxygen", "The amount of oxygen gas dissolved in water, essential for aquatic animals; lower in warm water"),
        ("Oil dispersant", "A chemical that breaks oil into small droplets so it disperses in the water, which may increase toxicity"),
        ("Bioremediation", "Using microbes to break down pollutants such as oil into harmless products"),
        ("Bund wall", "A wall around an oil storage tank that contains any leak"),
        ("Ballast water", "Water carried in ship tanks for stability; discharging it can release oil or introduced species"),
    ],
    "pesticides": [
        ("Pesticide", "A chemical used to kill organisms that damage crops or livestock: insecticides, herbicides, fungicides"),
        ("Specificity", "The range of organisms a pesticide affects; a specific pesticide harms only the target group"),
        ("Systemic pesticide", "A pesticide absorbed and transported through the plant so pests that feed on it are poisoned"),
        ("Contact pesticide", "A pesticide that acts when it touches the pest or the surface the pest lands on"),
        ("Organochlorine", "A persistent, liposoluble group of insecticides such as DDT that bioaccumulate and biomagnify"),
        ("Neonicotinoid", "A systemic, water-soluble insecticide similar to nicotine, toxic to insects including bees"),
        ("Integrated pest management", "Combining cultural, biological and chemical control to minimise pesticide use"),
    ],
    "nutrient-pollution": [
        ("Eutrophication", "Nutrient enrichment of water causing algal blooms, shading, deoxygenation and loss of species"),
        ("Deoxygenation", "The removal of dissolved oxygen from water by the respiration of microbes decomposing organic matter"),
        ("Biochemical oxygen demand (BOD)", "The amount of oxygen used by microbes breaking down organic matter in a water sample; a measure of organic pollution"),
        ("Activated sludge", "Aerated sewage in which bacteria and protozoa break down organic matter during secondary treatment"),
        ("Tertiary treatment", "Extra sewage treatment that removes nutrients such as phosphate (eg with iron(III) sulfate) or nitrate"),
        ("Nitrate Vulnerable Zone", "An area where nitrate use is restricted because water supplies are at risk of nitrate pollution"),
        ("Acid mine drainage", "Acidic, metal-rich water produced when sulfide minerals in mine waste are oxidised"),
        ("Methaemoglobinaemia", "'Blue baby syndrome', caused by nitrite from nitrate reducing the ability of blood to carry oxygen"),
    ],
    "heavy-metals": [
        ("Heavy metal", "A dense, toxic metal such as lead, mercury or cadmium that persists in the environment"),
        ("Neurotoxin", "A substance that damages the nervous system, eg lead and methyl mercury"),
        ("Methyl mercury", "The organic, liposoluble form of mercury produced by anaerobic microbes that biomagnifies in food chains"),
        ("Minamata disease", "Neurological poisoning of people who ate fish contaminated with methyl mercury discharged into Minamata Bay, Japan"),
        ("Tetraethyl lead", "The lead compound formerly added to petrol as an anti-knock agent"),
        ("Ion exchange", "A treatment that removes dissolved metal ions from effluent by swapping them for harmless ions on a resin"),
    ],
    "solid-waste": [
        ("Landfill", "Disposal of solid waste by burying it, ideally in a lined, capped site with leachate and gas collection"),
        ("Leachate", "Liquid that drains from a landfill site carrying dissolved and suspended pollutants"),
        ("Incineration", "Burning waste at high temperature to reduce its volume, often recovering energy"),
        ("Encapsulation", "Mixing hazardous waste with cement or glass to immobilise it"),
        ("Vitrification", "Converting high-level radioactive waste into a stable glass for long-term storage"),
        ("Composting", "Aerobic decomposition of organic waste to produce a soil conditioner"),
        ("Asbestos", "A fibrous mineral whose inhaled fibres cause asbestosis and mesothelioma"),
    ],
    "noise": [
        ("Decibel (dB)", "The logarithmic unit of sound intensity; 10 dB more is ten times the intensity"),
        ("dBA", "Decibels weighted to the frequencies the human ear hears most, used for noise measurement"),
        ("Leq", "The equivalent continuous sound level - the steady level with the same energy as a fluctuating noise over a period"),
        ("Noise contour", "A line on a map joining points with the same noise level, eg 57 dB Leq around an airport"),
        ("Bypass ratio", "In a jet engine, the ratio of air passing around the core to air passing through it; high ratios are quieter"),
        ("Acoustic baffle", "A wall, mound or fence that blocks or absorbs sound between a source and residents"),
        ("Bubble curtain", "A screen of rising bubbles around underwater piling that absorbs sound to protect marine mammals"),
    ],
    "radiation": [
        ("Ionising radiation", "Radiation with enough energy to remove electrons from atoms, producing free radicals that damage DNA"),
        ("Half-life", "The time taken for half the atoms of a radioactive isotope to decay"),
        ("Alpha, beta, gamma", "Radiation types: alpha (helium nuclei, weakly penetrating but very damaging inside the body), beta (electrons), gamma (electromagnetic, very penetrating)"),
        ("Gray (Gy)", "The unit of absorbed dose: one joule of radiation energy absorbed per kilogram"),
        ("Sievert (Sv)", "The unit of effective dose, allowing for the different biological effects of radiation types"),
        ("Contamination", "Radioactive material on or inside a person or object, continuing to expose them"),
        ("Somatic / gonadic effect", "Damage to body cells (eg cancer) / damage to sex cells that can be inherited"),
        ("Radon", "A naturally occurring radioactive gas from granite that gives about half of the average radiation dose"),
    ],
    # ---------------- research methods ----------------
    "methodology": [
        ("Accuracy", "How close a measured value is to the true value"),
        ("Precision", "The smallest interval between possible recorded results; the fineness of a measurement"),
        ("Reliability", "The consistency of results when a method is repeated"),
        ("Validity", "Whether a study measures what it claims to and its conclusions are justified by precise, accurate, reliable data"),
        ("Representative sample", "A sub-sample that accurately reflects the whole population or area"),
        ("Null hypothesis", "The statement that there is no difference or relationship, which a statistical test attempts to reject"),
        ("Random sampling", "Selecting sampling sites using random numbers so every site has an equal chance of being chosen, avoiding bias"),
        ("Systematic sampling", "Sampling at regular intervals, eg along a transect"),
        ("Preliminary study", "A small trial used to test a method and decide sample size, number, spacing and timing"),
        ("Anomalous result", "A result that differs from others expected to be similar; repeating shows whether it is real"),
    ],
    "sampling": [
        ("Quadrat", "A frame of known area used to sample plants or slow-moving animals"),
        ("Transect", "A line across a habitat along which samples are taken to record changes in distribution"),
        ("Pitfall trap", "A container sunk into the ground to catch ground-dwelling invertebrates"),
        ("Tullgren funnel", "Apparatus using heat and light to drive soil invertebrates down through a funnel into a collecting vessel"),
        ("Lincoln index", "Estimating population size from mark-release-recapture: N = (M x C) / R"),
        ("Kick sampling", "Disturbing a stream bed so invertebrates are washed into a net held downstream"),
        ("Light trap", "A trap using a bright lamp to attract and collect night-flying insects such as moths"),
        ("Abundance scale", "A scale such as ACFOR (abundant, common, frequent, occasional, rare) for estimating how common a species is"),
        ("Percentage cover", "The proportion of a quadrat's area covered by a species"),
    ],
    "stats": [
        ("Standard deviation", "A measure of the spread of values around the mean"),
        ("Statistical significance", "A result unlikely to have occurred by chance, usually with a probability below 0.05"),
        ("p-value", "The probability that an observed result was produced by random chance"),
        ("Correlation", "A relationship in which one variable changes consistently as another changes; does not prove causation"),
        ("Spearman's rank correlation", "A test of whether two variables are correlated, based on their rank orders"),
        ("Chi-squared test", "A test of whether observed frequencies in categories differ significantly from expected frequencies"),
        ("t-test", "A test of whether two means of normally distributed measured data are significantly different"),
        ("Mann-Whitney U test", "A test of whether two medians of counted or non-normal data are significantly different"),
        ("Simpson's index of diversity", "D = N(N-1) / sum of n(n-1); a higher value means greater variety and evenness of species"),
        ("Error bars", "Lines on a graph showing the standard deviation (or range) around each mean"),
    ],
    # ---------------- Paper 2: living environment ----------------
    "life-conditions": [
        ("Goldilocks zone", "The range of distances from a star at which a planet's temperature allows liquid water"),
        ("Magnetosphere", "The region around the Earth where its magnetic field deflects the solar wind"),
        ("Solar wind", "A stream of charged particles from the Sun that would damage living organisms if not deflected"),
        ("Archaea", "Single-celled organisms similar to bacteria, the earliest form of life, some of which are anaerobic"),
        ("Photoautotroph", "An organism that makes its own food from carbon dioxide using light energy"),
        ("Insolation", "The amount of solar radiation reaching a surface"),
        ("Anomalous expansion of water", "Water is densest at 4 degrees C, so ice floats and water bodies do not freeze solid"),
    ],
    "biodiversity-value": [
        ("Biodiversity", "The variety and abundance of life in an area: genetic, species and habitat diversity"),
        ("Biomimetics", "Copying the adaptations of other species to improve the design of manufactured items"),
        ("Ecosystem services", "Processes carried out by living organisms that benefit humans, eg pollination, soil formation, regulation of atmospheric gases"),
        ("Crop wild relative", "A wild species related to a crop that holds genes useful in breeding programmes"),
        ("Vavilov centre", "A region where a crop was first domesticated and where its wild relatives and greatest genetic diversity are found"),
        ("Gene pool", "The total genetic variation within a population or species"),
        ("Keystone species", "A species whose activities have a disproportionately large effect on the ecosystem, eg elephants"),
        ("Alkaloid", "A nitrogen-containing plant chemical, often toxic to herbivores, that may be medicinal in controlled doses"),
    ],
    "human-impacts": [
        ("Direct exploitation", "Deliberately killing or collecting a species for food, fashion, pets, ornaments or traditional medicine"),
        ("Introduced species", "A species moved by humans to an area where it does not naturally occur"),
        ("Habitat fragmentation", "The breaking up of a habitat into smaller isolated patches, reducing population size and gene flow"),
        ("Hybridisation", "Interbreeding between species or populations, which can dilute the gene pool of a native species"),
        ("Abiotic factor", "A non-living environmental factor such as temperature, water availability, light or pH"),
        ("Biotic factor", "A living factor such as food, predators, competitors, pollinators or pathogens"),
    ],
    "conservation-priorities": [
        ("IUCN Red List", "The International Union for Conservation of Nature's assessment of how threatened each species is (eg Critically Endangered, Vulnerable)"),
        ("Endemic species", "A species found naturally in only one area"),
        ("Flagship species", "A charismatic species used to gain public support for conserving its habitat"),
        ("Evolutionarily distinct (EDGE) species", "A species with few close relatives, whose loss would remove a unique part of evolutionary history"),
        ("CITES", "The Convention on International Trade in Endangered Species, which bans (Appendix I) or controls (Appendix II) trade in listed species"),
        ("SSSI", "Site of Special Scientific Interest - a UK designation protecting important habitats from damaging activities"),
        ("Ramsar site", "A wetland of international importance protected under the Ramsar Convention"),
        ("IWC", "The International Whaling Commission, which regulates whaling and imposed the 1986 moratorium"),
    ],
    "cbr-habitat": [
        ("Captive breeding", "Breeding endangered species in zoos or reserves to increase numbers, often for release"),
        ("Studbook", "A record of the ancestry of captive animals used to choose mates that avoid inbreeding"),
        ("Inbreeding", "Breeding between closely related individuals, increasing homozygous recessive disorders"),
        ("Hard / soft release", "Releasing captive-bred animals with no support / with gradual acclimatisation and post-release feeding and monitoring"),
        ("Plagioclimax", "A community maintained by human activity such as grazing or coppicing, preventing succession to the climatic climax"),
        ("Biological corridor", "A strip of habitat linking isolated reserves so species can move between them"),
        ("Buffer zone", "An area around a reserve with restricted activities that protects it from external impacts"),
        ("Coppicing", "Cutting trees near the base so they regrow multiple stems, maintaining open woodland habitats"),
        ("Rewilding", "Restoring natural processes and species, including predators, so an ecosystem manages itself"),
    ],
    "habitats": [
        ("Biome", "A large-scale ecosystem type determined by climate, eg tropical rainforest, temperate broadleaf forest"),
        ("Zooxanthellae", "Photosynthetic algae living inside coral polyps that supply most of the coral's food energy"),
        ("Coral bleaching", "The expulsion of zooxanthellae from coral polyps, usually caused by raised water temperature, leaving the coral pale"),
        ("Ocean acidification", "The fall in ocean pH as more carbon dioxide dissolves, making it harder for corals and molluscs to build skeletons"),
        ("Mangrove", "A salt-tolerant tree of tropical coasts whose roots trap sediment and provide fish nursery habitat"),
        ("No Take Zone", "A marine area where all fishing is banned so breeding populations can recover"),
        ("Debt-for-nature swap", "Cancelling part of a country's debt in return for protecting an area of habitat"),
        ("Krill", "Small shrimp-like crustaceans that are the key food source in the Antarctic food web"),
    ],
    "eco-monitoring": [
        ("Environmental DNA (eDNA)", "DNA shed into water or soil that can be analysed to detect the presence of a species without catching it"),
        ("Geolocator tag", "A tiny device recording time and light so an animal's daily position can be calculated when it is recaptured"),
        ("Sonogram", "A visual record of sound used to identify species such as bats and dolphins"),
        ("Remote sensing", "Collecting information about the Earth's surface from a distance, eg by satellite sensors"),
        ("ROV / AUV", "Remotely operated vehicle / autonomous unmanned vehicle - carrier systems for sensors underwater or in the air"),
        ("Calibration", "Adjusting an instrument so its readings match a known accurate standard"),
        ("Indirect evidence", "Signs of a species' presence such as droppings, tracks, feeding marks or nests"),
    ],
    "life-processes": [
        ("Adaptation", "A feature that increases an organism's chance of survival and reproduction in its environment"),
        ("Range of tolerance", "The range of an abiotic factor within which a species can survive"),
        ("Niche", "The role of a species in its ecosystem: its habitat, food, interactions and the conditions it needs"),
        ("Succession", "The sequence of changes in a community over time as species modify the environment"),
        ("Pioneer species", "The first species to colonise bare ground, tolerant of harsh conditions"),
        ("Climax community", "The final, stable community at the end of succession, controlled by climate"),
        ("Carrying capacity", "The maximum population of a species that an environment can support indefinitely"),
        ("Density-dependent factor", "A factor whose effect increases with population density, eg disease, food shortage, predation"),
        ("r-selected / k-selected species", "Species that breed early and produce many young / species that breed late, produce few young and live long"),
        ("Maximum sustainable yield", "The largest harvest that can be taken from a population year after year without causing it to decline"),
    ],
    # ---------------- Paper 2: biological resources ----------------
    "agroecosystems": [
        ("Agroecosystem", "An ecosystem managed to produce food, with abiotic and biotic factors controlled to maximise yield"),
        ("Cultural pest control", "Non-chemical practices such as crop rotation, weeding, barrier crops and companion planting that reduce pests"),
        ("Biological control", "Using a predator, parasite or pathogen to control a pest species"),
        ("Sterile insect technique", "Releasing large numbers of sterilised males so wild females produce no offspring"),
        ("Monoculture", "Growing a single crop species over a large area"),
        ("Hydroponics", "Growing plants in nutrient solution without soil, allowing precise control of nutrients"),
        ("Legume", "A plant such as clover or beans with nitrogen-fixing Rhizobium bacteria in root nodules"),
        ("Barrier crop", "A crop planted around a field to stop pests reaching the main crop"),
    ],
    "food-species": [
        ("Selective breeding", "Choosing parents with desirable characteristics to produce offspring with those characteristics"),
        ("Hybrid vigour", "The improved health and productivity of offspring from crossing two different breeds or varieties"),
        ("Artificial insemination", "Impregnating females with semen collected from a selected male, allowing many more offspring"),
        ("Embryo transfer", "Fertilising many eggs from a selected female and implanting each in a surrogate"),
        ("Genetic modification (transgenics)", "Transferring a gene from one species to another, eg Bt toxin gene into corn"),
        ("Energy subsidy", "Any input to agriculture that requires energy, eg fertiliser manufacture, machinery, irrigation"),
        ("Energy ratio", "Food energy output divided by energy input; a measure of efficiency"),
        ("Food conversion ratio", "The mass of feed needed to produce a unit mass of livestock growth; lower is better"),
        ("Law of diminishing returns", "Each additional unit of input produces a smaller increase in yield than the previous one"),
    ],
    "agri-impacts": [
        ("Set-aside", "Paying farmers to take land out of production and keep it in a farmable condition"),
        ("Quota", "A limit on the amount of a product a farmer may produce or sell"),
        ("Agri-environment scheme", "Payments to farmers for managing land in ways that benefit wildlife, soil and water"),
        ("Guaranteed market", "A government commitment to buy surplus produce at an agreed price, giving farmers financial security"),
        ("Food miles", "The distance food travels from producer to consumer, related to transport energy use"),
        ("Fairtrade", "Trade that guarantees producers a price that covers basic needs such as water, education and health care"),
        ("Organic agriculture", "Farming that uses natural processes for nutrients and pest control so artificial fertilisers and pesticides are unnecessary"),
    ],
    "fishing": [
        ("Photic zone", "The surface layer of water where enough light penetrates for photosynthesis"),
        ("Upwelling", "The rise of cold, nutrient-rich deep water to the surface, increasing productivity"),
        ("Demersal fishing", "Fishing for species living on or near the seabed, eg cod, plaice"),
        ("Pelagic fishing", "Fishing for species living in open water, eg herring, mackerel, tuna"),
        ("By-catch", "The unwanted catch of non-target species, undersized fish or over-quota fish"),
        ("Ghost fishing", "Lost or discarded fishing gear that continues to trap and kill marine organisms"),
        ("Catch quota", "A limit on the total weight of a species that may be landed"),
        ("Turtle exclusion device", "A spring-loaded escape panel in a trawl net that lets turtles escape"),
        ("Purse seine", "A net laid around a shoal and pulled tight underneath it"),
    ],
    "aquaculture": [
        ("Aquaculture", "The farming of aquatic organisms such as fish, shellfish and seaweed"),
        ("Polyculture", "Farming several species together so they use different food sources and wastes are recycled"),
        ("Integrated multi-trophic aquaculture", "Farming species from different trophic levels together so the waste of one feeds another"),
        ("Fishmeal", "Feed made from wild-caught fish, needed by carnivorous farmed species such as salmon"),
        ("Sea lice", "Parasitic crustaceans that multiply on densely stocked farmed salmon and spread to wild fish"),
        ("Gene pool contamination", "Escaped farmed fish breeding with wild fish and reducing their genetic fitness"),
        ("Closed-system aquaculture", "Farming in tanks where water is recirculated and treated, preventing pollution and escapes"),
    ],
    "forests": [
        ("Deforestation", "The clearance of forest for other land uses, or its degradation until it no longer functions as forest"),
        ("Selective logging", "Removing only chosen high-value trees, leaving the forest structure largely intact"),
        ("Clear felling", "Removing all trees from an area at once"),
        ("Afforestation", "Planting new forest on land that was not previously forested"),
        ("Agroforestry", "Growing trees together with crops or livestock on the same land"),
        ("Forest Stewardship Council (FSC)", "An organisation certifying timber from sustainably managed forests"),
        ("ITTO", "The International Tropical Timber Organisation, which promotes sustainable management of tropical forests"),
        ("Shifting cultivation", "Clearing and burning a patch of forest, farming it briefly, then moving on and allowing regrowth"),
    ],
    # ---------------- Paper 2: sustainability ----------------
    "dynamic-equilibria": [
        ("Sustainability", "The ability to maintain a lifestyle or activity indefinitely without depleting resources or damaging the environment"),
        ("Sustainable development", "Development that meets the needs of the present without compromising the ability of future generations to meet their own needs (Brundtland, 1987)"),
        ("Dynamic equilibrium", "A balance maintained by opposing processes, so a system fluctuates around a stable state"),
        ("Negative feedback", "A response that resists change and returns a system towards equilibrium"),
        ("Positive feedback", "A response that amplifies change and may push a system past a tipping point"),
        ("Tipping point", "The threshold beyond which change becomes self-sustaining and a new equilibrium forms"),
        ("Per capita impact", "The environmental impact of each individual person, which rises with affluence"),
    ],
    "natural-systems": [
        ("Energy density (natural systems)", "Natural processes are driven by low energy-density resources, especially solar power"),
        ("Material cycle", "A sequence of processes in which the waste of one is the raw material of the next, so nothing is depleted"),
        ("Linear system", "A human system that uses resources once, from extraction to disposal, producing waste and depletion"),
        ("Biodegradable", "Able to be broken down by living organisms into non-toxic products"),
        ("Enzyme", "A biological catalyst that lowers the activation energy so reactions occur at low temperatures"),
        ("Persistent toxin", "A poison such as PCBs or organochlorines that is not broken down and may bioaccumulate"),
    ],
    "circular-economy": [
        ("Circular economy", "An economy in which materials are kept in use through re-use, repair and recycling and energy comes from renewable sources, copying natural cycles"),
        ("Ecological footprint", "The area of productive land and sea needed to supply a population's resources and absorb its wastes"),
        ("Biocapacity", "The capacity of an area to produce renewable resources and absorb wastes"),
        ("Global hectare", "A hectare of world-average biological productivity, the unit of ecological footprint and biocapacity"),
        ("Earth Overshoot Day", "The date each year by which humanity has used the resources the Earth can regenerate in that year"),
        ("Industrial symbiosis", "Neighbouring industries using each other's wastes as raw materials, eg Kalundborg, Denmark"),
        ("Cradle to Cradle design", "Designing products so all materials can be recovered and re-used at the end of their life"),
        ("Living Planet Index", "A measure of global biodiversity based on population trends of thousands of vertebrate species"),
        ("Carbon footprint", "The total greenhouse-gas emissions caused by a person, product or activity"),
    ],
}
